### ISSUE TITLE
@scope directive

### ISSUE THREAD

**Issue by raderio** [graphql/graphql-js#1002]
Please add @scope directive to be possible to mark what permissions/roles should have user in order to be able to fetch data.
Example

```
type Post {
    id: ID
    comments: [Comment] @scope(authenticated)
}
```

**Comment by wincent** [comment]
Thanks for posting @raderio. I'm going to close this one in favor of discussing this on the corresponding issue that you already posted over on the facebook/graphql repo: https://github.com/facebook/graphql/issues/348
