### ISSUE TITLE
Not possible to return timestamps!?

### ISSUE THREAD

**Issue by bradennapier** [graphql/graphql-js#1003]
So it is apparently not possible to handle timestamp values in ms ?  Seems completely broken

```
{
      "message": "Int cannot represent non 32-bit signed integer value: 1503608145148",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "project",
        "events",
        0,
        "timestamp"
      ]
    },
```

Should there not be some kind of support to handle timestamp values?  I would imagine a HUGE amount of api's need this...

**Comment by bradennapier** [comment]
Ok, float does work -- but still seems like there needs to be built-in date support.

**Comment by wincent** [comment]
This is following [the GraphQL spec](http://facebook.github.io/graphql/#sec-Int):

> Numeric integer values larger than 32‐bit should either use String or a custom‐defined Scalar type, as not all platforms and transports support encoding integer numbers larger than 32‐bit.

So, the answer is to encode this kind of value to string.

As for date support, that is a separate issue: https://github.com/facebook/graphql/pull/315

**Comment by psy21d** [comment]
Пугающая ситуация. Компьютеры с гигагерцами и десятками ядер не умеют считать большие числа. Разве мы не достойны этого?
