### ISSUE TITLE
utilities/extendSchema is undocumented

### ISSUE THREAD

**Issue by spencerwilson** [graphql/graphql-js#1014]
It was recommended for use [here](https://github.com/graphql/graphql-js/issues/223#issuecomment-308951838) a couple months ago, and is among the package exports, so it seems like there's intent that it's a supported API. Seems like it's in need of being documented at http://graphql.org/graphql-js/utilities/.

**Comment by robzhu** [comment]
Thanks for identify this. You're right, we should at least add a description for extendSchema in the docs.

**Comment by brysgo** [comment]
Speaking of extendSchema, I added an optional parameter called resolveConflict that lets you resolve resolve conflicting fields instead of throwing, I can make a PR if anyone is interested in it.

**Comment by IvanGoncharov** [comment]
We have deep documentation depth all around `graphql-js` and it's documented in #1368 so I will close this as a duplicate
