### ISSUE TITLE
fieldname type leads to strange error: Abstract type must resolve to an object...

### ISSUE THREAD

**Issue by appsthatmatter** [graphql/graphql-js#1018]
We define a `GraphQLObjectType`. When we return object data with a field `type` a strange error appears:
```
Abstract type Node must resolve to an Object type at runtime for field Query.node with value \"[object Object]\", received \"null\".
```

The workaround is to rename that field from `type` to `typeFoo` and rename it back with the resolve function.

Example of the workaround:
```
    new GraphQLObjectType({
        name: 'Foo',
        interfaces: [nodeInterface],
        resolve: (id) =>
          // the map that we return here must not have a field `type`
          // so we rename from `type` to `typeFoo`
          // [snip]
        fields: () => ({
            type: {
                type: GraphQLString,
                resolve: ({ typeFoo }) => typeFoo, // rename it back to `type`
            },
```

**Comment by robzhu** [comment]
Hey @appsthatmatter, I tried creating a simple repro of this issue, but I'm able to successfully query the `type` field: https://gist.github.com/robzhu/2182cfbb17189d4163001e7164a4cea7. Does that repro successfully model what you're trying to do?

**Comment by robzhu** [comment]
@appsthatmatter, I haven't heard back from you on my question for a while now. Closing out the issue, please feel free to re-open if it's not resolved (see my last response).
