### ISSUE TITLE
Why unique constrain on GraphQLScalarType name?

### ISSUE THREAD

**Issue by mjasnikovs** [graphql/graphql-js#1019]
```javascript
const SafeString = new GraphQLScalarType({
	name: 'String',
	description: 'String',
	serialize: v => v,
	parseValue: v => v,
	parseLiteral: v => v
})

module.exports = {
	type: UserType,
	description: 'Update user object',
	args: {
		id: {type: new GraphQLNonNull(GraphQLID)},
		name: {
			type: SafeString
		},
		email: {
			type: SafeString
		},
```

Produces Error 

```
Error: Schema must contain unique named types but contains multiple types named "String".
```

How can I trick GraphQL, so he accepts custom scalar type as a standard String type, so I can attach my custom validators. So I don't have to invent infinite numbers of unique GraphQLScalarType names for every mutation.

**Comment by wincent** [comment]
Type name uniqueness doesn't apply just to scalar types.

I would think if you just didn't ever use anywhere in your schema `GraphQLString`, then you'd be free to provide your own without violating the constraint. [The spec](http://facebook.github.io/graphql/#sec-Scalars) doesn't rule out providing your own:

> GraphQL provides a basic set of well‐defined Scalar types. A GraphQL server should support all of these types, and a GraphQL server which provide a type by these names must adhere to the behavior described below.

However, graphql-js itself *does* use the built-in `GraphQLString` type (for example, in implementing introspection capabilities), which means that you can't really prevent it from being used and triggering the uniqueness constraint.

> How can I trick GraphQL, so he accepts custom scalar type as a standard String type, so I can attach my custom validators. So I don't have to invent infinite numbers of unique GraphQLScalarType names for every mutation.

Can you just make one, call it `SafeString`, and use it everywhere?

**Comment by mjasnikovs** [comment]
I would love that, but...

```javascript
const {
	graphql,
	GraphQLSchema,
	GraphQLString,
	GraphQLObjectType,
	GraphQLScalarType
} = require('graphql')

const safeString = () => {
	return new GraphQLScalarType({
		name: 'SafeString',
		description: 'SafeString',
		serialize: v => v,
		parseValue: v => v,
		parseLiteral: v => v
	})
}

const schema = 	new GraphQLSchema({
	query: new GraphQLObjectType({
		name: 'query',
		description: 'test query',
		fields: {
			input: {
				type: GraphQLString,
				description: 'Provides test',
				args: {
					stringOne: {
						type: safeString()
					},
					stringTwo: {
						type: safeString()
					}
				},
				resolve: (parentValue, {string}) => string
			}
		}
	})
})

return graphql(schema)
```
Result

```javascript

c:\hub\graphql-input\node_modules\graphql\jsutils\invariant.js:19
    throw new Error(message);
    ^

Error: Schema must contain unique named types but contains multiple types named
"SafeString".
    at invariant (c:\hub\graphql-input\node_modules\graphql\jsutils\invariant.js:19:11)
    at typeMapReducer (c:\hub\graphql-input\node_modules\graphql\type\schema.js:193:58)
    at Array.reduce (<anonymous>)
    at c:\hub\graphql-input\node_modules\graphql\type\schema.js:217:36
    at Array.forEach (<anonymous>)
    at typeMapReducer (c:\hub\graphql-input\node_modules\graphql\type\schema.js:210:27)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (c:\hub\graphql-input\node_modules\graphql\type\schema.js:98:34)
    at Object.<anonymous> (c:\hub\graphql-input\test\delete.testt.js:19:17)
    at Module._compile (module.js:573:30)


npm ERR! Test failed.  See above for more details.
```

**Comment by IvanGoncharov** [comment]
@mjasnikovs You create new Scalar type every time `safeString` is called.
Please changes it to:
```ts
const safeString = new GraphQLScalarType({
		name: 'SafeString',
		description: 'SafeString',
		serialize: v => v,
		parseValue: v => v,
		parseLiteral: v => v
	})
```

**Comment by mjasnikovs** [comment]
This works, but then I can' t assign unique configuration for each string.

**Comment by wincent** [comment]
> This works, but then I can' t assign unique configuration for each string.

That may be an insurmountable impedance mismatch. If they have different configurations/behaviors, then they should be different types, right?

**Comment by mjasnikovs** [comment]
No, this is clutter. I understand why Facebook needs tons of boilerplate and strict rules to control everything. But there are human beings, who can understand that field with key "email" should be formatted as email. And nobody should invent tons of new types. Email is still a string!
Whats next, TrimmedString, FirstLetterToCapitalCaseType and TrimmedFirstLetterToCapitalCaseType.

It's still a string with some helper methods. Nobody should look into manual (To list all strings types) every time he wants to write a simple query.  I don' t see any value in such approach.

**Comment by wincent** [comment]
It would indeed be clutter, but that's exactly what you seemed to be asking for wanting to "assign unique configuration for each string".

Effectively, an email address *is* a `String`, and at FB we do use a `String` type for it.

**Comment by mjasnikovs** [comment]
So where do you do validation/trimming /etc... ?
I had to create middleware for resolve and write two schemas, one for GraphQL and one for validation.
https://github.com/mjasnikovs/format-schema
It is a clutter. It would be nice to have custom validation inside one schema.

**Comment by wincent** [comment]
I'm not super familiar with the server stack here (which is built using Hack, not graphql-js) but my belief is that the schema itself is a relatively thin layer on top of the underlying data models (which you may have heard of referenced in some places as the "Ent" framework), and its at that layer that the deeper validation occurs (ie. string format, as opposed to just type-checking that something is a string).
