### ISSUE TITLE
Field errors

### ISSUE THREAD

**Issue by gabrielf** [graphql/graphql-js#102]
From the discussion of #44.
According to [the spec on scalars](http://facebook.github.io/graphql/#sec-Scalars) under "Result Coercion":

    If the server encounters some value that cannot be reasonably coerced 
    to an Int, then it must raise a field error.

However it seems most examples and tests simply return null instead. What's correct?

**Comment by leebyron** [comment]
They raise a field error, but the error handling semantics (http://facebook.github.io/graphql/#sec-Error-handling) explain:

> If an error occurs when resolving a field, it should be treated as though the field returned null, and an error must be added to the “errors” list in the response.

**Comment by leebyron** [comment]
Though that clause needs some explanation for non-nullable typed fields. I'll keep this open to handle that.

**Comment by leebyron** [comment]
https://github.com/facebook/graphql/commit/c589e2ef23d0bd0347418ff133237bee465be6ac
