### ISSUE TITLE
returning null from visitor doesn't behave as expected

### ISSUE THREAD

**Issue by brysgo** [graphql/graphql-js#1021]
Hello! Thanks for all the great work on graphql. I'm working on creating some simple tools for manipulating schemas and queries, so I have been playing around with the internals (which are pretty sweet). I came across this visiting functionality and thought, that would be great for what I am going to try and build*

I quickly took a stab at trying to remove a node from the AST, and this is what happened:

```js
const { parse, visit, print } = require("graphql");

const ast = parse(`
  query RandomQuery {
    this {
      is
      a
    }
    random
    thing
  }
`);

const editedAst = visit(ast, {
  enter(node, key, parent, path, ancestors) {
    if (node.value === "is") {
      return null;  //  according to comments... "null: delete this node"
    }
  }
});

console.log(print(editedAst));
```

The result I get is:

```graphql
query RandomQuery {
  this {
    null
    a
  }
  random
  thing
}
```

Is this expected? If it isn't, this seems like as good a place as any to document it, if it is, maybe you can help me understand it better.

*I'm building a utility that will take a graphql schema and a graphql query, and mask the query with the schema. If you want to know why I am doing this, I'd be happy to discuss that too :-)

**Comment by brysgo** [comment]
Answered my own question

**Comment by wincent** [comment]
No worries about the noise. Thanks for asking/answering @brysgo.
