### ISSUE TITLE
0.10.5 -> 0.11.x breaking change (field must be Output, got Connection)

### ISSUE THREAD

**Issue by kamek-pf** [graphql/graphql-js#1024]
Hi,

Not sure where to report this, but since swapping between `graphql-js` version fixes the problem I figured this is the right place.
We're using `graphql-relay-js`'s Connections.
In `graphql-js#0.10.5`, everything works fine. After upgrading to `graphql-js#0.11.x`, I get the following error :
```
Error: Campaign.guestProfiles field type must be Output Type but got: GuestProfilesConnection.
```

Any idea what I might be missing ?

**Comment by Gregoor** [comment]
And here I was thinking I've gone crazy. Now that I know that it's probably not me, I'll look for the bug.

**Comment by IvanGoncharov** [comment]
@kamek-pf @Gregoor Usually issues like that happen when you have multiple versions of `graphql-js`.  To find out which library depend on the older version of `graphql-js` you can run `npm ls graphql`.

**Comment by Gregoor** [comment]
:see_no_evil: thanks lots Ivan! How could I forget that one. It didn't happen to me already a while ago.

Would it be possible to show a specific error when that happens?

**Comment by IvanGoncharov** [comment]
@Gregoor There were a few attempts to make different versions of `graphql-js` compatible.
Here is the most recent one: https://github.com/graphql/graphql-js/pull/996

As for better error message, the only way to implement this correctly would be to check all input arguments of all public functions.

**Comment by leebyron** [comment]
#1080 will dramatically improve this error message. Some PRs partly implementing it are already going up. Sorry for the confusion and happy to hear your problem was solved.
