### ISSUE TITLE
passing arguments to queries.

### ISSUE THREAD

**Issue by satishrao84** [graphql/graphql-js#1028]
I've been trying to solve this all day, but just can't seem to even know how to approach this. 
I have the below schema : 

    const applicationRootType = new GraphQLObjectType({
    name : 'Bucket',
    fields : () => ({
        id:{
            type: new GraphQLNonNull(GraphQLID),
            resolve:(obj) => obj._id
        },
        timestamp:{type:Date},
        app_name:{type:GraphQLString},
        buckets: { type : new GraphQLList(bucketTypeRoot) }
    }),
    interfaces:[nodeInterface]
    })

    let applicationType = new GraphQLObjectType({
       name : 'Application',
       fields : () => ({
        id : globalIdField("Application"),
        //app_name:{type:GraphQLString, resolve:(obj) => obj.app_name},
        bucketConnection : {
            type : bucketConnection,
            args : {
                ...connectionArgs,
                query:{ type : GraphQLString}
            },
            resolve:(_,args) => {
                return connectionFromPromisedArray(
                   db.collection("buckets").find({}).toArray(),args
                );
            }
        }
      }),
    interfaces:[nodeInterface]
    });

    const { connectionType: bucketConnection } = 
    connectionDefinitions({ name: 'Bucket', nodeType: applicationRootType });

    const Query = new GraphQLObjectType({
     name: 'Query',
     fields: () => ({
        node: nodeField,
        application: {
            type: applicationType,
            resolve: () => application,
        },

     }),
    });
    const schema = new GraphQLSchema({
      query: Query,
    });
    return schema;
    }
    export default Schema;

All this works fine.

 But now I would like to pass an argument to just query for the "app_name" i.e. query on a specific app_name. I just don't know how I can do this. Have gone through a lot of graphql documentaiton, but everyone just seems to skip this part. 

Can someone please help me?

Thanks!

**Comment by leebyron** [comment]
Try adding field arguments to your `application` field, perhaps `application(name: String)`

More about field arguments: http://facebook.github.io/graphql/October2016/#sec-Object-Field-Arguments
