### ISSUE TITLE
Pass rootValue from execution context to resolveType

### ISSUE THREAD

**Issue by charypar** [graphql/graphql-js#103]
It would be quite useful to get the `rootValue` in `resolveType` the same way you get it in field resolvers. 

In my case I need to dynamically chose which fetching backend implementation to use and I'm passing it in in the rootValue. The backend also does list filtering by various predicates, one of which is the item type - the backend therefore needs to be able to resolve the item type the same way the interface does. 

The natural place for this logic is the backend itself (all backend-specific things sit in one place), but since I only know the right implementation at query run time the type detection logic is now duplicated.

I can imagine other use-cases for the `rootValue` in resolveType - e.g. using an authorisation system to resolve to basic or extended type (guess that is kinda contrived) or some sort of user-specified type resolution rules maybe.

**Comment by leebyron** [comment]
This happens today, though the variable naming is probably confusing. We're using the terms `context` and `rootValue` interchangeably. I'll keep this task open to resolve the naming sloppiness.

**Comment by leebyron** [comment]
These last two diffs should add the functionality you're looking for!

**Comment by leebyron** [comment]
They will be released on npm in the near future.
