### ISSUE TITLE
defaultValue with dates

### ISSUE THREAD

**Issue by satishrao84** [graphql/graphql-js#1034]
Hello,
Is there a way for a Scalar type to have defaultValues of dates? For example ; 

    let TimeFilterType = new GraphQLInputObjectType({
      name : 'TimeFilter',
      fields : () => ({
        start_time : {
            type : DateType,
            defaultValue : "2017-09-06T23:09:13.093Z"
        },
        end_time : {
            type : DateType,
            defaultValue : "2017-09-06T23:09:11.093Z"
        }
      })
    })

Is it possible for the start_time and end_time to have the current time and (current time - 1 day) respectively? I cannot seem to reference external variables in defaultValues. 

Thanks.

**Comment by leebyron** [comment]
This is not possible, no. 

Default values are static and communicated to tools which might see them at different times from when a query is executed. They may decide to omit a query based on a default value, assuming it is static.

I recommend not using default values and instead in your resolver check for `null` and supply your default behavior.

Alternatively, you might define these as "seconds before now" in an Int if you always expect these values to be relative to the current time.
