### ISSUE TITLE
Bug in buildASTSchema: Adding a Float scalar to type definition breaks the materializer

### ISSUE THREAD

**Issue by nemanja-stanarevic** [graphql/graphql-js#104]
When a Float field is added to type definition, the materializer (`buildASTSchema`) breaks down with `Error: Type Float not found in document`.  Adding a float field to HelloScalars test confirms the issue.

Patch is simple, one-line tweak to getTypeDefProducer function in utilities/buildASTSchema.js to add `Float` to `innerTypeMap` map, as follows:

```javascript
  function getTypeDefProducer() {

    var innerTypeMap = {
      String: GraphQLString,
      Int: GraphQLInt,
++++  Float: GraphQLFloat,
      Boolean: GraphQLBoolean,
      ID: GraphQLID,
    };
```

With this, the new HelloScalars test passes, I'll submit a PR in a sec (updated test + patch).

**Comment by dschafer** [comment]
Looks like #105 fixed this, thanks for the report and patch!

**Comment by nemanja-stanarevic** [comment]
Dan, you are welcome; I'm looking forward to v0.2.5 on npm :)

Thanks again for all the great work you all are putting into this
