### ISSUE TITLE
graphql-js 0.11.3 and Flow 0.55.0 incompatibilities

### ISSUE THREAD

**Issue by finneganh** [graphql/graphql-js#1045]
Hi pals. Looks like the latest Flow upgrade's breaking changes are incompatible with GraphQL 0.11.3, specifically "Fixed a bug that caused unsoundness with $ObjMap."

https://github.com/facebook/flow/releases/tag/v0.55.0

Seeing a lot of errors like:

Error: node_modules/graphql/execution/execute.js.flow:289
289:     Object.create(null);
         ^^^^^^^^^^^^^^^^^^^ Object.create. This type is incompatible with
288:   const fragments: {[name: string]: FragmentDefinitionNode} =
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

Error: node_modules/graphql/execution/execute.js.flow:350
350:     Object.create(null),
         ^^^^^^^^^^^^^^^^^^^ Object.create. This type is incompatible with the expected param type of
514:   fields: {[key: string]: Array<FieldNode>},
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type

**Comment by leebyron** [comment]
Thanks for the report. We're looking into this, and think it might be a bug with Flow. We'll hopefully have this resolved soon

**Comment by asiandrummer** [comment]
Thanks for the report @finneganh!
