### ISSUE TITLE
Missing file in 0.11.5

### ISSUE THREAD

**Issue by oliviertassinari** [graphql/graphql-js#1050]
The following file `/utilities/index.js` seems to be missing in the `0.11.5` release. I have reverted to `0.11.4`.

**Comment by wincent** [comment]
@oliviertassinari. I just checked a local v0.11.6 install and the file seems to be there, so I am going to close this. Please report back if you find any issues with v0.11.6 (or later).

**Comment by oliviertassinari** [comment]
Thanks, it's all good :).
