### ISSUE TITLE
Upgrading from 0.11.3 to 0.11.4+ breaks compatibility with IE11

### ISSUE THREAD

**Issue by PhilippSpo** [graphql/graphql-js#1051]
After upgrading from 0.11.3 to 0.11.4 our app stops working in IE11. Upgrading to 0.11.5 doesn't fix it either.

Seems like the issue lies within `iterall`:
![image](https://user-images.githubusercontent.com/8394418/31024482-808deb56-a53f-11e7-833c-1665b3b1e419.png)
Which I guess is this function:
https://github.com/leebyron/iterall/blob/a43fc763cc8bb1b3944bd85d8a9af3cb6e07babf/index.js#L640-L660

**Comment by PhilippSpo** [comment]
Looks like it has been [fixed already](https://github.com/leebyron/iterall/commit/325e8ff9e7cd966156688d2012b16f3a588b886a#diff-168726dbe96b3ce427e7fedce31bb0bc).

**Comment by PhilippSpo** [comment]
So as soon as the dep is bumped to `1.1.3`  this issue is resolved 👍

**Comment by wincent** [comment]
Thanks for opening the issue @PhilippSpo. I bumped the dep and released v0.11.6 earlier this morning.
