### ISSUE TITLE
Extract tests into language agnostic conformance tests

### ISSUE THREAD

**Issue by F21** [graphql/graphql-js#106]
It would be awesome if some of the tests can be extracted into a language agnostic format so that we can use them as conformance tests for implementations in other languages.

Something like `twitter-text`'s conformance tests would be nice: https://github.com/twitter/twitter-text/tree/master/conformance

**Comment by OlegIlyenko** [comment]
+1 
I also opened very similar issue in graphql repo recently: https://github.com/facebook/graphql/issues/72

**Comment by leebyron** [comment]
Closing this task in favor of https://github.com/facebook/graphql/issues/72
