### ISSUE TITLE
GraphQL union and conflicting types

### ISSUE THREAD

**Issue by jdemangeon** [graphql/graphql-js#1065]
Hello everybody!

I've got an issue on my project and i can't find any solution on the internet. Here is the situation.

- I've an Union ("DataResult") of 2 types ("Teaser" & "Program")
- I've a "Zone" type with a "data" field (an array "DataResult")
- "Teaser" & "Program" have the same "title" field with a different type (String vs String!)

Here is parts from "Zone", "Teaser" and "Program" schemas:

```
type Program {
    title: String
}

type Teaser {
    title: String!
}

union DataResult = Teaser | Program

type Zone {
    (...)
    data: [DataResult!]
}
```

When I tried to query zone data as described in the query part below, i've got an error from graphQL.

```
zones {
    ...zoneFieldsWithoutData
    data {
        ... on Program {
            ...programFields
        }
        ... on Teaser {
            ...teaserFields
        }
    }
}
```

Here is the error:Error: GraphQL error: 

```Fields \"title\" conflict because they return conflicting types String and String!. ```

Use different aliases on the fields to fetch both if this was intentionalI can't use an alias because the specs needs the same attribute name for all "DataResult" entities. What can I do ?

Moreover, even if I set the same Type for "title", I've a lot of warning about "missing fields" in the console...

Thanks for your help!

PS: I use Vanilla Apollo as graphQL client (on the server side)

**Comment by IvanGoncharov** [comment]
> Fields \"title\" conflict because they return conflicting types String and String!.

It's intentional see here:
https://github.com/facebook/graphql/blame/master/spec/Section%205%20--%20Validation.md#L362-L365
http://facebook.github.io/graphql/October2016/#SameResponseShape()

> Moreover, even if I set the same Type for "title", I've a lot of warning about "missing fields" in the console...

Switching both fields to `String` or `String!` should work.
Can you please post error messages here?

**Comment by jdemangeon** [comment]
Thanks for your reply :)

Here is a part of my logs. As you can see, i've a lot of warnings about missing fields.
But it's intentionnal, I can have "programs" and not "teasers", no one, or both, ... in my "data" field.

The "data" field can hold 2 different objects, but they're not mandatory.

```
WARNING: heuristic fragment matching going on!
Missing field kind in {
  "id": "057385-008-A_**********",
  "type": "teaser",
  "programId": "057385-008-A",
  
Missing field shortDescription in {
  "id": "057385-008-A_**********",
  "type": "teaser",
  "programId": "057385-008-A",
  
Missing field fullDescription in {
  "id": "057385-008-A_**********",
  "type": "teaser",
  "programId": "057385-008-A",
  
Missing field player in {
  "id": "057385-008-A_**********",
  "type": "teaser",
  "programId": "057385-008-A",
  
Missing field availabilityDates in {
  "id": "057385-008-A_**********",
  "type": "teaser",
  "programId": "057385-008-A",
```

**Comment by IvanGoncharov** [comment]
@jdemangeon It looks like all those logs cause by Apollo client.
You can try to add `___typename` like that:
```graphql
zones {
    ...zoneFieldsWithoutData
    __typename
    data {
        ... on Program {
            ...programFields
        }
        ... on Teaser {
            ...teaserFields
        }
    }
}
```
If this doesn't help please report issue on Apollo repo:
https://github.com/apollographql/apollo-client

**Comment by jdemangeon** [comment]
It's not working, i'll do it. :+1: 

Thanks a lot @IvanGoncharov !

**Comment by valoricDe** [comment]
@IvanGoncharov You mentioned https://spec.graphql.org/June2018/#SameResponseShape(). There in the Explanatory Text it says: `... Therefore any two field selections which might both be encountered for the same object are only valid if they are equivalent. ...`
But if we use
```
data {
        __typename
        ... on Program {
            ...programFields
        }
        ... on Teaser {
            ...teaserFields
        }
    }
```
we refer to field selections for different objects. Once for object with __typename Program and once for an object with __typename Teaser

**Comment by pelhage** [comment]
is this still an issue in the graphql spec? Seems like unions don't fully work flexibly if we need to rename properties via aliases as opposed to sticking with the expected schema property names

**Comment by sebastiangug** [comment]
I can't believe this isn't working, it makes little to no sense for it to be designed this way.
