### ISSUE TITLE
what is declare?

### ISSUE THREAD

**Issue by u-can-miracle** [graphql/graphql-js#1068]
Hi, can someone ask me what is the ["declare" keyword](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L49)?
P. S. I know it's not correct place to asking what is declare keyword but I don't know where else I can get answer about this.

**Comment by intellix** [comment]
I'm guessing this: https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-global-function
You should take this to stackoverflow though as the issue system is for issues :)

**Comment by leebyron** [comment]
A Flow type feature
