### ISSUE TITLE
Custom directives are stripped during schema printting?

### ISSUE THREAD

**Issue by dotansimha** [graphql/graphql-js#1072]
Trying to understand why my custom GraphQL directives are stripped when `printSchema` is executed (also using ``).

Found this line of code (`isSpecDirective`): 
https://github.com/graphql/graphql-js/blob/4f5e351c2afb28e4ae3a44eae76d45d895ff3aa2/src/utilities/schemaPrinter.js#L33-L43

Is there a reason for removing custom directives? I understand the `@deprecated` is a special directive and it effects more than just the docs, but I want to implement a custom directive such as `skip` or `include` - but the printer/introspection removes them.

**Comment by mrjj** [comment]
There were an answer on this:
https://github.com/graphql/graphql-js/issues/869

**Comment by leebyron** [comment]
`@skip` and `@include` cannot be added as custom directives - they will always be implemented using the built-in spec-compliant versions.

Other custom directives will be included. I've just added a test which confirms this
