### ISSUE TITLE
Accute characters do not work.

### ISSUE THREAD

**Issue by danilohgds** [graphql/graphql-js#1073]
{
	"asset": {
		"fantasyName": "LTN222233444",
		"indexerName": "PRÉ"
	}
}

While using the update above, the mutation fails with invalid json due to the É character, I have tried escaping it to \ with no successs, can you guys please help me out?

**Comment by leebyron** [comment]
Sorry, I don't have enough information to help. What was the error? Where did you see it? Was it from this library or another one hosting it?

JSON allows for unicode in strings, so perhaps you're using a broken JSON encoder. You could always try using unicode escapes (eg "\u00C9")
