### ISSUE TITLE
Browser functionality

### ISSUE THREAD

**Issue by lastmjs** [graphql/graphql-js#1075]
Is this library sufficiently decoupled from Node.js to work in the browser? For example, imagine I would like to create a schema that resolves queries to IndexedDB in a user's browser. Is this possible?

**Comment by leebyron** [comment]
It is! In fact the GraphiQL browser utility is powered via GraphQL.js. 

Go for it!

**Comment by lastmjs** [comment]
So, I went to install this and try it out in the browser. The code installed into my node_modules does not look like the code here in the repo. I was hoping this wouldn't be the case. The source code uses ES modules and should work great in the browser without any kind of build step. The built code installed into node_modules is filled with requires, making it unusable in the browser without appropriate tooling. Will this be addressed? I feel it would be more appropriate to leave the source code installed using ES modules, since all JavaScript environments will soon support them

**Comment by lastmjs** [comment]
Also the source code has flow syntax...there is not a suitable preparation for use in the browser, the source code has flow types, the built code has requires, can we consider an option that is platform agnostic?

**Comment by lastmjs** [comment]
Why would the project compile from ES modules, which are more universal
than CommonJS, to CommonJS? Bundlers also understand ES modules.

**Comment by IvanGoncharov** [comment]
@lastmjs `graphql` already publish as ES module since `0.12` just look for `module` directory inside the package. More details in #1105.

**Comment by lastmjs** [comment]
@IvanGoncharov Thank you!

**Comment by HouCoder** [comment]
This is a bit annoying, I just wanted to make a simple demo to explain GraphQL to my backend co-works without extra npm, webpack work involved, would be great if it could support browser directly without tooling.

For people who're looking for a **browser** client, try this - https://github.com/f/graphql.js

**Comment by lastmjs** [comment]
The biggest problem is bear specifiers, I don't see it in their best
interest to change that. The polymer team is hopefully working on a
standard for bear specifiers in the browser. If you want a really easy
solution, try https://github.com/lastmjs/zwitterion

On May 9, 2018 11:25 PM, "Tonni" <notifications@github.com> wrote:

This is a bit annoying, I just wanted to make a simple demo to explain
GraphQL to my backend co-works without extra npm, webpack work involved,
would be great if it could support browser directly without tooling.

For people who're looking for a *browser* client, try this -
https://github.com/f/graphql.js

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/graphql/graphql-js/issues/1075#issuecomment-387964268>,
or mute the thread
