### ISSUE TITLE
Dynamically constructed fields cannot return a promise

### ISSUE THREAD

**Issue by ana0** [graphql/graphql-js#1076]
I'm trying to dynamically construct a type based on objects in my database, but having trouble getting `fields` to return a promise

```
const buildParentFields = () => {
  return Parents.find().lean()
    .then((parents) => {
      const fields = {};
      parents.forEach((parent) => {
        fields[parent.name] = { type: parentType, };
      });
      return fields;
    });
};

export default new GraphQLObjectType({
  name: 'someType',
  fields: () => {
    return {
      parents: {
        type: new GraphQLObjectType({
          name: 'parents',
          fields: buildParentFields,
        }),
        resolve: someResolver,
      }
    };
  },
});
```

Throws `Error: parents._bitField field config must be an object`

I've followed it down to resolveThunk not expecting a promise, but small patches in here are turning up larger assumptions about the schema building process.

```
function resolveThunk(thunk) {
  return typeof thunk === 'function' ? thunk() : thunk;
}
```

Thoughts?  A quick glance at the spec isn't turning up anything saying that this can't be an asynchronous process.  

Also, suggestions on how to get this to work very much appreciated

**Comment by IvanGoncharov** [comment]
@ana0 You forget to add return in this line
> **return** Parents.find().lean()

So in your example, `buildParentFields ` returns `undefined` instead of Promise.

**Comment by ana0** [comment]
Thanks @IvanGoncharov - mistake in the issue, not in my actual code.  Edited to fix.  

Error continues and is `Error: parents._bitField field config must be an object`

**Comment by leebyron** [comment]
The fields themselves must not be a promise since they need to be immediately invokeable from the type definition, however you could have a promise which resolves the entire schema which does this work before hand.
