### ISSUE TITLE
[meta] Speed up loading of schema

### ISSUE THREAD

**Issue by kassens** [graphql/graphql-js#1079]
This is a meta issue tracking progress on significantly speeding up loading a schema from disk. There are multiple incremental steps that should get us there.

- [x] Split validation from instantiation. If we have a schema persisted on disk and know that we already validated it before, there's no reason to validate it *again• every time we want to load it (#1080).
- [ ] Change from classes to simple data objects that are manipulated and queried using functions. This would allow the schema to be persisted and loaded as a plain JSON object.

Note: This is still just a rough outline and there's likely more steps to get there including making sure this is an incremental change and doesn't break existing users unexpectedly.

**Comment by IvanGoncharov** [comment]
Closing since, schema loading performance increased dramatically in recent years.
Also, there are no other reports about schema loading performance.
