### ISSUE TITLE
Modularizing GraphQL schemas with nested schemas

### ISSUE THREAD

**Issue by francisngo** [graphql/graphql-js#1087]
I am currently working on a project where I am learning GraphQL. I have two types that has nested schemas. In one type, the UserType, I am requiring another type, the ReviewType because the user will have many reviews so I want GraphQL to return all the reviews that the user is associated with. Now, if I was also to request for reviews, I'd like it to return the user who is associated with it. But when I try to import the files for both, I get an error:

`Error: review.user field type must be Output Type but got: [object Object].`

In UserType, I require ReviewType and create a field: 

```
const ReviewType = require('../reviews/type');
const UserType = new GraphQLObjectType({
  ...
  ...
  fields: () => ({
    ...
    reviews: {
      type: new GraphQLList(ReviewType),
      resolve(user) { 
        return user.getReviews();
      },
    },
  });
});
```

This will work if I do not try to import UserType in ReviewType or vise versa. But, when I do, I get the error.

In ReviewType, I require UserType and create a field: 

```
const UserType = require('../users/type');
const ReviewType = new GraphQLObjectType({
  ...
  ...
  fields: () => ({
    ...
    user: {
      type: UserType,
      resolve(review) {
        return review.getUser();
      },
    },
  });
});
```
As I understand, Apollo-Server has something that is called makeExecutableSchema but I am not sure what is equivalent to that in graphql-js. How might I resolve this synchronous issue?

**Comment by leebyron** [comment]
This looks like it may simply be a circular import issue. I suggest doing some research on circular node requires. The solution is usually replacing `module.exports = something` with `exports.something = something`.
