### ISSUE TITLE
RFC: WithMetadata modifier

### ISSUE THREAD

**Issue by brysgo** [graphql/graphql-js#1089]
WithMetadata Modifier

When wrapped a WithMetadata Modifier, a scalar field can have an optional
selection underneath it. When a selection is present, the value field holds
the scalar, when a selection is not present, the scalar is returned.

Example:
```javascript
const NameType = new WithMetadata(GraphQLString, new GraphQLObjectType({
  name: 'Name',
  fields: () => ({
    firstName: { type: GraphQLString },
    middleName: { type: GraphQLString },
    lastName: { type: GraphQLString },
    nickname: { type: GraphQLString }
  })
}))
```

Or in graphql:

```graphql
type Name: String {
  firstName: String
  middleName: String
  lastName: String
  nickname: String
}
```

Not sure if #914 helps to make this possible, would love to hear everyone's thoughts.

**Comment by IvanGoncharov** [comment]
@brysgo This feature requires changes to GraphQL specification so it should be discussed in this repo: https://github.com/facebook/graphql
For example #914 is based on https://github.com/facebook/graphql/pull/326
Can you please move your issue there?

**Comment by brysgo** [comment]
Alright @IvanGoncharov - see 381 above ^^^

**Comment by leebyron** [comment]
Closing here in favor of non-library-specific discussion
