### ISSUE TITLE
Empty selections work with printer, but throw a parser error

### ISSUE THREAD

**Issue by brysgo** [graphql/graphql-js#1092]
(Thanks again for writing these awesome tools!)

Expectation: GraphQL printed by printer always parses as valid

Result: If printing GraphQL that has an empty selection, subsequent parsing of the GraphQL throws a parser error.

This doesn't have a huge impact unless you are trying to write tools to manipulate graphql language and reprint it. Hence, probably pretty low priority but I figured I'd point it out.

**Comment by leebyron** [comment]
Thanks for the report. I've fixed this in the master branch and will have a release soon.
