### ISSUE TITLE
is type Case Sensitivity?

### ISSUE THREAD

**Issue by YoungPeanut** [graphql/graphql-js#1138]
is type in graphql Case Sensitivity? ....

**Comment by leebyron** [comment]
Yes it is

**Comment by YoungPeanut** [comment]
@leebyron thx.   and type must begin with a capital letter？

**Comment by leebyron** [comment]
Types may be any valid name, however it is a common convention to start type names with a capital letter.

Read more about that here: http://facebook.github.io/graphql/October2016/#sec-Names
