### ISSUE TITLE
Coercing variables

### ISSUE THREAD

**Issue by freiksenet** [graphql/graphql-js#115]
Currently Scalar types have two methods `coerce` and `coerceLiteral`. `coerceLiteral` is used to create a javascript value from ast, `coerce` is used both on variables and on data received from resolve in executors. 

Unfortunately that is not enough - variables usually come from some format like `json` which wouldn't always support all the new scalar types and most likely will return them as string. On the other hand, eg, databases might return types in javascript format already. Therefore `coerce` can't support both variable coercion and execution coercion.

@leebyron suggested that for variable coercion, a new method is added to the Scalars - `coerceVariable`.

**Comment by freiksenet** [comment]
Okay, so we cleared it with @leebyron. `coerce` is actually a function that should do serialization. We've agreed to rename `coerce` to `serialize`, rename `coerceLiteral` to `parseLiteral` and add `parseVariable`.

I'll try to make a PR asap.

**Comment by leebyron** [comment]
Merged in! this will be in the next release.

**Comment by Dashed** [comment]
These changes should reflect onto the docs: http://graphql.org/docs/api-reference-type-system/#graphqlscalartype

When playing with graphql-js, I got super confused on why `coerce` stuff was missing and not working.
