### ISSUE TITLE
multiple query response needed 

### ISSUE THREAD

**Issue by waheed25** [graphql/graphql-js#1151]
i needed a response two queries in a file one is node query and the other is viewer query. I wrap it with graphql like that
`export default graphql(nodeQuery)(graphql(viewerQuery)(Component));`
but i always getting response of first query mean which query is written first and i didn't get response of second one.please suggest me some solution.

**Comment by leebyron** [comment]
Try:

```
const [nodeResults, viewerResults] = await Promise.all([
  graphql(nodeQuery, ...),
  graphql(viewerQuery, ...),
]);
```

This will run both queries in parallel and get both responses at the same time.
