### ISSUE TITLE
Passing field arguments to type definition for multiple representations

### ISSUE THREAD

**Issue by kbrandwijk** [graphql/graphql-js#1154]
I have a number of use cases where data can have multiple representations. For example: numbers can have a decimal, hexadecimal, binary, etc. representation. Temperatures can have a Celcius or Fahrenheit representation, measurement units have different representations.

The only way to implement this right now, is by adding a parameter to the fields, and implement the conversion/formatting in the resolvers.

It would be great if it was possible to move this implementation to one central place, the GraphQLScalarType definition. This could be easily achieved by passing field arguments to the `serialize` method on the type definition. For example:
```graphql
scalar ExtendedNumber
scalar Temperature

type MyType {
   value(base: Int): ExtendedNumber 
   temperature(unit: String): Temperature
}
```
With type definitions:
```js
const extendedNumberScalarType = new GraphQLScalarType({
  name: 'ExtendedNumber',
  description: 'Description of my custom scalar type',
  serialize: (value, { base }) => value.toString(base),
  parseValue: (value) => value,
  parseLiteral: (ast) => ast.kind === Kind.INT ? value : null
  }
});

const temperatureScalarType = new GraphQLScalarType({
  name: 'Temperature',
  description: 'Description of my custom scalar type',
  serialize: (value, { unit }) => unit === 'C' ? value : value * 1.8 + 32,
  parseValue: (value) => value,
  parseLiteral: (ast) => ast.kind === Kind.FLOAT ? parseFloat(value) : null
  }
});
```
Note that this is fully backwards compatible. It is completely optional to use the `parameters` passed in as second argument to `serialize`, but it would really help to move all these similar implementations to a central place.

**Comment by leebyron** [comment]
Arguments are properties of the fields they're attached to, not the types they return. I'd be interested in seeing a PR which implements what you propose, but I have a feeling it may look messy due to the concepts being unrelated in semantics and implementation.

**Comment by IvanGoncharov** [comment]
I agree with Lee that scalar type should be independent of field arguments.
Plus it very easy to solve this problem with a very simple Higher-order function:
```js
function convertTemperatureUnits(resolver) {
  return (parent, args, context, info) => {
     const { unit } = args;
     const result = resolver(parent, args, context, info);
     return unit && unit === 'F' ? value * 1.8 + 32 : values;
  }
}
```

I don't see any PR or activity in the last 6 month so I close this issue but feel free to submit PR as Lee suggested.
