### ISSUE TITLE
Issue with Flow 0.61.0 and graphql function

### ISSUE THREAD

**Issue by lgraziani2712** [graphql/graphql-js#1177]
### Description

When I'm trying to excecute graphql (I'm writting my first grapqhl test), Flow reports this error:

```js
const { graphql } = require('graphql');

const result = await graphql(executableSchema, query, rootObj, context);
//                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Promise. This type is incompatible with the expected param type of
declare function $await<T>(p: Promise<T> | T): T;
//                            ^^^^^^^^^^^^^^ union: `Promise` | `T`. See lib: C:\Users\~\AppData\Local\Temp\flow\flowlib_fe9353\core.js:613
```

I'm doing something wrong?

### Extra information

- Flow version: v0.61.0
- graphql-js version: v0.12.3

Thank you!

**Comment by leebyron** [comment]
Definitely strange! This library uses Flow 0.61 and has all tests passing right now, so it's possible something else is wrong. Can you include a full output of any Flow errors?
