### ISSUE TITLE
Is this supposed to not parse anymore?

### ISSUE THREAD

**Issue by vjeux** [graphql/graphql-js#1186]
I'm trying to upgrade prettier to the latest version of the GraphQL spec (from 0.10.5 to 0.12.3) and the following no longer parse:

```js
    SyntaxError: Syntax Error: Unexpected Name "FIELD1" (1:17)
    > 1 | directive @a on FIELD1
        |                 ^
```

Is this supposed to not parse anymore or is it a mistake? It happens in a few places in prettier test suite.

**Comment by vjeux** [comment]
All those syntax error after the `on` keyword

```js
directive @a on FIELD1
directive @a(as: String) on FIELD1
directive @a(as: String = 1) on FIELD1
directive @a(as: String, b: Int!) on FIELD1
directive @a(as: String! = 1 @deprecated) on FIELD1
directive @a(as: String! = 1 @deprecated) on FIELD1 | FIELD2
```

**Comment by IvanGoncharov** [comment]
> Is this supposed to not parse anymore or is it a mistake?

@vjeux It's invalid since `FIELD1` is not a correct location, here is list of supported locations:
https://github.com/graphql/graphql-js/blob/master/src/language/parser.js#L1413-L1433

> Syntax Error: Unexpected Name "FIELD1" (1:17)

This error message looks confusing and it would be great if someone improves it.

**Comment by vjeux** [comment]
I'm trying to write something that parses but I'm miserably failing :( Would you be able to write me an example of something that parses after `on`? Thanks!

**Comment by vjeux** [comment]
Nevermind, the things commented with backticks were not types but literals. This works:

```js
directive @a(as: String! = 1 @deprecated) on QUERY | MUTATION
```
