### ISSUE TITLE
"""\nabc\n""" and """abc""" are not distinguishable from the ast

### ISSUE THREAD

**Issue by vjeux** [graphql/graphql-js#1188]
Both of then look exactly the same. I would expect \n to be part of the value.

```js
"""abc"""
type T {
  a: Int
}

"""
abc
"""
type T {
  a: Int
}

```

```js
{ kind: 'StringValue',
  value: 'abc',
  block: true,
  loc: { start: 0, end: 9 } }
{ kind: 'StringValue',
  value: 'abc',
  block: true,
  loc: { start: 31, end: 42 } }
```

**Comment by IvanGoncharov** [comment]
@vjeux It's intentional:
> Note: Block string values are interpreted to exclude blank initial and trailing lines and uniform indentation with {BlockStringValue()}.

https://github.com/facebook/graphql/blob/master/spec/Appendix%20B%20--%20Grammar%20Summary.md#lexical-tokens

**Comment by vjeux** [comment]
Thanks for the quick reply. This is unfortunate as it means I have to read from the raw input to print it as it was entered... I can live with it though!

**Comment by lydell** [comment]
I’m not 100% sure this is an issue: https://github.com/prettier/prettier/pull/3605#discussion_r159255170

**Comment by IvanGoncharov** [comment]
@vjeux I saw you [removed workaround](https://github.com/prettier/prettier/commit/5356db0e696b970bff91a42bc644cf90c267b685#diff-e6e272291fd4f200aa8617e6548d62b3L129) from `prettier`.
Does it mean that your problem is solved and this issue could be closed?

**Comment by vjeux** [comment]
Yes, sorry!
