### ISSUE TITLE
"Arg must supply type" error message seems to include field index rather than field name.

### ISSUE THREAD

**Issue by johanatan** [graphql/graphql-js#121]
e.g., 

```
  "errors": [
    {
      "message": "Arg must supply type. createSite.0", ...
```

And this is the relevant portion of my _schemaConfig:

```
{ type: 
   { name: 'Site',
     description: undefined,
     _typeConfig: { name: 'Site', fields: [Function] },
     _interfaces: [] },
  args: 
   [ { name: [Object] },
     { address: [Object] },
     { owner: [Object] },
     { nodes: [Object] } ],
  resolve: [Function] }
```

[As you can see, the 'type' fields are indeed missing from the args yet a more useful error message would include the field name (and the source code `/node_modules/graphql/type/definition.js:259` does seem to attempt to print the field name)].

**Comment by johanatan** [comment]
Oops, sorry. Types are embedded inside those [Object]s.

**Comment by johanatan** [comment]
Turns out that the issue is that `args` is an array above (rather than an object). Still think there is opportunity for a better message here: maybe assert that `args` is an object rather than an array?

**Comment by johanatan** [comment]
Re-opening in light of the completion of root cause analysis.

**Comment by leebyron** [comment]
Thanks for the report! I agree the error messaging could be a lot better here. I'll get to work!
