### ISSUE TITLE
Provide .mjs enty for native ESM

### ISSUE THREAD

**Issue by jaydenseric** [graphql/graphql-js#1217]
This will make it possible for packages dependant on `graphql` to in turn do the same for their consumers, without encountering https://github.com/babel/babel/issues/7294.

[Node.js with `--experimental-modules` can run ESM in .mjs files](https://nodejs.org/api/esm.html#esm_ecmascript_modules).

Essentially, package.json needs to go from this:

```json
{
  "main": "index.js",
  "module": "module/index.js"
}
```

To this:

```json
{
  "main": "index",
  "module": "index.mjs"
}
```

Sibling `index.js` (CJS) and `index.mjs` (ESM) files need to be published. Node.js will load the relevant file, looking up `.mjs` before `.js` for `main` if `--experimental-modules` is enabled.

**Comment by leebyron** [comment]
I'm happy to entertain PRs that add this functionality to the build process. We already produce module files, which are used by rollup and other ES6 aware bundlers. Is all that necessary is changing file extension?

**Comment by leebyron** [comment]
@jaydenseric I just put up a PR which seeks to support this case - would you might helping out with a test case? Even if you want to just pull down the PR and run the build to see if the resulting output solves things for you
