### ISSUE TITLE
0.13-rc.1 notice for maintainers who build tools around graphql-js 

### ISSUE THREAD

**Issue by nodkz** [graphql/graphql-js#1221]
If your tool uses AST type checks something like:
```js
import { LIST_TYPE, NON_NULL_TYPE, DOCUMENT, NAMED_TYPE } from 'graphql/language/kinds';

...
if (inputTypeAST.kind === LIST_TYPE) { ...
```

You need to change your code in following manner:
```diff
- import { LIST_TYPE, NON_NULL_TYPE, DOCUMENT, NAMED_TYPE } from 'graphql/language/kinds';
+ import { Kind } from 'graphql';

...
- if (inputTypeAST.kind === LIST_TYPE) { ...
+ if (inputTypeAST.kind === Kind.LIST_TYPE) { ...
```

According to last [improvements for v0.13.0](https://github.com/graphql/graphql-js/commit/17a0bfd5292f39cafe4eec5b3bd0e22514243b68#diff-fc9da17436b6ffdf301f6e41e53fc207) by @IvanGoncharov you not able to import desired AST types directly from `graphql/language/kinds`. 

And if you want that your tool must **support new and old versions of graphql lib**, please use code above.

**Comment by IvanGoncharov** [comment]
If possible you should use:
```graphql
  import { Kind } from 'graphql';
```

 I didn't think it will break any 3rd-part code since `graphql/*` files are treated like private API.
@nodkz Did you use `graphql/*` files to minimize bundle size or you need to import some private APIs?

**Comment by nodkz** [comment]
It breaks my graphql-compose, already fixed.
And 82 other repos https://github.com/search?l=JavaScript&q=%22graphql%2Flanguage%2Fkinds%22&type=Code&utf8=%E2%9C%93

**Comment by nodkz** [comment]
It's our problem, that we use internals imports. 
So don't worry. Your work is amazing!

**Comment by leebyron** [comment]
Thanks for highlighting this! I'm going to close the issue, but reference it as a potentially breaking change from the release notes!
