### ISSUE TITLE
Allow for legacy comment descriptions in `parse` like is supported in `buildASTSchema`

### ISSUE THREAD

**Issue by mikeparisstuff** [graphql/graphql-js#1236]
The implementation of *buildASTSchema* allows you to pass the options object with the *commentDescriptions* key set to true to enable legacy description comments. It would be great if this were exposed in both the *parse* and *print* functions that operate on the AST as well.

**Comment by IvanGoncharov** [comment]
@mikeparisstuff To work with legacy comment descriptions you can use this function:
https://github.com/graphql/graphql-js/blob/81db4101853924327c53b2fe389b4ab032cd178d/src/utilities/buildASTSchema.js#L470-L482
It's the same function that `buildASTSchema` schema uses internally so by passing `{ commentDescriptions: true }` as options you would get the description from comment.

**Comment by leebyron** [comment]
@mikeparisstuff - comments as descriptions vs the spec compliant block strings does not affect the behavior of parse. No option is needed there.

For printing, you're likely looking for the `printSchema()` function which accepts  `commentDescriptions` as an option as you're looking for.
