### ISSUE TITLE
parseType check if is GraphQLScalarTypes

### ISSUE THREAD

**Issue by j** [graphql/graphql-js#1238]
I want to be able to dynamically create GraphQLString / other GraphQLScalarTypes from simple strings.

I was trying to use parseType and it seems to get close.

How can I get to this result: `parseType('String!') is object like new GraphQLNonNull(GraphQLString)`?

Thanks!

**Comment by IvanGoncharov** [comment]
@j You should use `typeFromAST`:
https://github.com/graphql/graphql-js/blob/98751e473fd7a02c514af48218d87d26daadb5f5/src/utilities/typeFromAST.js#L20-L28

**Comment by IvanGoncharov** [comment]
@j Did I answer your question or do you need additional help?

**Comment by leebyron** [comment]
typeFromAST is definitely what you're after!

**Comment by j** [comment]
Hey @IvanGoncharov and @leebyron.  Yep!  It was definitely typeFromAST.  Thanks.

**Comment by githbq** [comment]
how can I use typeFromAST ,  it need two parameters ,  first is  shcme , and second is NamedTypeNode ,

what can I make the second parameter , what is NamedTypeNode if I only has a string of graphql language
