### ISSUE TITLE
input type mutation for

### ISSUE THREAD

**Issue by pratibha2** [graphql/graphql-js#1239]
mutation {
    createCourse(title:"react",description:"happy",
      courseCode:"white",courseCategory:{name:"happy"}){
      id
     courseCode
     title
     description
    courseCategory{
      name
    }
    }
  }

**Comment by IvanGoncharov** [comment]
@pratibha2 Can you please provide the more detailed description for your problem?
Please note that issues in this repo are intended for bug reports and feature requests if you have a question regarding how to use graphql [please post it to stackoverflow](https://github.com/graphql/graphql-js/blob/master/.github/ISSUE_TEMPLATE.md#questions-regarding-how-to-use-graphql).

**Comment by pratibha2** [comment]
error while performing 2 queries simultaneously in apollo react
const  LOCATION_QUERY = gql`
query {
  allLocations {
        city
  }
}
`;
const  INSTRUCTOR_QUERY = gql`
query {
  allInstructors {
    id
        name
  }
}
`;
export default compose(
        graphql(LOCATION_QUERY,{name:'allLocations'}),
        graphql(INSTRUCTOR_QUERY,{name:'allInstructors'})
  
      )(AddBatch);

**Comment by IvanGoncharov** [comment]
@pratibha2 Can you please post the error message here?
Also please use [code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in your comments, it makes them more readable.

**Comment by leebyron** [comment]
Please bring issues like this to the appropriate repository
