### ISSUE TITLE
printSchema: not valid comments

### ISSUE THREAD

**Issue by hendrul** [graphql/graphql-js#1245]
I must be doing something wrong, no one else seems to complain... my schema is being printed with comments with wrong syntax like...
```graphql
"""
A signed eight-byte integer. The upper big integer values are greater then the
max value for a JavaScript number. Therefore all big integers will be output as
strings and not numbers.
"""
scalar BigInt
```
the expected syntax is
```graphql
# A signed eight-byte integer. The upper big integer values are greater then the
# max value for a JavaScript number. Therefore all big integers will be output as
# strings and not numbers.
scalar BigInt
```

**Comment by hendrul** [comment]
Ohh I see, it has an undocumented option "commentDescriptions"
```
// Generates comments right
printSchema(schema, { commentDescriptions: true })
```

**Comment by galki** [comment]
did that option work for you?

**Comment by IvanGoncharov** [comment]
> the expected syntax is

@hendrul Version `0.13.0` introduced some breaking changes to SDL syntax, see here:
https://github.com/graphql/graphql-js/releases/tag/v0.13.0

`commentDescriptions` was added as an option to provide the backward compatible format of descriptions.

**Comment by hendrul** [comment]
Ok I see, cool!, now this option needs to be known

**Comment by leebyron** [comment]
This behavior has been around since v0.12 and was documented in the release notes!
https://github.com/graphql/graphql-js/releases/tag/v0.12.0

Note that the block string is the correct syntax for descriptions in the SDL - we used to use comments before we had a completed specification for this feature.
