### ISSUE TITLE
printSchema relay-complier error

### ISSUE THREAD

**Issue by galki** [graphql/graphql-js#1246]
After updating from `0.11.7` to `0.13.0` and adding the `{ commentDescriptions: true }` option to printSchema, relay-compiler produces the following error when compiling the printed schema:
```
Error loading schema. Expected the schema to be a .graphql or a .json
file, describing your GraphQL server's API. Error detail:

GraphQLError: Syntax Error GraphQL request (5:36) Cannot parse the unexpected character "&".
```
#### error line from 0.13.0 generated schema:
`type Hub implements HubInterface & Node {`

#### same line from 0.11.7 generated schema:
`type Hub implements HubInterface, Node {`

**Comment by IvanGoncharov** [comment]
@galki Version `0.13.0` introduced breaking changes into SDL syntax, see here:
https://github.com/graphql/graphql-js/releases/tag/v0.13.0

Master branch of relay was updated to work with it: https://github.com/facebook/relay/commit/c433f8b5a7a0482c3b12fb045b4fa56ba083ee32
But as I understand it wasn't released yet.
I would suggest report it to Relay repo.

**Comment by galki** [comment]
waiting for relay support https://github.com/facebook/relay/issues/2323

**Comment by IvanGoncharov** [comment]
@galki Since there is nothing we can do in `graphql-js` can I close this issue?

**Comment by leebyron** [comment]
Relay v1.5.0 was released today which supports the latest changes in GraphQL.js v0.13.0. If you're updating to v0.13.0 make sure you're using this latest version of Relay.
