### ISSUE TITLE
How to set directives for fields when creating GraphQLObjectType?

### ISSUE THREAD

**Issue by nodkz** [graphql/graphql-js#1262]
Can somebody share proper way how to pass `directives` for fields when creating type via `GraphQLObjectType`? I want to integrate [graphql-cost-analysis](https://github.com/pa-bru/graphql-cost-analysis) to our GraphQL Schema.

A [astNode](https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/type/definition.js#L757): [FieldDefinitionNode](https://github.com/graphql/graphql-js/blob/499a75939f70c4863d44149371d6a99d57ff7c35/src/language/ast.js#L436-L444) in `GraphQLFieldConfig` is ReadOnly and there is now way to write directives via object config. Or i something missing?

Desired way to declare directive will be such:
```js
const UserType = new GraphQLObjectType({
  name: 'User',
  fields: {
    name: {
      type: GraphQLString,
      description: '...',
      resolve: () => ...,
      directives: [
        { name: 'cost',  args: { useMultipliers: false, complexity: 2 } },
        { name: 'unique' },
      ],
      // or maybe simpler if graphql spec does not allow duplicated names
      directives: {
        cost: { useMultipliers: false, complexity: 2 },
        unique: true,
      },
    },
  },
});
```

cc @IvanGoncharov @leebyron

**Comment by IvanGoncharov** [comment]
@nodkz It was already discussed in my PR that added `astNode` feature and @leebyron had the following position: https://github.com/graphql/graphql-js/pull/746#issuecomment-301554231

> Right now directives are purely a feature of the GraphQL language and IDL, so a schema not created using IDL definitionally won't contain directives. When building a schema in code, you have the full power of the host programming environment, so directives shouldn't be necessary. Directives are a tool for supplying additional intent to be later interpreted by the host programming environment.

Also, I think this question is connected to the topic discussed on the last WG: [Exposing schema metadata](https://github.com/graphql/graphql-wg/blob/master/notes/2018-02-01.md#exposing-schema-metadata). So I think we should decide what we expose through introspection(directives or something else) and then add the same thing to `GraphQL*Type` classes.

**Comment by leebyron** [comment]
Yeah - I stand by that comment.

You can include any arbitrary data on a GraphQLObjectType that you like - it's just a JS object after all. Directives are a language-level feature, not a structural property of a type.

Typically tools which use directives in the SDL are adding properties to the created underlying type objects to track within their runtimes.

**Comment by SamMaxwell** [comment]
The GraphQL schema and the GraphiQL browser provide accessible and interactive documentation for the available query types and mutations of a system. It demos quite nicely. If the GraphQLObjectType supported directives it could become just more helpful documentation for the API surface.

The GraphQLFieldConfig includes a deprecationReason.

I developed a dynamic relay server that introspects SQL Server metadata and builds a schema dynamically at runtime. It has a plugin system to allow programmatic enhancement to the schema just prior to firing up the graphQLHTTP middleware.

It would be awesome to allow the domain-specific developer to add directives to the types and fields to document the security scheme (for example) via the plugin mechanism.

Cc: @IvanGoncharov @leebyron
