### ISSUE TITLE
Memory leak during buildASTSchema

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#1265]
Something between v0.12.0 and v0.13.1 has introduced a memory leak when building a schema from SDL - on large schemas this can result in the node process running out of memory and exiting early.

I'm not sure yet what the blame is since I haven't found a consistent repro, but I suspect #1230

Will share what I find here

**Comment by IvanGoncharov** [comment]
@leebyron Can I help somehow?

**Comment by leebyron** [comment]
I'm still working on getting a consistent repro of the leak :/

**Comment by leebyron** [comment]
Ok, I think this was actually a false report - I've done some analysis of heap size after using buildASTSchema to construct a very large schema (facebook's schema) in a loop. There does not seem to be a leak and there does not seem to be any meaningful change in heap size after each construction between versions v0.12.0, v0.13.0, or v0.13.1.

We should still try to do as best as we can to limit the size of the heap when building up a schema, since this ends up being a constant factor in any tool.
