### ISSUE TITLE
Migrate to Babel 7

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#1266]
Following React's move to Babel v7, GraphQL.js should do the same. The babel config for this project is not that complex, so hopefully this is an easy transition.

**Comment by leebyron** [comment]
Something to consider is Babel v7 may not build correctly on Travis CI's Node v4 subjob. Technically we don't care about Babel builds on Node v4, but we do want the npm distributed bundle to be Node v4 safe - at least through the LTS window (end of April)

We could either: 
* drop the CI job early and keep our fingers crossed and eyes open, 
* wait to do this migration until May
* write a slightly complex CI job that uses a different version of node to run the build than run the tests on the output

**Comment by Thezone1975** [comment]
I agree, this was dragged and dropped on my Facebook page while I was at work today, by a "friend" who happens to be a girl, it has 3 or more mistakes that I found, but my pages that I have have gone out of control. System Prune?  Any input.

**Comment by AaronCCWong** [comment]
Is this waiting on babel v7 to come out of beta?

**Comment by IvanGoncharov** [comment]
Implemented in #1350 by @AaronCCWong 👍

**Comment by leebyron** [comment]
Great work, @AaronCCWong!
