### ISSUE TITLE
Entire result thrown away after error on part of the query

### ISSUE THREAD

**Issue by itilitymaarten** [graphql/graphql-js#1271]
I have a query like the following:
```
{
      root1(arg1: "arg-content") {
        field1
        subField {
          field3
          field4
        }
      }
      root2(arg1: "other-arg-content") {
        field1
        field2
      }
      root3(arg1: "more-arg-content", arg2: "even-more-arg-content") {
        field1
        field2
      }
    }
```

The way I understand the GraphQL spec (http://facebook.github.io/graphql/October2016/#sec-Response), if an error occured in resolving `root3`, I should still be getting the results from `root1` and `root2` in my `data` field, with the error from `root3` in `errors`.

The error from `root3` is properly returned, however the `data` field is empty.

It seems that this issue only occurs for the "root" fields; if the resolver for `subField` fails, the result of `root1` is still nicely returned along with the errors that occured.

I am using graphql-js version 0.13.1. My resolvers make HTTP calls and return Bluebird promises for them. When the HTTP call was successful, the promise fulfills with the response. If errors were found in the HTTP call, or the HTTP call itself failed (usually the former happens), the promise is rejected.

**Comment by IvanGoncharov** [comment]
@itilitymaarten Please make sure that `root3` is a nullable type.
If it's wrapped with non-null then it's expected behaviour:
http://facebook.github.io/graphql/draft/#sec-Errors-and-Non-Nullability

> Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

> If all fields from the root of the request to the source of the error return Non-Null types, then the  "data" entry in the response should be null.

**Comment by itilitymaarten** [comment]
@IvanGoncharov Ah...it was indeed non-nullable, I hadn't realized that. I had expected that a second error would be raised to indicate that the non-nullable `root3` had received the value null, but the spec says that shouldn't happen :)

Thank you for your response, and my apologies for not knowing the spec well enough to expect this behaviour!
