### ISSUE TITLE
Circular import breaks building with Google Closure Compiler

### ISSUE THREAD

**Issue by Jannis** [graphql/graphql-js#1275]
There is a circular dependency between `type/definition.js` and `type/wrappers.js`, which breaks building graphql-js with the Google Closure Compiler (which has no solution to breaking circular imports yet, see [this issue](https://github.com/google/closure-compiler/issues/1883)).

The affected code is located here:

https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L35

and

https://github.com/graphql/graphql-js/blob/master/src/type/wrappers.js#L10-L11

Any chance we could break this cycle? Among other things, it would allow to include graphql-js seamlessly in ClojureScript via its new `:npm-deps` feature.

**Comment by IvanGoncharov** [comment]
The simplest solution would be to just merge `wrappers.js` into `definitions.js`.
Or we can minimize changes somehow?

@Jannis Do you want to work on this PR?

**Comment by Jannis** [comment]
@IvanGoncharov Sure, I can cook something up.
