### ISSUE TITLE
Throw error if no possible concrete types found

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#1277]
While using relay modern v1.5.0, I got the following when running relay-compiler (I promise this is a graphql issue):

```sh
ERROR:
Cannot read property 'some' of undefined
error An unexpected error occurred: "Command failed.
Exit code: 100
```
Note that the error has no stack trace!

The `some` that it mentioned was:
```js
	function hasConcreteTypeThatImplements(schema, type, interfaceName) {
	  return isAbstractType(type) && getConcreteTypes(schema, type).some(function (concreteType) {
	    return implementsInterface(concreteType, interfaceName);
	  });
	}
```

Ultimately, this was caused because when graphql built my schema, it crawled & found the GraphQLInterfaceType, but it didn't find the concrete types that implemented the interface.
This didn't throw an error in GraphQL; however, calling `schema.getPossibleTypes` returned `undefined`, which borked it in the compiler.

While it'd be nice for relay-compiler to catch errors & include a stack trace, I think the real issue is that GraphQL allows an abstract type to exist without any concrete types!

I propose closing this hole by calling schema.getPossibleTypes for each abstract type when building the schema. if the result is `undefined` then throw a friendly error telling the user to add that concrete type to their `rootSchema.types`.

Happy to PR if this sounds like a reasonable plan!

**Comment by IvanGoncharov** [comment]
@mattkrick Sounds very reasonable to me 👍
I think it should be fixed in 3 places:
1. `getPossibleTypes` should always return an array even if empty. It's required since schema validation is optional since #1132.
2. Add new validation here: https://github.com/graphql/graphql-js/blob/master/src/type/validate.js#L259
3. Add new validation to the specification, here: https://github.com/facebook/graphql/blame/master/spec/Section%203%20--%20Type%20System.md#L973

**Comment by mattkrick** [comment]
Wow, thank you @IvanGoncharov that made the PR super easy!
After reviewing the spec, I saw it already mentioned this issue, so there was no need to update it: 
 
Spec:  
> An Interface type must define one or more fields

**Comment by IvanGoncharov** [comment]
> An Interface type must define one or more fields

@mattkrick Prevents you from writing without fields:
```graphql
interface NoFields {
}
```
So it's different check.
