### ISSUE TITLE
Feature Request - Allow Directives to Modify Query Description

### ISSUE THREAD

**Issue by jdolle** [graphql/graphql-js#1283]
I would like to be able to expose directive usage through Graphiql. This would be incredibly useful for documenting field requirements/behavior. A good example would be authentication -- if I apply a custom `@authorized` directive to a field, I would like the description to mention that the user must be authorized.

**Comment by leebyron** [comment]
Please open these kinds of issues on the GraphQL spec repository: https://github.com/facebook/graphql/

There's already active discussion about adding metadata to the introspection API, which you might want to take part in. Directives are purely a syntactical construction - which could be used to represent metadata in those discussions' proposals.
