### ISSUE TITLE
Exported names for types

### ISSUE THREAD

**Issue by taion** [graphql/graphql-js#130]
Currently, types are exported with names qualified by `GraphQL`: https://github.com/graphql/graphql-js/blob/v0.4.2/src/index.js#L13-L35

This is inconsistent with both React and Relay, which strip qualifiers from the exported names, e.g.: https://github.com/facebook/relay/blob/v0.1.1/src/RelayPublic.js#L41-L46

If the variables were instead exported without the qualifier as e.g. `Schema`, `ScalarType`, `ObjectType`, &c., then users could also import them with e.g. `import * as GraphQL from 'graphql'`, and access them as e.g. `GraphQL.Schema`, `GraphQL.ScalarType`, `GraphQL.ObjectType`, &c., which ends up being very similar to the status quo, just with a bit less typing on the `import` line.

The saving of typing is a bit petty since I'm hopefully only doing this once per project, but it might be nicer for the naming to be more consistent with React and Relay?

**Comment by leebyron** [comment]
Thanks for the feedback. I'm working on a broader re-working of the type definition API I've started to track in #134 which I will merge this feedback into.
