### ISSUE TITLE
Development on Windows and VS Code

### ISSUE THREAD

**Issue by mgrenier** [graphql/graphql-js#1320]
*This is not an issue.* I just wanted to document how to get development started on Windows + VS Code and didn't think of a better place.

The graphql-js project forces Windows developers to jump through some hoops before they can do anything.

*This guide was written for `graphql-js v0.13.2` commit 54f631ff3238affdddb4dc736fc282b620d70b15.*

**1. Windows Subsystem for Linux (WSL)**
This repository needs a Linux/OSX-like OS to work. Gladly, on Windows you can install *Linux subsystem for Windows*. [Here the official docs on how to install WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**2. Install a distro from the Windows Store**
Next step is to install a official distro from the store. You can install [Ubuntu 16.04 from the store](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6).

**3. Install Git, and Node**
Now, if you managed to log into your Ubuntu (just start `bash.exe`), you now need to install Git and Node : `sudo -s apt-get install -y git node`.

**4. Fork & clone graphql-js repository as you would normaly**
Please refer to the [official CONTRIBUTE.md](https://github.com/graphql/graphql-js/blob/master/.github/CONTRIBUTING.md)

**5. Inspect mocha tests with VS Code**
You'll need to change terminal used by VS Code. You can achieve that by changing either your workspace or user settings. Here's the settings for Ubuntu with `bash.exe`
```
"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\bash.exe",
```
Secondly, you'll need to create a launch config (`.vscode/launch.json`) with 
```
{
	"type": "node",
	"request": "launch",
	"name": "Launch mocha",
	"cwd": "${workspaceFolder}",
	"runtimeArgs": [
		"--inspect-brk",
	],
	"sourceMaps": true,
	"program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
	"args": [
		"--require",
		"babel-register",
		"--require",
		"${workspaceRoot}/resources/mocha-bootload",
		"--check-leaks",
		"--full-trace",
		"--timeout",
		"15000",
		"${workspaceRoot}/src/**/__tests__/**/*-test.js"
	],
	"env": {
		"NODE_ENV": "development"
	}
}
```
Finaly, you need to modify the `.babelrc`. Add the following lines :
```
"sourceMaps": "both",
"retainLines": true
```
*Please note that these changes should not be staged in your commit.*

**Comment by IvanGoncharov** [comment]
@mgrenier Not a Windows developer myself, but I thought that installing https://gitforwindows.org/ is enough. Did you try it?

**Comment by leebyron** [comment]
Hey @mgrenier this is great, but we're trying to keep issues focused on tasks to complete.

I'm going to close this issue as part of triage, but I'd highly recommend you resubmit this as a PR in something like `WindowsSetup.md`
