### ISSUE TITLE
getPossibleTypes should return an empty array, not undefined

### ISSUE THREAD

**Issue by lucasconstantino** [graphql/graphql-js#1335]
`getPossibleTypes` returns `undefined` when no type implements the provided abstract type. It should probably return an empty array for consistency.

https://github.com/graphql/graphql-js/blob/5dc773eaf16180a68c9bfe720b0405c283883d94/src/type/schema.js#L195-L202

**Comment by IvanGoncharov** [comment]
> getPossibleTypes returns undefined when no type implements the provided abstract type. It should probably return an empty array for consistency.

It's fixed #1280 but not released yet.
Note: Spec was changed to require that every interface has at least 1 concrete type
https://github.com/facebook/graphql/pull/424
So now such schema will fail during validation.

**Comment by lucasconstantino** [comment]
@IvanGoncharov thanks!
