### ISSUE TITLE
[bug] does not work with @angular/angular-cli@6.0.0

### ISSUE THREAD

**Issue by amitport** [graphql/graphql-js#1344]
The core issue is the same as https://github.com/angular/angular-cli/issues/10744
I'm not sure the fix should be only in `@angular-devkit`- to me it seems reasonable to expect that graphql lib provide a `.js` main file.

There is an additional complication. After editing `@angular-devkit` trying to fix `.mjs` issue according to https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574, I'm getting the following error:
```
instanceOf.mjs:3 Uncaught ReferenceError: process is not defined
    at Object../node_modules/graphql/jsutils/instanceOf.mjs (instanceOf.mjs:3)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/graphql/type/definition.mjs (vendor.js:151316)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/graphql/type/validate.mjs (vendor.js:153362)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/graphql/graphql.mjs (vendor.js:146722)
    at __webpack_require__ (bootstrap:81)
    at Object../node_modules/graphql/index.mjs (vendor.js:146842)
    at __webpack_require__ (bootstrap:81)
```

**Comment by Ben305** [comment]
This is a blocking issue for us. Is there any ETA for a fix?

**Comment by amitport** [comment]
@IvanGoncharov can we wait a couple of days until it will be included in some release? make sure everything is working OK together.

**Comment by IvanGoncharov** [comment]
> I'm still getting the instanceOf.mjs:3 Uncaught ReferenceError: process is not defined part. This lib still doesn't work with Angular@6.

@amitport It looks like this was fixed in 60c03ab23852074896fd9134c24c46ba595bf014 but not released yet. Can you please run your test on `master`, you can use built version from here:
https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge

**Comment by amitport** [comment]
Did work, though I got to say IMO it's missing the point made in https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814.

A library should not rely on a specific build tool, and in this case it relies on webpack to replace the `process.env.NODE_ENV === 'production'` block.  In this specific case, I would remove the `instanceof` wrap entirely for the same reason Angular removed `process` wrap. Shouldn't hide the real problem which is with npm/yarn. Plenty of other libs have the same concern.

Closing this. Thanks!

**Comment by Ben305** [comment]
@amitport Can confirm this works with @angular/cli 6.0.3 and latest master branch. Can we get a new release on NPM please?

**Comment by amitport** [comment]
@Ben305 worked for me with `@angular-devkit/build-angular@0.6.3` (Angular 6+ version is irrelevant) and `graphql@master`. 👍 for new graphql release (@leebyron ? not sure who should be tagged here :/ )

**Comment by Ben305** [comment]
Maybe @mjmahone could also publish a new release with this fix

**Comment by IvanGoncharov** [comment]
@Ben305 @amitport Update: @mjmahone working on `0.14.0` release, see here: https://github.com/graphql/graphql-js/pull/1346#issuecomment-391137211

**Comment by DmitryEfimenko** [comment]
when is this expected to be released?

**Comment by danutzcodrescu** [comment]
I have update to `graphql 14` and it solved the issue.

**Comment by Cybernetixs** [comment]
Yes, its a graphql issue, had the same problem with React@16, had to upgrade to graphql 14
