### ISSUE TITLE
Reproduce query structure despite parent nulls

### ISSUE THREAD

**Issue by KyleAMathews** [graphql/graphql-js#135]
Right now if the `parent` object doesn't exist in the following query, keys for `childA` and `childB` aren't returned.

```
node(id: $id) {
  parent {
    childA
    childB
  }
}
```

This complicates child code as there has to be defensive code to check if data is defined or not. It'd be nice if graph-ql would always return the full structure of the query e.g.

```javascript
{
  parent: {
    childA: null
    childB: null
  }
}

**Comment by leebyron** [comment]
There is a semantic difference between:

```js
{
  parent: {
    childA: null
    childB: null
  }
}
```

and 

```js
{
  parent: null
}
```

The former means that the `parent` field did return a value, however the `childA` and `childB` fields did not return values. the latter means that the `parent` field did not return a value.

The difference is often very important for applications to distinguish between, so I do not think it's safe for GraphQL to fill in child fields to make these two distinct cases indistinguishable.

> This complicates child code as there has to be defensive code to check if data is defined or not.

Can you illustrate what you mean by this? The child resolve functions should not be called at all if the parent field is null, so I don't think I follow.

**Comment by KyleAMathews** [comment]
That was a typo... should of been "this complicates *client* code" as you have to check if parent exists before accessing `childA`.

I see your point though on the semantic difference so... closing :)
