### ISSUE TITLE
feature request export mapAsyncIterator

### ISSUE THREAD

**Issue by dh94** [graphql/graphql-js#1354]
I found the function really handy when dealing with subscriptions,
It will be nice and useful if that function would be exported 😃 
[mapAsyncIterator](https://github.com/graphql/graphql-js/blob/master/src/subscription/mapAsyncIterator.js)

**Comment by IvanGoncharov** [comment]
@dh94 There is nothing GraphQL-specific in this function so I think it's better to move it into [iterall](https://github.com/leebyron/iterall). What do you think?

**Comment by dh94** [comment]
@IvanGoncharov sounds good

**Comment by leebyron** [comment]
See my comment on leebyron/iterall#47 but you're probably looking for https://github.com/ReactiveX/IxJS
