### ISSUE TITLE
defaultFieldResolver does not resolve field alias

### ISSUE THREAD

**Issue by alvis** [graphql/graphql-js#1360]
Currently `defaultFieldResolver` is used in `graphql-tools` as the default resolver. However, it doesn't work with aliased field. e.g. The first example works but not the second one. In the second case, `nickname` would be resolved to `null` rather than being identical to `name`.

```graphql
query {
  me {
    name
  }
}
```

```graphql
query {
  me {
    nickname: name
  }
}
```

The cause of the issue is that the current resolver only takes the `fieldName` from `info` rather than any aliased name in line 1232.

https://github.com/graphql/graphql-js/blob/ef585e9db8d161e715dfaa4e70c1ed2efa58294c/src/execution/execute.js#L1224-L1238

This issue is also related to https://github.com/apollographql/graphql-tools/issues/519, which leads to a custom solution ([doc](https://github.com/apollographql/graphql-tools/blob/v3.0.0/docs/source/schema-delegation.md#aliases)) in https://github.com/apollographql/graphql-tools/blob/v3.0.0/src/stitching/defaultMergedResolver.ts

I believe that we should fix this at the root. Changing `info.fieldName` to `info.path.key` or `info.fieldNodes[0].alias.value` seems to be non-breaking and yet a proper fix for supporting field alias. If agreed, I'd like to make a PR for that.

@robinhood: Do you have any opinion on the change?

**Comment by IvanGoncharov** [comment]
@alvis It works exactly as expected. If we use aliases, you can't return objects from your resolver. For example, in your query, your resolver can't return `{ name: 'IvanGoncharov' }` anymore.

Also note that current behavior is design to support wrapping your resolvers in classes, see here: https://graphql.org/graphql-js/object-types/

So using aliases make sense only for proxying request but absolute majority of users use this library to execute requests so library optimized for this use cases. The solution used Apollo totally makes sense in this case.

**Comment by alvis** [comment]
@IvanGoncharov Thanks for explaining.

I'm trying to understand this. You said the resolver can't return `{ name: 'IvanGoncharov' }` in my example if I use `info.path.key` instead of `info.fieldName`. Do you mean that `info.path.key` and `info.fieldName`are different if there's no alias? Becoz what I observe is that they're always identical for ordinary call, except the case of alias.

**Comment by IvanGoncharov** [comment]
@alvis Let's make a concrete example, I will use `graphql-tools` wrapper since it more familiar to you:
```js
const typeDefs = `
  type User {
    name: String
  }

  type Query {
    me: User
  }
`;

const resolvers = {
  Query: {
    me() {
      return { name: 'Ivan' };
    }
  }
}

export const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
});
```
Let's apply proposed change and call this query:
```graphql
{ 
  me {
    name
  }
}
```
Everything is good and you will get:
```json
{
  "data": {
    "me": {
      "name": "Ivan"
    }
  }
}
```
Let's send:
```graphql
{ 
  me {
    firstName: name
  }
}
```
Since graphql will look for `firstName` instead of `name` you will get:
```graphql
{
  "data": {
    "me": {
      "firstName": null
    }
  }
}
```

**Comment by alvis** [comment]
@IvanGoncharov Yes. It's a good example.

My question is: aren't we suppose to get
```
{
  "data": {
    "me": {
      "firstName": "Ivan"
    }
  }
}
```
since `firstName` is an alias of `name`? This is the reason I open this issue.

May be I'm wrong, but as far as in my expereince with Prisma, `obj` received in `resolve(obj, args, ctx, info)` becomes 
```
{ "firstName": "Ivan" }
```
in the 2nd example. That's why I thought using `info.path.key` is a better idea.

**Comment by IvanGoncharov** [comment]
@alvis I'm confused, so let's go step by step based on my example:
1. Resolver called for `me` field it returns `{ name: 'Ivan' }`  and this value becomes `source`.
2. `name` doesn't have resolver so `defaultFieldResolver` is called with args:
  * `source` - `{ name: 'Ivan' }`
  * `info` - where `fieldName` is `name` but `info.path.key` is `firstName`.
3. Here is where current and proposed behavior differs:
  * **Current**: `const property = source[info.fieldName];` so `property` became `Ivan`.
  * **Proposed**: `const property = source[info.path.key];` so `property` became `undefined`.
4. `defaultFieldResolver` resolver returns `property` and it becomes value in the responce.

**Comment by IvanGoncharov** [comment]
> May be I'm wrong, but as far as in my experience with Prisma , obj received in resolve(obj, args, ctx, info) becomes

Ok, I think I understand now. You right because `Prisma` is proxy but as wrote previously: 
> So using aliases make sense only for proxying request but absolute majority of users use this library to execute requests so library optimized for this use cases.

**Comment by alvis** [comment]
Thanks for explaining. It's clear to me now.

**Comment by IvanGoncharov** [comment]
> Thanks for explaining. It's clear to me now.

@alvis Great to hear! Proxying GraphQL requests are a pretty new field, so not everything works as expected. For example, you can break the majority of proxies with a query like that:
```graphql
{
  interfaceOrUnion {
    __typename: someField
  }
}
```
And it's not a `graphql-js` or GraphQL specification problem it just one more case that proxy needs to handle.

**Comment by sneharam7** [comment]
Hi,
I need help in binding data in graphql due to field name mismatch.

This is my type defined in schema.
type sc{
cnt_nmbr: String!
}
type Query {
  scresponse: [sc]
}
But the api response that i am trying to bind:

{ "Services.row": [
                {
                    "Services.cnt_nmbr": "1-206980667125"
                 }
]}

I understand that api response "Services.cnt_nmbr" is not equal to cnt_nmbr and hence data binding is failing. How will i resolve this?
