### ISSUE TITLE
Fields arguments is not passed in defaultResolveFn

### ISSUE THREAD

**Issue by zetachang** [graphql/graphql-js#138]
According to https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L718, 

> If a resolve function is not given, then a default resolve behavior is used
> which takes the property of the source object of the same name as the field
> and returns it as the result, or if it's a function, returns the result
> of calling that function.

The `args` is not passed while calling the function of the source object.

**Comment by leebyron** [comment]
We've left this off as we felt that it was probably wrong to make assumptions about the shape of the arguments a function on the source object. We figured that if someone was using arguments, that they would want to explicitly call their resolve function with the arguments in the correct form.

I'm curious what you expected to happen here?

**Comment by zetachang** [comment]
Actually I didn't expext the function to be invoked by default resolver,
but turns out it did get invoked, so it makes me wonder how field args are
handled.

Maybe pass the args object as the only argument to the function?

Lee Byron <notifications@github.com> 於 2015年8月20日週四 上午3:28 寫道：

**Comment by leebyron** [comment]
Closing this aging issue.

For posterity:

> Maybe pass the args object as the only argument to the function?

In my experience, it's pretty rare that existing methods expect arguments to be passed in this fashion. For clarity I think it's reasonable to provide lambda functions to express this:

```js
resolve: (obj, args) => obj.myMethod(args.someArg, args.otherArg)
```

And leave the default resolver function to not presume much about what a default method might accept as parameters.
