### ISSUE TITLE
Provide a full TodoApp-like example

### ISSUE THREAD

**Issue by ilmattodel93** [graphql/graphql-js#14]
I've read the specs and saw that mutators are'nt quite well explained, but I have also seen that some sort of implementation seems to be provided.
https://github.com/graphql/graphql-js/blob/master/src/executor/executor.js#L229

Should maybe provide a test example for the mutator or is'nt intentionally provided in the spec yet?

**Comment by leebyron** [comment]
I'm sure @dschafer can help explain a bit, and learn more from you on how we should improve our spec, tests and docs.

Here's a good place to start for our current test coverage: 
https://github.com/graphql/graphql-js/blob/master/src/executor/__tests__/mutations.js

**Comment by ilmattodel93** [comment]
I think that maybe a simple todo-app comprhensive of mutators and all sort of things that graphqljs could offer could be nice!
(it could show query, query parameters, composition, mutators, etc...)

**Comment by leebyron** [comment]
I agree. We're missing a few pieces to make that full demo as compelling as it could be, but we're definitely interested in working on. Stay tuned and thanks for the feedback!

**Comment by mathieumg** [comment]
> I think that maybe a simple todo-app comprhensive of mutators and all sort of things that graphqljs could offer could be nice!

:+1:

**Comment by gyzerok** [comment]
Any progress on this?

**Comment by leebyron** [comment]
This is underway now, but may take some time to complete.

**Comment by dschafer** [comment]
https://github.com/facebook/relay/tree/master/examples/todo contains a sample Todo app server, along with a Relay client.
