### ISSUE TITLE
Problem with GraphQLList

### ISSUE THREAD

**Issue by highskillzz** [graphql/graphql-js#1403]
I am getting this error 
Error: Expected [object Object] to be a GraphQL type. 
whenever I try to use GraphQLList in this type file and this is how my type file is

const graphql = require("graphql");
const ProjectType = require("./projectType");

const { GraphQLObjectType, GraphQLString, GraphQLList } = graphql;

const UserType = new GraphQLObjectType({
  name: "UserType",
  fields: () => ({
    id: { type: GraphQLString },
    name: { type: GraphQLString },
    githubProfile: { type: GraphQLString },
    username: { type: GraphQLString },
    password: { type: GraphQLString },
    email: { type: GraphQLString },
    projects: {
      type: new GraphQLList(ProjectType),
      resolve(parentValues, args) {
        return new Promise((resolve, reject) => {
          User.findById(parentValues.id)
            .populate("projects")
            .then(user => {
              resolve(user.projects);
            });
        });
      }
    },

    

  })
});

module.exports = UserType;

This question is also stackoverflow but no one was able to answer to so I am opening it here.
https://stackoverflow.com/questions/50905175/error-expected-object-object-to-be-a-graphql-type
Thanks in advance

**Comment by highskillzz** [comment]
Removing the GraphQLList makes the error go away

**Comment by Cito** [comment]
The error is caused by the cyclic dependency between your modules defining the UserType and the ProjectType. See my answer on StackOverflow.

**Comment by highskillzz** [comment]
Yes, it solved it. Thank you very much
