### ISSUE TITLE
Setting type via object directly and object through a function has different results

### ISSUE THREAD

**Issue by garyrutland** [graphql/graphql-js#1420]
Hi,

I'm not sure if this is a bug can't see any obvious reason as to why it wouldn't work, the other issue I'm facing is that I'm not getting any errors returns and just an empty object.

```
// works using module.exports = new GraphQLObjectType({...}); in ./type
const type = require('./type');

module.exports = () => ({
  object: {
    type: type,
    resolve: () => ({})
  },
});


// does NOT work using module.exports = () => new GraphQLObjectType({...}); in ./type
const type = require('./type');

module.exports = () => ({
  object: {
    type: type(),
    resolve: () => ({})
  },
});
```

Being able to use a function would be ideal as I can then pass a database connection through which is proving difficult with a "static" object.
Is there any obvious reason why this wouldn't work as they both seem to return exactly the same object when creating a schema, but the schema creation fails.

Thanks,
Gary

**Comment by IvanGoncharov** [comment]
@garyrutland It's hard to understand your problem from code snippets you posted,
can you please provide the full example?
Like put the content of different files in separate code snippets and provide code that constructs `GraphQLSchema` object.
Or alternatively, you can create a GitHub repo with the minimal example.

**Comment by lisbetfalero** [comment]
You are terminated🤗

**Comment by garyrutland** [comment]
I think I've found the problem, it was just quite well hidden.
`Schema must contain unique named types but contains multiple types named "Object".`

I need to rethink how to structure this to work AWS Lambdas as the DB connection gets closed after the first execution which is why I was trying to use `module.exports = () => new GraphQLObjectType({...});`.

Sorry for the trouble.

**Comment by garyrutland** [comment]
Also, turns out if I had wrapped my schema creation in a try/catch I would have seen the missing error.
