### ISSUE TITLE
[Feature request] Provide parse, compile, merge and check functions

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#143]
It would be cool if you can provide functionality for parsing, merging and compiling GraphQL queries. So not only Relay can use awesome features of GraphQL.

1. ```parse``` function should parse GraphQL query string into structure like ```info``` object which you can get in ```resolve``` function.
2. ```compile``` function should be an opponent for ```parse```
3. ```merge``` function should merge two ```info``` objects to later perform optimised query to the server.

Consider this example:

```
query FirstQuery {
  ... on Root {
    todos: todos(count: 5) {
      _id,
      text
    }
  }
}

query SecondQuery {
  ... on Root {
    todos: todos(count: 6) {
      _id,
      createdAt
    }
  }
}
```
Using suggested functions it can be merged in:
```
query OptimizedQuery {
  ... on Root {
    todos: todos(count: 6) {
      _id,
      text,
      createdAt
    }
  }
}
```

**Comment by gyzerok** [comment]
Also it would be nice to have ```check``` function to be able to check query agains schema to know if it is valid.

**Comment by Nexi** [comment]
+1

**Comment by nemanja-stanarevic** [comment]
they expose parser and you can import it from language/parser.  you can then work with ASTs returned by the parser by importing visit from language/visitor. In-code documentation for visitor is great, but ping me if you have any questions
