### ISSUE TITLE
GraphQLInputObjectType inputFields vs fields

### ISSUE THREAD

**Issue by HurricaneJames** [graphql/graphql-js#144]
Should GraphQLInputObjectType use `inputFields` instead of `fields`? The spec does not say how to define the schema specifically. However, it does say that introspection queries for `fields` on input object should be `null`. Instead it requires an `inputFields` query. If the introspection is `inputFields`, then it would make more sense to call the property `inputFields` in the schema as well.

Note: I have a related issue open on the spec facebook/graphql#85 regarding whether `inputFields` should return a keyed set like `fields` does for objects. I guess it could be argued that `inputFields` is not necessarily the best query name too.

**Comment by leebyron** [comment]
Great suggestion

**Comment by leebyron** [comment]
Closing aging issue, but for posterity:

We decided not to do this mostly because of ergonomics when defining the input objects. It was too easy to forget and become frustrating.
