### ISSUE TITLE
printType function to get GraphQLSchema object as a query string

### ISSUE THREAD

**Issue by PedramMarandi** [graphql/graphql-js#1464]
Hi everyone, 
I've been struggling to mix Graphql query language with `GraphQLObjectType`  in `makeExecutableSchema` and I realized at the moment there is not any neat way to do so. 

However, there is a function to print the schema object which is `printSchema` and I wonder if there is any functionality like a `printType` function or any other solution to implement such a transformation from `GraphQLObjectType` to Graphql query language?

Thanks

**Comment by IvanGoncharov** [comment]
>  I wonder if there is any functionality like a printType function or any other solution to implement such a transformation from GraphQLObjectType to Graphql query language?

https://github.com/graphql/graphql-js/blob/7cfd6865cebdca1c1760246a5c132babb791b7d7/src/index.js#L359-L360
