### ISSUE TITLE
Cypher optimization 

### ISSUE THREAD

**Issue by Nexi** [graphql/graphql-js#149]
I have the following GraphQL query:

```
post(id: 3000) {
  author {
    name
  },
  comments {
    text,
    author {
      name
    }
  }
}
```

It seems to me that I have to make many requests to Neo4j in order to fetch all needed data. Is there any way how I can optimize this query to be just one Cypher query and there be only one round trip to the database?

**Comment by Nexi** [comment]
In other words maybe it would be like if there were something like this:

```javascript
var authorType = new Type({
  name: {
    map: function( queryBuilder, params  ){ 
      queryBuilder.return(“name”);  
    }
    resolve: function( data ){ 
      return data.name; 
    }
  },
})

var postType = new Type({
  text: {
    map: function( queryBuilder, params  ){ 
      queryBuilder.return(“text”);  
    }
    resolve: function( data ){ 
      return data.text 
    }
  },
  author: {
    type: authorType,

    map: function( queryBuilder, params  ){ 
      queryBuilder.match({
        nodeLabel: “Author”,
        params: {},
        parentRelLabel: "WRITTEN_BY"
        parentRelDir: "-$->"
      });
    },

    resolve: function(data){
      return data.author;
    }
  }
});

var RootQuery = new Schema({
  post: {
    type: postType,

    // this builds cypher query
    map: function( queryBuilder, params ){
      queryBuilder.match({
        nodeLabel: “Post”,
        params: {id, params.id }
      });
    },

    // data coming from executed query
    resolve: function( data ){
        return data.post;
    }
  } 
});
```

and the executor first goes in map functions to build a query, and then after query has been executed, it goes in resolve functions

**Comment by freiksenet** [comment]
See https://github.com/graphql/graphql-js/issues/26 for discussion. It's a known issues and there is not clear way on how to address it yet. At FB they aggregate the queries and combine them outside of graphql.

**Comment by leebyron** [comment]
Closing this to merge into #26

**Comment by keyvan-m-sadeghi** [comment]
@Nexi there is a project that might be of help:
https://github.com/jhwoodward/neo4j-graphQL
