### ISSUE TITLE
14.0.1 is missing on NPM

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#1512]
Latest version on NPM:
https://www.npmjs.com/package/graphql
![image](https://user-images.githubusercontent.com/8336157/45181422-188a8500-b227-11e8-9d87-bb59ea241c34.png)

This happened because of this:
https://travis-ci.org/graphql/graphql-js/jobs/424976995#L491-L493
```
Authenticated with email lee@leebyron.com and API key ****************b8da
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
```

Details: https://blog.npmjs.org/post/175824896885/incident-report-npm-inc-operations-incident-of
> As a precautionary measure, npm has revoked every access token that had been created prior to 2:30 pm UTC (7:30 am California time) today. This measure requires every registered npm user to re-authenticate to npmjs.com and generate new access tokens,

**Comment by IvanGoncharov** [comment]
@leebyron Can you please update your key here:
https://github.com/graphql/graphql-js/blob/d1c4e7d0c86bcc921c778ad692e644c828d017bd/.travis.yml#L40-L44

**Comment by IvanGoncharov** [comment]
@mjmahone @leebyron It makes sense to either manually publish `14.0.1` to NPM.
Or to publish `14.0.2` since we didn't add any major or minor change since `14.0.0`.
But the first step would be to update NPM key.

**Comment by IvanGoncharov** [comment]
@leebyron Can you please also update a few other keys in `graphql/*` repos:
* `experess-graphql` https://github.com/graphql/express-graphql/blob/750cfd5e803ce5aa4bd4be69d1a76472f4d439de/.travis.yml#L40-L43
* `graphiql` https://github.com/graphql/graphiql/blob/b777e07ccdfb7f3bbbba7b9d3be8f30674cc4498/.travis.yml#L11-L15
* `codemirror-graphql` https://github.com/graphql/codemirror-graphql/blob/8eb39e283515db49044099733a7e8a447293fb56/.travis.yml#L11-L14

**Comment by mjmahone** [comment]
I don't have the ability to update the API key, but I can try to publish `14.0.1`. Give me a few minutes.

**Comment by mjmahone** [comment]
:/ I made the mistake and didn't check out the correct commit, so `14.0.1` was published off the latest commit rather than the tagged commit.

So I published `14.0.2` just now on a correct, tagged commit. Sorry about that.

**Comment by leebyron** [comment]
I unpublished 14.0.1 from the registry since it's on the wrong commit

**Comment by IvanGoncharov** [comment]
@leebyron Can you please update keys, especially for `express-graphql` (I was planning to make a release on the next week).

**Comment by leebyron** [comment]
Yes. I’m looking into those today

**Comment by IvanGoncharov** [comment]
@leebyron Thanks a lot 👍

**Comment by IvanGoncharov** [comment]
@leebyron Can you please update keys in `graphql/*` repos:
* `experess-graphql` https://github.com/graphql/express-graphql/blob/750cfd5e803ce5aa4bd4be69d1a76472f4d439de/.travis.yml#L40-L43
* `graphiql` https://github.com/graphql/graphiql/blob/b777e07ccdfb7f3bbbba7b9d3be8f30674cc4498/.travis.yml#L11-L15
* `codemirror-graphql` https://github.com/graphql/codemirror-graphql/blob/8eb39e283515db49044099733a7e8a447293fb56/.travis.yml#L11-L14

It will significantly improve GraphQL bus factor: https://en.wikipedia.org/wiki/Bus_factor
