### ISSUE TITLE
[Feature Request] Resolver Middleware

### ISSUE THREAD

**Issue by dereklavigne18** [graphql/graphql-js#1516]
I'm interested to hear how others feel about the idea of using middleware installed on resolver functions to allow all resolvers in a schema to perform common functionality.

As my schema grows I've found more and more of a need to add some of the same logic to all my resolvers. It would be nice if we could add some middleware that would be executed on resolvers in the schema when we go to execute the query. This could allow users to implement things like custom error handling, logging, and authorization on all resolvers without the need to add them to each resolver on the schema.

**Comment by IvanGoncharov** [comment]
@dereklavigne18 That sounds great 👍 
I think it has a potential to address a bunch of feature requests like #284, #662, etc. 

One important note is that we should be extremely careful not to add a performance penalty, especially for big queries that resolved asynchronously. See this discussion in #723.

**Comment by bogdanned** [comment]
+1 to @dereklavigne18. Custom error handling and authorization middlewares would save so much time.

**Comment by buoyantair** [comment]
What if it was more event oriented? As in, instead of having a middleware sort of thing, we can have an event emitter api of sorts, and have a couple of options like:
- BeforeResolverExecution
- AfterResolverExecution

Later on we can just add more event handlers which can be plugged into.

**Comment by Cito** [comment]
Note that there is already a middleware implementation in GraphQL-core (see [middleware.py](https://github.com/graphql-python/graphql-core-next/blob/master/src/graphql/execution/middleware.py) and [test_middleware](https://github.com/graphql-python/graphql-core-next/blob/master/tests/execution/test_middleware.py)) where you can steal ideas from.

**Comment by fabienjuif** [comment]
I coded this naive implementation of middlewares here if you are still interested: https://github.com/unirakun/graphql-directives-middlewares

The solution given by @stalniy seems quite good to me tho!

**Comment by sibelius** [comment]
I think we can solve this in userland instead

**Comment by danielrearden** [comment]
@sibelius The community [already has](https://github.com/prisma-labs/graphql-middleware)

**Comment by sibelius** [comment]
I don’t think this should be in the graphql-js core package

**Comment by jgcmarins** [comment]
I've been using an approach like this: https://github.com/JCMais/graphql-yup-middleware

**Comment by jgcmarins** [comment]
As @sibelius said and me and @danielrearden pointed, we already have a solution for that out of graphql-js.
Not sure if it makes sense to bring it here. I think that graphql-js exists to implement the [graphql-spec](https://github.com/graphql/graphql-spec).
Any implementation that does not belong to the GraphQL specification, should be out of graphql-js

**Comment by vwkd** [comment]
How about making resolvers full-fledged middleware? It seems currently resolvers are like middleware, but limited in that a parent can only run code before but not after.

One use case is handling resolver errors in the parent resolver. For example, if a certain error was thrown in a child resolver, the parent resolver could decide to retry the whole child resolver chain again.

I recognize this might make validation more complex, since graphql-js can't just verify the response from each resolver once and be done with it, since parents now might be able to modify it. Maybe graphql-js could delay the response validation until all middleware is run.

**Comment by yaacovCR** [comment]
Closing this issue as solved in user land. In terms of retrying on error, that functionality seems at first glance counter to the specification — there may be an algorithmic equivalence that makes it neutral, but it would still seem to be best done outside the reference implementation.

**Comment by Urigo** [comment]
The approach that @the-guild-org is taking and recommending for middleware and plugins for graphql-js is the approach of the [Envelop plugin system](https://the-guild.dev/blog/introducing-envelop).
We believe it is a superior approach to the `graphql-middleware` library (which we've maintained till we've managed to migrate all of our users from it)
We have a whole [plugin ecosystem](https://the-guild.dev/graphql/envelop/plugins) around Custom error handling, Authentication and Authorization, Tracing and Metrics, security, caching and many others, including many custom plugins that companies create for themselves.

It is also the core of our GraphQL Yoga Plugin system and our Hive Gateway Plugin system.
You can read more about the plugin system on these resources:

https://the-guild.dev/graphql/envelop/docs/plugins/lifecycle
https://the-guild.dev/graphql/yoga-server/docs/features/envelop-plugins
https://the-guild.dev/graphql/hive/docs/gateway/other-features/custom-plugins
