### ISSUE TITLE
Parser/Lexer error with an empty interface

### ISSUE THREAD

**Issue by simPod** [graphql/graphql-js#1517]
Related to https://github.com/graphql/graphql-js/issues/1495

Is having empty interface in schema allowed?

```gql
interface Node
```

I was wondering when [empty type](https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-kitchen-sink.graphql#L37) is possible, empty interface could be too. Thanks!

**Comment by IvanGoncharov** [comment]
@simPod It's possible in SDL so you can write:
```graphql
interface Node

# In this or separate file or string
extend interface Node {
  id: ID
}
```

But schema that is used to execute requests can't have empty interfaces:
http://facebook.github.io/graphql/June2018/#sec-Interfaces
> An Interface type must define one or more fields.
