### ISSUE TITLE
Feature request: flag for old, deprecated variable scalar coercion behavior

### ISSUE THREAD

**Issue by dallonf** [graphql/graphql-js#1519]
To start, I think the changes made in #1382 are good and definitely the direction GraphQL should be going!

However, for my team, this is a _huge_ breaking change that will prevent us from updating to 14.x or later for the forseeable future. I suspect there are many client applications depending on our GraphQL server that send incorrect variable types, expecting them to be coerced. Right now I'm just doing a bit of housekeeping on the dependencies of the server - I simply don't have the bandwidth to go through all of these client applications and fix them, or even to investigate where this might be happening.

Previous breaking changes (ex. https://github.com/graphql/graphql-js/pull/927) have provided flags and options to affected functions - can we get one of those for this change? This would allow my team to at least stay up to date and save this chore for another time.

**Comment by IvanGoncharov** [comment]
@dallonf Sorry for the trouble this change caused.

> Previous breaking changes (ex. #927) have provided flags and options to affected functions - can we get one of those for this change?

The difference here is that `GraphQLInt`, `GraphQLFloat` and others are singletons so we can't pass a flag to them or wrap them.

It would be great if someone will figure out some way to implement it in a clean way?
@leebyron If you have time, can you please comment on this issue?

**Comment by IvanGoncharov** [comment]
Closing issue since no solution was suggested.
Note: since `graphql` typically used a peer dependency you don't tie to a particular version and can migrate to `14.0.0` after you will upgrade your clients.
