### ISSUE TITLE
Change Notification/Subscription

### ISSUE THREAD

**Issue by ronag** [graphql/graphql-js#152]
Add support for change notification/subscription for use by real-time application, i.e. similar to Firebase and Meteor.

I know this is discussed on Slack. Just adding this ticket to keep track of potential progress.

**Comment by defrex** [comment]
Are there any updates on progress here? I'm very interested in this feature.

**Comment by leebyron** [comment]
I just merged in #189 which I'll release shortly in v0.4.8. There are no pub-sub mechanisms for GraphQL itself, but this PR adds support to the schema itself for those who want to experiment with this.

**Comment by leebyron** [comment]
Closing this aging issue.

FYI, this is still something on the longer term roadmap for GraphQL so stay tuned. 

You can also check out Meteor's early foray into this space: http://info.meteor.com/blog/reactive-graphql
