### ISSUE TITLE
After upgrading package got "Expected ... to be a GraphQL schema"

### ISSUE THREAD

**Issue by vlad1777d** [graphql/graphql-js#1524]
Hello.

After upgrading package from `"graphql": "^0.13.2"` to `"graphql": "^14.0.2",`,
When I'm trying to get any query, I receive error:
`Expected [object GraphQLSchema] to be a GraphQL schema.`

<img width="1440" alt="screen shot 2018-09-14 at 7 37 50 pm" src="https://user-images.githubusercontent.com/12682937/45563339-b8fb2d80-b855-11e8-8462-f7a2cba93802.png">

My package.json:
[package.txt](https://github.com/graphql/graphql-js/files/2384162/package.txt)

App structure:
<img width="1440" alt="screen shot 2018-09-14 at 7 39 38 pm" src="https://user-images.githubusercontent.com/12682937/45563435-024b7d00-b856-11e8-8d42-3ba1266437ad.png">
<img width="1440" alt="screen shot 2018-09-14 at 7 39 47 pm" src="https://user-images.githubusercontent.com/12682937/45563451-0d9ea880-b856-11e8-8c4c-48707b980dca.png">

Can this be issue in a package or it's some migration problem ?
(I didn't updated project after it)

Thank you.

**Comment by IvanGoncharov** [comment]
@vlad1777d Can you please run `npm ls graphql` and post the output here?
You should have only one instance of this package.

**Comment by vlad1777d** [comment]
I have such output:
```
➜  metrix-api git:(master) npm ls graphql
metrix-api@0.1.0 /Users/develops/Documents/projects/metrix-api
└─┬ graphql-yoga@1.16.2
  ├─┬ apollo-server-express@1.3.6
  │ └─┬ apollo-server-core@1.3.6
  │   └── graphql@0.13.2  extraneous
  └─┬ graphql-playground-middleware-express@1.7.2
    └─┬ graphql-playground-html@1.6.0
      └─┬ graphql-config@2.0.0
        └── graphql@0.13.2  extraneous

npm ERR! extraneous: graphql@0.13.2 /Users/develops/Documents/projects/metrix-api/node_modules/apollo-server-core/node_modules/graphql
npm ERR! extraneous: graphql@0.13.2 /Users/develops/Documents/projects/metrix-api/node_modules/graphql-config/node_modules/graphql
```

**Comment by IvanGoncharov** [comment]
@vlad1777d You have conflicting dependencies `14.0.2` and `0.13.2`.
You can't use both at the same time so you need to revert back to `0.13.2` and wait until all your dependencies will support `14.0.2`.

**Comment by vlad1777d** [comment]
@IvanGoncharov , thank you very much.
