### ISSUE TITLE
RFC: Extra property on field definition to pass extra metadata

### ISSUE THREAD

**Issue by JCMais** [graphql/graphql-js#1527]
I'm currently adding extra properties to some graphql object field definitions, like the following:

```js
const MutationType = new GraphQLObjectType({
  name: 'Mutation',
  fields: () => ({
    AddSomething: {
      // ... normal field properties
      somethingElse: {},
    }
  }),
})
```

And then using them later on via the `info` argument inside some middlewares (using [`graphql-middleware`](https://github.com/prisma/graphql-middleware/)):
```js
const mutationField = info.schema.getMutationType().getFields()[info.fieldName];
console.log(mutationField.somethingElse);
```

For more details, see the following medium post: [graphql mutation arguments validation using yup](https://itnext.io/graphql-mutation-arguments-validation-with-yup-using-graphql-middleware-645822fb748)

---

The thing is, this is relying on internal behavior.
The following code spreads all properties given to the field:
https://github.com/graphql/graphql-js/blob/81719749e01f030cfb3a01a97e7e4bfc534bb08f/src/type/definition.js#L720-L724

Is that something expected to not change? If yes, then no need for any other extra property or for this issue. 😄 

But if this is something that can change in future versions, I would love the possibility of having an extra field for that extra metadata.

I'm available to work on adding this, if it's approved.

**Comment by JCMais** [comment]
+1 for `extensions` 

Ideally libraries using this would allow to customize the key name, to reduce possibility of key collisions.

**Comment by JCMais** [comment]
what can be done to move this forward?

**Comment by sibelius** [comment]
I think the first part is to remove exact types on flow definitions

**Comment by scpwebdev** [comment]
+1 this could help fix issues with join-monster that requires extra metadata for fields

**Comment by flipxfx** [comment]
+1 this could help fix issues with join-monster that requires extra metadata for fields

**Comment by 19majkel94** [comment]
I would treat this exact Flow definition as a bug because this quote from @leebyron (https://github.com/graphql/graphql-js/issues/1262#issuecomment-368110891):

> You can include any arbitrary data on a GraphQLObjectType that you like - it's just a JS object after all. 

So I treat this pattern as a recomended way to have some metadata on types/fields like directives allows use to do in SDL.

**Comment by IvanGoncharov** [comment]
> I would treat this exact Flow definition as a bug because this quote 

This quote is about actual `GraphQL*Type` not about config types like `GraphQL*TypeConfig`.

> You can include any arbitrary data on a GraphQLObjectType that you like - it's just a JS object after all.

It basically says you can do:
```js
const someType = new GraphQLObjectType({
  name: 'Foo',
  // ...
});

someType.customProperty = "Custom Value";
```

Personally, I think it's a workaround especially for clients who use Flow/TS at the same time I think config types should remain exact.

------------

The alternative proposal would be:
```js
const someType = new GraphQLObjectType({
  name: 'Foo',
  // ...
  extensions: {
    customProperty: "Custom Value",
  },
});
```
Where `extensions` defined as `ObjMap<mixed>'.

@JCMais What do you think about this proposal?

**Comment by JCMais** [comment]
@IvanGoncharov that was exactly the kind of alterative I was looking for.

Just a specific key that we can be sure it will be available later on, from the `info` argument inside resolvers, for example.

**Comment by 19majkel94** [comment]
> This quote is about actual GraphQL*Type not about config types like GraphQL*TypeConfig.

> `someType.customProperty = "Custom Value";`

So how to place metadata on fields and args like directives do by using this way?
We configure fields and its args in a type config for `GraphQLObjectType` as a plain objects.

Should we mutate this object later (by using `(schema.getType("typeName") as GraphQLObjectType).getFields()["fieldName"].complexity = 5;`) or is it safe to rely on `...fieldConfig` behavior in that case?

**Comment by IvanGoncharov** [comment]
> Should we mutate this object later (by using (schema.getType("typeName") as GraphQLObjectType).getFields()["fieldName"].complexity = 5;) or is it safe to rely on ...fieldConfig behavior in that case?

@19majkel94 It should work fine as a workaround until we ship an `extensions` solution however no long-term guarantees afterward.

I will work on adding immutable `extensions` into types, fields, args and enum values on next week so we will able to ship it in `14.2.0`.

**Comment by nodkz** [comment]
🛑Before shipping this we should consider how `extensions` can be provided via SDL.

Add `@extensions` directive like so:

```graphql
type User {
  name @extensions(cost: { complexity: 2 })
}
```

We MUST provide a unified solution for SDL and configObjects. And will be nice if it will be covered by static analysis. For now `mixed` value for extensions is weak and error-prone.

**Comment by JCMais** [comment]
@nodkz this sounds good, since it has been some time since I last used `graphql-js` directly, how is the custom directive going to be extended by library authors? 

That would be like a schema directive that apollo has, correct? Do we have support for that currently?

**Comment by freiksenet** [comment]
We've been using it very effectively at Gatsby through graphql-compose extensions. Adding it here as an example of "usage in the wild".

**Comment by j** [comment]
@IvanGoncharov any updates on this?  I'm working on implementing `apollo-federation` support into `type-graphql`, this would be a clean way of supporting everything needed to piece it together cleanly.

**Comment by IvanGoncharov** [comment]
@j Thanks for pinging 👍
It looks like we have consensus around `extensions` feature so I will try to prepare PR this week.

**Comment by j** [comment]
@IvanGoncharov yay :) I can start the process of implementing in both libraries mentioned above.

Is `extensions` going to simply be part of the `*Type` config as `{ [key: string]: any}`.

And if the PR lands this week, is there an ETA on a release?  Simply because we've sorta freezed our back-end due to the fact that we want to immediately move to federated services but are locked until it's supported in `type-graphql`.

**Comment by IvanGoncharov** [comment]
> Is extensions going to simply be part of the *Type config as { [key: string]: any}.

Yes, except it would be `unknown` (`mixed` in Flow) instead of `any`. Also, it would be `{ [key: string]: unknown}` in config (and `toConfig` result) but inside object itself it would be `{ readonly [key: string]: mixed }`

> And if the PR lands this week, is there an ETA on a release? Simply because we've sort of put a freeze on our back-end until federation is supported intype-graphql. :)

I will make `14.5.0` after this merge.

> Also, can/will extensions be added to the type.toConfig()?

Definitely, also I need to support it in other places, e.g. `lexicographicSortSchema` should sort extensions.

**Comment by cliedeman** [comment]
Maybe string and symbol for keys? This can ensure we don't have collisions

**Comment by IvanGoncharov** [comment]
@cliedeman We can definitely use Symbols for solving collisions inside in-memory schema but it will just push the problem down the road. For example, I have a long term plan to figure out how to allow exposing `extensions` through introspection but it's impossible to use symbols inside introspection responses.

So my proposal is to keep everything simple for the first release and figure out how to solve problems only if they will happen in the wild.

BTW, you can also have collisions of directive names so it's not a new problem in GraphQL world.

**Comment by j** [comment]
@IvanGoncharov This push will make my week.  :)

**Comment by IvanGoncharov** [comment]
@j Just to give some transparency about the timeline.
At the moment I'm working on #2037 since it's security-related and this issue is second in my pipeline.
After both PRs merged I will release `14.5.0`.

**Comment by IvanGoncharov** [comment]
Quick update: #2037 taking more time than I initially expected so now I'm pushing for releasing at the end of this month. Thanks for the patience.

**Comment by j** [comment]
I see movement! Yay! :p

**Comment by IvanGoncharov** [comment]
It took longer than I planned but I finally merged it in #2097 
Thanks for patience 🙇 
I will try to cut release today/tomorrow

**Comment by JCMais** [comment]
Thank you @IvanGoncharov !

**Comment by j** [comment]
@IvanGoncharov holy moly, the GraphQL world is going to get so much better now. :) Thanks!
