### ISSUE TITLE
Fragments with aliases: Cannot return null for non-nullable fields

### ISSUE THREAD

**Issue by kamranayub** [graphql/graphql-js#1530]
# Reporting issues with GraphQL.js

Given the following schema:

```
type Query {
  books: Books
}

type Books {
  categoryHierarchy: [Category]!
  name: String!
}

type Category {
  name: String!
  categories: [Category]!
}
```

And then issuing a query:

```
{
  books {
    name
    categoryHierarchy {
      ...category
      categories {
        ...category
      }
    }
  }
}

fragment category on Category {
  abc: name
}
```

I am seeing a regression in 0.13.x+ (coming from 0.11.7) where `graphql` is throwing the following error:

    Cannot return null for non-nullable field Category.name.

If I remove the `abc` alias, it works. Aliases in the query selection set and on nullable fields appears to work.

**Comment by kamranayub** [comment]
I'm still investigating this but it looks like no field aliases work anymore--however, not sure if the `graphql` stack trace is misleading or it's actually Apollo Server or something more upstream.

**Comment by IvanGoncharov** [comment]
@kamranayub I can't reproduce your issue on `0.13.2` using following script:
```js
const {
  buildSchema,
  graphqlSync,
} = require('graphql');

const schema = buildSchema(`
type Query {
  books: Books
}

type Books {
  categoryHierarchy: [Category]!
  name: String!
}

type Category {
  name: String!
  categories: [Category]!
}
`);

const result = graphqlSync(schema, `
{
  books {
    name
    categoryHierarchy {
      ...category
      categories {
        ...category
      }
    }
  }
}

fragment category on Category {
  abc: name
}
`);

console.log(result);
```

So it's probably issue somewhere in Apollo stack, so please report it there.

**Comment by kamranayub** [comment]
@IvanGoncharov Thanks, I reproduced it with Apollo playground.
