### ISSUE TITLE
Subscriptions do not work with asynchronous resolver function

### ISSUE THREAD

**Issue by Cito** [graphql/graphql-js#1535]
I noticed that the `subscribe` function does not work properly when it is used with an asynchronous field resolver function.

Also, there is no unit test for this case. This is what I have in mind (must be added to `subscribe-test.js`):

```javascript
  it('should work with an asynchronous resolver', async () => {
    const asyncEmailSchema = emailSchemaWithResolvers(
      async function*() {
        yield { email: { subject: 'Hello' } };
      },
      async function*(email) { // <-- this currently does not work
        return email;
      },
    );

    const subscription = await subscribe(
      asyncEmailSchema,
      parse(`
        subscription {
          importantEmail {
            email {
              subject
            }
          }
        }
      `),
    );

    const payload = await subscription.next();
    expect(payload).to.deep.equal({
      done: false,
      value: {
        data: {
          importantEmail: {
            email: {
              subject: 'Hello',
            },
          },
        },
      },
    });

    expect(await subscription.next()).to.deep.equal({
      done: true,
      value: undefined,
    });
  });
```

Is this an oversight? Or am I doing something stupid or against the spec? As far as I see the [ResolveFieldEventStream](https://facebook.github.io/graphql/draft/#sec-Source-Stream) section says nothing about whether the resolver function can be asynchronous, so I am assuming that is allowed, just at it is for resolver function used for normal queries, and as far as I understand it is intended that they are compatible.

**Comment by Cito** [comment]
> can you write a failing test?

See above. The test fails - `email` is `null` instead of `{subject: 'Hello'}`.

**Comment by asishallab** [comment]
I might be mistaken, but is this Issue not somewhat similar to Issue #1537 ?

**Comment by Cito** [comment]
@asishallab this is a different issue, it exists only in the context of a subscription.

**Comment by yaacovCR** [comment]
Hi @Cito 

i think things have been reworked a bit since 2018, has this been fixed or otherwise addressed ?

https://github.com/graphql/graphql-js/blob/c7d7026982ceee536900a24ae31235127560297a/src/execution/__tests__/subscribe-test.ts#L299

**Comment by yaacovCR** [comment]
Is the old problem that generators return values are a separate beast from the yielded payloads?

**Comment by yaacovCR** [comment]
This has been addressed, as far as I can tell. Feel free to reopen.
