### ISSUE TITLE
14.1.0

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#1543]
I think we need to start preparing `14.1.0`.
Beyond #1520 it would be great to include all RFC we agree on at last WG.

@mjmahone What do you think?

**Comment by vreality64** [comment]
When will it be released? I'm waiting for this release ~😃~

**Comment by GlennMatthys** [comment]
While we're here... [This ](https://github.com/graphql/graphql-js/issues/1527) also needs some attention. With the release of version 14 it basically prohibited middlewares to tie in directly into the graphql definitions, making everybody using middlewares get stuck on version 13.

**Comment by IvanGoncharov** [comment]
@mjmahone just published `14.1.0` 🎉
