### ISSUE TITLE
How to use graphql-js in immutable manner?

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#155]
So far I've ended up with a solution of denormalizing data, received from graphql on the client. The next step I want to do is to be able to run client queries against denormalized data. The problem is I have no mutable state like with database on the server, so I need my data inside ```resolve``` function to select from it.

Any thoughts?

**Comment by gyzerok** [comment]
I suppose the solution here is to use rootValue. Am I right?

**Comment by leebyron** [comment]
Correct. `rootValue` is available throughout the entire query and is provided as the primary way in which GraphQL schema can remain functional and avoid reaching into global state.
