### ISSUE TITLE
'Abstract type must resolve to an object' error; resolver maps not resilient

### ISSUE THREAD

**Issue by sarora2073** [graphql/graphql-js#1553]
# Feature requests

Hi,

I came across the expected error 'Abstract type must resolve to an object' when using a resolver map to resolve various entities in a collection to their respective types. Turns out the immediate issue causing the error was one record in the collection had stale data that didn't resolve to either of the expected types. 

I tried a few variations of the resolver map (see below for snippets) but as afar i can tell from experimentation and researching there is no way around the limitation to get the all the "good" data, and ignore the bad record..either *all* the queried data conforms to the resolver map OR you get back 0 results and the 'Abstract type must resolve to an object' error. From my applications perspective, getting all available valid results would be preferable, and there would a 'soft' error that can be handled / logged etc. not a hard error for a bad record.

Here are the approaches I tried that didn't work to ignore the one bad record:

Example 1 of resolver map (graphql-tools syntax) - returns nothing if obj typename isn't a match

```
  Activity: {
    __resolveType(obj, context, info) {
      if (obj instanceof NoteActivity) {
        return 'NoteActivity';
      } else if (obj instanceof CallActivity) {
        return 'CallActivity';
      } else if (obj instanceof MeetingActivity) {
        return 'MeetingActivity';
      }
    }
  }
```
Example 2 - I tried defaulting to returning null or empty object {}
```
  Activity: {
    __resolveType(obj, context, info) {
      if (obj instanceof NoteActivity) {
        return 'NoteActivity';
      } else if (obj instanceof CallActivity) {
        return 'CallActivity';
      } else if (obj instanceof MeetingActivity) {
        return 'MeetingActivity';
      } else {
        return {} // OR return null
    }
  }
```

If there is some solution aside from what I've tried, please share, but at this point in my research i'm guessing that this is a constraint of graphql.

Thanks!

-S. Arora

**Comment by IvanGoncharov** [comment]
> Here are the approaches I tried that didn't work to ignore the one bad record:

@sarora2073 You should filter out "bad" record inside resolver that returns the array:
```js
{
  SomeType: {
    activities() {
      // ...
      return activities.filter(activityToClassName);
    }
  },
  Activity: {
    __resolveType: activityToClassName,
    // ...
  }
}

function activityToClassName(obj) {
  if (obj instanceof NoteActivity) {
    return 'NoteActivity';
  } else if (obj instanceof CallActivity) {
    return 'CallActivity';
  } else if (obj instanceof MeetingActivity) {
    return 'MeetingActivity';
  }
}
```

> no way around the limitation to get the all the "good" data, and ignore the bad record..either all the queried data conforms to the resolver map OR you get back 0 results and the 'Abstract type must resolve to an object' error. 

Can you please share relevant part of SDL?
Based on citation I would assume this particular field returning `[Activity!]` and if you convert it to `[Activity]` (drop non-null) you would get `null` only for items that failed to return correct types from `__resolveType` and valid values for the rest of items.

**Comment by sarora2073** [comment]
Thanks for this! Filtering in the resolver function solves this for me. 

fyi - the relevant SDL snippet you're asking about is this...

```
  interface Activity {
    _id: ID
    type: String
    etc.
   }

  type NoteActivity implements Activity {
    _id: ID
    type: String
    etc.
  }

  extend type Query {
    getActivities: [Activity]
  }
```

You can see that i'm not requiring Activity, but nevertheless experienced the error, which is why I felt graphql was being too brittle in expecting a resolver map response. However, i'm glad to close this given that there's an easy work around.

btw, rather than using the activityToClassName function verbatim, i went with a minimalistic function that simply returns true / false for valid activities like this:

```
function validateActivity(obj) {
  if (obj instanceof NoteActivity || obj instanceof CallActivity || obj instanceof MeetingActivity) {
    return true;
  } else { return false; }
}
```
and now i'm able to use mongoose to query against all 'Activity' items in the collection like so:

```
        return Activity.find(query)
          .then(activities => activities.filter(validateActivity))
          .catch((err) => {
            logger.error(err);
          });
```
Again, thanks so much for this!
