### ISSUE TITLE
Text color in search bar using "light" theme

### ISSUE THREAD

**Issue by dabyland** [graphql/graphql-js#1556]
Quite a minor "issue", if you can even call it that. 

When using the "light" theme on the graphql Playground, the text "Search:" and contents within the SearchBar are nearly invisible. I have text input into the field however you're unable to tell since the color of both mentioned texts are white.

Maybe just change to black when the theme is switched?

<img width="1314" alt="screen shot 2018-10-22 at 3 07 49 pm" src="https://user-images.githubusercontent.com/9575583/47316337-7ecb3b80-d60c-11e8-98e5-55464b6d9e38.png">

**Comment by IvanGoncharov** [comment]
@dabyland I think this is the right repo for this issue: https://github.com/prisma/graphql-playground
Please report it there.

**Comment by dabyland** [comment]
@IvanGoncharov Thanks, will do.
