### ISSUE TITLE
Require properties by default

### ISSUE THREAD

**Issue by TriStarGod** [graphql/graphql-js#1561]
Is there a way to require properties by default? Currently, I'm placing ! on everything. Is there a setting to have it considered required by default with selective ones as not required?

**Comment by IvanGoncharov** [comment]
@TriStarGod Sorry for the delay.

> Is there a setting to have it considered required by default with selective ones as not required?

No, GraphQL spec is very explicit about that:
https://facebook.github.io/graphql/June2018/#sec-Type-System.Non-Null
> By default, all types in GraphQL are nullable;

`graphql-js` is implemented according to the spec so there is nothing we can do in this repo.

**Comment by langpavel** [comment]
@TriStarGod If you are placing `!` on everything, you are really happy front ←→ endier.
I'm almost sure that you aren't — except in very limited situations. (Really; possible but uncommon)

BTW are you talking about `input` types? or generally at all?

**Comment by TriStarGod** [comment]
@langpavel I have far more situations in which I place an ! than not. GraphQL seems the opposite of most languages where you have to explicitly specify what is optional.

**Comment by langpavel** [comment]
@TriStarGod True. GraphQL is for querying data. *at first.*
So if you specify `!` in type it may be interpreted as *this value is always present. *if you need*.

On the other hand, you may use `!` on ***input***; so it takes strict assertion: This value is **always required** and then (hope, *mutation* fails)

---

Can you describe more? Bot don't worry, this issue will remain closed :smiling_imp:
