### ISSUE TITLE
Extending an Object Type in Code

### ISSUE THREAD

**Issue by ldiego08** [graphql/graphql-js#1569]
(Posting here since haven't been able to get an answer from any other of channels. 😅)

So, using SDL you can add fields to an existing type like:

```
extend type Query {
   extraField: Int!
}
```

But how can I do this in code using the built-in classes (`GraphQLObjectType`, etc)? 

Sounds like `extendSchema` might offer a way, but it is undocumented and I'm not sure how to use it in this case.

Is this supported?

My apologies in advance if I'm missing something really obvious.

**Comment by otonielguajardo** [comment]
+1

**Comment by IvanGoncharov** [comment]
> Is this supported?

@ldiego08 Yes, it's supported. Our documentation lagging behind since it had last major updated in 2016. Discussed in #1368

For example on how to use `extendSchema` please see our tests:
https://github.com/graphql/graphql-js/blob/master/src/utilities/__tests__/extendSchema-test.js

**Comment by CoericK** [comment]
@IvanGoncharo Sorry to ask this after a while, but do we have now docs about this?

**Comment by CoericK** [comment]
@IvanGoncharov Sorry to ask this after a while, but do we have now docs about this?

**Comment by sibelius** [comment]
can we reopen this?

as extendSchema only works with SDL and not with graphql-js types?

**Comment by tot-ra** [comment]
+1, wanna reference external type for apollo federation as a plain string, but don't see other way than low-level string replace atm

**Comment by danielblignaut** [comment]
+1, any ideas on how to do this via code

**Comment by ostap1010** [comment]
+1, how to use "extend" with GraphQLObjectType?

**Comment by sjerratsch** [comment]
I was just experimenting with this and it turns out you can force the "extend type ..." in the SDL string output, if you do the following:

```js
new GraphQLObjectType({
    ...
    astNode: {kind: "ObjectTypeExtension", name: {kind: "Name", value: *NAME HERE*}},
    extensionASTNodes: [{kind: "ObjectTypeExtension", name: {kind: "Name", value: *NAME HERE*}}],
    ...
})
```

You need to set both. This won't interfere with the fields, but you may need to put directives yourself in "astNode" then, not sure.

**Comment by isaacgr** [comment]
> +1, how to use "extend" with GraphQLObjectType?

Is there anything like this?
