### ISSUE TITLE
Feature request: Pre-release or patch version bump for flow 0.85 compat

### ISSUE THREAD

**Issue by KevinGrandon** [graphql/graphql-js#1577]
Just requesting either a pre-release or patch version bump for flow 0.85 compatibility. Seems like support for 0.85 has landed, and we'd rather not stub the library out if possible.

Thank you for the excellent library.

**Comment by IvanGoncharov** [comment]
@KevinGrandon You can use NPM 📦 built from `master`:
https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge

**Comment by KevinGrandon** [comment]
I’ll do that for now, but pre-releases would be nice so automatic upgrade scripts would bring us to the main release cycle (which has better performance for installs). Thanks for the tip.

**Comment by IvanGoncharov** [comment]
> I’ll do that for now, but pre-releases would be nice so automatic upgrade scripts would bring us to the main release cycle (which has better performance for installs). 

@KevinGrandon Are suggesting releasing `14.1.0-rc1`?
Would `upgrade/npm-check-updates` react to releases without `latest` tag?

**Comment by KevinGrandon** [comment]
You all don't need to change your workflow, but a `14.1.0-rc1` would be nice. The reason being, many existing tools will upgrade `14.1.0-rc1` to `14.1.0` when released, and gives consumers a slightly better decision making process. E.g., "I'll take the risk to upgrade to this next minor version with a pre-release, but wouldn't want to upgrade to a major version".

You all don't need to change your workflow, but just consider this a request for more frequent pre-releases :).

**Comment by IvanGoncharov** [comment]
@KevinGrandon We just released `14.1.0` which should work with Flow `0.90.0`.
We started working on simplifying release process so it would result in more frequent feature & patch releases.
