### ISSUE TITLE
Allow non-English enum name

### ISSUE THREAD

**Issue by s97712** [graphql/graphql-js#1584]
Hi, I need use non-English enum name, but I get below error:
` Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "己审核" does not.`

Can support validate for other language?

**Comment by IvanGoncharov** [comment]
@s97712 It's intentional and according to the spec:
https://facebook.github.io/graphql/June2018/#Name

Please discuss this spec change here:
https://github.com/facebook/graphql/issues/256
