### ISSUE TITLE
[Possible bug] Using schema on the client doesn't work

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#159]
When I'm trying to run ```graphql``` on the client:
```
Error: Schema must be an instance of GraphQLSchema.
Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.
```
It seems the I'm using single version of graphql-js.

**Comment by gyzerok** [comment]
Bug was connected with webpack.

**Comment by alexandrethsilva** [comment]
@gyzerok Would you mind detailing what was the webpack issue at least for reference? I'm having the same issue.. :(

**Comment by gyzerok** [comment]
In my case this problem was with multiple version of graphql-js. Don't try
to require file within another directory with node_modules
16.09.2015 1:16 пользователь "Alexandre Theodoro da Silva" <
notifications@github.com> написал:

**Comment by richburdon** [comment]
@gyzerok, sorry to come back to this so much later, but I see that I also have:

node_modules/babel-relay-plugin/node_modules/graphql/graphql.js
node_modules/graphql/graphql.js

Do you know how to exclude the first one from webpack?

Thanks a lot.
