### ISSUE TITLE
How to know exactly which fields have error ? Is it possible to add metadata to errors ?

### ISSUE THREAD

**Issue by devnieL** [graphql/graphql-js#1591]
Hello,

I'm using a mutation that is returning **TypeError** errors like these (I assume that this is something usual and is handled in some elegant way by someone, but I'm not finding the proper approach, so give me a tip please)

![image](https://user-images.githubusercontent.com/1231888/49322581-a00e2a00-f4de-11e8-8897-92afb39728ce.png)

As defined by graphql spec, the `errors` array in the response have `error` objects with `locations` and `message` as properties. Considering that this is the result of a form that is send to the graphql backend and I need to map the failed inputs based on the response, **how to know exactly which field have errors?** I have thinking of these options:

- Implementing and additional validation layer in each resolver. (redundant, and I think that these errors are thrown before passing to the resolver, right?)
- Parse the `message` property with `regexp` to get the exact field. (really?)
- Add metadata to each error (maybe in its [extensions](https://facebook.github.io/graphql/June2018/#sec-Errors) property), at least the problematic field, modifying `graphql-js`. (where?)
- Add dynamic metadata to each error based on definitions in the schema. (is possible?)

Thanks

**Comment by devnieL** [comment]
Related https://github.com/graphql/express-graphql/issues/460

**Comment by IvanGoncharov** [comment]
@devnieL Can you please explain your use case for this feature?
Please note GraphQL errors are not intended to be used for client-side validation they are developer-friendly instead of user-friendly, don't support localization, etc.

**Comment by cvle** [comment]
@IvanGoncharov What's bad about using errors for validation? If it's about localization: The client could for example extract an `ERROR_CODE` to do localization by itself.

**Comment by cvle** [comment]
It's also useful for just handling unexpected situations. E.g. server configuration changed and the client wasn't refreshed yet to know about the latest changes. An application specific error code would let the client gracefully deal with the situation.
