### ISSUE TITLE
`.inspect()` is deprecated

### ISSUE THREAD

**Issue by bradennapier** [graphql/graphql-js#1599]
Are there plans to resolve the deprecation warnings that come with this library due to the use of `.inspect()` method being used?

Any attempt to log values within the library result in: 

```
(node:19489) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

on the LTS version of nodejs (v10)

https://github.com/graphql/graphql-js/blob/master/src/jsutils/inspect.js

https://github.com/nodejs/node/issues/15549

**Comment by IvanGoncharov** [comment]
@bradennapier Thanks for reporting 👍 
Fixed in `master`.
You can test it using:
https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge

**Comment by bradennapier** [comment]
Sweet! Thanks! I’ve since found quite a few libraries with this as an issue so seems fairly common.  Appreciate taking care of it as Node 11 removes support and it publishes the whole thing :)
