### ISSUE TITLE
Enum value is not resolved to internal value for directive argumets and default values

### ISSUE THREAD

**Issue by raduflp** [graphql/graphql-js#1604]
the [original issue](https://github.com/apollographql/graphql-tools/issues/715) was submitted to the `graphql-tools` repo,  but it seems that it never made it here. 

the issue is that after following the [official documentation ](https://www.apollographql.com/docs/graphql-tools/scalars.html#internal-values) the enum value is not resolved to the internal value when used as a default value or in directives. 

the test attached to the original issue provided by @JakeDawkins 
https://gist.github.com/JakeDawkins/66f5b026cf21515f1004f057754a2cd4

**Comment by IvanGoncharov** [comment]
@raduflp With current `graphql-js` design `defaultValue` should be in internal representation. So to correct example you need to do:

```js
const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
      avatar: {
        type: GraphQLBoolean,
        args: {
          anEnum: {
            type: allowedColor,
            defaultValue: '#f00',
            //            ^ Changed to value
          },
        },
        resolve: (root, args) => (args.anEnum === '#f00' ? false : true),
      },
    }),
  }),
});
```

Same goes for custom scalars, arrays or any other example of input coercion.
For example `ID` coerce numbers to strings but this coercion is not applied on `defaultValue`:

```js
const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: () => ({
      avatar: {
        type: GraphQLBoolean,
        args: {
          id: {
            type: GraphQLID,
            // INVALID defaultValue: 0
            defaultValue: '0', //VALID
          },
        },
      },
    }),
  }),
});
```

**Comment by langpavel** [comment]
Current behavior is expected :+1:

**Comment by IvanGoncharov** [comment]
@raduflp If you want this issue to be reopened, please free to ping me.

**Comment by dandv** [comment]
@IvanGoncharov: how do I pass the default value in the internal representation if it's a query parameter?

I've tried `0`, but the resolver gets `undefined`. I've tried an enum value, and the resolver gets it as a string. Here's the [Code Sandbox](https://codesandbox.io/s/apollo-server-typescript-starter-xx5jk?file=/index.ts).

**Comment by yaacovCR** [comment]
See https://github.com/ardatan/graphql-tools/issues/715#issuecomment-638526540

**Comment by dandv** [comment]
Actually see https://github.com/ardatan/graphql-tools/issues/715#issuecomment-638532140, which shows the problem lies with graphql.js.
