### ISSUE TITLE
Why root-level resolver params aren't passed to instance-level resolver by default ?

### ISSUE THREAD

**Issue by MendesKevin** [graphql/graphql-js#1632]
Hi, in [https://graphql.github.io/graphql-js/object-types/](graphql/graphql-js)
> Instead of a root-level resolver for the RandomDie type, we can instead use an ES6 class, where the resolvers are instance methods.

But graphql-js doesn't pass params resolver `( root, args, context, info )` for "instance-level" resolver.

There is a way to allow that globally or I must need wrap with a root-level resolver for each field where I call the instance-level resolver or this isn't the recommended GraphQL way ?
```
class RandomDie {
  constructor(dice) {
    this._numSides = dice.numSides
  }

  numSides(context) {
    context.canSeeNumSides ? this._numSides : null
  }
}

const resolvers = {
  RandomDie: {
    numSides: (root, args, context, info) => root.numSides(context)
  }
}
```
note: I use `{ makeExecutableSchema } from graph-tools`

**Comment by IvanGoncharov** [comment]
> But graphql-js doesn't pass params resolver ( root, args, context, info ) for "instance-level" resolver.

@MendesKevin It passes `( args, context, info )` all arguments shifted by one, because is `root` is equal to `this`.
So you can write:
```js
class RandomDie {
  constructor(dice) {
    this._numSides = dice.numSides
  }

  numSides(ags, context) {
    context.canSeeNumSides ? this._numSides : null
  }
}
```

**Comment by MendesKevin** [comment]
Oops, thank you !
