### ISSUE TITLE
Bug in parser: "extend type" declaration breaks parser

### ISSUE THREAD

**Issue by nemanja-stanarevic** [graphql/graphql-js#166]
Adding the following test to schema kitchen sink breaks the print test (visitor throws "Invalid AST Node")- 
```
extend type Foo {
  seven(argument: [String]): Type
}
```

Root cause is a typo in the parser code -  parser currently imports TYPE_EXTEN**T**ION_DEFINITION (instead of TYPE_EXTEN**S**ION_DEFINITION).  This causes `parseTypeExtensionDefinition` to return a `TypeExtensionDefinition` value with `kind` field undefined, which in turn causes visitor to throw "Invalid AST Node".

I will submit a PR with the patch and updated test case shortly.

**Comment by leebyron** [comment]
Thanks for the investigation and fix!

**Comment by tjwebb** [comment]
Where is this `extend` documented? I see it mentioned only as an afterthought in the spec.

**Comment by leebyron** [comment]
It's experimental right now and thus has limited documentation. There's a proposal to add it to the spec.

**Comment by tjwebb** [comment]
How is it used? I'd like to be able to extend `Query` so that I don't need to define all of my root queries in one place.
