### ISSUE TITLE
Latest version v14.1.0 breaks react-apollo and apollo-boost

### ISSUE THREAD

**Issue by pitops** [graphql/graphql-js#1668]
I have upgraded to latest version of GraphQL v14.1.0 and my build won't work after that. It fails to require `react-apollo` and `apollo-boost`. 

Version 14.0.2 works fine.

**Comment by langpavel** [comment]
Can you provide more info please?

**Comment by michalkvasnicak** [comment]
For us it breaks typecheck. 

Flow `0.83.0`, when downgrading to `14.0.2` typecheck passes. 

![image](https://user-images.githubusercontent.com/174716/51238094-55554e00-1976-11e9-9974-16061a8a1d42.png)

**Comment by langpavel** [comment]
Flow 0.84.0:
* Added support for wildcard (`_`) type arguments to function / constructor calls. This is
especially useful when some type arguments are sufficient to pin down the type of the result; the
others can simply be `_`.

[full changelog](https://github.com/facebook/flow/releases/tag/v0.84.0)

**Comment by michalkvasnicak** [comment]
@langpavel thank you very much. I lost a track of flow changes as we are slowly transitioning to typescript.

**Comment by IvanGoncharov** [comment]
@langpavel Thanks for the clarification 👍 

@michalkvasnicak I still Flow placeholders are pretty confusing so I removed them as #1669 

>I have upgraded to latest version of GraphQL v14.1.0 and my build won't work after that. It fails to require react-apollo and apollo-boost.

@pitops Can you please provide some details? For example, copy-paste errors here.

**Comment by pitops** [comment]
@IvanGoncharov sure give me until tomorrow and I will try to replicate again.

**Comment by pitops** [comment]
@IvanGoncharov i was able to replicate it today, but after removing `node_modules` and `yarn.lock` and re-installed, everything seems to be working correctly. 

It seems as though the issue is with `yarn.lock` ?

**Comment by langpavel** [comment]
yarn.lock should guarantee that same package versions will be installed.
Then it should be deterministic if your app fail or work same way.
Which yarn.lock? Your is yours :-p :smiling_imp:

**Comment by IvanGoncharov** [comment]
@pitops You probably had two different versions of `graphql-js` in your `node_modules`.
This could happen if one of dependencies depend on `graphql` as direct dependency and not as `peerDependency`.
You can test it using `npm ls` and should see only one version of `graphql`.
