### ISSUE TITLE
Add tests for 'toConfig' functionality

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#1674]
Just a reminder that I need to write a test for `toConfig` functionality but I don't mind if someone wants to help 😉

**Comment by doniyor2109** [comment]
@IvanGoncharov  Hi ✋. I want to help for this issue if you want)

**Comment by IvanGoncharov** [comment]
@doniyor2109 Would be great 👍 
Then you will have a few tests ready please open WIP PR so I can provide feedback early on.

**Comment by doniyor2109** [comment]
@IvanGoncharov I have opened PR and it contains first test. I have test equality of config values. Is there anything to add in this test?

**Comment by yaacovCR** [comment]
Closed by #4225
