### ISSUE TITLE
how to extend execution?

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#169]
I would like to create new method for schema ```fromCache``` which would be similar to ```resolve``` but for client-side usage. It would look like as follows:
```javascript
const todoType = new GraphQLObjectType({
  name: 'Todo',
  description: 'Todo type',
  fields: () => ({
    id: {
      type: new GraphQLNonNull(GraphQLID),
      description: 'Todo id',
    },
    text: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Todo text',
    },
    owner: {
      type: userType,
      resolve: (todo, _, { rootValue: db }) => {
        // server resolution logic
      },
      fromCache: (todo, _, { rootValue: cache }) => {
        // cache resolution logic
      },
    },
    createdAt: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Todo creation date',
    },
  }),
});
```
Is there a way to do it easily?

**Comment by leebyron** [comment]
I'm assuming that you're sharing this code across server and client. Perhaps you could put this in `resolve`?

resolve: (todo, _, { rootValue: { db, cache } }) => {
  if (cache) {
    // cache logic
  } else {
    // db logic
  }
});

**Comment by gyzerok** [comment]
@leebyron Yes I could, but it would force developer to write some boilerplate code. It would be awesome to have an ability to select default resolve behavior for a field in some cases.

**Comment by leebyron** [comment]
I'm curious what this looks like in practice and what kind of boilerplate it creates. 

To me, having two separate functions (6 LOC) vs an if-case (7 LOC) do not feel like a wildly different amount of boilerplate, and certainly the separate function you propose would require GraphQL's internals to understand caching at a deep level which currently it does not.

Perhaps I'm missing something in the example above about the boilerplate that would be more clear in a fuller example of the usage of these two functions. For example, what does a typical vs advanced use of `fromCache` look like? Where does `cache` get populated? Invalidated?

**Comment by gyzerok** [comment]
I'm writing a tool on top of GraphQL and Redux. Its somehow similar to Relay. The purpose is I do not want to force the developer always write cache resolve strategies. I'd like to provide simple resolve mechanism as a default realisation for a resolve function. But as soon as I cant somehow hook up into GraphQL execution logic I need to rewrite all the execution code in order to achieve this. Mostly this rewrited code would be copypaste from [your execution](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js).

So if I'm able to do it the default behaviour would be 0 LOC vs 7 LOC.

const todoType = new GraphQLObjectType({
  name: 'Todo',
  description: 'Todo type',
  fields: () => ({
    id: {
      type: new GraphQLNonNull(GraphQLID),
      description: 'Todo id',
    },
    text: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Todo text',
    },
    owner: {
      type: userType,
      resolve: (todo, _, { rootValue: db }) => {
        // server resolution logic
      },
      fromCache: (todo, _, { rootValue: cache }) => {
        // If this function not provided just populate todo owner implicitly
      },
    },
    createdAt: {
      type: new GraphQLNonNull(GraphQLString),
      description: 'Todo creation date',
    },
  }),
});

**Comment by gyzerok** [comment]
So if I have separate function here I can get if its provided or not which I cant achieve with If ... else.

**Comment by gyzerok** [comment]
As far as I understand execution source code all I'm requesting is an ability to configure [this step](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L482).

```javascript
const resolveFn = getResolveFn === 'function' ? getResolveFn(fieldDef) : fieldDef.resolve || defaultResolveFn;
```

Where `getResolveFn` may be provided by the developer.

**Comment by freiksenet** [comment]
One way to do this is to define different resolve function on schema creation time. You can wrap `GraphQLObjectType` in a factory method that will pass `resolve` corresponding to current environment, so cache resolve in client side and normal resolve on server side.

**Comment by freiksenet** [comment]
eg

```js
function createType(config) {
   return new GraphQLObjectType({
      ...config,
      resolve: IS_CLIENT ? config.clientResolve : config.serverResolve
   });
}
```
