### ISSUE TITLE
Single-argument mutation fails

### ISSUE THREAD

**Issue by JeffML** [graphql/graphql-js#1691]
graphql@0.13.2

This fails when queried from Playground (apollo-boost@0.1.22):
```
    mutation logarino {
    	login(pw:"flum")
    }
```
but only if the mutation is defined with one argument:

```
type Mutation {
    login(pw: String!): Int!
}
---
    Mutation: {
        login: (pw) => login(pw),
---
async function login(_, {pw}) {    //ERROR:  second parameter is null, so {pw} = null throws exception
    console.log({pw})

    return 3;
}
```

This works:

```
type Mutation {
    login(pw: String!, dummy: Int): Int!
}
---
    Mutation: {
        login: (pw, dummy) => login(pw, dummy),
---
async function login(_, {pw}) {    //NO ERROR
    console.log({pw})  // displays pw value

    return 3;
}

```

**Comment by Neitsch** [comment]
Hi Jeff,
```
    Mutation: {
        login: (pw) => login(pw),
```
Above you are calling login with only one argument, hence all following ones will be undefined or null.

The order of arguments for a field is the following: `obj, args, context, info`, so you are looking to do something like
```
    Mutation: {
        login: (_, {pw}) => login(pw),
---
async function login(pw) {
    console.log({pw})

    return 3;
}
```

**Comment by JeffML** [comment]
Okay, maybe I got lucky on my other two mutators, which have two parameters
and have been working:

    Mutation: {
        login: (pw, dummy) => login(pw, dummy),
*        deleteOptions: (type, names) => deleteOptions( type, names ),*
*        upsertOptions: (type, options) => upsertOptions(type, options),*

    }

async function deleteOptions(_, {optionType, names}) {
    console.log(_, {optionType, names} )
    const result = await doQuery(mDeleteOptions(optionType), [names])
    // console.log(result)
    return result.affectedRows;
}

async function upsertOptions(_, {optionType, options}) {
    const results = [];
    options.forEach(o => results.push(doQuery(mUpsertOptions(optionType),
[o, o])))
    await Promise.all(results);
    return results.length;
}

Those two function get the correct arguments (somehow).  I can see where I
might have forgotten about the underscore parameter in the resolvers.  I'll
review tomorrow.

-- Jeff
