### ISSUE TITLE
Custom GraphQLScalarType instance: parseLiteral is called twice

### ISSUE THREAD

**Issue by createcsoft** [graphql/graphql-js#1713]
The parseLiteral method is called twice 

```
const express_graphql = require('express-graphql')
var { buildSchema } = require('graphql')

var OddType = new GraphQLScalarType({
  name: 'Odd',
  parseLiteral(ast) {
   console. log('this print twice before continue with the resolver')
    return null
}
}
```

**Comment by IvanGoncharov** [comment]
@createcsoft Thanks for taking the time to report this issue 👍 
It was already reported as #383 so I'm closing this as a duplicate.

**Comment by applegrew** [comment]
I have faced this issue, but the issue in my case is with Mercurius. It first runs `buildContext` which evaluates the variables, then it fires `execute` which again fires `buildContext` which in-turn again executes the variables. (ref: https://github.com/mercurius-js/mercurius/blob/master/index.js#L507)
