### ISSUE TITLE
Mutation Error

### ISSUE THREAD

**Issue by thecodelayeriser** [graphql/graphql-js#1716]
Graphql returns a unexpected error message: 

```
"message": "Variable \"$_v0_data\" got invalid value { data: { firstName: \"Testname\" }, where: { id: \"cjrqiecl7p0b40a85th4ie4uf\" } }; Field \"data\" is not defined by type MemberUpdateInput; did you mean avatar?\nVariable \"$_v0_data\" got invalid value { data: { firstName: \"Testname\" }, where: { id: \"cjrqiecl7p0b40a85th4ie4uf\" } }; Field \"where\" is not defined by type MemberUpdateInput."
```

The expected behaviour is to run the mutation:

```
mutation {
  updateMember(
    data: {
      firstName: "Testname" }
    where: {
      id: "cjrqiecl7p0b40a85th4ie4uf"
    }
  ) {
    id
    email
  }
}
```

Below image with schema mutation and arguments that should take the above used data. 

<img width="2509" alt="screenshot 2019-02-06 at 13 55 46" src="https://user-images.githubusercontent.com/41742232/52343079-6e05d080-2a17-11e9-895f-a2d626f07248.png">

**Comment by jgcmarins** [comment]
can you write a failing test?

**Comment by thecodelayeriser** [comment]
@jgcmarins I would love to - by honestly not at that level yet. I'm just very unsure why I'm getting this error my setup is according to spec. Any idea?

**Comment by IvanGoncharov** [comment]
@thecodelayeriser It looks like you are using Prisma as your backend, right?
If so please report it their repo: https://github.com/prisma/prisma
