### ISSUE TITLE
Schema, handling many-to-many queries

### ISSUE THREAD

**Issue by AJ1310** [graphql/graphql-js#173]
I have a problem with this specific scenario, and have not found much documentation. How in JS can i make a schema that allows me to query many to many ObjectTypes?

**Comment by freiksenet** [comment]
You can define a `GraphQLList` on both sides.

```js
const User = new GraphQLObjectType({
   name: 'User', 
   fields: () => ({
     groups: {
       type: new GraphQLList(Group)
     }
  })
});

const Group = new GraphQLObjectType({
   name: 'Group', 
   fields: () => ({
     users: {
       type: new GraphQLList(User)
     }
  })
});
```

How the `resolve` function would work is totally up to how you store your data.

**Comment by leebyron** [comment]
@freiksenet is dead on - closing this task.

**Comment by LouisStAmour** [comment]
For those who (like me) stumble on this page from Google, instead of a list, consider connections for the pagination benefits: https://facebook.github.io/relay/docs/graphql-connections.html -- see also https://github.com/graphql/graphql-relay-js/issues/20

**Comment by YasinYA** [comment]
How about making mutations?
