### ISSUE TITLE
"graphql" function promise never resolved

### ISSUE THREAD

**Issue by OwenCalvin** [graphql/graphql-js#1749]
In my jest test (TS) I have this part of code:
```javascript
import { GraphQLSchema, graphql } from "graphql";
...
describe("Functional", () => {
  let schema: GraphQLSchema
  ...
  it("should pass input validation when data without optional field is correct", async () => {
    const mutation = `mutation {
      sampleMutation(input: {
        stringField: "12345",
        numberField: 5,
      }) {
        field
      }
    }`;
    await graphql(schema, mutation);
    expect(argInput).toEqual({ stringField: "12345", numberField: 5 });
  });
});
```
the `schema` variable has this value (The object is too big to post it entirely, so I give you a screenshot):
![image](https://user-images.githubusercontent.com/17951357/53095677-c19b1280-351d-11e9-90f8-2d405b42d080.png)

# The problem
The `await graphql(schema, mutation);` promise are never resolved so the next line are never executed... I don't know why....

**Comment by IvanGoncharov** [comment]
@OwenCalvin Please check your resolvers it's almost 100% it stuck there.
If all of your resolvers is sync you can replace `graphql` with `graphqlSync`and remove `await` to diagnose this problem.
If you sure that all of your resolvers returned and execution stuck in `graphql-js` code please provide a simplified reproduce example.
