### ISSUE TITLE
Upgrading broke custom scalar resolvers when using with apollo-server

### ISSUE THREAD

**Issue by stephenhandley** [graphql/graphql-js#1755]
I'm having an issue when `graphql` when using with `apollo-server` and upgrading from `0.13.2` to `14.1.1`. After upgrading, our previously working Scalar Resolvers stopped working: `parseDefault`, `parseLiteral`, and `serialize` are no longer getting called. 

The reason for the upgrade was that in `0.13.2`, primitive scalar types weren't being properly validated (more details available [here](https://github.com/apollographql/apollo-server/issues/2375)). 

There are some additional details on [this comment](https://github.com/apollographql/apollo-server/issues/2218#issuecomment-467648380) I made on a related issue in `apollo-server`.

I'm hoping to get some guidance on whether there is some intermediate version of `graphqI` I could use so that both custom and primitive scalar validation work properly in `apollo-server`.

**Comment by IvanGoncharov** [comment]
> I'm hoping to get some guidance on whether there is some intermediate version of `graphql` I could use so that both custom and primitive scalar validation work properly in `apollo-server`.

We have very limited developer resource ATM so we stopped supporting `0.13.x` after `14.0.0` release.
Don't know why `parseLiteral` and `serialize` stopped working for you but I highly suspect it some `apollo-server` specific issue. 
If you can reproduce this issue using pure `graphql-js` API please post example code and we will fix it ASAP otherwise please report it to `apollo-server` repo.

**Comment by stephenhandley** [comment]
Hi @IvanGoncharov The issue had to do with the upgrade breaking the approach I was taking in [graphql-validated-types](https://github.com/stephenhandley/graphql-validated-types) where I subclassed `GraphQLScalarType` from `graphql`.

Basically, using the `GraphQLScalarType` constructor directly still works, however the approach I took to subclassing `GraphQLScalarType` in [graphql-validated-types](https://github.com/stephenhandley/graphql-validated-types) appears to break on all versions of `graphql` after `0.13.2`, wherein those custom scalar resolvers are not run.

Was resolved by bumping the version of graphql that lib was using and modifying my implementation to be compatible with `14.x.x`, there's a repo demonstrating a fix for the issue [here](https://github.com/stephenhandley/CustomScalarResolversFailToRunExample)
