### ISSUE TITLE
CoerceFloat throwing error instead of parsing string to float from json

### ISSUE THREAD

**Issue by BePasquet** [graphql/graphql-js#1779]
Hi i notice that recently i started getting this error
TypeError: Float cannot represent non numeric value: "234234234"
    at GraphQLScalarType.coerceFloat [as parseValue]
i have another api that works fine when i started looking at the problem i realize that graphql was a different version where in version 14.1.1 coerceFloat is 
```
function`` coerceFloat(value) {
  if (!(0, _isFinite.default)(value)) {
    throw new TypeError("Float cannot represent non numeric value: ".concat((0, _inspect.default)(value)));
  }

  return value;
}
```
 in version 0.13.2 coerceFloat is 
```
function` coerceFloat(value) {
  if (value === '') {
    throw new TypeError('Float cannot represent non numeric value: (empty string)');
  }
  var num = Number(value);
  if (num === num) {
    return num;
  }
  throw new TypeError('Float cannot represent non numeric value: ' + String(value));
}
```

when i copy paste second one in first one in scalar.js it just works fine

**Comment by IvanGoncharov** [comment]
@BePasquet It was one of breaking change that we made in `14.0.0`:
https://github.com/graphql/graphql-js/releases/tag/v14.0.0

Note: it was always intended to work like this, since here is what GraphQL spec says:

https://facebook.github.io/graphql/June2018/#sec-Float
> When expected as an input type, both integer and float input values are accepted. Integer input values are coerced to Float by adding an empty fractional part, for example 1.0 for the integer input value 1. **All other input values, including strings with numeric content, must raise a query error indicating an incorrect type**.

**Comment by BePasquet** [comment]
Hi @IvanGoncharov thanks for the quick response sorry my ignorance but input type number return strings so all inputs on fe web apps will need to be parsed?

**Comment by IvanGoncharov** [comment]
> sorry my ignorance but input type number return strings so all inputs on fe web apps will need to be parsed?

@BePasquet Yes, moreover it's always a good idea to validate on fe.
GraphQL validation is intended to assist with debugging during development that's why error messages are not user-friendly and don't support for internationalization.

**Comment by BePasquet** [comment]
@ivanGoncharov Thanks for building things like this for us

**Comment by riginoommen** [comment]
> @BePasquet It was one of breaking change that we made in `14.0.0`:
> https://github.com/graphql/graphql-js/releases/tag/v14.0.0
> 
> Note: it was always intended to work like this, since this is what GraphQL spec says:
> 
> https://facebook.github.io/graphql/June2018/#sec-Float
> 
> > When expected as an input type, both integer and float input values are accepted. Integer input values are coerced to Float by adding an empty fractional part, for example 1.0 for the integer input value 1. **All other input values, including strings with numeric content, must raise a query error indicating an incorrect type**.

What is the proposed change to do it in the code

**Comment by BePasquet** [comment]
@riginoommen in angular i created a directive that parses strings to number not to have to parse every time hope it helps
