### ISSUE TITLE
[QUESTION] Variables to ID

### ISSUE THREAD

**Issue by csabascript** [graphql/graphql-js#1780]
# Questions about variables.

Can't find any examples online. If i have a query with 10+ variable object the id would be stringified object. Usually in this object some variables are just defaults.

Is it possible to override the generated id? so i would like to remove the keys with default values.

```javascript
query({a: 1, b: 'foo', c: null, d: [], e: 2, f: undefined, g: {}})
```
1) will have an ID of `"$ROOT_QUERY.xyz({a: 1, b: 'foo', c: null, d: [], e: 2, f: undefined, g: {}})"` however It could be shortened to `"$ROOT_QUERY.xyz({a: 1, b: 'foo', e: 2})"` in my use case.
or
2) `someHashingAlgorithm({a: 1, b: 'foo', c: null, d: [], e: 2, f: undefined, g: {}})` would also suite my needs.

**Comment by IvanGoncharov** [comment]
@csabascript Not sure that I understand your question.

> Is it possible to override the generated id?

This library doesn't provide any functionality to generate query IDs are you sure that you opened this issue in the correct repo?
