### ISSUE TITLE
Cut  '14.2.0' release

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#1803]
ATM we have 113 unreleased commits in `master` including few bug fixes and a partial fix for security problem reported #1753 
I don't think we should further delay this release.
Also, a few community members contacted me saying they depend on features that exist only in `master` and they can't release they code util `14.2.0`.

ATM, I'm working on generating changelog based on PR labels.
@mjmahone What do you think?

**Comment by mjmahone** [comment]
This sounds like a good plan to me. We should not have any breaking changes, to my knowledge, so a minor version bump seems reasonable.

**Comment by IvanGoncharov** [comment]
@mjmahone One potential issue that can affect Flow users is #1702 since before it `print` was untyped.
Because no runtime behavior is changed and Fow errors are pretty easy to fix I don't think it will be a big problem, just something that can affect mainly GraphQL tooling.
I will add a warning about it into changelog.

**Comment by mjmahone** [comment]
Yeah if it's just typing and not actual behavior changes that is fine.

We want to avoid a situation where flow types were added and functionality changed at the same time, so if you upgrade you can't easily know how to get your formerly-working code to conform. Seems like there's no danger of that: if your flow types are wrong your expectations of what `print` was producing was wrong, so your existing code is probably not quite right.

**Comment by IvanGoncharov** [comment]
📦 was successfully released to NPM 🎉
