### ISSUE TITLE
custom serializing & parsing for nullable and non-nullable data types

### ISSUE THREAD

**Issue by abdul-takt** [graphql/graphql-js#1859]
I'd like to handle serializers & parsers for nullable and non-nullable data types differently.  An example is using Maybe types to handle `Nullable` values.

example
```graphql
type data {
  nullable: Int,
  nonNullable: Int!
}
```
parseValue for nullable Int  (using sanctuary.js or ramda.js)
```javascript
import S from 'sanctuary';

serialize (val) {
  if (val == null) return 'Nothing';
  else return `Just (${val})`;
}
parseValue (val) {  // example:  "Just (10)", "Just ('String Value')" or "Nothing" 
  if (val == 'Nothing' || !val) return S.Nothing
  else return customParser (val); // returns S.Just (10) if val === "Just (10)"
}
```

parseValue for non-Nullable Int
```javascript
serialize (val) {
  return String (val);
}
parseValue (val) {
  return Number (val)
}
```

Is there a way to override the default methods or a way to check to see if the value has been define as nullable or not in the serializer, parser or resolver functions?

**Comment by IvanGoncharov** [comment]
> Is there a way to override the default methods or a way to check to see if the value has been define as nullable or not in the serializer, parser or resolver functions?

@abdul-takt No, since `graphql-js` is the reference implementation of GraphQL it should strictly follow GraphQL specification which is very detailed on how `Int` type should behave: https://graphql.github.io/graphql-spec/June2018/#sec-Int
