### ISSUE TITLE
Add experimental @live directive to subscribe to query

### ISSUE THREAD

**Issue by KyleAMathews** [graphql/graphql-js#188]
In a conversation with @dschafer he suggested using a `@live` directive as a way to tell the graphql server to create a subscription around a query.

Per #41 support for this would need to be added to graphql-js itself?

**Comment by leebyron** [comment]
https://github.com/graphql/graphql-js/pull/215 adds the ability to provide custom directives to a schema, but of course you'll still have to interpret those directives yourself :)

**Comment by KyleAMathews** [comment]
👍🏻 thanks!
