### ISSUE TITLE
Having multiple inputs

### ISSUE THREAD

**Issue by tonystaark** [graphql/graphql-js#1890]
# Feature requests
It would be great if we can have this feature to enable multiple inputs insertion for example :
```
type Mutation{
  add(input: {typeA, typeB}): output
}
```
Then in our resolver we can do,
```
Mutation:{
   add: async(_, arg, ctx) => {
      let author = new Author();
      author.key = arg.typeA.id;

      let book = new Book();
      book.key = arg.typeB.id;
   }
}
```
In the playground, for query we can do;
```
mutation($input: input){
 addAuthorAndBook(input: $input){
  author{
   key
  }
  book{
    key
  }
 }
}
```
For Variable, we can
```
{
  "input"":{
    "typeA":{
      id
    },
   "typeB":{
      id
    }
  }
}
```

**Comment by IvanGoncharov** [comment]
@tonystaark `graphql-js` is the reference implementation of GraphQL so it new language features should be added to the spec first: https://github.com/graphql/graphql-spec
So you can open an issue there but please note that GraphQL tries to avoid complexity introduced by syntax sugar:
https://github.com/graphql/graphql-spec/blob/master/CONTRIBUTING.md#guiding-principles
> There are plenty of behaviors and patterns found in other languages intentionally absent from GraphQL. "Possible but awkward" is often favored over more complex alternatives. Simplicity (e.g. fewer concepts) is more important than expressing more sophisticated ideas or writing less.
