### ISSUE TITLE
Name of a field inside errors:{locations:[]}

### ISSUE THREAD

**Issue by xpepermint** [graphql/graphql-js#192]
Can we add somehow the name of a field which has an invalid value? I would like to use this inside `parseLiteral` - that's where I do validation and where the GraphQLError with a custom message is thrown.

```
mutation RootMutation {
  addUser(
    email: "invalid.email",
  ){email}
}
```

``` js
  return new GraphQLScalarType({
    name: attrs.name,
    serialize: function(value) {
      return value;
    },
    parseValue: function(value) {
      return value;
    },
    parseLiteral: function(ast) {
      if (!isValid) {
        throw new GraphQLError(`The field ${ast.fieldName} is invalid.`, [ast]); // HERE
      }
      return ast.value;
    }
  });
```

```
{
  "errors": [
    {
      "message": "\"Email\" is invalid.",
      "locations": [
        {
          "line": 5,
          "column": 12,
          "field": "email" // HERE
        }
      ]
    }
  ]
}
```

**Comment by laktarugar** [comment]
I have another solution of this error. We may add to GraphQLError method "toJson". In this case we will be able to customize error response inside each project.

**Comment by leebyron** [comment]
Totally! There's a nice PR in progress at #204 that will make errors for input objects easier to understand

**Comment by xpepermint** [comment]
Great!

**Comment by richburdon** [comment]
Runtime errors are still inscrutable:

```
demos/sub/graphql/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: Expected Output type.
    at invariant (demos/sub/graphql/node_modules/graphql/jsutils/invariant.js:19:11)
```

Suggest to output the schema snippet/line no. or at least the typename?

**Comment by stubailo** [comment]
In other news, this should probably be closed since we have `path` on errors now.

**Comment by leebyron** [comment]
@richburton can you give a full stack trace so we can look into it? Typically this kind of invariant shouldn't be throwing errors, so it seems like a sign of a different issue

**Comment by leebyron** [comment]
@richburdon ^

**Comment by leebyron** [comment]
Agree @stubailo, the original issue here has been solved. Closing this, but feel free to discuss further if there's anything missing

**Comment by richburdon** [comment]
@stubailo Can you confirm which versions have the path on error?

I have graphql@0.8.2 and graphql-tools@0.8.1 with the error above (no path) while executing makeExecutableSchema.

**Comment by stubailo** [comment]
@richburdon the original issue was about a different thing - `formatError` for returning the `errors` field on the result. Your error seems to be something else, and you should open a new issue for it including the full stack trace as Lee suggested.

**Comment by richburdon** [comment]
Sorry. Got it.
