### ISSUE TITLE
GraphQL not accepting the Bearer token sent via restassured

### ISSUE THREAD

**Issue by veeramanib** [graphql/graphql-js#1925]
Hi, I am trying to test the graphql queries via restassured. When i try to pass bearer token via header, its not accepting the token and gives this error:

{"timestamp":"2019-05-28T20:47:48.065+0000","status":403,"error":"Forbidden","message":"Invalid Access Token.User Not logged In")

Here's my restassured call:

response = given().relaxedHTTPSValidation().header(new Header("Authorization", "Bearer " + token))	             			       .contentType(ContentType.JSON).request().body(request).when().post(baseUrl);

what im doing wrong here? Same thing works fine from Postman & Graphiql

**Comment by IvanGoncharov** [comment]
Hi @veeramanib,

This questing is unrelated to `graphql-js` since it doesn't deal with HTTP.
Please, open a question on StackOverflow or repo issue to client or server library you are using.
