### ISSUE TITLE
Mutation with custom JSON attribute

### ISSUE THREAD

**Issue by xpepermint** [graphql/graphql-js#193]
I need to save a `custom` field which is a dynamic JSON/Hash object (e.g. key-value object but you don't know key names) and you never know its structure.
```
mutation RootMutation {
  addUser(
    id: "1",
    name: "John",
    custom: {"json": "data", "unknown": "structure"} // THIS ???
  ){name, custom}
}
```
```js
module.exports = new GraphQLObjectType({
  name: 'RootMutation',
  fields: {
    addUser: {
      type: GraphQLIdentityType,
      args: {
        id: {type: GraphQLID},
        name: {type: GraphQLName},
        custom: {type: ????} // HERE
      },
      resolve(parent, args) {
        ...
      }
    }
  }
});
```
How can I do that? I could convert JSON object to string but it doesn't feel right. Currently I get `Syntax Error GraphQL`.

**Comment by Sandreu** [comment]
Hello,

I think that's what we are talking about here #172 and in specs https://github.com/facebook/graphql/issues/101

**Comment by xpepermint** [comment]
True, closing.
