### ISSUE TITLE
what are the additional parameters used for in the graphql function?

### ISSUE THREAD

**Issue by matt453** [graphql/graphql-js#194]
in examples of calling graphql()  I only see the schema and the request being passed
```
graphql(schema, req.body)
```
what can I do with the other parameters I see present in graphql.js
```
function graphql(schema, requestString, rootValue, variableValues, operationName) {
...
}
```
what I need to do is be able to access the headers of the request further along.  specifically I want access to the headers when I am defining my promise for resolving one of my types and I was wondering what these fields were for, if I can use them to pass additional info through, or if there is another way to pass additional info deeper in besides the schema and the graphql request

**Comment by jifeon** [comment]
I think you can use `rootValue` which will be passed to `resolve` function as first argument:
```js
graphql(scema, req.body, req.headers);

...

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      user: {
        type: userType,
        resolve: (headers, params, ...args) => {
          // ... do something tricky with headers
        }
      },
    }
  })
});
```

**Comment by matt453** [comment]
I can confirm that this does work.  is this what the rootValue parameter is intended for?  passing along addtional info beyond the graphql query to resolve?

**Comment by jifeon** [comment]
I think yes, but I have never seen documentation about it. Maybe @leebyron could clarify where it's described..

**Comment by leebyron** [comment]
You can check out docs for this on the site http://graphql.org/docs/api-reference-graphql/#graphql or in the code. I'll update the code to have more verbose docs.
