### ISSUE TITLE
Duplicate graphql modules cannot be used at the same time

### ISSUE THREAD

**Issue by jatinvmehta** [graphql/graphql-js#1951]
We have react relay application which uses react 16.2 and graphql 0.13.1 We are trying to upgrade to latest react to use some of the advance feature and getting above error.

Here is our dependency and dev dependency look like

`  "dependencies": {
    "@fullcalendar/daygrid": "^4.0.1",
    "@fullcalendar/interaction": "^4.0.2",
    "@fullcalendar/react": "^4.0.2-beta",
    "@fullcalendar/timegrid": "^4.0.1",
    "axios": "^0.18.0",
    "babel-plugin-relay": "^1.7.0",
    "babel-polyfill": "^6.26.0",
    "draft-js": "^0.10.5",
    "draft-js-export-html": "^1.2.0",
    "draft-js-import-html": "^1.2.1",
    "express": "^4.16.2",
    "farce": "^0.2.3",
    "found": "^0.3.5",
    "found-relay": "^0.3.1",
    "found-scroll": "^0.1.4",
    "graphql": "^14.3.1",
    "isomorphic-fetch": "^2.2.1",
    "jsonexport": "^2.0.11",
    "lodash": "^4.17.5",
    "moment": "^2.24.0",
    "moment-range": "^4.0.2",
    "nodemon": "^1.12.1",
    "papaparse": "^4.6.2",
    "prop-types": "^15.6.0",
    "react": "^16.8.6",
    "react-big-calendar": "^0.20.3",
    "react-daterange-picker": "^2.0.1",
    "react-dom": "^16.8.6",
    "react-draft-wysiwyg": "^1.12.13",
    "react-relay": "^1.7.0",
    "relay-compiler": "^1.7.0",
    "relay-compiler-webpack-plugin": "^1.0.4",
    "sanitize-html": "^1.19.1",
    "semantic-ui-css": "^2.2.12",
    "semantic-ui-react": "^0.77.2",
    "snyk": "^1.52.0",
    "sync-request": "^4.1.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.0.2",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "concurrently": "^3.5.1",
    "css-loader": "^0.28.7",
    "dotenv": "^4.0.0",
    "eslint": "^4.12.0",
    "eslint-plugin-react": "^7.5.1",
    "extract-text-webpack-plugin": "^3.0.1",
    "file-loader": "^1.1.5",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "node-sass": "^4.12.0",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.0",
    "url-loader": "^0.6.2",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.5"
  }`

When try to compile project, it compile successfully but hitting application gives following error

Module not found: Error: Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
 @ ./src/pages/RecommendationEngine/RecommendationEngineContainer.js 859:15-86 865:11-82
 @ ./src/lib/routes.js
 @ ./src/lib/farceRouter.js
 @ ./src/browser.js
 @ multi (webpack)-dev-server/client?

Thanks in advance

**Comment by IvanGoncharov** [comment]
@jatinvmehta Please remove `node_modules` and do fresh `npm install` or `yarn`.
If this doesn't help please check the output of `npm ls graphql` to see what packages that depend on conflicting versions.
