### ISSUE TITLE
Don't wait for parent to resolve before requesting child

### ISSUE THREAD

**Issue by appleton** [graphql/graphql-js#196]
I have a query like this:

```
{
  parent_type(id: "1232") {
    id
    child_type {
      id
    }
  }
}
```

and type definitions like this:

```js
new GraphQLObjectType({
  name: 'parent_type',
  fields: () => {
    return {
      id: {
        type: GraphQLString
      },
      children: {
        type: new GraphQLList(ChildType),
        resolve(parent, args, query) {
          return request({
            method: 'GET',
            path:   `/parents/${parent.id}/children`
          });
        }
      }
    };
  }
});
```

When I run the query, the app first fetches the parent, *then* fetches the children. In my case I could do these operations in parallel as the request for children only needs the ID which I'm providing as an argument.

Is there a way to make this happen?

**Comment by leebyron** [comment]
Unfortunately this isn't possible at the moment.

**Comment by Cyberlane** [comment]
@leebyron is this still the case with the current version v.0.8.2 ?
If so, is there perhaps some metadata that could be stored and shared within the lifetime of the executed query, allowing me to share the ID with all my other type resolvers?

**Comment by leebyron** [comment]
This is still the case. It also isn't a matter of what version of the library you're using or some missing feature - but a fundamental aspect of recursive fetching.

This was addressed in more depth at https://github.com/graphql/graphql-js/issues/623#issuecomment-266851309
