### ISSUE TITLE
how can I use typeFromAST

### ISSUE THREAD

**Issue by githbq** [graphql/graphql-js#1967]
how can I use typeFromAST , it need two parameters , first is schema , and second is NamedTypeNode ,

what can I make the second parameter , what is NamedTypeNode if I only has a string of graphql language

**Comment by githbq** [comment]
const graphqlString = `  
"user info"
type User {

  "用户ID"
  id: String! 
  name: String!
  introduction: String
}
`  
  const schema = buildSchema(graphqlString)
 
 const User = typeFromAST(buildSchema(graphqlString),  /* what  is this */)

**Comment by IvanGoncharov** [comment]
> const User = typeFromAST(buildSchema(graphqlString),  /* what  is this */)

```
const User = typeFromAST(buildSchema(graphqlString),  parseType(`[User]!`))

**Comment by githbq** [comment]
> > const User = typeFromAST(buildSchema(graphqlString),  /* what  is this */)
> 
> ```
> const User = typeFromAST(buildSchema(graphqlString),  parseType(`[User]!`))
> ```

but I don't know what type the given graphql string containing , it is came from database , how to use it

**Comment by IvanGoncharov** [comment]
@githbq So trying to get `User` type? If so just use `getType` on schema:
```js
const graphqlString = `  
"user info"
type User {

  "user ID"
  id: String! 
  name: String!
  introduction: String
}
`  
  const schema = buildSchema(graphqlString)
 
 const User = schema.getType('User');
```

If you want to do something different can you please provide more info?
