### ISSUE TITLE
mixed object as field

### ISSUE THREAD

**Issue by magalhas** [graphql/graphql-js#198]
Hi, I would like to know how to define a field that contains a mixed object?

**Comment by clentfort** [comment]
If by mixed object you mean an object you don't know the shape of you could serialize it when writing it to the backend and rehydrate it on your clients.
There is an outstanding PR that introduces plain JavaScript Objects as a first class GraphQL-type, see #172.

**Comment by leebyron** [comment]
Sorry for losing track of this issue.

Currently there is no `Mixed` type (that is, the "bottom" type or "dynamic" type) for fields that would allow for *anything* to be returned.

However there is a `Union` type which may better fit what you need. `Union` describes a few different possible types and ensures the response is one of those types.

**Comment by nodkz** [comment]
For future googlers:
@taion released awesome [scalar GraphQLType JSON](https://github.com/taion/graphql-type-json) that supports dynamic values for a field!

I'm using it in [graphql-compose-mongoose](http://graphql-compose.herokuapp.com/), so live demos with dynamic field's type can be found here: 
- [Find User with field of MIXED type](http://graphql-compose.herokuapp.com/user/?query=%0A%7B%0A%20%20userById(_id%3A%20%2257bb44dd21d2befb7ca3f001%22)%20%7B%0A%20%20%20%20_id%0A%20%20%20%20name%0A%20%20%20%20someMixed%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)
- [Create user mutation (with arg of MIXED type)](http://graphql-compose.herokuapp.com/user/?query=%0Amutation%20%7B%0A%20%20userCreate(record%3A%20%7B%0A%20%20%20%20name%3A%20%22My%20Name%22%2C%0A%20%20%20%20age%3A%2024%2C%0A%20%20%20%20gender%3A%20ladyboy%2C%0A%20%20%20%20contacts%3A%20%7B%0A%20%20%20%20%20%20email%3A%20%22mail%40example.com%22%2C%0A%20%20%20%20%20%20phones%3A%20%5B%0A%20%20%20%20%20%20%20%20%22111-222-333-444%22%2C%0A%20%20%20%20%20%20%20%20%22444-555-666-777%22%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20someMixed%3A%20%7B%0A%20%20%20%20%20%20a%3A%201%2C%0A%20%20%20%20%20%20b%3A%202%2C%0A%20%20%20%20%20%20c%3A%20%5B%201%2C%202%2C%203%2C%20true%2C%20false%2C%20%7B%20sub%3A%201%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D)%20%7B%0A%20%20%20%20recordId%0A%20%20%20%20record%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%20%20gender%0A%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20email%0A%20%20%20%20%20%20%20%20phones%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20someMixed%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)

**Comment by taion** [comment]
Don't give me too much credit here. Everything eventually goes back to https://github.com/graphql/graphql-js/pull/242.

**Comment by nodkz** [comment]
@taion you may point it in your repo. But I found your solution, that was easy to integrate and works like a charm. So all my credits belong to you ;p
