### ISSUE TITLE
GraphQLEnumType doesn't work if value doesnt match the key

### ISSUE THREAD

**Issue by stringbeans** [graphql/graphql-js#1997]
Experiencing this in both **14.4.0** and **14.3.1** with `apollo-server-express@2.6.2`

I have a simple query:

```
const LanguageCode = new GraphQLEnumType({
  name: 'LanguageCode',
  values: {
    en: {
      value: 'english'
    },
    fr: {
      value: 'french'
    }
  }
})

export default {
  type: ListResultInterface(SchoolCompanyPromotionObject),
  args: {
    languageCode: {
      type: LanguageCode
    }
  },
  resolve
}
```

However, when I try to access this query...

```
query {
  myQuery(languageCode: en) {
    # ...fields
  }
}
```

I receive the following error: `"Variable \"$_v1_languageCode\" got invalid value \"english\"; Expected type LanguageCode."`

However, if I map the value to be the same as the key (`en: {value: 'en'}`) then the query works.

**Comment by stringbeans** [comment]
hmm... after digging into it a little bit I've noticed that this occurs **only** if i am using schema stitching with the `mergeSchemas` fn from graphql-tools. if i do not do any schema stitching then this works fine..

**Comment by stringbeans** [comment]
i was able to fix this problem by reverting to `graphql@0.13.0` and `graphql-tools@2.22.0`. seems as though its something with schema stitching but i had to revert both graphql and graphql-tool packages in order to properly fix the issue

**Comment by IvanGoncharov** [comment]
@stringbeans It's the issue with `graphql-tools` and reported here: https://github.com/apollographql/graphql-tools/issues/1033
Also fixed here: https://github.com/apollographql/graphql-tools/pull/1075

**Comment by stringbeans** [comment]
@IvanGoncharov thank you so much!
