### ISSUE TITLE
Provide example through tests for mutation queries.

### ISSUE THREAD

**Issue by hekike** [graphql/graphql-js#20]
Would be great to see some `mutation` queries.

**Comment by ilmattodel93** [comment]
Possible duplicate of #14 , mutation examples are provided in the tests folder of the executor :)

https://github.com/graphql/graphql-js/blob/master/src/executor/__tests__/mutations.js

**Comment by leebyron** [comment]
Yes, @dschafer wrote some pretty good tests for mutations.

**Comment by hekike** [comment]
@leebyron ahh sry. I just missed that!

**Comment by lacker** [comment]
Just mentioning, because this page keeps showing up on Google, that the above link is old, and mutation examples are in:

https://github.com/graphql/graphql-js/blob/master/src/execution/__tests__/mutations-test.js
