### ISSUE TITLE
undefined is not a function in nodejsCustomInspectSymbol

### ISSUE THREAD

**Issue by jaynetics** [graphql/graphql-js#2007]
is it feasible to add another check, `typeof Symbol.for === 'function'` to nodejsCustomInspectSymbol?

we get some cases of `TypeError: undefined is not a function` originating from https://github.com/graphql/graphql-js/blob/master/src/jsutils/nodejsCustomInspectSymbol.js#L5

in other words: there are cases were `Symbol` is a `function`, but `Symbol.for` is `undefined` :~(

unfortunately i have no idea how this can happen and no idea how to reproduce. we use core-js and no other polyfills.

interestingly, the bug only occurs exclusively in a few user agents:

- Chrome 74.0.3729.169 
- Chrome 74.0.3729.157
- Samsung Browser 9.2

if you don't want to add another check, i'll investigate further. this *might* be a bug or conflict related to core-js...

**Comment by IvanGoncharov** [comment]
> if you don't want to add another check, i'll investigate further. this might be a bug or conflict related to core-js...

@jaynetics Proposed check doesn't add too much complexity so I don't have a problem merging it if `Symbol.for` is really missing in some environments.
That said I think it's important to understand the root cause of this issue and document it in the source code.
Can you please investigate root cause?

**Comment by jaynetics** [comment]
@IvanGoncharov

i went to some lengths to install outdated chromes in VMs and could not reproduce the issue.

my random guess is that some browser plugin undefines `Symbol.for` for these users.

either way, i found that all browsers happily allow modifying `Symbol.for`, as in `Symbol.for = undefined`, so i think an extra check can't hurt.
