### ISSUE TITLE
Why is GraphQLObjectType not a constructor? 

### ISSUE THREAD

**Issue by boblamceo** [graphql/graphql-js#2012]
Is my code even valid??? Because the terminal says that GraphQLObjectType is not a constructor. What in the world just happened??? 

my code: 
<img width="727" alt="Screen Shot 2019-07-04 at 10 32 48 AM" src="https://user-images.githubusercontent.com/34760070/60635946-24df6e80-9e47-11e9-99df-f38af7288932.png">

error: 
<img width="760" alt="Screen Shot 2019-07-04 at 10 34 23 AM" src="https://user-images.githubusercontent.com/34760070/60636003-5ce6b180-9e47-11e9-94cc-3a0699db0436.png">

_**can anybody tell me how to solve this ↑↑↑↑?**_

**Comment by apalm** [comment]
@boblamceo It looks like you have a typo in `user_type.js`? `GraphQlObjectType` -> `GraphQLObjectType`

**Comment by IvanGoncharov** [comment]
Answered by @apalm ⬆️ 
Thanks @apalm 👍
