### ISSUE TITLE
Custom error obejct properties are not propagated to `originalError` from a rejected promise

### ISSUE THREAD

**Issue by magicmark** [graphql/graphql-js#2018]
In https://github.com/graphql/graphql-js/issues/251, we added `originalError` to be able to look at the original error object and read stuff from it.

Great! Inside of `formatError`, I want to be able to see a custom property on the original error object.

### works (regular synchronous `Error`):

```js
const resolvers = {
  foo: () => {
    try {
      throw new Error('yikes!');
    } catch (e) {
      e.foo = "bar";
      throw e;
    }
  }
};

formatError: e => {
  console.log("originalError", e.originalError.foo); // logs 'bar'
  return e;
}
```

### does _not_ work (async `Promise.reject`):

```js
const resolvers = {
  foo: async () => {
    try {
      await Promise.reject("yikes!");
    } catch (e) {
      e.foo = "bar";
      throw e;
    }
  }
};

formatError: e => {
  console.log("originalError", e.originalError.foo); // logs 'undefined'
  return e;
}
```

**Repro**: https://codesandbox.io/embed/nodejs-graphql-server-xo0vh

Not sure if this is intended, or if this is to do with there being some difference between an error object and a rejected promise, but we seem to treat rejected promises and synchronous errors the same elsewhere 🤔 

Thoughts?

Thanks!!

**Comment by IvanGoncharov** [comment]
@magicmark You need to replace
> await Promise.reject("yikes!");

with
> await Promise.reject(new Error("yikes!"));

Because currently, you are throwing string not the instance of `Error` class.

**Comment by magicmark** [comment]
@IvanGoncharov ack, thanks.

The issue remains if you do 

```
      await Promise.reject({ message: "yikes!" });
```

though, per the repro link?

Allowing for this is desirable since we aren't always on control of what's being thrown - a 3rd party lib could be throwing/rejecting anything.

Going to assume here the fix is that we just have to wrap all promises in resolvers and make sure they're rejecting error objects? (Less than ideal?)

**Comment by IvanGoncharov** [comment]
@magicmark Throwing instances of Error class is a standard practice in JS.
You can also enforce it through ESLint rule: https://eslint.org/docs/rules/no-throw-literal
So, in the long run, it's better to open PR against 3rd party lib that fixes this issue there.
