### ISSUE TITLE
How to get resolver arguments from GraphQLResolveInfo

### ISSUE THREAD

**Issue by marusapur** [graphql/graphql-js#2048]
Hello! How can i get object of arguments(that does pass into resolver) from GraphQLResolveInfo object that does build every time while request sends. I need it for my unit tests. Default "args" is not match for me, i need only get it from resolveInfo, that i builds by graphql parser from query. Is there any possible idea?

**Comment by IvanGoncharov** [comment]
@marusapur You can use `getArgumentValues`:
https://github.com/graphql/graphql-js/blob/670bbaca5ed897d0ee2caadbc8ac3a0bbf281b87/src/execution/values.js#L113-L125

**Comment by marusapur** [comment]
@IvanGoncharov

**Comment by IvanGoncharov** [comment]
@marusapur It's actually enough:
```
getArgumentValues(
  info.parentType.getFields()[info.fieldName],
  info.fieldNodes[0],
  info.variableValues,
)
```

**Comment by marusapur** [comment]
@IvanGoncharov i can't use getFields() method does not exist in GraphQLResolveInfo object and info.parentType is a string. Can you please explain how can i do make first argument for getArgumentValues() method?

**Comment by IvanGoncharov** [comment]
@marusapur `parentType` should be of `GraphQLObjectType` if not you have an invalid instance of `GraphQLResolveInfo `

**Comment by marusapur** [comment]
@IvanGoncharov Yes, your right, I have an invalid instance of GraphQLResolveInfo because I mocked and prepares it as a JSON.
I found print() method in your awesome library and it is exactly match for me. Thank you very much!

btw, i leave code which i uses for taking arguments from JSON instance of GraphQLResolveInfo:
```
import { print } from 'graphql'
import _ from 'lodash'

// WARNING! this function is only for mocking/testing because using eval() is unsafe
export const getArgsFromInfo = (info) => {
	let argsNode = JSON.stringify(info.fieldNodes[0].arguments)
	let preparedToPrintArgs = JSON.parse(_.replace(argsNode, new RegExp('"kind":"EnumValue"', 'g'), '"kind":"StringValue"')) 
	let argsString = print(preparedToPrintArgs)
	let argsObject = eval(`(function(){ return {${argsString}}; })()`)
	return argsObject
}
```

**Comment by shashankredemption** [comment]
@IvanGoncharov 
Is there a way to call `getArgumentValues` using the `GraphQLContext` instead of `GraphQLResolveInfo`?

**Comment by IvanGoncharov** [comment]
@shashankredemption We don't have `GraphQLRequestContext` type in this library.

**Comment by MoSattler** [comment]
Is there a way to get the arguments of a descendant GraphQLResolveInfo of `info`?
