### ISSUE TITLE
starWarsIntrospection-test __schema.types confusion

### ISSUE THREAD

**Issue by burner** [graphql/graphql-js#2081]
I'm implementing a graphql backend in D and when looking at the expected types
returned in https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsIntrospection-test.js#L22
I'm confused why "Boolean" is part of the returned names.
I get that bool is a standard type but so is Int and Int does not appear in the names array.
That being said, no field or inputvalue has the type bool or int in the star wars schema.

Could somebody please clarify this for me

**Comment by IvanGoncharov** [comment]
> I get that bool is a standard type but so is Int and Int does not appear in the names array.

@burner You absolutely correct types (both standard and user-defined) are included only if they are used in the schema.
`Boolean` type is used both inside introspection types, e.g.:
https://github.com/graphql/graphql-js/blob/f85d9b67576da5d1f23b12b07e30588bd0d8791d/src/type/introspection.js#L227
and in standard directives, e.g.:
https://github.com/graphql/graphql-js/blob/f85d9b67576da5d1f23b12b07e30588bd0d8791d/src/type/directives.js#L133

**Comment by burner** [comment]
Thank you for the quick answer. 
My bad, sorry for the noise.

**Comment by IvanGoncharov** [comment]
@burner No problem. The main purpose of `graphql-js` is to be the reference implementation of GraphQL and assist with implementing interoperable GraphQL servers in various languages.
If something is not clear from source code it should be addressed in comments so you actually helping us to improve source code and save time for future readers.
For example, based on this issue I added this comment:
https://github.com/graphql/graphql-js/blob/d9f959e7d2ce569157c5993d66250d5e4961c16c/src/__tests__/starWarsIntrospection-test.js#L29-L32

So please feel free to open similar issues if you will have such questions.
Also if you discover something that is not covered by our tests please open an issue or PR.

**Comment by burner** [comment]
@IvanGoncharov will do, thanks
