### ISSUE TITLE
Add link to GraphQL website in repo description

### ISSUE THREAD

**Issue by cesarandreu** [graphql/graphql-js#209]
I just discovered the [GraphQL website](http://graphql.org/) and [API reference](http://graphql.org/docs/api-reference-graphql/). So far I've been diving into the source to find API references, which is a little annoying.

Please consider adding a link to the website in the repo description (and maybe the README as well).

**Comment by leebyron** [comment]
Great suggestion. Our readme and docs could use some attention soon!
