### ISSUE TITLE
IE not working with for...of

### ISSUE THREAD

**Issue by christieb7007** [graphql/graphql-js#2092]
The app is erroring out in IE 11 with `SCRIPT5007: Object expected` which is coming from `Symbol.iterator` from the `for...of` loops added in 7e159058908220a6465549e689667d20802a446b and elsewhere (jsutils/mapValue..js#L23, etc)

UPDATE: I was able to fix this in my project by adding the core-js symbol as a polyfill. Perhaps the solution is to add that to https://github.com/graphql/graphql-js/tree/master/src/polyfills

**Comment by IvanGoncharov** [comment]
@christieb7007 Thanks for the detailed report 👍 
Fixed in #2099.
I plan to make release today/tomorrow.
