### ISSUE TITLE
Spec and Build client-side GraphQL parser.

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#21]
Client-side GraphQL should have access to the type IDL we refer to in the spec and any other features that are useful for client-side GraphQL development but have no semantic meaning for execution.

**Comment by ecstasy2** [comment]
What would be a good way to start helping on this?

**Comment by leebyron** [comment]
We're not sure yet. We'll speak with those working on GraphQL client tools at Facebook to figure out what will best support their needs and that will help us understand the direction to move in.

**Comment by charypar** [comment]
More about #16 (I think?), but is there any vision for parsing the schema definition language into (partial) "AST" (which you now build by hand) and providing an API to define resolve functions for individual attributes? 

I have something roughly like this in mind:

```
import {schemaDefine} from 'graphql'

const schema = schemaDefine(`
type User {
	name: String!,
	interests: [String]
}

queryType {
	user(id: ID): User
}
`);

schema.getType('User').defineFieldResolvers(() => {
	name: (user) => user.name,
	interests: (user) => user.interests.map(interest => interest.label)
})
```

There's obviously more thinking to be done around defining custom scalars, etc., but is this something that you have on the roadmap or would be interested in?

**Comment by leebyron** [comment]
This isn't something on the roadmap. We haven't considered an approach like that very seriously because while it could make simple cases more terse, it could also be harder to understand and harder to extend.

Documentation, for example, is missing from this particular suggestion and a critical part of a well built GraphQL server, so we want to avoid giving tools that makes documentation harder rather than easier.

There's probably something to a partial code-generation (similar to Rails or Yeoman) that would be really valuable to reduce typing, which is one of the interesting paths that could be taken for building a parser for client-side types.

The primary desire for client-side types, at least from how I've seen GraphQL used at Facebook over the last 3 years, is for doing code-generation in our client applications when the types a GraphQL server provides need to be extended by the iOS or Android client.

**Comment by leebyron** [comment]
This is now mostly covered by https://github.com/graphql/graphql-js/pull/74

**Comment by gyzerok** [comment]
@leebyron I have a case for client-side usage.

For now I'm storing data on the client in normalized form. To restore this data I want to use same GraphQL schema as I use on the server. But currently I cant do this.

Guess https://github.com/graphql/graphql-js/issues/159 is duplicate for this. SHould I close it?

**Comment by leebyron** [comment]
Individual changes increment towards this, and the tracking task is at https://github.com/facebook/graphql/pull/90
