### ISSUE TITLE
Question: Any advice on query error handling?

### ISSUE THREAD

**Issue by matthewmueller** [graphql/graphql-js#214]
Looks like Graphql differentiates between soft error and hard errors. If it's a soft error, it means that the query was executed, but it was invalid and returns an array of errors as a result.

I was wondering if you had any advice on how to handle this array of errors. Should they be combined into a single error object? It's application-specific, but just wondering if you had any general advice.

**Comment by leebyron** [comment]
This of course totally depends on the context of your application and even the individual fields you query. Usually these soft errors are returned so clearer UI decisions can be made and caches can be intelligent about the differences between fully successful and partially successful responses.

**Comment by matthewmueller** [comment]
Got it thanks! And sorry for the late response!
