### ISSUE TITLE
Setting default value to null is wrong behavior.

### ISSUE THREAD

**Issue by deser** [graphql/graphql-js#2155]
Hey, according to https://github.com/graphql/graphql-js/issues/1034 response defaultValue is bad way of defining things.
I'm converting mongoose models and they have default value, it can be of any type. GraphQl supports only string as defaultValue. If I don't set default value for an argument in schema then graphql sets it to null. Mongoose understands null as a valid value and inserts instead of default value described for a model null.
Seems graphql should not setup null as defaultValue by default?

**Comment by IvanGoncharov** [comment]
> Hey, according to #1034 response defaultValue is bad way of defining things.

@deser They are bad only for dynamic values as answered here:
> Default values are static and communicated to tools which might see them at different times from when a query is executed. They may decide to omit a query based on a default value, assuming it is static.

> GraphQl supports only string as defaultValue. 

@deser No, GraphQL supports values of any type as `defaultValue`.

> If I don't set default value for an argument in schema then graphql sets it to null.

No, it shouldn't. For example here is our test:
https://github.com/graphql/graphql-js/blob/6609d3942e2ce129ff44c3be24eb7917de444583/src/execution/__tests__/executor-test.js#L910-L937

Can you please provide a full example?

**Comment by deser** [comment]
Thanks for fast response. 

I have such errors:
```
 {
      "message": "Cannot convert value to AST: [function Array]",
      "locations": [
        {
          "line": 57,
          "column": 5
        }
      ],
      "path": [
        "__schema",
        "types",
        94,
        "inputFields",
        9,
        "defaultValue"
      ]
    },
```
Seems I found that it blaims for `[]`. But error description isn't good enough, I have to debug:) 

Also, in code I see:
```
defaultValue: {
        type: _scalars.GraphQLString,
        description: 'A GraphQL-formatted string representing the default value for this input value.',
        resolve: function resolve(inputVal) {
          var valueAST = (0, _astFromValue.astFromValue)(inputVal.defaultValue, inputVal.type);
          return valueAST ? (0, _printer.print)(valueAST) : null;
        }
      }
```
It says that defaultValue is string only.

**Comment by IvanGoncharov** [comment]
@deser Default value is **serialized to** string, e.g `[1, 2, 3]` becomes `"[1, 2, 3]"`.
Please provide a minimal example that I can run locally?
Without it, I don't think I can help you with this problem.

**Comment by deser** [comment]
Let me see, seems I have problems with how mongoose converts default value of array type in its schema.

**Comment by deser** [comment]
Skip it. I had issues in conversation of mongoose schema to gql schema.
Thanks for helping!

**Comment by deser** [comment]
Actually one questions stays unresolved: seems setting defaultValue to null by default is not good practice. Null eventually is a value, so graphql validator which mustn't change behavior actually changes it: before validation application thought that if key doesn't exists in input then its ok, after validation the key appears with the null value. Then this null value goes to be written to DB by default.
