### ISSUE TITLE
Mutation field resolve methods not being called

### ISSUE THREAD

**Issue by LegNeato** [graphql/graphql-js#217]
I have a Relay mutation like this:

```js
const myCoolDataMutation = mutationWithClientMutationId({
  name: 'saveMyCoolDataChoice',
  inputFields: {
    myCoolValue: {
      type: new GraphQLNonNull(GraphQLString),
    },
  },
  outputFields: {
    mycool_data: {
      type: MyCoolData.GraphQLType,
      resolve: async (payload) => {
        console.log('CALLED');
        // Return payload.
      },
    },
  },
  mutateAndGetPayload: async ({ newCoolValue }, { rootValue }): => {
   // Writes to db and returns payload.
  },
});
```

I can see `mutateAndGetPayload` get called with the correct info and return the correct payload.

:beetle: The `resolve` function on `mycool_data` in `outputFields` is not called.

When I look at the response from the server Relay gets I see:

```js
{
  "data": {
    "saveMyCoolDataChoice": {
      "clientMutationId": "0"
    }
  }
}
```

So obviously my code with the payload `resolve` function isn't being called and instead the default is used.

Perhaps part of the issue is my Relay component does a query for an optional record in the database at creation time. If it doesn't exist, the eventual call to `saveMyCoolDataChoice` ends up not calling `resolve` (but does call `mutateAndGetPayload`). If the record in the database exists at Relay component instantiation time, everything works fine (`resolve` is called on `mycool_data` in `outputFields`).

I think this is a fairly common pattern (read from the database, if not there do some defaults, take user input and eventually write the data row) and the server seems to get a well-formed query and call `mutateAndGetPayload`, so I am at a loss for what is going on...

**Comment by dschafer** [comment]
What's the request that your client is sending to the server? It sounds like the request is:

```graphql
mutation {
  saveMyCoolDataChoice($input) {
    clientMutationId
  }
}
```

In which case GraphQL would not call `mycool_data`'s `resolve`, because the query did not ask for `mycool_data`.

**Comment by dschafer** [comment]
If the query was

```graphql
mutation {
  saveMyCoolDataChoice($input) {
    clientMutationId
    mycool_data { someOtherField }
  }
}
```

Then I would expect to see `resolve` called so GraphQL could fulfill that field.

**Comment by LegNeato** [comment]
Interesting! Let me check.

**Comment by LegNeato** [comment]
Yep, that was the issue! Now I need to figure out why Relay isn't including that... thanks! :beers:
