### ISSUE TITLE
Why Node and not HHVM?

### ISSUE THREAD

**Issue by smolinari** [graphql/graphql-js#219]
Hi,

What was the reasoning by the Facebook team to go with a Node back-end implementation as a reference system instead of using HHVM and Hack?

Scott

**Comment by Agrosis** [comment]
GraphQL was built with React in mind, which is also built in JS, so it was probably to cater to the people who already use React.

**Comment by smolinari** [comment]
Yes, but 80%+ of web backends are built with PHP. To port from Hack to PHP (or the other way around) would be a whole lot easier and would probably mean a lot more community support for the project.

http://w3techs.com/technologies/overview/programming_language/all

JS at 0.2% against PHP at 81.5%!!!

And, Facebook has its roots in PHP.

Scott

**Comment by leebyron** [comment]
Our internal Facebook version of GraphQL is built in Hack, and we're working to get it into a state where we can open source it, ideally later next year. We decided to build a reference implementation for the new GraphQL spec in JavaScript for a couple reasons:

1) There is a huge JavaScript community, it's one of the most commonly known languages, and it's very easy to get a JavaScript environment up and running to test things. This is ideal for a reference implementation which is likely to be ported to many other languages by the community.

2) GraphQL is not just a server runtime but also a suite of client utilities. At Facebook we use JavaScript for a lot of our client tools, and it's very convenient when building tools that can run in a browser. Having a single reference implementation which can power both a server and client tools is very compelling.

3) It's very easy to get a JavaScript server up for free using Parse's cloud code. This allows us to illustrate new examples very quickly.

Ultimately we wish for GraphQL's server to be implemented in just about every language people care to use for building web services. Hack/PHP is obviously an important one for Facebook and the web community, and one we hope to include soon.

**Comment by smolinari** [comment]
> Hack/PHP is obviously an important one for Facebook and the web community, and one we hope to include soon.

This is great news. Thanks for answering. And hopefully, the Hack/PHP version will be out a bit sooner than the end of next year. I certainly am hoping so. :smile: 

Scott

**Comment by raeesiqbal** [comment]
@leebyron Any update on HackLang implementation of GraphQL?

**Comment by leebyron** [comment]
This is something we're actively working on now. We don't have a time frame for a date to release code, and we're still in the early phase of having a version that is detached from the particulars of Facebook's internal working and spec compliant. The plan is to publish this sometime later this year ideally.

**Comment by smolinari** [comment]
Thanks for the update Lee. 

For anyone interested in something that is available now, there is a PHP version.  

https://github.com/webonyx/graphql-php

Still in beta though, but looks fairly promising.  

Scott

**Comment by smolinari** [comment]
@leebyron - could it be possible to get an update?

Scott

**Comment by leebyron** [comment]
This is something we're actively working on right now for our internal use, but there's currently no time frame for an open source release. The team is interested in an open source release in the future, perhaps later this year.

**Comment by raeesiqbal** [comment]
Yeah I heard something similar about HHVM release for Windows and it has been 3 years since. :stuck_out_tongue_winking_eye:

**Comment by smolinari** [comment]
Any chance on getting an update on the public release of this Hack version? @leebyron  We are getting closer to the end of the year?

Scott

**Comment by leebyron** [comment]
There's no planned time frame for an open source HHVM server, though the team is still interested in doing so at some point in the future.

**Comment by smolinari** [comment]
Ok, Thanks for the quick response. All I can say is, I think an HHVM version would put both HHVM and GraphQL much more in the open source spotlight from a PHP community perspective. 

Scott

**Comment by 1331Inv** [comment]
(@￣ρ￣@)

**Comment by smolinari** [comment]
So everyone else knows, I've given up on a Facebook driven HHVM reference GraphQL server solution and also on PHP in general for my backend with GraphQL. ([and despite the hard work of others doing a good PHP GraphQL implementation](https://github.com/webonyx/graphql-php)). There is just soooo much more work and cool things being done on the Node front for GraphQL, I couldn't resist. 

Scott

**Comment by wincent** [comment]
> any Updates?

@ae1080, @1331Inv, @smolinari and any others who may be interested. We still don't have any concrete dates to announce related to an HHVM open source release, however we continue to be interested in making that happen. Jan Jergus recently gave a talk on what we've been focused on over the last couple of years on the HHVM side, as well as what we're working on right now and some forward-looking discussion. Check out [the video here](https://www.youtube.com/watch?v=r-SmpTaqpDM&feature=youtu.be&t=5400).

**Comment by smolinari** [comment]
Thanks for the update Greg (@wincent). As I mentioned above, I'm now in the node world for the backend and am quite happy. In fact, it is pretty cool only needing to work in one language. 😄

Scott

**Comment by jrs43215** [comment]
For what it's worth, I'm still interested in the HHVM version.

**Comment by leocavalcante** [comment]
Any plans to open-source the Hack/PHP implementation? Is this the used version inside Facebook?

**Comment by vmsp** [comment]
Hey guys! Is it still in your plans to open source the implementation? Thanks, graphql's awesome!

**Comment by smolinari** [comment]
I highly doubt they will @vmsp, since they haven't already. It's been over 2 years......

Just go with Node. It's great and getting better by leaps and bounds. JavaScript as a backend language with Node is just as powerful as PHP without needing to have any extra asynchronous bits (Hack/HHVM), because it's built into Node from the start. 

Scott
