### ISSUE TITLE
Invalid schmea with interface extension does not fail

### ISSUE THREAD

**Issue by realdoug** [graphql/graphql-js#2199]
Perhaps this is user error, but is the following schema valid?  Based on my reading of the language spec, this program should fail with a validation exception:

```
var { graphql, buildSchema, printSchema } = require("graphql");

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: Person
  }

  interface NamedEntity {
    fullName: String
  }

  extend interface NamedEntity {
    nickname: String
  }

  type Person implements NamedEntity {
    isCool: Boolean
    fullName: String
  }
`);


var root = {
  hello: () => {
    return { isCool: true };
  }
};

graphql(schema, "{ hello { isCool } }", root).then(response => {
  console.log(response);
});
```

yet, it executes with no problems.  Rolling the `nickname` field into the original `NamedEntity` portion, and removing the extension (see below) does result in a schema validation error.

```
  type Query {
    hello: Person
  }

  interface NamedEntity {
    fullName: String
    nickname: String
  }

  type Person implements NamedEntity {
    isCool: Boolean
    fullName: String
  }
```

So my question is, despite being a bit of a contrived example, is this a bug?

**Comment by IvanGoncharov** [comment]
@realdoug Thanks for detailed report 👍 
> Perhaps this is user error, but is the following schema valid?

Yes, it's invalid. The problem here is that `buildSchema` silently ignores extensions so
`nickname` is never added. It's already reported in #922 and I finishing adding support for extensions and it will be included in upcoming `15.0.0-alpha.0` (ETA later this week).

Meanwhile you wan workaround using `extendSchema`:
```
var { graphql, buildSchema, extendSchema, parse, printSchema } = require("graphql");

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: Person
  }

  interface NamedEntity {
    fullName: String
  }

  type Person implements NamedEntity {
    isCool: Boolean
    fullName: String
  }
`);

schema = extendSchema(schema, parse(`
  extend interface NamedEntity {
    nickname: String
  }
`));

var root = {
  hello: () => {
    return { isCool: true };
  }
};

graphql(schema, "{ hello { isCool } }", root).then(response => {
  console.log(response);
});
```
