### ISSUE TITLE
How can we improve the existing library, all ideas welcomed!

### ISSUE THREAD

**Issue by kassanj** [graphql/graphql-js#2207]
Hey Fellow GraphQL-ers,
We're looking to improve the existing library. :)
We wanted to know the latest issues. How we could help or improve the ecosystem?
Yeah! Lets us know... we are given the time and resources... we want to make everyone's lives easier.... all ideas are welcomed!

**Comment by mike-marcacci** [comment]
I'm really sad to see this closed without any comments. I suspect there is a bottleneck at the "final phase" of contribution (review, etc) with the majority of that work falling to very few individuals. I know I have [some changes](https://github.com/graphql/graphql-js/pull/2084) that have been in the pipeline for a while, and other [substantial initiatives](https://github.com/graphql/graphql-js/issues/2188) that are blocked by other changes that are not yet merged. With this in mind, the prospect of adding more changes to the backlog might have dissuaded any suggestions from popping up here.

I hope this gives some context. I'll bring this up at the next WG meeting, as it's sad that the community was unable to benefit from your offer.
