### ISSUE TITLE
Upgrade cause loss of originalError

### ISSUE THREAD

**Issue by purpleD17** [graphql/graphql-js#2213]
We are upgrading to latest graphql and express graphql in our Node app from very old versions (graphql 0.8, graphqlexpress 0.7). In doing so we lose the error response data in our underlying api calls graphql is making. I traced the issue here. 

https://github.com/graphql/graphql-js/blob/d85fc1186cca57fd3a74b93601a297e811b4bb13/src/execution/execute.js#L715

At one point in the older releases, an error object with a nested originalError was returned. Now instead I get only a string back.

 If instead of doing `new Error(error.errorString)` the code would call new `GraphQLError(...,...,...,error)` where error is the originalError part, then I can extract the data from my error object in the graphql express module as referenced here : https://github.com/graphql/express-graphql/blob/master/README.md#debugging-tips

At one point the code must have returned an error that wrapped the originalError object and now it does not, it only returns an error that wraps a string.

**Comment by purpleD17** [comment]
I think I'm running into the same issue as https://github.com/graphql/graphql-js/issues/1393#issuecomment-469314100

It sounds like the author of the project here is against passing through a custom `Error` object with a nested original error object inside. It seems the argument is that we should only be throwing vanilla `Error` objects to calling systems.

I understand this argument but am at a loss for what to do. I can't upgrade our current version of graphql because I lose the `orignalError` that backend services were returning to our clients. Our clients are parsing the `statusCode1` and json `body` from this object that we pass on, and we can't break the API, we have many clients calling our graphql app. Any help here on what to do short of monkey patching?

**Comment by yaacovCR** [comment]
You should just make sure your custom error object inherits from Error? Maybe share the format of that object?

**Comment by IvanGoncharov** [comment]
@purpleD17 Also note that if you need to pass some extensions to clients you can pass them through `extensions` property on `originalError`: 
https://github.com/graphql/graphql-js/blob/48ea2d3e8df5e4fbbdb5e0ce67c0a3c219b024f8/src/error/GraphQLError.js#L137-L142

To make easier you can for example subclass `Error`:
```js
class ErrorWithExtensions extends Error {
  constructor(message, extensions) {
    super(message);
    this.extensions = extensions;
  }
}
```

**Comment by purpleD17** [comment]
Thanks, this was a big help. after about almost a weeks worth of work I think i have a full upgrade. I've moved to a custom error as suggested above. I catch the underlying serivce calls in the store that graphql is making, then rethrow this custom error. I then extract the data to return in the response

**Comment by IvanGoncharov** [comment]
@purpleD17 Great to hear!
Can I close this issue?

**Comment by purpleD17** [comment]
Yes I'll do that.
