### ISSUE TITLE
Conflict because differing arguments for ENUMs.

### ISSUE THREAD

**Issue by jardakotesovec** [graphql/graphql-js#222]
This is related to https://github.com/facebook/relay/issues/553 .

If there is more fragments requesting same field with same argument, Relay sends these fields with same (generaged) name. So its there multiple times - but seems that graphq-js handles that just fine and merge them and return one response for that field. Only exception is if argument is ENUM, than it returns error.

Here is example, let me know if you need any more details:
```
{ 
  "query": "query test($something1: ImageFilterMode, $something2: ImageFilterMode){    viewer {       someFieldTest: someField(something: $something1) { id}     someFieldTest: someField(something: $something2) { id}   }}",
  "variables": {"something1": "GLAZE", "something2": "GLAZE2"}
}
```

Gives
```
{"errors":[{"message":"Fields \"someFieldTest\" conflict because they have differing arguments."}]}
```

**Comment by kassens** [comment]
This is a bug in Relay as it should merge the fields with same names.
