### ISSUE TITLE
ValuesOfCorrectType is not correctly implementing the spec

### ISSUE THREAD

**Issue by attilah** [graphql/graphql-js#2222]
As the [spec](https://graphql.github.io/graphql-spec/June2018/#sec-Values-of-Correct-Type) states, this rule should validate that a given document is conforming to the schema, by verifying the type of fields for any given type.

When the schema defines a List type with non-null items and an Object is passed in the document, validation is not failing.

Schema:
```graphql
type Post {
  id: ID!
  title: String
  content: String
}

input UpdatePostInput {
  id: ID!
  title: String
  content: String
}

input PostConditionInput {
  title: StringConditionInput
  content: StringConditionInput
  and: [PostConditionInput!]
}

input StringConditionInput {
  contains: String
}

type Mutation {
  updatePost(input: UpdatePostInput!, conditions: PostConditionInput): Post
}

type Query {
  listPosts : [Post!]!
}
```

Document:
```graphql
mutation InvalidUpdate {
	updatePost(
        input: {
            id: "P1"
            title: "New Title"
            content: "New Content"
        }
        conditions: {
            and: {
                title: { contains: "ABC" }
                content: { contains: "DEF" }
            }
        }
    ) {
        id
        title
        content
    }
}

mutation ValidUpdate {
	updatePost(
        input: {
            id: "P1"
            title: "New Title"
            content: "New Content"
        }
        conditions: {
            and: [
                { title: { contains: "ABC" } }
                { content: { contains: "DEF" } }
            ]
        }
    ) {
        id
        title
        content
    }
}
```

Notice that ```and``` is an object instead of an array in ```InvalidUpdate``` mutation, which would be valid, if a single object would be coerced into a single element array after parse and the object would be validated against the type of the list item.

The document above is passing validation, with the following code, using the latest 14.x version of the library.
```typescript
import * as fs from 'fs';
import { buildSchema, parse } from 'graphql';
import { GraphQLSchema } from 'graphql/type';
import { validate, specifiedRules } from 'graphql/validation';

const schema = fs.readFileSync('schema.graphql').toString();
const mutation = fs.readFileSync('mutation.graphql').toString();

const rules = specifiedRules;

const schemaObject: GraphQLSchema = buildSchema(schema);
const document = parse(mutation);

const validataionResult = validate(schemaObject, document, rules);

console.log(JSON.stringify(validataionResult, null, 2));
```

**Comment by IvanGoncharov** [comment]
> When the schema defines a List type with non-null items and an Object is passed in the document, validation is not failing.

@attilah Yes, it's expected behavior:

https://graphql.github.io/graphql-spec/draft/#sel-FAHjBHFCAACE_Gh7d
> If the value passed as an input to a list type is not a list and not the null value, then the result of input coercion is a list of size one, where the single item value is the result of input coercion for the list’s item type on the provided value (note this may apply recursively for nested lists).

Does this quote answers your question?

**Comment by attilah** [comment]
@IvanGoncharov so validation is "assuming" that the inputs will be coerced at the time of processing, that's the reason why it is passing the validation?

A plain ```parse``` call will not do this coercion as that method is unaware of the schema that given document is parsed against. How can one parse a document against a given schema with automatic input type coercion?

How will this snippet:
```graphql
and: {
  title: { contains: "ABC" }
  content: { contains: "DEF" }
}
```

become this:
```graphql
and: [
  { title: { contains: "ABC" } }
  { content: { contains: "DEF" } }
]
```
in the parsed document AST - since it is a multi-element array?

A related issue is that for directive arguments the same can happen, so I assume the quoted part of the spec are applying to every List?

**Comment by IvanGoncharov** [comment]
> so validation is "assuming" that the inputs will be coerced at the time of processing, that's the reason why it is passing the validation?

@attilah Yes
https://graphql.github.io/graphql-spec/draft/#sel-HALXDHDABAB1EzpY
> Literal values must be compatible with the type expected in the position they are found as per the coercion rules defined in the Type System chapter.

> A plain parse call will not do this coercion as that method is unaware of the schema that given document is parsed against. How can one parse a document against a given schema with automatic input type coercion?

Parsing have no information about type system so it can't do coercion.
Coercion happening here: https://graphql.github.io/graphql-spec/draft/#sec-Coercing-Field-Arguments

Before we get too much deep into technical details can you please explain your use case?

**Comment by IvanGoncharov** [comment]
@attilah Can I close this issue or you still have some questions?

**Comment by attilah** [comment]
Sure, yes, I will ping you if I encounter any further issue when I get back to this.
