### ISSUE TITLE
What is the meaning of the parameter of resolver function

### ISSUE THREAD

**Issue by Yangk030208** [graphql/graphql-js#2230]
I've read all the docs at graphql.org and the READMEs for graphql-js and express-graphql, Here is my understanding of each parameters。
```
resolve(parentValue, args, request) { 
 //parentValue:     **I can't understand this parameter.**
//args:The arguments provided to the field in the GraphQL query.
//request:A value which is provided to every resolver and holds important contextual information 
}
```
I tried ```console.log(parentValue)```,But I got null. so who can tell me ,What does this parameter do。thanks。

**Comment by wtrocki** [comment]
GraphQL resolver plan is like graph with root being mutation or query function. Parent on root will be empty, but on children's - individual fields of the objects parent will be present. 
Usually parent will be used to fetch extra relationships that were not loaded in root resolver or calculating derived fields.

There are a lot of good blogs on this topic. Github issues are to log some actions to maintainers. If you feel that resolver documentation should be improved feel free to propose some changes. For any questions feel free to use slack or stackoverflow.

**Comment by IvanGoncharov** [comment]
@wtrocki Thanks for a great answer 👍
