### ISSUE TITLE
Infinite loop when using directives

### ISSUE THREAD

**Issue by santaclauze** [graphql/graphql-js#2243]
First of all thanks for the great project. I use graphql a lot and am trying to look in the deeper functionalities. 

I have a large entity that I query in multiple places in my app. I realized I could query only parts of it by using directives. 

In one of my components, I have to query within a `useEffect` and thus opted for the lazy query.

![Screen Shot 2019-11-01 at 5 59 13 PM](https://user-images.githubusercontent.com/17665998/68003240-5ec76100-fcd1-11e9-9c00-e29216a3a073.png)

![Screen Shot 2019-11-01 at 5 59 54 PM](https://user-images.githubusercontent.com/17665998/68003266-71da3100-fcd1-11e9-9529-830f565120d7.png)

I then added directives as follows:

![Screen Shot 2019-11-01 at 6 00 43 PM](https://user-images.githubusercontent.com/17665998/68003297-8fa79600-fcd1-11e9-96bd-987fd3090c07.png)
![Screen Shot 2019-11-01 at 6 00 51 PM](https://user-images.githubusercontent.com/17665998/68003300-90d8c300-fcd1-11e9-90b4-68d367dc9fb5.png)

When loggin on my app, I get an infinite loop that keep triggering the lazyQuery even though the directive arguments seem to be set.

![Screen Shot 2019-11-01 at 6 02 22 PM](https://user-images.githubusercontent.com/17665998/68003344-d72e2200-fcd1-11e9-9dce-7c57ecd1b26c.png)

HOWEVER, As soon as I add the arguments as follows, it fixes the infinite loop.

![Screen Shot 2019-11-01 at 6 03 38 PM](https://user-images.githubusercontent.com/17665998/68003381-f88f0e00-fcd1-11e9-9fd8-44db78e609d5.png)

Is there something in the behaviour of Graphql that I am missing? is this an expected behaviour?

It seems quite odd to me that passing the variables in the query even though they were visible in teh query before and being set with a default value would give any different result.

**Comment by IvanGoncharov** [comment]
@santaclauze Sorry for the delay, I was traveling to/from GraphQL Summit ✈️
Looks like you are using Apollo on your frontend?
`graphql-js` has no relationship to React or frontend frameworks in general so I recommend reporting it here: https://github.com/apollographql/apollo-client
