### ISSUE TITLE
Links Broken on APIReference-GraphQL Markdown

### ISSUE THREAD

**Issue by fullStackDataSolutions** [graphql/graphql-js#2244]
# Reporting issues with GraphQL.js

I'm just trying to read the page at this URL: 
https://github.com/graphql/graphql-js/blob/master/docs/APIReference-GraphQL.md

However whenever I click one of the links I get a GitHub 404 page.

**Comment by M1seRy** [comment]
It looks like we should update the url link  ：）

**Comment by JoviDeCroock** [comment]
We are moving to a new docs site, it's already on https://graphql.org/graphql-js
