### ISSUE TITLE
Error: Input.property field has a resolve property, but Input Types cannot define resolvers

### ISSUE THREAD

**Issue by arjun-kava** [graphql/graphql-js#2245]
I am using graphql with typescript, problem is after compilation to javascript input type has 
```js
resolve: undefined
```
It causes error as "field has a resolve property, but Input Types cannot define resolvers".

**Comment by IvanGoncharov** [comment]
@arjun-kava Yes, input types can't have `resolve` properties.
If you wrote schema by hand just remove `resolve` but if you use some tool to generate schema please report it to the appropriate repository.

**Comment by esatterwhite** [comment]
you'll get the is error trying to reuse the fields from a type as the fields for an input

```
const custom = new GraphQLObjectType({
  fields: {
    id: GraphQLString
  , description: 'The id'
  }
})
new GraphQLInputObjectType({
  fields {
    ...custom.getFields()
  }
})
```

This worked fine until recently. It makes reusing type definitions rather difficult

**Comment by moin-almin** [comment]
Check if you are using GraphQLObjectType or GraphQInputObjectType. This error will come with the input type object.
