### ISSUE TITLE
introspectionTypes/isIntrospectionType TypeScript types could be more specific

### ISSUE THREAD

**Issue by glasser** [graphql/graphql-js#2260]
In `introspection.js`, `introspectionTypes` doesn't have an explicitly given type (I don't know Flow well enough to understand what is inferred), and `isIntrospectionType` takes a `GraphQLNamedType` as an argument.

In the TypeScript `introspection.d.ts`, `introspectionTypes` is given as `ReadonlyArray<GraphQLType>` and `isIntrospectionType` takes a `GraphQLType` as an argument.

I think it would make sense to change the TypeScript types to `ReadonlyArray<GraphQLNamedType>` and an argument of `GraphQLNamedType` respectively. (We have a project that uses `introspectionTypes` and expects them all to have names.)

I can send a PR if you agree!

**Comment by IvanGoncharov** [comment]
Fixed by @pcarrier in #2261
