### ISSUE TITLE
`serialize` and `parseValue` are not called for input parameter of a customised scalar type

### ISSUE THREAD

**Issue by zhaoyi0113** [graphql/graphql-js#2282]
I define a schema like this:

```
const query = new GraphQLObjectType({
    name: 'Query',
    fields: {
      quote: {
        type: queryType,
        args: {
          id: { type: QueryID }
        },
      },
    },
  });
const schema = new GraphQLSchema({
    query,
  });
```

The `QueryID` is a customised scalar type.

```
const QueryID = new GraphQLScalarType({
  name: 'QueryID',
  description: 'query id field',
  serialize(dt) {
    // value sent to the client
    return dt;
  },
  parseLiteral(ast) {
    if (ast.kind === 'IntValue') {
      return Number(ast.value);
    }
    return null;
  },
  parseValue(v) {
    // value from the client
    return v;
  },
});
```

I found that the `serialize` and `parseValue` methods are not called when clients send query to my server. I can see `parseLiteral` is called correctly. 
In most of the document I can find, they use `gql` to define schema but in my case I am using `GraphQLSchema` object. Is this the root cause?

**Comment by IvanGoncharov** [comment]
> I found that the serialize and parseValue methods are not called when clients send query to my server. I can see parseLiteral is called correctly.

@zhaoyi0113 Please note `serialize` will be called only if your return value of `QueryID` type.
As for `parseValue` it's called only if you provide a value of `QueryID` as a query variable.

> In most of the document I can find, they use gql to define schema but in my case I am using GraphQLSchema object. Is this the root cause?

Even if you define your schema as SDL string it still will be constructed using `GraphQLSchema` object so it's perfectly fine to use it directly.
