### ISSUE TITLE
Can't create custom scalar type within GraphQLNonNull

### ISSUE THREAD

**Issue by zhaoyi0113** [graphql/graphql-js#2292]
I have below customised scalar type. It extends from `GraphQLScalarType` and wrapped within `GraphQLNonNull`. None of the three methods `serialize`, `parseValue` and `parseLiteral` are called. It works fine if I remove `GraphQLNonNull`. How I can make GraphQLNonNull works with customised type?

```
const ds = new GraphQLScalarType({
  name: 'DataSource',
  description: 'Description of my custom scalar type',
  serialize(value) {
    return value;
  },
  parseValue(value) {
    return value;
  },
  parseLiteral(ast) {
    return ast.value;
  },
});

const DataSource = GraphQLNonNull(ds);
```

**Comment by IvanGoncharov** [comment]
@zhaojunz Can you please provide a full example including a query that you sending?
Also, note that if you passing/returning `null` value none of the three methods would be called.

**Comment by zhaoyi0113** [comment]
I understand `null` value doesn't call any of these three methods. I expect the graphql framework rejects query with `null` value for `GraphQLNonNull`. But I figured it out.
The one in my example is declare the type in one file:

scalars.js
```
...
const DataSource = GraphQLNonNull(ds);
module.exports = { DataSource };
```
Then import it in the schema file:

```
const { DataSource } = require('./scalars');

...
     dataSource: { type: DataSource}
```

It works if I don't export the type with `GraphQLNonNull` wrapper like:

```
module.exports = { DataSource: ds };
```
then import it as:

```
const { DataSource } = require('./scalars');

...
     dataSource: { type: GraphQLNonNull(DataSource)}
```

I am not sure whether this is graphql library issue or I used a wrong javascript syntax

**Comment by IvanGoncharov** [comment]
@zhaoyi0113 Both code sample looks good and should work.
However, I can't help you without the ability to run code.
Can you please create a minimal example to reproduce this problem?

**Comment by zhaoyi0113** [comment]
No worries @IvanGoncharov , I will close it since it works. Thanks for your response.
