### ISSUE TITLE
spellchecker: Contribute "custom" words upstream

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2298]
Would be great to upstream these words to https://github.com/streetsidesoftware/cspell-dicts repo: 
https://github.com/graphql/graphql-js/blob/bacffcf60c9e0cf61612fa795d121693c32456a8/cspell.json#L40-L83

**Comment by gagahpangeran** [comment]
@IvanGoncharov  Hey, I want to help for this issue!
Can you tell me where to begin?

**Comment by IvanGoncharov** [comment]
@gagahpangeran You just need to add words into appropriate dictionaries in this repo:
https://github.com/streetsidesoftware/cspell-dicts and open PR.

**Comment by hereisnaman** [comment]
@IvanGoncharov I would like to work on this. We can include the `software-terms` dict in our project and I'll open a PR to add the remaining custom words in that dict itself. 

Please assign this issue to me. :)

**Comment by IvanGoncharov** [comment]
@hereisnaman Sounds great 👍 

>  We can include the software-terms

Didn't knew you need to explicitly include it 🤔

**Comment by IvanGoncharov** [comment]
Tracked in #2538
