### ISSUE TITLE
Type Support for `Infinity`

### ISSUE THREAD

**Issue by RealAdamSinger** [graphql/graphql-js#2299]
Currently Infinity cannot be passed into a graphql query even if type `Float` or `Int` is used.
Should there be support for this?

The query below has no functional value, it is for demonstration purposes using https://www.graphqlbin.com/v2/6RQ6TM
![image](https://user-images.githubusercontent.com/10245291/71200462-17d40180-2266-11ea-81e3-883140bbd7df.png)

**Comment by mjmahone** [comment]
Infinity is not a valid [GraphQL Spec `Integer` token](http://spec.graphql.org/June2018/#IntValue): GraphQL the language is not JS, and so just like how integer representations are different between JS and C++, Integer representations are different between JS and GraphQL.

**Comment by dopry** [comment]
I would argue that Infinity is a general math concept and not specific to JS so it would make sense to implement support for Infinity in graphql in general. @RealAdamSinger  maybe it makes sense to open this as a feature request for the graphql spec.
