### ISSUE TITLE
Roadmap to v15

### ISSUE THREAD

**Issue by mike-marcacci** [graphql/graphql-js#2303]
Hi @IvanGoncharov! I just wanted to check in on the roadmap to v15. I missed the last WG meeting, so perhaps this was discussed and I just didn't see it on the notes.

I know that previously we had discussed releasing 15 quickly (last month or so) with the existing breaking changes, and then releasing v16 with the TypeScript rewrite in early 2020, to corresponding with the next cut of the spec.

Is this still the game plan? There are several pieces sitting in master (such as intermediate interfaces) that could provide immediate value. If we're waiting on any other pieces, let me know and I can try to get some time over the next couple weeks to work on them.

**Comment by IvanGoncharov** [comment]
Hi @mike-marcacci 

So the plan is as follows I'm finishing #2248 today and releasing `15.0.0-alpha.2`.
I will ping GraphiQL guys and Apollo guys to test it and report if anything is broken.
After that release `15.0.0-rc.1` and encourage the general public to try it (twitter and your article) wait for 1 week and release `15.0.0`.

What do you think?

**Comment by mike-marcacci** [comment]
This sounds great – thanks so much @IvanGoncharov. Do let me know if you need any help!

**Comment by IvanGoncharov** [comment]
@mike-marcacci Happy new year 🎄 
Sorry for the delay, I release `15.0.0-alpha.2` yesterday and nobody complained. 
I will ping GraphiQL team and Apollo guys after the new year.

**Comment by mike-marcacci** [comment]
Thanks so much for getting that out @IvanGoncharov; I've integrated the new alpha in some of my projects and everything functions correctly. I will note that the typescript types are deeply flawed (not just "less-than-ideal", but actually incorrect) in all the ways they were in DefinitelyTyped. I'm definitely OK keeping this behavior for now as we rework the codebase into TypeScript to prevent making multiple "breaking" type changes.

**Comment by jack-guy** [comment]
Hi there, thanks so much for the hard work on v15 (Mike in particular, for championing `interface implements`!)

Per the timeline laid out in this issue, v15 should be ready to graduate from RC. Are there any blockers for that? Thanks!

**Comment by IvanGoncharov** [comment]
@jack-guy Working on RC.2 ETA: Today

**Comment by moulikcipherX** [comment]
Hy @IvanGoncharov I have a previous experience in Typescript and I want to work with you all as I love graphql and want to work from a long time.
I have experience of GSoC'19 in Typescript.

**Comment by derek-miller** [comment]
Any more updated on the planned release date of v15?

**Comment by obi1kenobi** [comment]
Perhaps safe to close this issue now, given that v15 was released?
