### ISSUE TITLE
Should allow outputFields and inputFields arguments to mutationWithClientMutationId to be functions

### ISSUE THREAD

**Issue by saikat** [graphql/graphql-js#233]
This way we can refer to types that are defined below the mutation's definition.  Also it seems consistent with allowing fields on a type definition to be a function.

**Comment by kassens** [comment]
Sounds good. Want to send a pull request?

**Comment by leebyron** [comment]
Believe this was fixed in https://github.com/graphql/graphql-relay-js/commit/adb856f0ab6a400fa7b4ed5803def5764edeffb0
