### ISSUE TITLE
Warning when use GraphQLNonNull or GraphQLList

### ISSUE THREAD

**Issue by amjedomar** [graphql/graphql-js#2338]
The official graphql-js document refers that [GraphQLNonNull](https://graphql.org/graphql-js/type/#graphqlnonnull) is a class so if I want to use it I have to instantiate it and then pass a valid graphql type to it

But when I do that the IDE that I use (WebStorm) show me a warning about that:
> Interface can not be instantiated

![GraphQLNonNull](https://user-images.githubusercontent.com/40240660/71817233-43dce880-3096-11ea-8771-d061adbc4265.png)

However, the warning disappears when I use it without instantiating it (without writing `new` keyword before it)

![GraphQLNonNull2](https://user-images.githubusercontent.com/40240660/71817529-2e1bf300-3097-11ea-9e5e-6b671dda4d83.png)

This problem is also happening with [GraphQLList](https://graphql.org/graphql-js/type/#graphqllist)

**Comment by amjedomar** [comment]
This problem is also happening with [GraphQLList](https://graphql.org/graphql-js/type/#graphqllist)

**Comment by mjmahone** [comment]
This is intentional: the types are interfaces, and `GraphQLNonNull(ofType)` is a method to get you a concrete instance of the `GraphQLNonNull`. This for instance helps prevent usages of `instanceof` that have caused issues in the past.
