### ISSUE TITLE
Validating a JSON Object against GraphQL Type

### ISSUE THREAD

**Issue by rawkode** [graphql/graphql-js#2343]
Is it possible to validate a JSON document against a GraphQL Output Type?

I found these docs: https://graphql.org/graphql-js/utilities/

I am able to load the schema and get the types. I can't work out how to validate a JSON doc against one of those types though.

I've tried `astFromValue` and `isValidJSValue`; both without success.

Please help :)

This is where I am thus far:

```javascript
jest.disableAutomock();

const fs = require("fs");
const graphql = require("graphql");
const yaml = require("js-yaml");

test("adds 1 + 2 to equal 3", () => {
  const teamMemberSchema = fs.readFileSync(
    "../../schemas/graphql/team/member.graphql",
    "utf8"
  );

  const schema = graphql.buildSchema(teamMemberSchema);

  const members = yaml.safeLoadAll(
    fs.readFileSync("../../examples/team/member.yaml", "utf8")
  );

  members.map(member => {
    const result = ???;
    console.log(result);
  });

  expect(1 + 2).toBe(3);
});
```

**Comment by IvanGoncharov** [comment]
@rawkode There is no specialized function for `astFromValue` and `isValidJSValue` are intended to work with Input types only.
The resolution of output types heavily depends on resolvers so output data is validated only during query execution.

What you can do is to use `graphql`:
```js
const testSchema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      testField: {
        type: new GraphQLList(schema.getType('SomeType')),
      }
    }
  });
})

const source = `
  {
     testField {
       someField
       # All other subfields
     }
  }
`;

const result = graphqlSync({ schema: testSchema, source, rootValue: members });
expect(result.errors).to.equal(undefined);
expect(result.data.testField).to.deep.equal(members);
```
Disclaimer: I didn't run this code just wrote it from the top of my head.

**Comment by IvanGoncharov** [comment]
Also, it's partly overlaps with #563

**Comment by mjmahone** [comment]
> I am able to load the schema and get the types. I can't work out how to validate a JSON doc against one of those types though.

When you do that, you've created a simple custom GraphQL Client. So that is outside ths cope of `graphql-js`, which is designed to be a reference server implementation with extra build-utility functions.
