### ISSUE TITLE
Type extension information gets lost when a schema is parsed and printed

### ISSUE THREAD

**Issue by pmantica1** [graphql/graphql-js#2386]
I noticed that type extension information gets lost when a schema is printed and parsed. Essentially, I noticed the following issue:
```javascript
const graphql = require("graphql");
schema = "type Object {a : Int} extend type Object {b: Int}"
console.log(graphql.printSchema(graphql.buildASTSchema(graphql.parse(schema))));
// type Object {a: int} 
```
This seems like a bug to me though I am not 100% what the expected behavior is. Please let me know what you think. 

(Please pardon my poor javascript since I am primarily a python developer. I noticed the issue originally in the python port of the GraphQL library and backtracked it here).

**Comment by IvanGoncharov** [comment]
@pmantica1 Thanks for reporting 👍 
This particular issue is fixed in #2248 and released in `15.0.0-alpha.2`
AFAIK it's not yet ported to Python.
