### ISSUE TITLE
Graphql Nested object: “must be Input Type but got” 

### ISSUE THREAD

**Issue by alakdam07** [graphql/graphql-js#2427]
I am trying to do a mutation on Graphql. I want to add another object in my query and mutation. My root query works fine but I had trouble with mutation. I am getting an error. This is the error: "The type of Mutation.addRestaurant(location:) must be Input Type but got: LocationType."

**This is my restaurant query**
```
const restaurantname = new GraphQLObjectType({
  name: "RestaurantType",
  description: "This is Helsinki's Restuarent",
  fields: () => ({
    name: { type: GraphQLString },
    image: { type: GraphQLString },
    address: { type: GraphQLString },
    info_url: { type: GraphQLString },
    location: { // This is locationtype
      type: location,
      resolve(parents, args) {
        return parents;
      }
    }
  })
});
```

**This is my locationtype object, where I added in restaurant type.**

```
const location = new GraphQLObjectType({
  name: "LocationType",
  description: "Helsinki's locations with lat and long",
  fields: () => ({
    lat: { type: GraphQLFloat },
    long: { type: GraphQLFloat }
  })
});
```

**This is my root query and it works fine:**

```
const query = new GraphQLObjectType({
  name: "Rootquery",
  description: "This is Rootquery",
  fields: () => {
    return {
      restaurant: {
        type: restaurantname,
        args: {
          name: { type: GraphQLString }
        },
        resolve(parents, args) {
          //return restaurant.models.restaurant.find({ where: args });
          return parents;
        }
      }
    };
  }
});
```

**This is the mutation which I don't know how to add locationtype object:**

```
const mutation = new GraphQLObjectType({
  name: "Mutation",
  fields: () => {
    return {
      addRestaurant: {
        type: restaurantname,
        args: {
          name: { type: new GraphQLNonNull(GraphQLString) },
          image: { type: new GraphQLNonNull(GraphQLString) },
          address: { type: new GraphQLNonNull(GraphQLString) },
          info_url: { type: new GraphQLNonNull(GraphQLString) },
          location: { type: new GraphQLNonNull(location) } //
        },
        resolve(parents, args) {
          let restaurantData = new restaurant({
            name: args.name,
            image: args.image,
            address: args.address,
            info_url: args.info_url,
            location: args.location
          });
          restaurantData.save();
        }
      }
    };
  }
});
```

This is second time Github issue. So, It looks mess. I am sorry for that.

**Comment by IvanGoncharov** [comment]
@alakdam07 You can't use the same `Location` type for output and input.
If you want to use a type in arguments you need to create separate input types using `GraphQLInputObjectType`.

**Comment by alakdam07** [comment]
Hi @IvanGoncharov, I understand about the **GraphQLInputObjectType** but the problem is when I am adding that location information to, it does not go to add to my Restaurant type. how can i add the location to my RestaurantType. I did not find anywhere good documentation or article about it.

**Comment by IvanGoncharov** [comment]
@alakdam07 You need to create separate types, for example `Location` and `LocationInput`.

**Comment by alakdam07** [comment]
@IvanGoncharov I did but it did, It did not work for me. I can location but I can't see in my database. I am new in graphQL. I might made silly mistake. If you help me out then my last two days work will be wroth. Thank you.

Here is the code:

`const restaurant = require("./models/restaurant");
const craftbeer = require("./models/craftbeer");
const bottlebeer = require("./models/bottlebeer");
const graphql = require("./node_modules/graphql");
const {
  GraphQLObjectType,
  GraphQLString,
  GraphQLSchema,
  GraphQLInt,
  GraphQLList,
  GraphQLID,
  GraphQLFloat,
  GraphQLNonNull,
  GraphQLInputObjectType
} = graphql;

const craftbeers = new GraphQLObjectType({
  name: "CraftBeerType",

  fields: () => ({
    beername: { type: GraphQLString },
    price: { type: GraphQLInt },
    image: { type: GraphQLString }
  })
});

const bottlebeers = new GraphQLObjectType({
  name: "BootleBeerType",

  fields: () => ({
    beername: { type: GraphQLString },
    price: { type: GraphQLInt },
    image: { type: GraphQLString }
  })
});

const location = new GraphQLObjectType({
  name: "location",
  description: "Helsinki's location with lat and long",
  fields: () => ({
    latitude: { type: GraphQLFloat },
    longitude: { type: GraphQLFloat }
  })
});

const restaurantname = new GraphQLObjectType({
  name: "RestaurantType",
  description: "This is Helsinki's Restuarent",
  fields: () => ({
    name: { type: GraphQLString },
    image: { type: GraphQLString },
    address: { type: GraphQLString },
    info_url: { type: GraphQLString },
    location: { type: new GraphQLList(location) } 
  })
});

const query = new GraphQLObjectType({
  name: "Rootquery",
  description: "This is Rootquery",
  fields: () => {
    return {
      restaurant: {
        type: restaurantname,
        args: {
          name: { type: GraphQLString }
        },
        resolve(parents, args) {
          // return restaurant.models.restaurant.find({ where: args });
          return parents;
        }
      }
    };
  }
});
const locationInput = new GraphQLInputObjectType({
  name: "LocationInput",
  description: "Helsinki's location with lat and long",
  fields: () => ({
    latitude: { type: GraphQLFloat },
    longitude: { type: GraphQLFloat }
  })
});
const mutation = new GraphQLObjectType({
  name: "Mutation",
  fields: () => {
    return {
      addRestaurant: {
        type: new GraphQLList(restaurantname),
        args: {
          name: { type: new GraphQLNonNull(GraphQLString) },
          image: { type: new GraphQLNonNull(GraphQLString) },
          address: { type: new GraphQLNonNull(GraphQLString) },
          info_url: { type: new GraphQLNonNull(GraphQLString) },
          location: { type: new GraphQLList(locationInput) }
        },
        resolve(parents, args) {
          let restaurantData = new restaurant({
            name: args.name,
            image: args.image,
            address: args.address,
            info_url: args.info_url,
            location: args.location
          });
          restaurantData.save();
        }
      }
    };
  }
});

const Schema = new GraphQLSchema({
  query,
  mutation
});

module.exports = Schema;`

**Comment by IvanGoncharov** [comment]
@alakdam07 Now schema looks correct.
Can't help with debugging your code DB code.
However please feel free to ask for help if you have problems specifically with `graphql` library but please provide full source code (try to reduce it as much as possible).

**Comment by alakdam07** [comment]
@IvanGoncharov 

This is my mongoose's restaurant schema

`const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const restaurant = new Schema({
  name: String,
  image: String,
  address: String,
  info_url: String,
  location: { latitude: Number, longitude: Number }
});

module.exports = mongoose.model("restaurant", restaurant);`

This is my server with mongoose. I will delete this DB if I successfully do the mutation. but you can feel free to use it.

`const express = require("express");
const app = express();
const graphqlHTTP = require("express-graphql");
const schema = require("./graphqlSchema");

var mongoose = require("mongoose");

mongoose
  .connect(
    "mongodb+srv://helsinkibeer:test123456@cluster0-e1jfj.mongodb.net/test?retryWrites=true&w=majority",
    { useUnifiedTopology: true, useNewUrlParser: true }
  )
  .then(() => console.log("DB Connected!"))
  .catch(err => {
    console.log(err);
  });

app.use(
  "/graphql",
  graphqlHTTP({
    schema,
    pretty: true,
    graphiql: true
  })
);

const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Example app listening on port ${port}!`));`

**Comment by IvanGoncharov** [comment]
@alakdam07 Sadly I don't have time to debug this code :(
I can try to find some help on StackOverflow: http://stackoverflow.com/

**Comment by alakdam07** [comment]
@IvanGoncharov I understand. Have a good one. 

Cheers

**Comment by carlosmori** [comment]
@alakdam07 Check your types
const **restaurant** = require("./models/restaurant");

`addRestaurant: {
        type: new GraphQLList(**restaurantname**),
        args: {
          name: { type: new GraphQLNonNull(GraphQLString) },
          image: { type: new GraphQLNonNull(GraphQLString) },
          address: { type: new GraphQLNonNull(GraphQLString) },
          info_url: { type: new GraphQLNonNull(GraphQLString) },
          location: { type: new GraphQLList(locationInput) }
        },`
I think restaurantname is not the type you are importing. Let me know if it helped!

Cheers

**Comment by georgesamy** [comment]
Had the same problem. The problem is that in the mutation you define address as type, on this line:
`address: { type: new GraphQLNonNull(GraphQLString) },`
It should be defined as `input` instead, making it:
`address: { input: new GraphQLNonNull(GraphQLString) },`
