### ISSUE TITLE
graphql svg

### ISSUE THREAD

**Issue by matthewmueller** [graphql/graphql-js#243]
Been looking for the graphql icon online, but haven't been able to find it. Would it be possible to upload the SVG?

**Comment by jonsharratt** [comment]
You could possibly grab the one from graphql.org :dancer: (http://graphql.org/img/logo.svg) ?

**Comment by matthewmueller** [comment]
oh perfect thanks! actually didn't know graphql.org existed, haha.

**Comment by dschafer** [comment]
It's also at https://github.com/facebook/graphql/tree/master/resources
