### ISSUE TITLE
`extend` incorrectly allows repeating of non-repeatable directives

### ISSUE THREAD

**Issue by m14t** [graphql/graphql-js#2442]
While working on https://github.com/graphql/graphql-js/pull/2276, it was discovered that it was possible to extend a type of a non-repeatable directive multiple times. [[comment](https://github.com/graphql/graphql-js/pull/2276/files#r364908343)].

Simple example that should NOT be allowed:
```graphql
directive @foo on SCALAR

type Query {
    someField: SomeScalar
}

scalar SomeScalar @foo

extend scalar SomeScalar @foo
```

It's my understanding that `extend` should simply try to add the directive here to the previous list of directives, and that should only be allowed if the directive is either not present, or is repeatable.

**PR with failing test case:** https://github.com/graphql/graphql-js/pull/2440

**Comment by IvanGoncharov** [comment]
@m14t Thanks for tracking this issue and especially for PR with a test case.
Fixed in #2446
