### ISSUE TITLE
validateSchema, option to make parts not throw but log for example?

### ISSUE THREAD

**Issue by maapteh** [graphql/graphql-js#2454]
Is it possible to have the error `isOutputType` conditionally? One of our organisations is in the process to slowly take micro-services one by one into a Graph but at this time it's not guaranteed that what they promise to give back stays like this but we wrapped them (cant be graphql totally).

I know one of the core principles of GraphQL is to never trust its resources but it now breaks our queries even when something little has been changed we don't even need. I know the underlying problem is that we should be more aware about these changes but at the moment this is not possible.

Is it possible to set it (by configuration argument) to logging type instead of error, or disable it :)

https://github.com/graphql/graphql-js/blob/6f70c862e38e227de4ad474806eb606e742f5fb5/src/type/validate.js#L298

For example we have now an enum `[LoyaltyCards!]!` and we keep it as ENUM but sometimes the service adds another variant to it. For us now in frontend we use the enum and only wrote parts for cards we are interested in, but it can lead to a total error for the whole query while we are never interested in this small addition and don't do anything with it. For now, we make it less strict and simply type it as `[String!]!`.

But the idea is that if its configurable to only log this error we can aggregate these and slowly adjust the schema. Now by throwing the error on one field will cause no response at all and error of the whole query (sometimes page). Don't get me wrong, I like the core principle but I'm just asking if we could have it more configurable.

**Comment by IvanGoncharov** [comment]
@maapteh You can pass `assumeValid: true` to `GraphQLSchema` or `buildASTSchema` (if you use SDL). Also in case if you can't change schema creation code just do:
```
schema.__validationErrors = []
```

**Note**: This will disable schema validation completely so you can have a lot of mysterious mistakes in other parts of your GraphQL server.

**Comment by IvanGoncharov** [comment]
@maapteh Also, you can run `validateSchema` before strating your server and do:
```
validateShema(schema);
schema.__validationErrors = __validationErrors.filter(someFunctionToFilterErrors)
```
`__validationErrors` is not a part of public API so it change in future but using it for a fixed release is pretty safe just don't use it anything more that temporary workarounds.

**Comment by maapteh** [comment]
:) Thanks Ivan, it seems like a perfect short term solution!
