### ISSUE TITLE
What is the Node compatibility for v0.13.2 and below?

### ISSUE THREAD

**Issue by johncmunson** [graphql/graphql-js#2455]
What is the Node compatibility for v0.13.2 and below? It is not called out in the package.json or README.

I am asking because my team has an application that used to be on Node 8. No memory leak was ever noticed then. We recently upgraded to Node 10, and we are now noticing a memory leak that we suspect is coming from our GraphQL layer.
node v10.15.2
graphql v0.13.2

I noticed a fix for a memory leak was merged into graphql v14 [here](https://github.com/graphql/graphql-js/pull/1417). I'm wondering if upgrading to v14 and above would fix our memory issue.

**Comment by IvanGoncharov** [comment]
@johncmunson We support Node10 until Apr2021
So our policy is to support all currently supported versions of Node including LTS:
https://github.com/nodejs/Release#release-schedule
