### ISSUE TITLE
GraphQL + rootValue Session

### ISSUE THREAD

**Issue by spyalert01** [graphql/graphql-js#247]
How do I make my session globally accessible in my schema.js? (I am using express-session)

**Comment by leebyron** [comment]
You should provide it as the rootValue when you run execution. The rootValue is then available in all resolution functions in your schema.

**Comment by spyalert01** [comment]
so in each Function, I need to call the rootValue to use it right? 
Is there a way to make it globally accessible , and update in GraphQL without calling it in every function?
