### ISSUE TITLE
Setting Internal Values for Enum doesn't work

### ISSUE THREAD

**Issue by taddyhuo** [graphql/graphql-js#2479]
I was trying to follow https://www.apollographql.com/docs/graphql-tools/scalars/#internal-values

TypeDefs:
```js
const typeDefs = `
  enum StatusEnum {
    ACTIVE
    INACTIVE
  }

  type Query {
    getTask(taskId: ID!): Task!
  }

  type Task {
    status: StatusEnum
  }
`
```

Resolvers:
```js
const resolvers = {
  Query: {
    getTask: () => {
      return { status: 0 };
    },
  },

  StatusEnum: {
    ACTIVE: 0,
    INACTIVE: 1,
  }
}
```

query:
```
query GetTask($taskId: ID!) {
  getTask(taskId: $taskId) {
    status
  }
}
```

However, I got `"Expected a value of type \"StatusEnum\" but received: \"ACTIVE\""`. Any idea why? My graphql version is 14.6.0, graphql-tools version is 4.0.7

**Comment by Cito** [comment]
This should work, but you did not show your complete code. The Query is missing in the typeDefs and you do not show how you execute the query. Also, you should have mentioned that you are using graphql-tools and which version of that you are using.

**Comment by taddyhuo** [comment]
I updated the Query in typeDefs and query for execution. I simplified the code, but the idea is the same. The API returns `number` for the `status`.

**Comment by yaacovCR** [comment]
Please move this potential bug report to
https://github.com/apollographql/graphql-tools/issues if you are using the
original repository or https://github.com/yaacovCR/graphql-tools-fork/issues if
you are using the fork.

This is unlikely to be a bug with graphql-js.

In any case, a minimal reproduction would be extremely helpful.

**Comment by yaacovCR** [comment]
See further discussion at https://github.com/apollographql/graphql-tools/issues/1295

**Comment by taddyhuo** [comment]
Posted https://github.com/apollographql/graphql-tools/issues/1295. Close this issue.

**Comment by IvanGoncharov** [comment]
@Cito @yaacovCR Big thanks for helping with this issue 👍
