### ISSUE TITLE
Resolver args type not correctly propagated from `GraphQLObjectType`

### ISSUE THREAD

**Issue by harrysolovay** [graphql/graphql-js#2481]
I'm running into issues relating to the inference of arguments and return types from within a given `GraphQLObjectType`.

My query interface looks like this:

```ts
interface Query {
  tweets: Tweet[];
  user: User;
}
```

And my schema like this:

```ts
export const schema = new GraphQLSchema({
  query: new GraphQLObjectType<Context, Query>({
    fields: {
      tweets: {
        resolve: async (_0, args) => {
          // `tweets` resolution here
        },
        type: new GraphQLList(TweetType),
      },
      user: {
        args: {
          id: {type: GraphQLID},
        },
        resolve: async (_0, args) => {
          // `user` resolution here
        },
        type: UserType,
      },
    },
    name: "Query",
  }),
});
```

The `tweets` query is meant to accept no arguments, whereas the `user` query accepts the user's id. So I specify the 3rd generic argument, which I hoped would map to the correct fields:

```diff
export const schema = new GraphQLSchema({
- query: new GraphQLObjectType<Context, Query>({
+ query: new GraphQLObjectType<Context, Query, {tweets: undefined; user: {id: string}}>({
    fields: {
...
```

Although I expect for those types to flow through to their respective resolver arguments, they do not. Instead, the entire map flows through:

<img width="530" alt="Screen Shot 2020-03-08 at 1 00 35 PM" src="https://user-images.githubusercontent.com/4893548/76170196-d3f1e980-613c-11ea-9c56-e86260abb628.png">

 While I could provide a union of the two types, this lacks specificity, and I was wondering if there's a better way?

Additionally, (perhaps this merits another issue), the resolver return types aren't inferred either (I have to manually append the return signature).

```diff
-         resolve: async (test, args) => {
+         resolve: async (test, args): Promise<Tweet[]> => {
          try {
            const tweets = await firestore.collection("tweets").get();
            return tweets.docs.map((tweet) => ({id: tweet.id, ...tweet.data()})) as Tweet[];
          } catch (error) {
            throw new ApolloError(error);
          }
        },
        type: new GraphQLList(TweetType),
      },
      user: {
        args: {
          id: {type: GraphQLID},
        },
-       resolve: async (_0, args) => {
+       resolve: async (_0, args): Promise<User> => {
```

Any help or advice would be greatly appreciated! Thank you!

Kind regards,

Harry

**Comment by IvanGoncharov** [comment]
@harrysolovay Thanks for reporting 👍 
Totally agree that 3rd-argument is very confusing so I removed `TArgs` in #2488.
It was added by `DefinetlyTyped` maintainers and we inherited when we adopted TS typings from them.

As for the long term solution, there is a discussion about adding more complex TS typings in #2188 
Also if you goal to have maximum type safety in TS I would suggest using 
https://github.com/MichalLytek/type-graphql or https://github.com/graphql-nexus/schema
