### ISSUE TITLE
When URL is invalid, no exception is raised

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [graphql/graphql-js#2496]
I think this is a valid issue, because without any type of error trace, then people are left in the wilderness. I have an Angular project. I use Apollo Client and Server with it. Inside the createApollo function, you pass in a URI to connect to (the Apollo Server). It works fine when the URI is correct, as in:

```
const uri = 'http://localhost:3000/graphql/v1';
export function createApollo(httpLink: HttpLink) {
  return {
    link: httpLink.create({uri}),
    cache: new InMemoryCache(),
  };
}
```

However, when the URI is incorrectly formatted, as in:

localhost:3000/graphql/v1

There is no error, and my app appears to be taking forever to load. That's the impression. But in fact, the issue is this unformatted URL. There should be an exception raised if the url is incorrectly formatted, otherwise end user starts troubleshooting and there could be a range of issues as to why the full page isn't loading.

**Comment by giautm** [comment]
This kind of error not related to graphql-js, It must be an issue of `apollo-client`. Please close this and open new issues at https://github.com/apollographql/apollo-client/issues

**Comment by IvanGoncharov** [comment]
@giautm Thanks for the answer, it is absolutely correct.
@lovefamilychildrenhappiness Please report it to Apollo team.
