### ISSUE TITLE
Imported npm package throws errors within flow

### ISSUE THREAD

**Issue by rricard** [graphql/graphql-js#25]
Since the transformations applied before exporting the package to npm strips the flow annotations but not the comments, a lot of flow errors arise after a `npm install graphql`.

Here's some of them:

```
/Users/rricard/src/github.com/rricard/td-foundation/lib/td-mirror/node_modules/graphql/lib/error/index.js:37:25,31: parameter message
Missing annotation

/Users/rricard/src/github.com/rricard/td-foundation/lib/td-mirror/node_modules/graphql/lib/error/index.js:39:3,7: parameter nodes
Missing annotation

/Users/rricard/src/github.com/rricard/td-foundation/lib/td-mirror/node_modules/graphql/lib/error/index.js:39:10,14: parameter stack
Missing annotation

/Users/rricard/src/github.com/rricard/td-foundation/lib/td-mirror/node_modules/graphql/lib/error/index.js:73:23,27: parameter error
Missing annotation

/Users/rricard/src/github.com/rricard/td-foundation/lib/td-mirror/node_modules/graphql/lib/error/index.js:73:30,34: parameter nodes
Missing annotation

...


... 121 more errors (only 50 out of 171 errors displayed)
To see all errors, re-run Flow with --show-all-errors
```

One solution would be to strip the `/* @flow */` comments from the npm package. But we would lose all of the useful information contained inside those annotations. If we had a transform able to put the annotations [in a comment](http://flowtype.org/blog/2015/02/20/Flow-Comments.html), that would be much better...

Anyway, I'm open to discuss the best way to fix this so I can start working on a pull-request and/or a new transform for flow annotations!

**Comment by rricard** [comment]
Here is a quick fix if you want to continue to work before that issue gets fixed:

Add this to your `.flowconfig`:

```ini
[ignore]
.*/node_modules/graphql/.*
```

**Comment by leebyron** [comment]
Sorry about this. I will bring this up with the Flow team to get their best advice

**Comment by rricard** [comment]
Oh don't worry! I deactivated the error with my small sed regex. It will be
fixed when it needs to be. Thanks for bringing this up to the flow team on
this though! Again, I can write the patch if it's not top priority for you
at fb.

**Comment by leebyron** [comment]
With the recent change to babel, the `/*@flow*/` header is now removed, so hopefully this solves your issues.

I'll continue to look into nicer ways to improve this going forward.

**Comment by angelf** [comment]
It would be briliant to have flow annotations preserved. For instance in facebook/draft-js they leave the original code in /lib/ and place the generated plain javascript in /build/.
