### ISSUE TITLE
Custom errors get reduced by GraphQLError

### ISSUE THREAD

**Issue by jardakotesovec** [graphql/graphql-js#251]
In some cases we already have custom errors that have extra properties to describe what happened in details, but graphql-js only [copies](https://github.com/graphql/graphql-js/blob/master/src/error/locatedError.js#L24) message and stack, so we loose them.

One option would be to keep reference to the original error. Or copy properties from original error - that would be more convenient option.

**Comment by leebyron** [comment]
Great suggestion. I decided to keep a reference to the original error to avoid colliding properties, to allow for computed properties, and also to allow for instanceof when necessary.

**Comment by leebyron** [comment]
any instance of GraphQLError can now use `error.originalError` to get the error before it was wrapped and located.
