### ISSUE TITLE
`printSchema` produces incorrect AST for descriptions ending in \ (backslash)

### ISSUE THREAD

**Issue by pcarrier** [graphql/graphql-js#2512]
```typescript
import { buildASTSchema, parse, printSchema } from 'graphql';
console.log(printSchema(buildASTSchema(parse(`"Example\\\\" scalar Foo`))));
```
=>
```graphql
"""Example\"""
scalar Foo
```

Which `parse` does not accept.

**Comment by IvanGoncharov** [comment]
@pcarrier Thanks for reporting 👍 
Definitely something we need to address.

**Comment by hereisnaman** [comment]
@IvanGoncharov what should be the correct result?

**Comment by IvanGoncharov** [comment]
@hereisnaman It should be reproducible even with:
```
const sdl = `
"""Example\\"""
scalar Foo
`;
expect(print(parse(sdl))).to.equal(sdl);
```
So it's not an issue with `printSchema` it's an issue with how we are printing block strings in general.

**Comment by pcarrier** [comment]
Oh yeah sorry I didn't mean to imply this was specific to schemas, absolutely a general printer issue, it's just where we reproduced it using our wealth of customer data and that's the easiest way to make GraphQL make those strings I know.

**Comment by IvanGoncharov** [comment]
@pcarrier No worries.
I'm mentoring @hereisnaman as part of "Google Summer of Code" and this issue is an excellent opportunity for him to learn how parser/printer works.
So my comments intended to guide him in the right direction so he could figure how to fix this issue.
