### ISSUE TITLE
Document TypeInfo's limitations

### ISSUE THREAD

**Issue by wheresrhys** [graphql/graphql-js#2516]
When working with TypeInfo I've discovered 2 things

1. Not every `Kind` is supported as a 'namespace' for enter/leave methods, e.g.  `FIELD_DEFINITION` nodes do not appear to ever get entered. The valid Kinds should be documented clearly - I wasted a lot of time before eventually digging into the TypeInfo source and surmising that I was trying to use an unsupported Kind
2. Does not appear to traverse input objects at all/in the same way as other parts of the query (This might be related to the first point as an input object may just contain lots of unsupported Kinds)

**Comment by IvanGoncharov** [comment]
@wheresrhys Thanks for taking the time to report this 👍 

> FIELD_DEFINITION nodes do not appear to ever get entered. 

`TypeInfo` requires constructed schema so it's useful only for query documents and not SDL documents.
Or I'm missing something?
If you think `TypeInfo` can be useful for working with SDL can you please describe your usecase?

> Does not appear to traverse input objects at all/in the same way as other parts of the query (This might be related to the first point as an input object may just contain lots of unsupported Kinds)

Can you please clarify which kinds?
Do you mean type definitions for input types?
