### ISSUE TITLE
graphql: Variable “$print” is not defined by operation

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [graphql/graphql-js#2521]
I already tried StackOverflow. While there are millions of similar questions, none solve my issue.

I am able to get graphql working fine with Apollo Client and Apollo Server, but I am writing one test that requires me to hit the endpoint with node-fetch. But all the examples from the documentation and other stackoveflow posts are not working for me:

```
const fetch = require('node-fetch'); // I tried isomorphic-fetch too
const uri = `http://localhost:3000/graphql/v1`;

const query = `
    query findLeadStat($print: PrintInput!) {
      findLeadStat(print: $print){
        answered
        print
        service
      }
    } 
`;

const variables = {
    print: {
        answered: 1,
        print: "123",
        service: "abc",
    }
}

const response = await fetch(uri, {
    method: 'post',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ query, variables})
})

console.log('and the resp: ', await response.json());
The response it gives is:

{
  errors: [
    {
      message: 'Variable "$print" is not defined by operation "findLeadStat".',
      locations: [Array],
      extensions: [Object]
    },
    {
      message: 'Variable "$print" is never used in operation "findLeadStat".',
      locations: [Array],
      extensions: [Object]
    }
  ]
}
```

Keep in mind, the same exact query works in Apollo Client, except I use print instead of $print in the variable list. But if I use print with node-fetch, I get another error Syntax Error: Expected $, found Name "print".

Again, I have this working with Apollo, but cannot get this working in node with node-fetch or isomorphic-fetch. How do I get this working outside of Apollo?

**Comment by IvanGoncharov** [comment]
@lovefamilychildrenhappiness You should always use `$` before query variable name.
Not sure how it worked with Apollo.
Here is a minimal example with fetch:
```js
fetch('http://swapi.apis.guru/', {
  method: 'post',
  headers: {'Content-Type': 'application/json'},
  body: JSON.stringify({
    query: 'query ($id: Int) { person(personID: 1) { name } }',
    variables: { id: 1 },
  }),
}).then(response => response.json());
```
Hope it would be useful.
