### ISSUE TITLE
How to write type resolvers?

### ISSUE THREAD

**Issue by benallfree** [graphql/graphql-js#2525]
I wonder if someone can supply a code sample, as the docs unclear on how to structure type resolvers. Here is an [example](https://www.apollographql.com/docs/graphql-tools/generate-schema/) from the Apollo docs:

```js
const resolvers = {
  Query: {
    libraries() {

      // Return our hardcoded array of libraries
      return libraries;
    }
  },
  Library: {
    books(parent) {

      // Filter the hardcoded array of books to only include
      // books that are located at the correct branch
      return books.filter(book => book.branch === parent.branch);
    }
  },
  Book: {

    // The parent resolver (Library.books) returns an object with the
    // author's name in the "author" field. Return a JSON object containing
    // the name, because this field expects an object.
    author(parent) {
      return {
        name: parent.author
      };
    }
  }

  // Because Book.author returns an object with a "name" field,
  // Apollo Server's default resolver for Author.name will work.
  // We don't need to define one.
};
```

I can use [makeExecutablSchma](https://github.com/ardatan/graphql-tools) to translate the above into something that `graphql-js` understands, but I don't know how to express it natively.

It's not feasible to deeply nest and repeat type resolvers and makes sense for graphql-js to "fall back" to the root type resolver when a requested field is not found.

Is there a way to do this?

**Comment by IvanGoncharov** [comment]
@benallfree You can use es6 classes like this:
https://github.com/IvanGoncharov/swapi-demo/blob/master/src/index.ts
As for supporting something similar to `graphql-tools` resolver format, it's planed for the major version.
