### ISSUE TITLE
defaultValue for argument of InputObjectType

### ISSUE THREAD

**Issue by vladar** [graphql/graphql-js#253]
I have complex argument for a field that is `ListOf(InputObjectType)`, but when I try to set `defaultValue` for this argument, I get error: 

```
Syntax Error GraphQL (1:3) Expected Name, found String "selectId"

1: [{"selectId":"value","selectedOptions":["a", "b", "c"]}]
     ^
```

I would expect parser to accept InputObject as default argument value, but it only accepts literals.

**Comment by leebyron** [comment]
Default values can by any value including InputObject, but the issue here is a syntax error as reported.

Try:

```
[ { selectId: "value", selectedOptions: ["a", "b", "c"] } ]
```
