### ISSUE TITLE
[Typescript] How to extend ExecutionResult?

### ISSUE THREAD

**Issue by deser** [graphql/graphql-js#2539]
Hey Guys,
Is it possible to add ability to for exported `graphql` function to have extension types? For example I need to extend `ExecutionResult` with my `data` response.

**Comment by erik-beus** [comment]
This used to be possible. But in v. 15 it seems this was changed :/
https://github.com/graphql/graphql-js/pull/2490

**Comment by IvanGoncharov** [comment]
@erik-beus Thanks for linking correct issue.

> For example I need to extend ExecutionResult with my data response.

@deser Yes, it was possible but was removed in #2490, please see discussion there.
