### ISSUE TITLE
GraphQL support for Deno

### ISSUE THREAD

**Issue by LaurenceM10** [graphql/graphql-js#2566]
# Feature requests

Deno was released a few days ago, is there any plan to support it?
https://deno.land/v1

**Comment by IvanGoncharov** [comment]
@LaurenceM10 Yes, it's planned 👍 
And @hereisnaman did some preliminary testing for that.
Our target is to add `graphql` module to this list: https://deno.land/x/
It's not a top priority at the moment but something that we want to do in the next few weeks.

**Comment by LaurenceM10** [comment]
Ok. Thanks!

**Comment by danielrearden** [comment]
FWIW, it's already possible to use GraphQL in Deno by utilizing Pika CDN

```
import {
  GraphQLObjectType,
  GraphQLSchema,
  GraphQLString,
} from "https://cdn.pika.dev/graphql@^15.0.0";
```

Here's a [full example](https://github.com/danielrearden/graphql_abc/blob/master/examples/server.ts) using the middleware I wrote for the ABC framework.

**Comment by mlow** [comment]
@danielrearden This isn't working anymore:

```The requested module '/-/graphql@v15.0.0-KZBXeLwp7DcGGGn15gbf/dist=es2019/graphql.js' does not provide an export named 'default'```

**Comment by dardanbujupaj** [comment]
> @danielrearden This isn't working anymore:
> 
> `The requested module '/-/graphql@v15.0.0-KZBXeLwp7DcGGGn15gbf/dist=es2019/graphql.js' does not provide an export named 'default'`

I ran into the same issue. On [reddit](https://www.reddit.com/r/Deno/comments/gwht72/the_requested_module_does_not_provide_an_export/) I learned that it's possible to use the URL from the error message as a work around.

`import { graphql, buildSchema } from "https://cdn.pika.dev/-/graphql@v15.0.0-KZBXe    Lwp7DcGGGn15gbf/dist=es2019/graphql.js";`

**Comment by khanakia** [comment]
Does anyone have the link to DENO package I could not find it ?

**Comment by rossholdway** [comment]
Hi. Would it be possible for a maintainer to provide some context on where the project currently is re. Deno support? I see various mentions of Deno in commits, branches etc but can't make out the overall picture. Is support for Deno still something that's being worked on?

Using a CDN like https://cdn.skypack.dev/graphql?dts seems to be working well...

**Comment by saihaj** [comment]
So we publish under deno branch here https://github.com/graphql/graphql-js/tree/deno which if you import should work

**Comment by Urigo** [comment]
Thanks to all the work that has been done here, If anyone wants to use a modern GraphQL framework with Deno, [Yoga Server now fully supports Deno](https://www.the-guild.dev/graphql/yoga-server/v3/integrations/integration-with-deno) without you needing to change anything about how you write your code
