### ISSUE TITLE
Documentation of GraphQLScalarType is outdated

### ISSUE THREAD

**Issue by Cito** [graphql/graphql-js#2567]
The [documentation for the GraphQLScalarType](https://github.com/graphql/graphql-js/blob/master/docs/APIReference-TypeSystem.md#graphqlscalartype) is outdated compared with the [current code](https://github.com/graphql/graphql-js/blob/74ce729eddf7c777a1c500d63f1c4fce35e9f1cf/src/type/definition.js#L676). For instance, `parseLiteal` takes a *valueNode* and a *variables* parameter instead of just one *valueAST* parameter (I think that was changed in 0.12), and there are some more differences.

**Comment by overhead525** [comment]
@Cito this seems pretty straightforward. Have you completed this yet? If not, I'll get it done if you'll assign me.

**Comment by Cito** [comment]
@overhead525 no, haven't done anything about this yet. @IvanGoncharov can you assign it to him?

**Comment by yaacovCR** [comment]
Changes in #3812 would also require documentation update
