### ISSUE TITLE
GraphQL printer produces invalid documentation strings

### ISSUE THREAD

**Issue by pcarrier** [graphql/graphql-js#2569]
With graphql-js 15.0.0:

```
import graphql from 'graphql';
console.log(graphql.printSchema(graphql.buildASTSchema(graphql.parse(`"Ex\\\\ample" scalar Foo`))));
```

```
node .\index.mjs
"""Ex\ample"""
scalar Foo
```

which is an invalid escape according to the spec.

**Comment by hereisnaman** [comment]
@pcarrier this is not an invalid result. The js string literals are auto escaped.

```javascript
`"Ex\\\\ample" scalar Foo`.split('') === [ "\"", "E", "x", "\\", "\\", "a", "m", "p", "l", "e", "\"", " ", "s", "c", "a", "l", "a", "r", " ", "F", "o", "o" ]
// true
```

So the string provided to the parser actually has only 2 `\` and it returns the correct result according to that. If you try using `String.raw` and wrap your gql string with it then this problem can be solved.

**Comment by IvanGoncharov** [comment]
@pcarrier Please also note that block strings are treated slash just as slash:
http://spec.graphql.org/draft/#sel-IAFdPVREBCABCCBvoT
So in GraphQL `"""Ex\ample"""` and `"Ex\\ample"` are equal.

**Comment by IvanGoncharov** [comment]
@hereisnaman Please ensure that we have such a similar test case in our tests.

**Comment by pcarrier** [comment]
Thanks for the explanation, block strings are indeed simpler yet smarter than I had originally understood.
