### ISSUE TITLE
Aliased fields don't preserve order

### ISSUE THREAD

**Issue by syrusakbary** [graphql/graphql-js#257]
When aliasing a field, the order is not preserved.

GraphQL-js implementation (not ordering well) example: http://graphql-swapi.parseapp.com/?query=%7B%0A%20%20x%3A%20film(id%3A%22RmlsbToz%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%2C%0A%20%20a%3A%20film(id%3A%22RmlsbToz%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%0A%20%20%7D%0A%7D

Graphene (using GraphQL-core python implementation) working example: http://swapi.graphene-python.org/graphiql?query=%7B%0A%20%20x%3A%20film(id%3A%22RmlsbToz%22)%20%7B%0A%20%20%20%20id%0A%20%20%7D%2C%0A%20%20a%3A%20film(id%3A%22RmlsbToz%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20title%0A%20%20%7D%0A%7D

**Comment by ptz0n** [comment]
Nice catch!

**Comment by leebyron** [comment]
Whoa crazy, thanks for the report!

**Comment by leebyron** [comment]
Hilariously enough, I believe this is a bug in the quite old JS runtime used in Parse's cloud code. As soon as I change the alias to anything other than the letter "a", the problem corrects itself. I think this is an issue with ordering of Object.keys() in older JS engines.

I'll likely replace this with a strict Map to ensure.

**Comment by leebyron** [comment]
Actually, replacing with a Map also results in issues. I'm chalking this one up to Parse specific bug.
