### ISSUE TITLE
Possible to affect node resolution plan by requesting certain fields?

### ISSUE THREAD

**Issue by totallymike** [graphql/graphql-js#259]
I'm exploring the concept of backing a GraphQL API with a Neo4j database, and it got me thinking about database queries, field resolve functions, and node resolve functions.

Say I have a `likeCount` field on a `Post` type, which pretty much is what it says.  

If my understanding is correct, the `resolve` attribute on a field is intended for when the node itself is already resolved, so one can either include the request for `likeCount` in all database queries and omit it when not wanted, or make an additional round trip to the DB when it's asked for.

We needn't get into the weeds of how to modify database queries or neo4j best practices in this thread, but is there a way to modify the original request to the database such that, when the `likeCount` field is requested, it includes the property in the original DB query, but omits it when not wanted?

I'm submitting this as an issue, because if such a concept doesn't exist, this issue could be modified into an RFC for such a concept.  Also, feel free to close with extreme prejudice if this is a dupe and my search skills have failed me.

**Comment by eyston** [comment]
The field AST's are included as part of the third argument to resolve.  A `getFieldList` method is outlined in this comment, but I can't speak to its validity:

https://github.com/graphql/graphql-js/issues/96#issuecomment-144222070

**Comment by leebyron** [comment]
This turns out to be a difficult thing to do because of the use of overlapping query fragments, however yes this data does exist today during a query. The `resolve` function associated with every field provides a collection of useful things as it's third parameter, of one which is the field AST node which you can use to determine all subfields as well.
