### ISSUE TITLE
`name` is immutably overwritten on `GraphQLError` in `locatedError`

### ISSUE THREAD

**Issue by kjvalencik** [graphql/graphql-js#2591]
The `locatedError` helper when used in `execute` converts errors to a `GraphQLError` causing them to lose their `name`. Unique `name` identifiers are valuable for application performance monitoring.

Instead, users must rely on a field in `extensions` to contain the true error code. This requires special error handling for GraphQL when working with APM solutions such as Datadog.

https://github.com/graphql/graphql-js/blob/7a327a6e2045e75c577be924694e6642d3e28e14/src/error/locatedError.js#L23-L30

**Comment by IvanGoncharov** [comment]
@kjvalencik Thanks for reporting 👍 
Can you use `originalError` for tracing?
Also, I don't think `graphql` is the only library that subclass errors so how `datadog` handling errors from other libraries?

**Comment by kjvalencik** [comment]
:man_facepalming: That's a great point. Thanks for answering so quickly!

Since the field resolvers are always defined to expect this type, this can be corrected in the datadog instrumentation by looking for the original error.

Cheers!
