### ISSUE TITLE
Deprecate isDeprecated

### ISSUE THREAD

**Issue by danielrearden** [graphql/graphql-js#2614]
The `isDeprecated` property on `GraphQLField` and `GraphQLEnumValue` needs to be deprecated. `deprecationReason` should be used directly instead to determine whether a field or enum value is deprecated. Deprecation notice needs to be added and any existing code needs to be updated to use `deprecationReason` instead.

**Comment by IvanGoncharov** [comment]
@danielrearden Forget that you can now claim issues yourself.
So feel free to self-assign if you want to work on this.
