### ISSUE TITLE
Remove bunch of disable istanbul comments for unreachable code

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2618]
In a few dozen places we have code like this:

```js
function someFunction(value: boolean) {
  if (value) {
    // ...
  } else {
    // ...
  }

  // istanbul ignore next (Not reachable. All possible values have been considered)
  invariant(false, 'Unexpected value: ' + inspect((value: empty)));
}
```

And Istanbul happily ignores `invariant` because we provide comment but at the same reports that we have uncovered branch.
Ideally, we would contribute a fix to Istanbul that makes it ignore uncovered branches if the only code that is reachable in this branch is uncovered.
Alternatively, we can write a script that removes those branches from `coverage/tests/coverage_final.json` using `@babel/parser` to parser source files.

**Comment by SumodBE** [comment]
Hi, I am new to graphQL-js and I am willing to help! let me know how can I help. Do I need to remove some comments here?

**Comment by sarathps93** [comment]
@IvanGoncharov Can I take this up?
