### ISSUE TITLE
GraphQLScalarType error on 15.1.0

### ISSUE THREAD

**Issue by gtolarc** [graphql/graphql-js#2628]
It seems that an error about custom scalar type occurs in version 15.1.0. There was no problem at 15.0.0. (with https://github.com/taion/graphql-type-json)
```
src/schema/index.ts:25:9 - error TS2322: Type 'GraphQLScalarType' is not assignable to type 'GraphQLNamedType'.
  Type 'GraphQLScalarType' is not assignable to type 'GraphQLEnumType'.

25         GraphQLJSON,
           ~~~~~~~~~~~
src/schema/index.ts:26:9 - error TS2322: Type 'GraphQLScalarType' is not assignable to type 'GraphQLNamedType'.
  Type 'GraphQLScalarType' is not assignable to type 'GraphQLEnumType'.

26         GraphQLJSONObject,
```

**Comment by IvanGoncharov** [comment]
@gtolarc Can you please provide a minimal code sample?

**Comment by gtolarc** [comment]
![스크린샷 2020-06-09 오후 7 01 07](https://user-images.githubusercontent.com/8623798/84134484-9c6c4380-aa83-11ea-9972-d614714d47c6.png)

```
import { GraphQLNonNull, GraphQLObjectType } from 'graphql';
import { GraphQLJSON } from 'graphql-type-json';

const sample = new GraphQLObjectType({
  name: 'Sample',
  fields: () => ({
    json: { type: new GraphQLNonNull(GraphQLJSON) },
  }),
});
```

**Comment by danielrearden** [comment]
@gtolarc `@types/graphql-type-json` is still using version 14.6.0 of `graphql-js`. You can fix this by either:

1. Using yarn and taking advantage of its [dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions) feature. You'd need to add a `resolutions` property of your `package.json` and do a clean reinstall of `node_modules` using `yarn install`

```
"resolutions": {
  "graphql": "^15.1.0"
},
```

2. Uninstalling `@types/graphql-type-json ` Writing your own type declaration file for `graphql-type-json`

3. Uninstalling both `graphql-type-json` and `@types/graphql-type-json` and just including the two scalars directly in your codebase (it's like 80 lines)

4. Submitting a PR to definitely typed with an update to `@types/graphql-type-json`

**Comment by gtolarc** [comment]
I solved it with the yarn resolutions method you gave me. Thanks for your advice. @danielrearden

**Comment by gtolarc** [comment]
graphql-type-json v0.3.2 has just been released, and the related type error has been fixed.
