### ISSUE TITLE
Moving Maybe is a breaking change in 15.1.0

### ISSUE THREAD

**Issue by haines** [graphql/graphql-js#2632]
https://github.com/graphql/graphql-js/pull/2621 was a breaking change for anyone consuming the `Maybe` type - e.g. [apollo-federation](https://github.com/apollographql/apollo-server/blob/cca20d96a35d0f6cf6f93fc33b592a74dc1c9aaf/packages/apollo-federation/src/composition/validate/sdl/matchingUnions.ts#L3)

Would it be possible to revert this change, or re-export `Maybe` from `ts-utils` for backwards compatibility and drop it the next major version?

Or is this supposed to be a private type and it shouldn't be consumed outside this package, in which case apollo-federation should implement its own `Maybe` type?

**Comment by haines** [comment]
Ah - just saw https://github.com/graphql/graphql-js/pull/2621#issuecomment-641927660, sorry!

**Comment by IvanGoncharov** [comment]
@haines No worries, thanks for taking time to report 👍

**Comment by haines** [comment]
Raised https://github.com/apollographql/apollo-server/pull/4230 to remove the import from apollo-federation 🙂
