### ISSUE TITLE
Empty string default values break buildClientSchema

### ISSUE THREAD

**Issue by jgillich** [graphql/graphql-js#2645]
Using `""` or even `"  "` (two spaces) as defaultValue for an argument causes `buildClientSchema` to throw  `Uncaught GraphQLError: Syntax Error: Unexpected <EOF>`. Exception is thrown here:

https://github.com/graphql/graphql-js/blob/791be1ae07457701818a5c89dca708053224e897/src/language/parser.js#L578

I'm not sure why though. Could be that the parser doesn't recognize empty strings / strings that only contain spaces as strings.

Example: https://gist.github.com/jgillich/28ebce25b663236be5d3253821f9ea9f

Ctrl+F `defaultValue: ''` and change it to `defaultValue: 'foobar'` and it suddenly works.

This issue is new in v15, before that empty strings were treated as undefined: https://github.com/graphql/graphql-js/pull/2178/commits/818575eed5f8d71686b1e846f9de237f82662135#

**Comment by IvanGoncharov** [comment]
@jgillich Thanks for taking time to report it 👍 
http://spec.graphql.org/draft/#sel-GAJbTHHDAAACDB78R
> `defaultValue` may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns null.

So it means if you have an empty string as `defaultValue` it should be encoded as `"\"\""` and not as `""`.
What server-side implementation you are using?

> This issue is new in v15, before that empty strings were treated as undefined: 818575e

It was a stereotypical JS bug since empty string implicitly convert to false.

**Comment by jgillich** [comment]
:man_facepalming: 

It's [my own Crystal server implementation](https://gitlab.com/everbase/graphql). I read that exact paragraph from the spec earlier but didn't realize what's wrong.

Thank you!
