### ISSUE TITLE
'toJSON' is declared here.

### ISSUE THREAD

**Issue by dhavaljardosh** [graphql/graphql-js#2648]
`await graphql(schema, query, new Query());`

This works good with `15.0.0` but not with `15.1.0`, and I get the following error.

```
'toJSON' is declared here.
      toJSON(): { start: number; end: number };
      ~~~~~~
        at https://cdn.pika.dev/-/graphql@v15.1.0-txyliWKfLgU2VsDvVwhF/dist=es2019,mode=types/language/ast.d.ts:36:3
```

It's the addition of `toJSON` as I looked into the source both in 15.0.0 and 15.1.0, but could someone please tell how to properly do this.

**Comment by IvanGoncharov** [comment]
@dhavaljardosh Can you please create a small repository that reproduces your problem?
Without it, there is nothing we can do to help you.

**Comment by dhavaljardosh** [comment]
@IvanGoncharov , Sure

https://github.com/dhavaljardosh/deno-gql-video

In this repo, please change a line in the `index.ts` from 
`import { graphql } from "https://cdn.pika.dev/graphql@^15.0.0";`

to

`import { graphql } from "https://cdn.pika.dev/graphql@^15.1.0";`

15.0.0 will work fine, but not, 15.1.0.

**Comment by IvanGoncharov** [comment]
We not yet support deno, but we working on it.
Progress is tracked in https://github.com/graphql/graphql-js/issues/2566
