### ISSUE TITLE
Switch to using native ES6 Map as much as possible

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2664]
We need to switch as much as possible `ObjMap` to `Map` to prevent bugs like this:
```js
const { buildSchema, graphqlSync } = require('./npmDist');

const schema = buildSchema(`type Query { foo: String }`);
const query = `
  query ($__proto__: Boolean!) {
    __typename
    __typename @skip(if: $__proto__)
  }
`;

const vars = JSON.parse('{ "__proto__": true }');
try {
  console.log(graphqlSync(schema, query, null, null, vars));
} catch (e) {
  console.log(e);
}
```

**Comment by markokr** [comment]
AFAIK only Object.create(null) gives proto-less instance, Map objects will have proto by default...

**Comment by IvanGoncharov** [comment]
@markokr For ES6 Map we would use `get`/`set` methods so Map object:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by markokr** [comment]
Aha, makes sense now.

**Comment by PiDelport** [comment]
Using maps instead of `Object.create(null)` for results would also help avoid the problems described in #484 / #504.
