### ISSUE TITLE
Duplicate module check on Windows should ignore casing of drive letter

### ISSUE THREAD

**Issue by jeffrson** [graphql/graphql-js#2673]
I'm launching my project from VSCode, where the launch configuration makes use of ${workspaceFolder}. Unfortunately it is expanded to an absolute path with a lower case drive letter. 

This leads to the famous
`Duplicate "graphql" modules cannot be used at the same time...`

I can confirm this problem manually, when I start the project with a lower case 'c' (for example). However, when I put the upper case 'C' there it works.

It would help a lot, if the casing of the drive letter is ignored on Windows when checking the instances.

**Comment by IvanGoncharov** [comment]
@jeffrson We don't check paths we just check that you have two different instances of `graphql` package in your code, you can check it yourself here: https://github.com/graphql/graphql-js/blob/master/src/jsutils/instanceOf.js
So you have an issue in some other place (maybe Node's `require`) that results in duplication.
It would be great if you post the result of your investigation here so it would help other developers with similar issues.
