### ISSUE TITLE
import GraphQLSomeObject from 'graphql' throws an error in node

### ISSUE THREAD

**Issue by lenneis** [graphql/graphql-js#2682]
Hi,

a simple import statement in node like 

```
import { GraphQLObjectType } from 'graphql';
```

results in a syntax error:

```
SyntaxError: The requested module 'graphql' does not provide an export named 'GraphQLObjectType'
```

going to the right index.mjs file directly works: 

```
import { GraphQLObjectType } from 'graphql/index.mjs';
```

This is in node 13.14, without using the esm module to run the code. It is probably because conditional exports for commonJS/ES6 modules are needed.

**Comment by IvanGoncharov** [comment]
@lenneis Can you create minimal repository that reproduces that?

**Comment by lenneis** [comment]
Done, at https://github.com/lenneis/graphql-es6-bug.git. I have included the graphql module in the repository. Run with "node index.mjs".

**Comment by lenneis** [comment]
I just tested with node 14.5 as well. The error message changes to this:

```
import { GraphQLObjectType } from 'graphql';
         ^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'graphql' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

Why would an import statement in an .mjs file expect a CommonJS module?

**Comment by karansinghgit** [comment]
anyone have a solution for this?

**Comment by mike-marcacci** [comment]
I haven't run across this issue, but I believe it's just a node limitation and _not_ anything specific to GraphQL.

As the error message suggests, try importing the CommonJS module object as its default import instead of using named imports:

```js
import graphql from "graphql";
const { GraphQLObjectType } = graphql;
```

**Comment by Mehak-Mehta** [comment]
I think you could use : 
const {GraphQLObjectType } =  require('graphql'); 
Instead of :
import { GraphQLObjectType } from 'graphql';

I might be wrong as I am new to graphql.

**Comment by yaacovCR** [comment]
Closing this old issue, feel free to reopen if recurs in current node versions
