### ISSUE TITLE
14.7.0 was published with @latest tag

### ISSUE THREAD

**Issue by simonhaenisch** [graphql/graphql-js#2694]
There was a feature that was backported from v15 into v14 and released as 14.7, but now `graphql@latest` points to `14.7.0` instead of `15.3.0`.

**Comment by IvanGoncharov** [comment]
@simonhaenisch Thanks for reporting 👍 
Fixed to point to `15.3.0`.
Will keep this open to write some wrapper around `npm publish` that prevents this problem in future.

**Comment by Blazingkevin** [comment]
@IvanGoncharov,  with a little guidance, I will like to work on the wrapper. (It's my first attempt to contribute).
