### ISSUE TITLE
Promise support in the resolve() function

### ISSUE THREAD

**Issue by rricard** [graphql/graphql-js#27]
I started to work on this graphql implementation in order to integrate it at least partially in our systems. We would like to stay very close to this implementation as much as we can as it may become the first community-supported implementation.

A feature we would need is the ability to wait Promise results when resolving. It doesn't seem that the current implementation support it.

I would like to discuss with you if you are open to support the addition of Promise responses. In this case, I can handle the Pull-request.

So if I were to implement this, I would do it like this:

1. Write tests with promises (either mix promises and direct calls in the current test schemas or create a completely new test schema with Promises)
2. When resolving the query, wait for the promises when a resolve function returns a Promise. At the end, this doesn't need any API change since the result goes to a final promise when querying anyway.

We can discuss all of that if you wish of course!

**Comment by freiksenet** [comment]
It should be possible to return promises in `resolve`. Can you provide code samples on what doesn't work?

**Comment by rricard** [comment]
Oh great. Didn't got it either from the code or the examples but I'll
definitely take a look. I could write some tests on this. You can close
that,  thanks!

**Comment by leebyron** [comment]
Yep! we support returning Promises or Arrays of Promises.
