### ISSUE TITLE
TypeInfo.getParentType() performs differently from expected/desired

### ISSUE THREAD

**Issue by sg2nq** [graphql/graphql-js#2734]
Given a mutation like:
```
mutation mutName( $var: UUID! ) {
  upperLabel(
    input: {
      label: {
        id: $var
      }
    }
  ) {
    label {
      id
    }
  }
}
```

(I think) You would expect the parentInputType for `ObjectField` `id` to be the InputType of `ObjectField` `label`. However, there are nodes between `label` and `id` that fill up the `_inputTypeStack`. Let me know if this is not actually an issue and just a misreading of what parentInputType should be

**Comment by isabelleingato** [comment]
New here! I'd like to look into this. Would you mind sharing your schema and what you're seeing in the `_inputTypeStack`?

I think your expectation is correct based on https://spec.graphql.org/June2018/#sec-Input-Object-Field-Names and what https://github.com/graphql/graphql-js/blob/main/src/utilities/TypeInfo.js#L231 is doing.

I tried adding the below "test" (adapted from https://graphql.org/graphql-js/mutations-and-input-types/ and your example) to https://github.com/graphql/graphql-js/blob/main/src/utilities/__tests__/TypeInfo-test.js to try this out and I seem to get the expected `_inputTypeStack`.

Feel free to let me know if I'm misreading the issue you're describing though.

```
it('parent input type should be correct', () => {
    const schema = buildSchema(`
    input MessageInput {
      content: String
      author: String
    }
  
    input l {
      d: MessageInput
    }
    
    type Message {
      id: ID!
      content: String
      author: String
    }

  input i {
    label: l
  }
 
  type Query {
    getMessage(id: ID!): Message
  }
 
  type Mutation {
    createMessage(i: i): Message
    updateMessage(id: ID!, i: MessageInput): Message
  }
    `);
    const ast = parse(`
    mutation CreateMessage($input: MessageInput) {
      createMessage(i: { label: { d: $input } }) {
        content
      }
    }
    `);
    const typeInfo = new TypeInfo(schema);
    visit(
      ast,
      visitWithTypeInfo(typeInfo, {
        enter(node) {
          const parentType = typeInfo.getParentType();
          const type = typeInfo.getType();
          const inputType = typeInfo.getInputType();
          const parentInputType = typeInfo.getParentInputType();
          console.log(node);
          console.log('Input type', inputType);
          console.log('Parent input type', parentInputType);
          console.log(typeInfo._inputTypeStack);
        },
        leave(node) {
           console.log(node);
        },
      }),
    );
  });
```

**Comment by yaacovCR** [comment]
Closing this stale issue, seemingly addressed above. Please reopen as necessary.
