### ISSUE TITLE
Async `parseValue` resolver does not provide promise resolution value

### ISSUE THREAD

**Issue by newhouse** [graphql/graphql-js#2758]
In `graphql` `v15.3` we've recently re-written our resolver for a custom type to be something like this:
```js
new GraphQLScalarType({
  name: 'MyThing',
  parseValue: async (value) => {
    return {foo: 'bar'}
  }
  ...
})
```

In code that handles a mutation where a `MyThing` is passed, it's coming out as an unresolved promise, like so:
```js
// myThing was defined as type MyThing

console.log(myThing) // => Promise { { foo: 'bar' } } }

console.log(await myThing) // => { foo: 'bar' }
```

I'd like to not have to `await myThing` every time I want to use it, and the following comment suggests that the resolution values of async/promise-returning `parseValue` will be what the user gets to work with:
> If a Promise is returned from a resolver, the executor will wait on that value to resolve before continuing.

_Originally posted by @leebyron in https://github.com/graphql/graphql-js/issues/820#issuecomment-302441789_

Am I misunderstanding this comment? Or is this not how it's supposed to work? Or is it a bug?

**Comment by danielrearden** [comment]
The comment you linked concerns resolving field values. Scalars do not have resolvers. They just have methods that parse values when they are submitted as inputs and serialize values when they are returned as outputs. These methods should not be asynchronous as discussed [here](https://github.com/graphql/graphql-js/issues/2663).

**Comment by newhouse** [comment]
Somehow I missed that issue when searching before posting...it's very helpful. Thank you!
