### ISSUE TITLE
Support thunks on a field itself?

### ISSUE THREAD

**Issue by ryancole** [graphql/graphql-js#277]
Currently, the entire `fields` property supports a thunk. Would it be worthwhile to also support thunks on a per-field basis, so code like the following would work ...

``` js
let destinationTeam = () => ({
  type: new GraphQLNonNull(TeamType),
  description: "The team to which the invite is extended.",
  resolve: source => Sql.Team.getById(source.destination_team)
});

export default new GraphQLObjectType({
  name: "ScrimInvite",
  fields: {
    destinationTeam
  }
});
```

This might allow more flexibility in code formatting and cleanliness on really unwieldy types.

**Comment by leebyron** [comment]
Good suggestion!

**Comment by ryancole** [comment]
I had been trying to improve the cleanliness of my code, particularly relating to larger `resolve` functions, and tried out this sort of approach. I have a helper function I'm using that allows the use thunked field definitions, currently. I figured maybe it'd be something that could easily be baked in.

**Comment by IvanGoncharov** [comment]
Closing as it tracked in #2273 (big thanks to @caseywebdev for this PR) that we can hopefully merge after we switch to TS.
