### ISSUE TITLE
Nested union types

### ISSUE THREAD

**Issue by gyzerok** [graphql/graphql-js#278]
How to achieve creating nested UnionTypes or extend some union type? I need to add one more type to UnionType. The problem is I don't like to add it to the UnionType itself since it and new type are different from Domain perspective.

**Comment by gyzerok** [comment]
What I'm talking about is https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L681

**Comment by leebyron** [comment]
We may make this more lenient in the future, for now you can achieve this by doing something like:

```js
const MyLargeUnion = new GraphQLUnionType ({
  types: MySmallUnion.getPossibleTypes().concat([ AnotherType, SomeOtherType ]);
})
```

I hope this works out for you!
