### ISSUE TITLE
graphql-js WG call

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2787]
As suggested by @dotansimha @leebyron let's start doing graphql-js calls to discuss problems/ideas/plans around `graphql-js` and also to better distribute work between volunteers.
How about September 16th 7PM UTC?

**Comment by IvanGoncharov** [comment]
I created a special https://github.com/graphql/graphql-js/tree/WokringGroup branch for agenda and notes.
If anyone wants to help please copy the structures and template files from https://github.com/graphql/graphql-wg and create PR against this branch.

**Comment by dotansimha** [comment]
@IvanGoncharov any chance we can do it at the same hours as the WG meetings?

**Comment by IvanGoncharov** [comment]
@dotansimha Works for me 🤝 
Also, let's wait for others to comment on what date/time would work for them.

**Comment by robrichard** [comment]
Either time works for me. Thank you for organizing!

**Comment by Urigo** [comment]
making it the hours of the working group also works for me.

Thank you for organizing and see you there!

**Comment by IvanGoncharov** [comment]
@dotansimha @robrichard @Urigo So as agreed let's have a call tomorrow: Sep 16th at 4 PM UTC.
I will post the Zoom link tomorrow.

**Comment by IvanGoncharov** [comment]
@dotansimha @robrichard @Urigo or anyone else who want to join.
Zoom link: https://zoom.us/j/94231288881?pwd=elZzREpLRGorcitTeXhFVnAzSUhrQT09
Password: graphqljs

**Comment by IvanGoncharov** [comment]
Video is live on YouTube: https://www.youtube.com/watch?v=NkpZJyCe1HA
If someone wants to help it would be great to extract action items.
So we can check them on the next call.

@Urigo As discussed during the call I gave you `Triage` role (please check your inbox) so you can create project board and sort issues in different categories.

**Comment by Urigo** [comment]
Thank you @IvanGoncharov !
mmm it looks like I can tag issues, but I don't think I can create or manage a project...

**Comment by Urigo** [comment]
it looks like you need `maintain` or `admin` in order to work on `projects`: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

**Comment by Urigo** [comment]
For now, here is the list of tasks from the meeting (timing is in respect for the meeting's date - Sep 16th):

- [ ] @IvanGoncharov to create until tomorrow an issue of him vision of Needed Characteristics for maintainers
- [ ] @IvanGoncharov to write a contribution guide - first iteration in a week from today
- [ ] @Urigo to create a prioritized public roadmap issue (@IvanGoncharov to give Uri triaging issue permissions to try using Github projects), Including classifying improvements and things we already agreed on
- [ ] @IvanGoncharov to clean the maintainers list on Github (has 60 old contributors from Facebook)
- [ ] @IvanGoncharov to schedule the next graphql-js working group meeting
- [ ] @IvanGoncharov to promote Marcelo in triaging permissions role
- [ ] @IvanGoncharov to create detailed separate issues for the Typescript migration so that contributors could follow and help

**Comment by IvanGoncharov** [comment]
> Also, we should schedule it recurrently, maybe every certain weekday once a month like the GraphQL WG?

@Urigo How about we continue to do it on the 3rd Wednesday of every month?
Since we already have other WG on the first and last week of every month.
So it means the next one would be Oct,21 4 PM UTC.

> As for the main upcoming task - Typescript Migration, could you please write a detailed comment about how you see the next phases, responding to the comments here?
> Also, could you write a short update about the rest of the tasks above from the WG, so I'll know where to place them in the project?

I will have some time next week and will push for finishing these action items.

**Comment by IvanGoncharov** [comment]
@dotansimha @robrichard @Urigo @onhate @mike-marcacci @saihaj
Sorry guys, I didn't finish my action items yet.
And without them, I feel like we will just repeat stuff that we already discussed last time.
How about postponing the call for one week to Oct, 28 4 PM UTC?
It will give me enough time to finish all action items and we can discuss the resulting documents during the call.
Also, the last Wednesday of the month is easier to remember and became available since we switched "GraphQL over HTTP" WG to async communication.


We can also prepare the official agenda this time.
If anyone wants to help please copy the structures and template files from https://github.com/graphql/graphql-wg and create PR against https://github.com/graphql/graphql-js-wg

**Comment by Urigo** [comment]
@IvanGoncharov that sounds great to me!

Also I took on myself to create the structures and templates from the regular working group and created the PR here:
https://github.com/graphql/graphql-js-wg/pull/1

Also I've created issues for all the action items here: https://github.com/graphql/graphql-js-wg/issues so we could track it all on our next meeting.

Looking forward for it!

**Comment by saihaj** [comment]
I think this issue can be closed now.
