### ISSUE TITLE
Differences between Kind and Type Kind?

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#279]
walking through an AST, I noticed types have different string constants than kinds.
Take a list for example:
kind: https://github.com/graphql/graphql-js/blob/master/src/language/kinds.js#L48
typeKind: https://github.com/graphql/graphql-js/blob/master/src/type/introspection.js#L265

What's the difference between these two? Would it be possible to merge them?

**Comment by noscripter** [comment]
My two cents is that kind is for introspection, while KindType is for definition. I'd also be interested to hear more authoritative answers.

**Comment by leebyron** [comment]
The first link is relating to kinds of AST nodes as they are parsed from the graphql language. The second link is relating to the types of graphql types that can be represented in a graphql type system. There isn't really a 1:1 correspondence between these concepts, and I don't believe there needs to be either. Language parsing and runtime type systems will just have different concepts and I think that's fine.

**Comment by leebyron** [comment]
Perhaps it would be clearer if we called the first "ASTKind" to make the distinction between the two clearer?

**Comment by mattkrick** [comment]
> Language parsing and runtime type systems

Thanks @leebyron, that helps! Could I say TypeKinds are for walking parsed query strings & Kinds are for parsing & schemas?
I think ASTKind would actually be more confusing, since if you `parse` a query string, the output is technically an AST, but the visitor requires using `TypeKind` consts.

**Comment by leebyron** [comment]
Almost. TypeKinds doesn't have anything to do with parsing. It just represents runtime types in the schema. Kinds are for parsing and AST operations. 

And I would certainly make sure that "ASTKind" was the name of the thing you used to deal with the output of "parse", otherwise I agree it would be confusing.

**Comment by leebyron** [comment]
Is there somewhere you're seeing where TypeKind is being used to walk a parsed query string? That would probably be a mistake

**Comment by mattkrick** [comment]
Nope, source code is clean, while writing a visitor I just noticed the introspected query was using different constants than I was expecting and couldn't figure out how the concepts of `ListValue` and `LIST` were fundamentally different. Seeing the line between runtime & parsing makes sense though. Thanks!
