### ISSUE TITLE
Don't swallow all errors in graphql function

### ISSUE THREAD

**Issue by freiksenet** [graphql/graphql-js#28]
There seems to be no way to get errors out of `graphql` function and one only gets error title, which can be the dreaded `undefined is not a function` deep inside schema or resolve. Would be nice if there'd be a flag to let errors pass through from `graphql` function, when they are not validation errors. I'd be willing to implement it if this change makes sense.

Thanks!

**Comment by madjam002** [comment]
Yeah this would be useful. Maybe a dev flag which could be passed to the `graphql` function during dev which exposes stack traces as well as error messages?

**Comment by leebyron** [comment]
Yeah, I feel this pain as well. I have a broader error handling refactor I need to do that should help this be less painful

**Comment by trobertsonsf** [comment]
:+1: Really hard to debug ATM.

**Comment by johanatan** [comment]
+1 on this.

**Comment by payneio** [comment]
This is killing me.

**Comment by johanatan** [comment]
in `error/formatError.js` I've added the line:

        stack: error.stack,

to the JSON returned and it has helped tremendously.

**Comment by rexxars** [comment]
+1 for this

Thanks for the tip, @johanatan! Lifesaver!

**Comment by obimod** [comment]
+1 good call johanastan

**Comment by mrjackdavis** [comment]
Now that #118 has been merged; what's the next step forward here? graphql/express-graphql#4 is closed but to my knowledge this issue is not resolved. How can we help?

**Comment by brokentone** [comment]
+1

**Comment by jeromecovington** [comment]
Has anybody patched this with https://github.com/graphql/graphql-js/issues/28#issuecomment-128847828 via @johanatan?

**Comment by vinerz** [comment]
+1, also, @johanatan, thanks a lot. I've already made a statue from you

**Comment by zuhair-naqvi** [comment]
+1

**Comment by tristanz** [comment]
This seems to be fixed here: https://github.com/graphql/express-graphql/pull/45/files

```
  graphiql: true,
  formatError: (error) => ({
    message: error.message,
    details: config.isProduction ? null : error.stack
  })
```

**Comment by leebyron** [comment]
Closing this since graphql-js no longer formats Errors anymore (the `errors` field on the output is a list of the original `Error` instances now).

Formatting is still recommended when using over a web endpoint, and `express-graphql` does the simple thing by default and allows for customization.

**Comment by Luchillo** [comment]
Using formatError as well, is there a way to pass the same error handler when using in testing? (in tests you most of the time query directly using the graphql object to execute the query with the schema.

```ts
let resp = (await graphql(Schema, query, {}, context));
```

**Comment by JanPeter** [comment]
I have currently the same problem. I'm not quite sure how to test my custom error messages. Or is it better to test the whole express-graphql endpoint for the error messages?

**Comment by bkoltai** [comment]
Agreed, how do we get a stack trace for the errors reported from using the `graphql` function directly, which I'm also doing in tests and get errors from my code with just the message and no trace.

**Comment by alfaproject** [comment]
Just stumbled upon this issue and not quite sure why is it closed. I only get the error title when invoking with `graphql` or `execute`...

**Comment by IvanGoncharov** [comment]
@bkoltai @alfaproject You can access original errors and their stack traces, like that:
```js
const result = await execute(/* ... */);
if (result.errors) {
  result.errors.forEach(err => console.log(err.originalError));
  // ...
}
```
