### ISSUE TITLE
Maybe<Error> Exposed in GraphQLError despite Maybe<T> being moved to jsutils

### ISSUE THREAD

**Issue by ctopherhague** [graphql/graphql-js#2808]
[Pull 2621](https://github.com/graphql/graphql-js/pull/2621#issuecomment-641927660) Removed Maybe<T> from tsutils export, however it still remains in the def for GraphQLError.originalError.

This broke our use case where we have leverage [customFormatErrorFn](https://github.com/graphql/express-graphql/blob/master/src/index.ts#L103) in express, in which we : 

``` Typescript
export function errorHandler(error?: Error) {
	//
}

errorHandler(error.originalError); 
```

Results in:
``` 
Argument of type 'Maybe<Error>' is not assignable to parameter of type 'Error | undefined'.
  Type 'null' is not assignable to type 'Error | undefined'.ts(2345)
```

We could go the route of the [Apollo Fix](https://github.com/apollographql/apollo-server/pull/4230) and re-define maybe in our own package, but if this is doable, would like to simply not expose it in `GraphQLError.d.ts`

Proposed Fix: https://github.com/graphql/graphql-js/pull/2807

**Comment by IvanGoncharov** [comment]
@ctopherhague Thanks for reporting 👍 
I answered it here: https://github.com/graphql/graphql-js/pull/2807#issuecomment-699541733
