### ISSUE TITLE
isvalidjsvalue was removed, but documentation is not updated

### ISSUE THREAD

**Issue by Andrei-Stepanov** [graphql/graphql-js#2814]
Good day.

Documentation: https://graphql.org/graphql-js/utilities/#isvalidjsvalue
The function `isValidJSValue` was removed in : https://github.com/graphql/graphql-js/pull/2126

Please update documentation. Thank you.

Please help me to understand how do I verify if value (part of data) on server side is consistent with schema, before I send it to client?

Thank you.

**Comment by tanman-** [comment]
Hi @Andrei-Stepanov 

Please use `coerceInputValue` instead.

I agree that the docs need to be updated.

I hope this helps.

Have a nice day.

**Comment by IvanGoncharov** [comment]
@tanman- Big thanks for answering this issue 👍

@tanman- We plan to generate our API docs from source code after TS migration, so it will always be up-to-date.

**Comment by nickwesselman** [comment]
This is still inaccurate 😞

**Comment by ris314** [comment]
> This is still inaccurate
Still true

**Comment by skilgoreT** [comment]
Still true
