### ISSUE TITLE
Printer swallows trailing and leading spaces in descriptions

### ISSUE THREAD

**Issue by pcarrier** [graphql/graphql-js#2817]
The description ` `, that could be printed as `" "`, gets printed as `""" """`, which is `""` because:
> * While the first item line in lines contains only WhiteSpace: Remove the first item from lines.
> * While the last item line in lines contains only WhiteSpace: Remove the last item from lines

-- https://spec.graphql.org/June2018/#BlockStringValue()

Observable with:

```
import { printSchema, buildSchema, parse } from 'graphql';

const once = printSchema(buildSchema(`" " type A { id:ID! }`));
const again = printSchema(buildSchema(once));

console.log(once);
console.log(again);
```

outputting:
```
""" """
type A {
  id: ID!
}

""""""
type A {
  id: ID!
}
```

**Comment by IvanGoncharov** [comment]
@pcarrier Thanks for taking the time to report it 👍 
It's a known issue described in #2577 so closing this one.
I reported #2577 as theoretical so it was a low priority, how critical is this issue for you?

**Comment by pcarrier** [comment]
@IvanGoncharov Yeah I don't know how to describe how "critical" it is, it degrades documents?
