### ISSUE TITLE
Resolvers are ignored

### ISSUE THREAD

**Issue by tillyboy** [graphql/graphql-js#2823]
I have this very frustrating issue, where GraphQL is basically ignoring my defined resolvers. I suppose as I defined a query:

```graphql
type Query {
    foobar(foo: String!, bar: String!): string!
}
```
and the corresponding resolver:

```typescript
foobar: ({ foo, bar }: { foo: string; bar: string }): string => {
    console.log("got request");
    return `${foo}::${bar}`;
}
```

The resolver is part of an object passed to graphql using the `graphqlHTTP` function from `express-graphql`, and I am not sure where this issue actually occurs. When trying the query with graqhiql, I get `"Cannot return null for non-nullable field Query.foobar."`. Looking at the server output, there is no `"got request"`. I feel like there is no way of debugging this, as

1. The stacktrace doesn't tell me where it tried to find a 'foobar' function and failed (which I assume is what happened). Narrowing down the issue from the server seems to be almost impossible.
2. Going from making a minimum example with breaking behaviour I cannot currently reproduce this (will link it as soon as I have it).
3. The error showed up in an otherwise working project when I actually fixed another function.

Any help is appreciated. I don't feel like this belongs on SO as it strongly seems to me that there is some bug in 'resolving the resolvers'.

**Comment by IvanGoncharov** [comment]
> foobar(foo: String!, bar: String!): string!

Maybe this will help: `string` => `String`

**Comment by IvanGoncharov** [comment]
Can you please show what you are passing to `graphqlHTTP`?

**Comment by IvanGoncharov** [comment]
> I feel like there is no way of debugging this, as

You can try this approach https://github.com/graphql/express-graphql#debugging-tips

**Comment by tillyboy** [comment]
> Can you please show what you are passing to `graphqlHTTP`?

```js
import User from "./user";

const app = express();
const userAPI = graphqlHTTP({
    schema: readGQLSchema("user"), // shorthand for buildSchema(readFileSync(schemaFileName).toString())
    rootValue: User,
    graphiql: true,
    customFormatErrorFn: (error) => {
        console.log(error.toString());
        return error;
    },
});

app.use("/user", api);
```

> You can try this approach https://github.com/graphql/express-graphql#debugging-tips

I did. However, I found that it's actually a TypeScript 'Error' (or at least inconvenience) that I ran into:

```typescript
interface User { ... };

export const User = {
  ...
  foobar: (...) => { ... },
  ...
};
export default User;
```

Still, it might have been really helpful if there was some `object rootValue has no member foobar` from GraphQL ;)
