### ISSUE TITLE
issue with last release 15.4.0

### ISSUE THREAD

**Issue by elcssmouhsine** [graphql/graphql-js#2830]
when i upgraded to latest release 15.4.0 

i get this error

Unable to resolve module `../polyfills/flatMap` from `node_modules/graphql/type/validate.js`: ../polyfills/flatMap could not be found within the project.

**Comment by dagamo** [comment]
Same error, any solution ?

**Comment by IvanGoncharov** [comment]
@elcssmouhsine @dagamo Can you please check that `node_module/graphql/package.json` has `15.4.0` version?
In 15.4.0 `type/validate.js` doesn't import `flatMap` so it looks like you did a partial update.
Can you please remove `node_modules` and install it from scratch?

**Comment by mjgasior** [comment]
I am trying to rebuild this in Expo (React Native) and even after deleting the node_modlues I keep getting the same error for this package version. I had to return to 15.1.0.

**Comment by charlex** [comment]
I've had this in my yarn project's package.json to avoid 15.4.0 problems:

```
deps: {},
...
devDeps: {},
...
 "resolutions": {
    "graphql": "15.3.0"
  },
...
```

**Comment by IvanGoncharov** [comment]
@elcssmouhsine @dagamo @mjgasior @charlex Can't reproduce this issue, it looks like it's something React Native specific, can you please confirm?
Can you please create a sample repo so I can debug this issue?

**Comment by louisholley** [comment]
fwiw I was experiencing a similar issue with Expo/React Native but my error message was `Unable to resolve "./rules/FieldsOnCorrectType" from "node_modules/graphql/validation/index.js"`. i tried 15.3.0 and was getting the same thing, but after updating expo-cli, removing `node_modules`, running `npm i` then `expo r -c` everything seems to be working again. this sort of thing seems to happen a lot with expo

**Comment by IvanGoncharov** [comment]
@louisholley Thanks for reporting it!
Now everything makes sense.

**Comment by chaiiplss** [comment]
I am still getting this type of error even after removing `node_modules` and cleaning the cache.

**Error**: Unable to resolve module `./rules/custom/NoDeprecatedCustomRule` from `node_modules/graphql/validation/index.js`

Any help would be appreciated!

**Comment by BerMoh** [comment]
changing the graphql version ^16.0.1 from to 15.4.0 make my nodejs work! 
The error I've got was: 
node_modules/graphql/utilities/extendSchema.js:597
    return nodes.flatMap(
                 ^
TypeError: nodes.flatMap is not a function

Thank you @IvanGoncharov for your help.
