### ISSUE TITLE
parameter extensions not being passed in GraphQLError constructor

### ISSUE THREAD

**Issue by kashiif** [graphql/graphql-js#2833]
Our code is throwing a `GraphQLError` exception with extensions set to `{ code: 'ValidationError' }`. However, the error always shows up with `extensions.code` = 'INTERNAL_SERVER_ERROR`.

After some debugging, I found that [this constructor call](https://github.com/graphql/graphql-js/blob/master/src/execution/values.js#L135-L142) is not passing the last argument `extensions`.

I don't know if this is by design or just a mistake. I will be happy to send a Pull Request for the fix once someone confirms it is a bug.

**Comment by IvanGoncharov** [comment]
@kashiif It's intentional since `extensions` should be extracted from `originalError` here:
https://github.com/graphql/graphql-js/blob/a5b95f0c2379916afed77ae21e9321ac19068183/src/error/GraphQLError.js#L131

Can you please ensure that your error that you throwing is passed into `GraphQLError` constructor?

**Comment by kashiif** [comment]
Thanks for the info!

**Comment by TroutZen** [comment]
@IvanGoncharov - I am running into a similar situation where the errors thrown in the resolver and handled in graphql layer are not getting their extensions mapped into the GraphQLError. I noticed lots of instances in `graphql-js` codebase where we are not explicitly passing `null` in for the extensions, so extensions would be undefined. Yet this [check](https://github.com/graphql/graphql-js/blob/a5b95f0c2379916afed77ae21e9321ac19068183/src/error/GraphQLError.js#L130) is explicitly checking if extensions are null before mapping extensions from the originalError onto the `GraphlQLError`. Should this conditional be changed to:

```
if ((_extensions === null || _extenions === undefined) && originalError != null) {}
```

**Comment by yaacovCR** [comment]
As I see it, the check has a double equals which should match null as well as undefined….
