### ISSUE TITLE
Execution & Error Logging

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#284]
We need the ability to provide a logger to the GraphQL executor which can be notified about events as the executor operates. This will provide the ability to log performance and error behavior in a systematic way.

**Comment by tuananhtd** [comment]
This would be great!
I'm finding the efficient way to log the error and hide the detailed message from user. I'm wondering what are some approaches for this right now? 
I found this [https://github.com/kadirahq/graphql-errors](url) but honestly the start number make me not so confident using it.

**Comment by sibelius** [comment]
@tuananhtd link is broken

https://github.com/kadirahq/graphql-errors

**Comment by stubailo** [comment]
Related: https://github.com/graphql/graphql-js/pull/402

**Comment by vladar** [comment]
Any plans on implementing this in the near future?

**Comment by IvanGoncharov** [comment]
Closing in favor of introducing general purpose middlewares (#1516)
