### ISSUE TITLE
16.0.0 Release plan

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#2860]
# Goals

1. Convert source code to idiomatic TypeScript
1. Remove Flow-specific workarounds and pre-ES6 JS artifacts
1. Support Deno
1. Support ESM
1. Switch `master` to `main`.

# Planned breaking changes

1. Legacy SDL syntax (deprecated 2year ago) and other deprecated APIs and flags 
1. Drop native IE support by removing built-in polyfills and switching the output to ES6. It would be still possible to support IE with `core-js` + `babel`.
1. Drop TS before 3.7 since we need to support recursive types.
1. Maybe we will have some unexpected breaking changes to TS types due to migration

# Post 16.0.0 goals

1. Convert test suite to Jest
2. Experiment with TS types to provide better typings for resolvers

P.S. We need to target `04/31/2021` for `17.0.0` release at that point we need to do a breaking release anyway to drop Node v10.

# Steps

- [x] 1. Branch out `15.x.x` release line and release `15.5.0` (Jan 8th)
- [x] 2. Switch `master` to `main` and update scripts & CI 
- [x] 3. Move commits from https://github.com/graphql/graphql-js/tree/16.x.x to `main`
- [x] 4. Remove last [few polyfills](https://github.com/graphql/graphql-js/tree/f2f0ddecff79693a0a52d7e62772840a8aa1c50a/src/polyfills)
- [x] 4. Release `16.0.0-alpha.1` with all expected breaking changes but still from Flow sources (~~Jan 12th~~)
- [x] 5. Rebase #2828 and merge it (no squash, keep separate commits) (~~Jan 15th~~)
- [x] 6. Fix tests, CI, and release scripts but disable `tsc` and TS-specific ESLint checks (~~Jan 18th~~)
- [x] 7. Mark `tsc` errors with `@ts-ignore` and fix them in separate PRs by volunteers 
- [x] 8. Enable TS-specific ESLint rules in separate PRs by volunteers
- [x] 9. Release new `16.0.0-alpha.3` and gather feedback (finish until Feb WG)
- [ ] 10. Work on ESM and Deno support in parallel
- [x] 11. Release `16.0.0-rc.1` and gather feedback
- [ ] 12. Generate basic docs with `tsdoc`
- [x] 13. Release `16.0.0` 🎉
- [x] 14. Wait couple weeks and gather feedback.
- [ ] 15. Switch main to the `17.0.0-alpha.0` branch and have a setup that will automatically release package after every merge.
- [ ] 16. Start accepting breaking/experimental PRs for `17.0.0`.

# How I can help?

- Review #2828 with basic TS conversion. It's split into multiple commits that are easy to review: https://github.com/graphql/graphql-js/pull/2828/commits
- Wait for #2828 to be merged and help with latter steps.

**Comment by dotansimha** [comment]
> * Convert source code to idiomatic TypeScript

Just adding my previous WIP PRs for this:
- Migrate all tests to TS: https://github.com/graphql/graphql-js/pull/2609
- Added missing `d.ts` files: https://github.com/graphql/graphql-js/pull/2616 
- Initial WIP for ESLint and TS: https://github.com/graphql/graphql-js/pull/2634

**Comment by Urigo** [comment]
Referencing the original Road To TS issue for visibility: https://github.com/graphql/graphql-js/issues/2104

**Comment by kamilkisiela** [comment]
@IvanGoncharov How the status of TS migration? On GraphQL-JS WG we talked about creating a branch for me and @saihaj so we could join forces.

**Comment by IvanGoncharov** [comment]
@kamilkisiela Sorry for the delay, was moving our company to a new office 🤯 
Not I'm back to OSS, working on merging PRs and releasing `16.0.0-alpha.1`

**Comment by saihaj** [comment]
> Convert test suite to Jest

Thoughts on using [`ts-jest`](https://kulshekhar.github.io/ts-jest/)? Ideally `src` directory will be compiled with `tsc` and maybe we can remove babel completely. Something to try out after 16.0.0 is released.

**Comment by kamilkisiela** [comment]
@IvanGoncharov any updates? I would love to push TS forward. Maybe @saihaj could rebase on `16.x.x` already and I could sync with him.

**Comment by saihaj** [comment]
@kamilkisiela me and @IvanGoncharov worked on rebasing my branch yesterday and as we discussed in WG my branch will be moved hopefully by tomorrow to this repo if all goes well today.

**Comment by glasser** [comment]
Is the `asynciterable` branch currently likely to land in v16?

**Comment by acao** [comment]
Is https://github.com/graphql/graphql-js/pull/2839 to be included in this effort?

**Comment by robrichard** [comment]
@acao I believe the plan is for `defer-stream` & `asynciterable` to be incorporated into `main` once it starts targeting 17.0.0-alpha.x

**Comment by khanakia** [comment]
I do not see any DENO package listed on https://deno.land/x/

**Comment by saihaj** [comment]
@khanakia we need to test Deno support. You can try deno branch in this repo and see if it works
