### ISSUE TITLE
Printer assumes anonymous operations are queries. 

### ISSUE THREAD

**Issue by BobertForever** [graphql/graphql-js#288]
After opening graphql/graphiql#90, it was found by @asiandrummer that the printer assumes all unnamed operations are queries and removes the operation. Via this assumption, unnamed mutations get incorrectly printed. For example:
```
mutation {
  doSomething {
    [...]
  } ,
}
```
gets transformed to:
```
{
  doSomething {
    [...]
  } ,
}
```
Which will fail because doSomething is a mutation and not a query.

[This](https://github.com/graphql/graphql-js/blob/master/src/language/printer.js#L34) appears to be the offending line.

**Comment by leebyron** [comment]
Thanks for the report, this has now been fixed in a patch release!
