### ISSUE TITLE
Extra nesting of errors in context function

### ISSUE THREAD

**Issue by HarishTeens** [graphql/graphql-js#2885]
# Reporting issues with GraphQL.js

As per the standards of graphql, whenever an error occurs, errors are expected to be in the below format
``` 
{
  "errors": [
        {
            "message": "Error message her",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
            }  
        }
    ]
}
``` 

### but when an error occurs inside context method

```
{
  "error": {
    "errors": [
      {
        "message": "Error message her",
        "extensions": {
          "code": "INTERNAL_SERVER_ERROR",
        }  
      }
    ]
  }
}
```

## Steps to reproduce

I had created a dummy apollo server with minimal configs just enough to produce this error when ran

- Paste this code in index.js
``` 
const { ApolloServer ,gql} = require('apollo-server');

const typeDefs = gql`
  type Query {
    readError: String
  }
`;

const resolvers = {
  Query: {
    readError: (parent, args, context) => {
      fs.readFileSync('/does/not/exist');
    },
  },
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ()=>{
    console.log(fs);
  }
});

server.listen({ port: 4000 }, () =>
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
)
``` 
- Run `npm init -y` 
- then `npm install apollo-server` and then run `node index.js`

**Comment by saihaj** [comment]
The error I got after replicating as you said is `"Context creation failed: fs is not defined"` which is not `graphql`.
![image](https://user-images.githubusercontent.com/44710980/105274485-edd4c900-5b62-11eb-98a1-581bb7bb0b79.png)

If you just remove the context where you instantiate the server it should work as expected. Similar to how Apollo Docs explain https://www.apollographql.com/docs/apollo-server/data/errors/#default-information

**Comment by HarishTeens** [comment]
Hey @saihaj , thanks for trying out the code.
If the same error happens inside any of the resolver, this same error wouldnt happen, but if the same happens on context, it behaves strange like this.

I encountered this issue, when I was trying to decode a client JWT and throw errors from context if the JWT is not valid. After realising this, I had to rewrite the all the resolvers to support this at the resolver level, where it all worked very well. But not at the context level 😢

**Comment by saihaj** [comment]
@HarishTeens I think this is an issue with Apollo server and how it handles errors for context creation (maybe FAI there). I tried running this using [`express-graphql`](https://github.com/graphql/express-graphql)  and it returns the error [as per spec](http://spec.graphql.org/draft/#sec-Errors.Error-result-format).

![image](https://user-images.githubusercontent.com/44710980/105525054-27fab380-5ca6-11eb-9e35-1161f0b63129.png)


```js
const { buildSchema } = require("graphql");
const express = require("express");
const { graphqlHTTP } = require("express-graphql");

const schema = buildSchema(`
  type Query {
    readError: String
  }
`);

const resolvers = {
  readError: (parent, args, context) => {
    fs.readFileSync("/does/not/exist");
  },
};

const app = express();

app.use(
  "/",
  graphqlHTTP({
    schema: schema,
    rootValue: resolvers,
    graphiql: true,
    context: () => {
      console.log(fs);
    },
  })
);

app.listen(4000, () => {
  console.log("Server ready at http://localhost:4000");
});
```

**Comment by HarishTeens** [comment]
Nice observation, thanks for creating the issue on behalf of me. I'll be closing the issue here. 
Thanks @saihaj
