### ISSUE TITLE
Dynamic Input Object Types

### ISSUE THREAD

**Issue by bringking** [graphql/graphql-js#290]
This is a cross issue from https://github.com/facebook/graphql/issues/140, but I need some advice on how to handle a "dynamic" nested input type. More specifically, I am trying to model the Sequelize operators listed here - http://docs.sequelizejs.com/en/latest/docs/querying/ for my work on  https://github.com/mickhansen/graphql-sequelize. Essentially, the piece I am having trouble with is the $and or $or operators. These operators can contain ...N number of nested types of themselves. e.g. -

```js
{
  rank: {//Where type
   $gte:1, //contains operators
    $or: { //and can contain OR
      $lt: 1000, //with the same nested operators
      $eq: null
    }
  }
}
```
I see a PR that supports something similar, but defining the "Where" type as a unstructured JSON Blob feels like a punt. 

I tried modeling this with a dynamic GraphQLInputObjectType, and using recursion -

```js
export function operatorTypeFactory(Model, attribute, name = '') {

  // determine the base type of the column
  // use it to define the available operator queries
  let type = typeMapper.toGraphQL(Model.rawAttributes[attribute].type, Model.sequelize.constructor);

  return {
    type: new GraphQLInputObjectType({
      name: `${name}_${attribute}`,
      fields: () => {
        return {
          and: {
            type: operatorTypeFactory(Model, attribute, `${name}_AND_operator_type_${Model.name}_${attribute}`).type,
            description: 'Nested AND operator'
          },
          or: {
            type: new GraphQLList(operatorTypeFactory(Model, attribute,
              `${name}_OR_operator_type_${Model.name}_${attribute}`).type),
            description: 'Nested AND operator'
          },
          eq: {
            type: type,
            description: 'Check if value is "="'
          },
```
But this obviously fails with a maximum call stack error when I try and run the server.. Any thoughts?

**Comment by leebyron** [comment]
I think you're on the right page here with using recursion. Also, I don't think it's wrong to use an unstructured JSON blob - in fact that might be a totally reasonable choice when your input is highly dynamic and difficult to type and especially so if your input type wants to be some JSON body that's not legal GraphQL input, like including `$` in key names like sequalize does. Today you can do that by typing the input as a `String` and then just performing the json encode/decode yourself. I'm really coming around to this idea though and may propose adding this kind of dynamic untyped input as part of the formal spec in the future.

However as to your strongly typed input case: I can see why this will infinitely recurse since you're calling your type factory recursively without a termination case. However GraphQL supports recursive types, but you have to recurse by reference:

```js
const SequalizeInput = new GraphQLInputObjectType({
  name: 'SequalizeInput',
  fields: () => ({
    and: {
      type: SequalizeInput,
      description: 'Nested AND operator'
    },
    or: {
      type: SequalizeInput,
      description: 'Nested AND operator'
    },
    eq: {
      type: SequalizeInput,
      description: 'Check if value is "="'
    }
  })
});
```

If you wanted to create one of these for every Model type like you're doing, then you need to create some kind of cache so you're not creating them over and over for every Model (and recursing infinitely).

```js
export function operatorTypeFactory(Model) {
  let type = someCache.get(Model);
  if (type) {
    return type;
  }

  type = new GraphQLInputObjectType({ ... });
  someCache.set(Model, type);
  return type;
}
```

Hopefully this helps!

**Comment by bringking** [comment]
@leebyron thanks for the helpful and thoughtful response. I ended up making a PR  to graphql-sequelize using the unstructured type, so I am glad to hear you are thinking about adding something similar to the spec. 

Regarding the recursion, I finally came around to the cache idea myself, so I am glad to have it validated by your idea! Thank you. I didn't end up using this solution since a side affect of the approach was quite a few very similar but different Input types in the system. Which doesn't sound like a big deal, but when you have ~ 50 model types, the documentation gets very cluttered.

**Comment by nodkz** [comment]
For future googlers:
@taion released awesome [scalar GraphQLType JSON](https://github.com/taion/graphql-type-json) that supports dynamic values for a field!

I'm using it in [graphql-compose-mongoose](http://graphql-compose.herokuapp.com/), so live demos with dynamic field's type can be found here: 
- [Find User with field of MIXED type](http://graphql-compose.herokuapp.com/user/?query=%0A%7B%0A%20%20userById(_id%3A%20%2257bb44dd21d2befb7ca3f001%22)%20%7B%0A%20%20%20%20_id%0A%20%20%20%20name%0A%20%20%20%20someMixed%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)
- [Create user mutation (with arg of MIXED type)](http://graphql-compose.herokuapp.com/user/?query=%0Amutation%20%7B%0A%20%20userCreate(record%3A%20%7B%0A%20%20%20%20name%3A%20%22My%20Name%22%2C%0A%20%20%20%20age%3A%2024%2C%0A%20%20%20%20gender%3A%20ladyboy%2C%0A%20%20%20%20contacts%3A%20%7B%0A%20%20%20%20%20%20email%3A%20%22mail%40example.com%22%2C%0A%20%20%20%20%20%20phones%3A%20%5B%0A%20%20%20%20%20%20%20%20%22111-222-333-444%22%2C%0A%20%20%20%20%20%20%20%20%22444-555-666-777%22%0A%20%20%20%20%20%20%5D%0A%20%20%20%20%7D%2C%0A%20%20%20%20someMixed%3A%20%7B%0A%20%20%20%20%20%20a%3A%201%2C%0A%20%20%20%20%20%20b%3A%202%2C%0A%20%20%20%20%20%20c%3A%20%5B%201%2C%202%2C%203%2C%20true%2C%20false%2C%20%7B%20sub%3A%201%20%7D%5D%0A%20%20%20%20%7D%0A%20%20%7D)%20%7B%0A%20%20%20%20recordId%0A%20%20%20%20record%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20age%0A%20%20%20%20%20%20gender%0A%20%20%20%20%20%20contacts%20%7B%0A%20%20%20%20%20%20%20%20email%0A%20%20%20%20%20%20%20%20phones%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20someMixed%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%20%20%20%20%20%20)

**Comment by granda** [comment]
I'm going to jump on this train and link my on going thread I'm having in the Meteor forums: https://forums.meteor.com/t/operators-in-graphql/29368.

**Comment by julian-rare** [comment]
graphql needs operators in the next implementation

**Comment by machineghost** [comment]
@leebyron 

> I'm really coming around to this idea though and may propose adding this kind of dynamic untyped input as part of the formal spec in the future.

Has anything happened with this since?  The 3rd-party JSON GraphQLType is a good workaround but an official GraphQL type would obviously be preferable.

**Comment by IvanGoncharov** [comment]
@machineghost Yes, here is PR to add `Any` type to the spec:
https://github.com/facebook/graphql/pull/325
