### ISSUE TITLE
Getting the error as 'Cannot return null for non-nullable field rootMutation.createUser'

### ISSUE THREAD

**Issue by Mukesh0996** [graphql/graphql-js#2939]
// resolver code
const {buildSchema} = require('graphql')
const User = require('../modals/userModel');
const bcrypt = require('bcryptjs');

module.exports = {
    createUser: async function ({ userInput }, req) {
    
        const email = userInput.email;
        const password = userInput.password;

        const existingUser = await User.findOne({email: email});

        if(existingUser){
            const error = new Error ("User already exists");
            throw error;
        }

        const hashedPassword = await bcrypt.hash(password,12);
        
        const user = new User({
            email: email,
            password: hashedPassword,
            status: "I am New"
        })

        const createdUser = await user.save();
        return { ...createdUser._doc, _id: createdUser._id.toString() }
  
    }
}
// Schema code

const { buildSchema } = require('graphql');

module.exports = buildSchema(`

    type Post {
        id: ID!
        title: String!
        content: String!
        imageUrl: String!
        creator: User!
        createdAt: String!
        updatedAt: String!
    }
    type User {
       _id: ID!
        email: String!
        name: String!
        status: String!
        password: String!
        posts : [Post!]!
    }
    input userInputData {
        email: String!
        password: String!
        status: String
        name: String!
    }
    type RootQuery {
        title: String
    }
    type rootMutation {
        createUser(userInput: userInputData): User!
    }

   schema {
       query:  RootQuery
       mutation: rootMutation
   }
`);

// error message

![1614089510482](https://user-images.githubusercontent.com/34233598/108857682-58b96a00-7611-11eb-8e8c-8727efd4c4ad.png)

**Comment by saihaj** [comment]
Looks like your `createUser` isn’t returning the  `User` as it should. You have made all fields non-nullable you might want rethink your schema.

**Comment by IvanGoncharov** [comment]
Thanks @saihaj 👍

**Comment by Mukesh0996** [comment]
const { buildSchema } = require('graphql');

module.exports = buildSchema(`

    type Post {
        id: ID!
        title: String!
        content: String!
        imageUrl: String!
        creator: User!
        createdAt: String!
        updatedAt: String!
    }
    type User {
        email: String!
        name: String!
        status: String!
    }
    type RootQuery {
        title: String
    }
    type rootMutation {
        createUser(email: String!, password: String!, name: String!): User!
    }

   schema {
       query:  RootQuery
       mutation: rootMutation
   }
`);


I have changed my Schema like the above mentioned code, but still doesn't work.
