### ISSUE TITLE
Limitation on graphQL whenever combining nested type definitions and #import

### ISSUE THREAD

**Issue by igorturturro** [graphql/graphql-js#2945]
The easiest way that I found to explain that was through an example. I have two `.graphql` files defining different schemas.

**File 1**

    # import secondLevel from '../../Workers/schema/typeDefs.graphql'
    
    type firstLevel {
      import: secondLevel
      a: String
    }

**File 2**

    type secondLevel {
      import: thirdLevel
      b: String
    }
    
    type thirdLevel {
      import: fourthLevel
      c: String
    }
    
    type fourthLevel {
      d: String
    }

Importing the second level into File 1 will generate an error. GraphQl can't recognize the type definition fourthLevel.

If I go only up to the third level, all works fine. The example follows below.

**File 1**

    # import secondLevel from '../../Workers/schema/typeDefs.graphql'
    
    type firstLevel {
      import: secondLevel
      a: String
    }

**File 2**

    type secondLevel {
      import: thirdLevel
      b: String
    }
    
    type thirdLevel {
      c: String
    }
    

So if I have a data structure according to the first example, the only solution I found to include the fourthLevel into the firstLevel document was importing and nesting straight away, as in the example below.

**File 1**

    # import secondLevel from '../../Workers/schema/typeDefs.graphql'
    # import fourthLevel from '../../Workers/schema/typeDefs.graphql'
    
    type firstLevel {
      test: secondLevel
      a: String
      d: fourthLevel
    }

**File 2**

    type secondLevel {
      test: thirdLevel
      b: String
    }
    
    type thirdLevel {
      test: fourthLevel
      c: String
    }
    
    type fourthLevel {
      d: String
    }

It breaks my structure since the conception was to have the fourth document nested into the third and so on. Is there any way to work around this limitation?

**Comment by saihaj** [comment]
This is not a `graphql-js` related issue. If any it is more of third party tooling limitation. I assume you are using webpack to resolve imports and then graphql tools or some other tool to combine schemas together to make a final SDL. I would suggest FAI issue there or ask on StackOverflow

**Comment by igorturturro** [comment]
It was a bad implementation of Graphql Tools. Thanks, @saihaj saihaj.
