### ISSUE TITLE
More detailed error output

### ISSUE THREAD

**Issue by vinerz** [graphql/graphql-js#295]
Hello everyone! I am missing a feature here that is about error output.

I really wish to send an Error Code alongside the error message, but I am not able to do this yet.

I wish I could do something like this:

```js
const error = new Error('Permission Denied');
error.code = 403;

throw error;
```

and receive a response like this

```json
{
  "data": {
    "user": {
      "email": null
    }
  },
  "errors": [
    {
      "code": 403,
      "message": "Permission Denied",
      "locations": [
        {
          "line": 1,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by leebyron** [comment]
When `graphql-js` executes, the resulting `errors` Array will be filled with the original `GraphQLError` objects that you throw, from which you can format however you like. You can get `GraphQLError` from `import { GraphQLError } from 'graphql';`

Then, if you wish to serialize this to JSON with the `code` field intact and you're using something like `express-graphql`, then you should provide a custom `formatError` https://github.com/graphql/express-graphql#options
