### ISSUE TITLE
Where is the schema language module/documentation?

### ISSUE THREAD

**Issue by calebmer** [graphql/graphql-js#302]
The GraphQL [docs](http://graphql.org/docs/api-reference-schema-language/) reference a schema language module at `graphql/language/schema`. I currently don't see it on master or any other documentation about it. Is there anywhere to learn more?

**Comment by leebyron** [comment]
Ah thanks, I'll update the website. It has since been merged into the existing parser.

https://github.com/graphql/graphql-js/blob/master/src/language/ast.js#L257

**Comment by calebmer** [comment]
Ok, thanks. Is there anywhere to find language documentation for the schema?

**Comment by leebyron** [comment]
Not yet, no, since it is experimental and still undergoing change. Once it's stabilized it will be added to the GraphQL working draft specification
