### ISSUE TITLE
Execute fragments directly

### ISSUE THREAD

**Issue by backbone87** [graphql/graphql-js#3060]
Currently, it seems not possible to execute a fragment directly against an executable schema.
```ts
      const result = await execute({
        schema: mySchema,
        document: gql`fragment ExecuteDirectly on MyModel { id }`,
        // operationName: 'ExecuteDirectly', // doesn't help
        rootValue: { id: 5 },
        variableValues: {},
        contextValue: createContext(),
      });
```

Is this something that could be supported? Is it already possible in another way? Is this better discussed on a spec level?

### Context
The schema of (some of) our Kafka topics is expressed in terms of GQL fragments. Some mutations want to produce to these topics and may execute an "internal" (sub-)request instead of assembling the message values themselves. Most of the time the root value of these fragments is already available in the mutation and sometimes there isn't even a top-level query available to execute a "normal" operation against. Being able to execute a fragment directly would efficiently reuse already available root values and avoids adding implementation details as top-level queries.

### Alternatives
Having had a quick look into how apollo federation solves a related issue, where the gateway server may need to do partial subqueries of types in federated services directly, it seems to me that they basically expose a special top-level query `_entities` in federated services which gets special treatment to do a direct type-based resolution.

**Comment by IvanGoncharov** [comment]
> Is this something that could be supported? Is it already possible in another way? Is this better discussed on a spec level?

It's not supported in direct way, however, you can create a schema with `MyModel` as query root and transform AST of the parsed fragment into valid query AST. Should be pretty straightforward to implement.

In general, `graphql-js` implemented according to spec so if you think it's a common problem please open an issue on the spec repo.
