### ISSUE TITLE
Best Practice Question: Passing tokens through the layers

### ISSUE THREAD

**Issue by matthewmueller** [graphql/graphql-js#307]
For example:

```
{
  teams {
    token
    channels {
      members {
         name
      }
    }
  }
```

If `teams` has an auth token that `members` would need in order to run it's queries, is there a good way to pass the token through the layers, assuming that `channels` doesn't need to have the auth as part of it's schema.

**Comment by freiksenet** [comment]
While you might not want to include auth info into channels, you can still pass it through in resolve function. For example:

```js
// teams
resolve(...) {
  return {
    token,
    ... other stuff
  }
}

// channels
resolve(parent) {
  return {
    token: parent.token,
    ...otherStuff
  }
}

// members 
resolve(parent) {
  const token = parent.token;
}
```

**Comment by clintwood** [comment]
Why not just pass it as a member to the `rootValue` when calling `graphql(schema, requestString, rootValue, ...)` which makes it available via the `info` argument to every `resolve` call.  See [here](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L46) for how to pass it as an argument and [here](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L534-L544) and [here](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L572) for what/how it gets passed to `resolve`.

**Comment by matthewmueller** [comment]
@freiksenet thanks, that's what i ended up doing and glad to hear other folks have done that too :-)
@clintwood I don't have access to it from root, I get access to it in teams

**Comment by helfer** [comment]
I think it's quite awkward to pass the token through every resolve function. Imho that's exactly what the rootValue (aka context) is for. Is there anything that prevents you from putting the token into the rootValue when you get access to it in teams?

**Comment by linonetwo** [comment]
Maybe because that documentation of rootValue is too obscure to get this point...

**Comment by stubailo** [comment]
I think context is a bit better documented than it was before, we have something here that could be improved: http://dev.apollodata.com/tools/graphql-tools/resolvers.html#Resolver-function-signature
