### ISSUE TITLE
COMMIT FREEZE DUE TO TS MIGRATION (until 24.05.2021)

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#3087]
As discussed on last WG we need to pull a trigger on long-overdue TS conversion.
Since we can't finish it in one merge and also expect some stuff to be broken in a process we need to do a temporary freeze on all commits not related to this conversion.
We should finish and return back to normal processes before 22.04.2021

**Comment by aprilrd** [comment]
Hello, could you double-check the due date? I wonder if you meant 22.06.2021, not 22.04.2021.

**Comment by leebyron** [comment]
One week freeze, planned completion by 22.5.2021, May 22

**Comment by IvanGoncharov** [comment]
Update: I run a diff comparing generated typings to the handwritten ones with have at the moment.
Some of the results were very surprising so I need a few more days to finish (until Monday 24th).
If someone has anything important to merge before that date, please feel free to ping me on this issue.

**Comment by IvanGoncharov** [comment]
Merged #3110 so `main` is unfrozen now.
But we still have a bunch of `@ts-expect-errors` and disable some of the strict checks in `tsconfig.json`.
