### ISSUE TITLE
in visit leave callback is skipped when enter callback returned false

### ISSUE THREAD

**Issue by DrorT** [graphql/graphql-js#315]
This might be by design, but it creates very weird results for me.
When the enter function of a specific field returns false the leave function will not be called.
Example:

const query = `
    {
        firstname,
        lastname
    }`;

const dataAST = GraphQLLanguage.parse(query);

const testVisitor = {
            Field: {
                enter(node, key, parent, path, ancestors) {
                    console.log("enter - " + node.name.value);
                    if(node.name.value == 'lastname')
                        return false;
                },
                leave(node) {
                    console.log("leave - " + node.name.value);
                }
            }
        };

const editedAST = GraphQLLanguage.visit(dataAst, testVisitor);

in my console I would expect to see: 
> enter - firstname
> leave - firstname
> enter - lastname
> leave - lastname

But what I get is:
> enter - firstname
> leave - firstname
> enter - lastname

**Comment by leebyron** [comment]
This is by design - returning false means stopping the traversal, and the `leave` event implies that the value was fully visited.

It would be helpful if you had a specific use case that illustrates why this behavior would be wrong?

**Comment by leebyron** [comment]
Feel free to re-open if you wish to discuss further
