### ISSUE TITLE
ScalarType: is there any purpose for renaming option `specifiedByUrl` (15.x) to `specifiedByURL` (16.x)? It affects on GraphQLJSON and other scalars distributed via npm

### ISSUE THREAD

**Issue by nodkz** [graphql/graphql-js#3156]
Is there any purpose that in v16 was renamed the following property:
```diff
export class GraphQLScalarType {  
  name: string;  
  description: Maybe<string>; 
-  specifiedByUrl: Maybe<string>;
+  specifiedByURL: Maybe<string>;
```
v15.5 https://github.com/graphql/graphql-js/blob/15.x.x/src/type/definition.js#L578
v16.0.0-alpha.2 https://github.com/graphql/graphql-js/blob/main/src/type/definition.ts#L580

---

This change breaks `specifiedByUrl` definition for Scalars distributed via npm. Most popular is GraphQLJSON: https://github.com/taion/graphql-type-json/blob/master/src/index.js#L55-L56

**Comment by saihaj** [comment]
@nodkz see https://github.com/graphql/graphql-js/pull/3032

**Comment by nodkz** [comment]
@saihaj thanks for the reference. I think that @IvanGoncharov made a typo in his comment with `specifiedByURL` (should be `specifiedByUrl`). He definitely didn't want to bring such kind of breaking changes.

**Comment by saihaj** [comment]
If you check the spec PR it is `specifiedByURL` so maybe you should raise this issue there
