### ISSUE TITLE
When resolving a GraphQLList is it necessary to return an array of promises

### ISSUE THREAD

**Issue by melbourne2991** [graphql/graphql-js#316]
I've noticed in this case, if my resolve method is as is below, I will get back an array of objects with the correct _id property, but all other properties (content, title) will be null.

However if I return an array of promises, everything's ok - i've been scouring the web for proper info on this, trying to determine if this is expected behaviour or not and have come up with nothing so I'm turning to you guys.

**When resolving a GraphQLList is it necessary to return an array of promises as opposed to a single promise which will resolve to an array?** and if so, why is this the case?

```
query(`
  query findListings {
    listings(offset: 1) {
      _id,
      title,
      content
    }
  }
`).then((json) => {
  console.log('json', json.data)
})
```

```
const ListingType = new GraphQLObjectType({
  name: 'Listing',
  fields: {
    _id: {
      name: '_id',
      type: GraphQLID
    },
    title: {
      name: 'title',
      type: GraphQLString
    },
    content: {
      name: 'content',
      type: GraphQLString
    }
  }
})

```

```
const QueryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    listings: {
      name: 'listings',
      type: new GraphQLList(ListingType),
      args: {
        limit: {
          type: GraphQLInt
        },
        offset: {
          type: GraphQLInt
        }
      },
      resolve(source, args, info) {
        const { fieldASTs } = info
        const projection = getProjection(fieldASTs[0])

        return ListingModel.find({}, projection).exec();
      }
    }
  }
})
```

**Comment by freiksenet** [comment]
If you look at the [completeValue](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L642-L776), GraphQL will always try to first resolve the promise. Then if the result is an array it will process each element one by one, it can handle both promises inside it and complete values. Could it be that ListingModel.find is returning something wrong? Or maybe the projection?

**Comment by melbourne2991** [comment]
Listing model .find.exec() just returns a standard es6 promise, I even wrapped it in an explicit native promise. The output for the console.log below is `[ { content: 'I am the content',
    title: 'Hello and welcome',
    _id: 56e6c94f1cf94a7c0a4e22ba } ]` and as usual, this is what the query gives me `json { listings: [ { _id: '56e6c94f1cf94a7c0a4e22ba', title: null, content: null } ] }.` I did try debugging the completeValue query, quite difficult because it's recursive - I guess i'll have another look - I was hoping this was expected behaviour but it sounds like it's not.

```
const QueryType = new GraphQLObjectType({
  name: 'Query',
  fields: {
    listings: {
      name: 'listings',
      type: new GraphQLList(ListingType),
      args: {
        limit: {
          type: GraphQLInt
        },
        offset: {
          type: GraphQLInt
        }
      },
      resolve(source, args, info) {
        const { fieldASTs } = info
        const projection = getProjection(fieldASTs[0])

        return new Promise((resolve) => {
          ListingModel.find({}, projection).exec().then((items) => {
            console.log(items);
            return resolve(items);
          })
        })
      }
    }
  }
})
```

**Comment by melbourne2991** [comment]
Ok so this is in fact an issue with my mongoose schema and not graphql. The object being returned has it's own setters and getters so listing.content / listing.title was returning undefined - despite being defined on the object.

We can close this issue.

**Comment by leebyron** [comment]
Glad you figured out what was going on!
