### ISSUE TITLE
More thorough Getting Started example

### ISSUE THREAD

**Issue by chrisbolin** [graphql/graphql-js#322]
Continuing a discussion @leebyron and I had on https://github.com/graphql/graphql-js/pull/321. 

This issue aims to address the first of Lee's suggestions:

> Here's my rough wish-list for improved documentation:
> 1. More in-depth prose and examples on using this library. http://graphql.org/docs/getting-started/ is a start, but there's not a lot of help beyond this for setting up anything more than this simple schema.
> 2. General higher quality version of all the "api reference" docs, filling in missing pieces and better examples and prose for each. It would be really awesome if we could automatically generate good documentation from the codebase itself. We've worked hard to maintain good flow type definitions and doc blocks within the codebase, but a reference docs site would be much easier to navigate.
> 3. Move the "api reference" documentation for graphql-js out of https://github.com/graphql/graphql.github.io/ (graphql.org) and into this repo so it's easier to maintain in sync with the rest of this codebase. (I'll probably eventually tackle this since it requires some gh-pages & travis-ci setup)

My general thoughts are to extend the [Getting Started page](http://graphql.org/docs/getting-started/) to include graphiql, some information on the `resolve` args, and asynchronous resolving.

Does this sound like a good start? Anything else you'd like? Should this be a separate doc, maybe part 2 of the Getting Started guide? (Currently clicking "Next" on the Getting Started page sends the viewer to the Videos page)

**Comment by chrisbolin** [comment]
It looks like we aren't assigning issues for this repo, correct? I'd be happy to be the assignee of this issue.

**Comment by leebyron** [comment]
Yeah, gh issues is a little rough and requires only explicit team-members be assignees for some reason, so I can't tag community members. But feel free to take the lead on any improvements on this front.

**Comment by chrisbolin** [comment]
https://github.com/graphql/graphql.github.io/pull/18

**Comment by JeffRMoore** [comment]
Should item 3 be its own issue?  At the moment this repo has 187 watchers and 3386 stars while the documentation repo has 26 watchers and 10 stars.  I think having the api documentation here will draw better PR reviews and perhaps more contributions.

**Comment by robzhu** [comment]
Looks like this was merged a while ago, closing.
