### ISSUE TITLE
Parsing SDL allows `true`, `false`, and `null` for enum value names

### ISSUE THREAD

**Issue by Yogu** [graphql/graphql-js#3221]
There is a schema validator that forbids `true`, `false`, and `null` as enum value names sinde https://github.com/graphql/graphql-js/pull/812/files. The `parse` function together with the `specifiedSDLRules` rules however allow these strings to be used as enum value names/values (they're the same there). This means you can parse and successfully validate an SDL which generates a validation error when creating the schema.

I'm not quite sure whether this is a bug in the parser or a missing SDL validator. `parseEnumValueDefinition` uses `parseName` and states that the `EnumValue` non-terminal is equivalent to the `name` non-terminal:

```javascript

  /**
   * EnumValueDefinition : Description? EnumValue Directives[Const]?
   *
   * EnumValue : Name
   */
  ;

  _proto.parseEnumValueDefinition = function parseEnumValueDefinition() {
    var start = this._lexer.token;
    var description = this.parseDescription();
    var name = this.parseName();
    var directives = this.parseDirectives(true);
    return {
      kind: Kind.ENUM_VALUE_DEFINITION,
      description: description,
      name: name,
      directives: directives,
      loc: this.loc(start)
    };
  }
```

There also is an `EnumValue` non-terminal which is defined as follows:

> EnumValue : Name but not `true`, `false` or `null`

So an enum declaration either should switch from `EnumName` to `EnumValue`, or there should be an SDL validator that rejects the three forbidden words when used as enum value names/values.

**Comment by renatobenks** [comment]
what a catch, sounds like a missing thing, interesting

**Comment by Yogu** [comment]
I looked into the specification. It's actually a bug in the parser. [Section 3.9](https://spec.graphql.org/draft/#sec-Enums) defines the `EnumValueDefinition` as follows:

> *EnumValueDefinition* :
>   *Description*[opt] *EnumValue* *Directives*[Const][opt]

And [section 2.9.6](https://spec.graphql.org/draft/#sec-Enum-Value) defines `EnumValue`:

> *EnumValue* :
>  *Name* but not **`true`** or **`false`** or **`null`**

I'll create a PR for this fix.

**Comment by IvanGoncharov** [comment]
@Yogu Thanks for reporting and especially for working on a fix 👍 
Closing and we will track progress in #3223
