### ISSUE TITLE
Disable suggestions

### ISSUE THREAD

**Issue by sandorvasas** [graphql/graphql-js#3229]
Recently we had a security test of our application and although I had disabled introspection on our GraphQL API, the `didYouMean` suggestions came up as a vulnerability. I kind of agree it's not a good idea to show around blackhats what methods our API exposes, and propose a `disableSuggestions: boolean` option.

**Comment by sahanatroam** [comment]
related: https://github.com/apollographql/apollo-server/issues/3919

**Comment by IvanGoncharov** [comment]
Closing in favor of #2247
