### ISSUE TITLE
Schema and type definition language parser

### ISSUE THREAD

**Issue by charypar** [graphql/graphql-js#33]
Are there any plans to implement the type definition shorthand language parser, so that one could actually write documents describing types instead of using the (slightly verbose) JS notation?

**Comment by charypar** [comment]
Oh, missed #16, sorry.

**Comment by leebyron** [comment]
Yeah, we're tracking adding a parser for the type DSL in #16, but note that there are no plans for writing types in this DSL replacing writing type definitions in JavaScript directly that link to your code. 

Doing so would be a limiting factor, and is better left as an exercise for individuals based on the own tradeoffs their environments make.
