### ISSUE TITLE
Why use two representations of graphq schema

### ISSUE THREAD

**Issue by sheerun** [graphql/graphql-js#333]
Hey,

I'm watching the development of this library and I wonder why we need two representations of graphql schema: introspection query result and schema AST.

Wound't it be easier for developers of other implementations to use the same format for both of them? Why not just use introspection query result as schema AST format? Now there's additional burden of handling both representations.

**Comment by helfer** [comment]
The AST actually contains information that's not in the introspection result, for example the location of nodes. That allows you to do stuff like syntax highlighting and producing more useful error messages.
The introspection result also doesn't contain stuff like resolve functions, etc.

I like the general idea, but I think the goal should be to produce an AST from an introspection result. And what do you know, graphql-js already has a function for that: https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js

**Comment by sheerun** [comment]
Aren't you mistaking AST (`Document` type) with Schema (`GraphQLSchema` type)?

Currently there are 3 classes:

1. `GraphQLSchema` - the schema with objects and resolves
2. `Document` - the AST, result of parsing the source (no resolve functions)
3. `IntrospectionSchema` - serialization format to send over the wire (no resolve functions)

My point is to replace `Document` with `IntrospectionSchema` (i.e. remove `Document`).

This would force 1:1 parity between AST and data available in introspection result.

`graphql-js` could still use `Document` internally, but probably it would be better to not expose it (i.e. remove all functions consuming or returning `Document` from public API). I think RFC spec is the best API.

**Comment by helfer** [comment]
You're right, most of the things I wrote are true of the schema, not the AST. Let me take a closer look at the differences.

**Comment by helfer** [comment]
@sheerun actually, while we're at it, I floated almost exactly the same idea [here](https://github.com/cameronhunter/graphql-shorthand-parser/pull/8#issuecomment-200704140), before I discovered that graphql-js had a parser for schema notation. For some reason I just didn't call the parser output what it is - an AST.

For me, the main advantage of having both be the same is that one could easily use the introspection result to generate a schema somewhere (minus the resolve functions etc.). Maybe that explains the context for my first comment in this issue thread.

**Comment by leebyron** [comment]
@sheerun you're correct there are currently three ways to represent a schema with 3 different use cases:

1. `GraphQLSchema` - as you correctly state, the runtime representation of a schema. Used for validation, execution, and other runtimey things.
2. Introspection via `__schema` - this is the system by which we can use GraphQL to ask questions about a server's GraphQL schema. This is important for building tools like GraphiQL and clients that need to be aware of the schema, like Relay. How this works is part of the Spec.
3. The IDL language AST - this is an experimental addition. You certainly do not need to use it if you don't have a use for it. 

> My point is to replace Document with IntrospectionSchema (i.e. remove Document).

This is actually the current reality. We always rely on Introspection results for requesting information about a server's schema, and we never use the experimental IDL language.

What the IDL language is available for is defining schema local to a codebase. For example, perhaps your server would like to define its schema in terms of this IDL (and fill in implementations elsewhere) or perhaps your iOS client would like to extend the schema to add some client-only fields.

For your question of why not just use the introspection result as the output of parsing the IDL - that's just a case of one not encoding the right information of the other. An introspection result can tell you info about an existing schema, but the AST for a parsed IDL can also tell you info about where things are defined within a file (character locations) as well as represent intermediate forms that a schema rightfully does not represent (eg `extend type`).

**Comment by leebyron** [comment]
@helfer I want to make sure you're aware of the buildClientSchema export which does what you say. Takes introspection result and build a usable schema instance.

**Comment by helfer** [comment]
@leebyron Yes, thanks! I found that some time after I commented here. Haven't used it yet, but looking forward to it.

**Comment by leebyron** [comment]
It's how GraphiQL works! https://github.com/graphql/graphiql/blob/master/src/components/GraphiQL.js#L450

**Comment by helfer** [comment]
Haha, in that case I _have_ used it!
