### ISSUE TITLE
GraphQL 15.7.0 Breaks Apollo Server

### ISSUE THREAD

**Issue by dhay** [graphql/graphql-js#3340]
We use Apollo Server, which depends on the graphql-js package.  The latest update to version 15.7.0 causes Typescript compilation errors related to GraphQLError.  Specifically the change related to `originalError` in this commit: https://github.com/graphql/graphql-js/commit/d8ca570ea9ebd7d5f24b769a0701afea2b001cd7

```
- readonly originalError: Maybe<Error>;
+ readonly originalError: Error | undefined;
```

Previously `Maybe` was defined as `null | undefined | T`.  Changing this to only `Error | undefined` causes errors like the following:

```
node_modules/apollo-server-errors/dist/index.d.ts(10,5): error TS2416: Property 'originalError' in type 'ApolloError' is not assignable to the same property in base type 'GraphQLError'.
  Type 'Error | null | undefined' is not assignable to type 'Error | undefined'.
    Type 'null' is not assignable to type 'Error | undefined'.
```

This is true when using both Apollo server version 2.x or 3.x

**Comment by charles-hill-exelon** [comment]
@IvanGoncharov Will this fix be ported to 16.x?
