### ISSUE TITLE
Upgrade issues with TypeScript enums and nominal typing

### ISSUE THREAD

**Issue by brainkim** [graphql/graphql-js#3356]
Hullo! I’m upgrading some Apollo projects to GraphQL 16 and running into slight difficulties with enums. The context is that we have utilities which create or modify AST nodes:

```diff
diff --git a/src/utilities/graphql/transform.ts b/src/utilities/graphql/transform.ts
index 2a5128d05..80db6d202 100644
--- a/src/utilities/graphql/transform.ts
+++ b/src/utilities/graphql/transform.ts
@@ -2,6 +2,7 @@ import { invariant } from '../globals';
 
 import {
   DocumentNode,
+  Kind,
   SelectionNode,
   SelectionSetNode,
   OperationDefinitionNode,
@@ -53,9 +54,9 @@ export type RemoveVariableDefinitionConfig = RemoveNodeConfig<
 >;
 
 const TYPENAME_FIELD: FieldNode = {
-  kind: 'Field',
+  kind: 'Field' as Kind.FIELD,
   name: {
-    kind: 'Name',
+    kind: 'Name' as Kind.NAME,
     value: '__typename',
   },
 };
```

The code is semantically sound, but TypeScript requires the assertion because you must reference enums directly wherever they are required (nominal typing).

```ts
enum Foo {
  a = "A",
  b = "B",
}

// This is a type error because we’re not referencing the enum directly.
const foo: Foo = "A";
// This is fine
const foo1: Foo = Foo.a;
```

The disadvantages of this change in GraphQL 16 are:
1. We have to add runtime dependencies on the files which contain the enums.
2. It’s slightly tricky to support ranges of graphql-js versions.

As a specific example of an enum-based difficulty, `OperationTypeNode` is an enum in GraphQL 16, but it’s not exported as a value in GraphQL 15, so there is no way to reference the enum value across 15 and 16, and you get type errors if you assign strings like `"query"` or `"mutation"` to the enum.

I think the above two concerns are reason enough to switch to using string unions, which are structurally typed, and don’t require direct reference. We can make this a non-breaking change by exporting a namespace instead of an enum, and shadowing the identifier on the type-level with a string union.

```ts
export type Kind = "Name" | "Document" /* ... */;
export namespace Kind {
  export const NAME = 'Name';
  export const DOCUMENT = 'Document';
  /* ... */
}
```

Thanks for reading. Let me know your thoughts!

**Comment by saihaj** [comment]
Why not use the `enum` directly? 
```diff
 const TYPENAME_FIELD: FieldNode = {
-  kind: 'Field',
+  kind: Kind.FIELD,
   name: {
-    kind: 'Name',
+    kind: Kind.NAME,
     value: '__typename',
   },
 };
```

>  Let me know your thoughts!

Exporting `namespaces` and string unions imo isn't very clean.

**Comment by brainkim** [comment]
@saihaj
> Why not use the enum directly?

I’m not sure I want to import a file from graphql-js just to access the enum value. And in the case of `OperationTypeNode`, the enum does not exist in v15.

> Exporting namespaces and string unions imo isn't very clean.

I agree it could be a pain to deal with and write. I still think the nominal typing part about enums is tricky.

**Comment by IvanGoncharov** [comment]
@brainkim Practically speaking is it a blocker for adding v16 support to `apollo-client`?
I will keep this issue open anyway just want to know how urgent it?

> I’m not sure I want to import a file from graphql-js just to access the enum value. And in the case of OperationTypeNode, the enum does not exist in v15.

It looks like you are using `visit` in Apollo client:
https://github.com/apollographql/apollo-client/blob/8716cbcaaa5f633768f2e44055921caa7858fcf9/src/utilities/graphql/transform.ts#L16
If so you already bundling entire `Kind`, see:
https://github.com/graphql/graphql-js/blob/30b446938a9b5afeb25c642d8af1ea33f6c849f3/src/language/visitor.ts#L185-L187

> It’s slightly tricky to support ranges of graphql-js versions.

If you have any idea on how to address this happy to implement it in previous versions.

> We have to add runtime dependencies on the files which contain the enums.

Const enums are ideal for this case however we can't do `Object.values` on them.
Ideally, TS would have a mechanism that allows us to mark enum as safe to inline but keep the runtime part for the case when you actually need it.

**Comment by benjie** [comment]
Could we do something like this, I wonder?

```ts
const Kind = {
  OBJECT: 'ObjectType' as const,
  OBJECT_FIELD: 'ObjectField' as const
};
type Kind = typeof Kind[keyof typeof Kind];

const a: Kind = Kind.OBJECT;
const b: Kind = 'ObjectType';
```

https://www.typescriptlang.org/play?#code/MYewdgzgLgBA0gSzAExgXhgbwFAxgeQCEApAUQGEAVALhgHJ8AjAKwFNgpKBPAB1bpgBDCDFCQoAGlwESFSgH0AYgElSAGQAitBi3ZRFCVgBtkA4aPDRsAXwDc2KL1bwkqDI74gAZi5QBtAGtWLm8YD1ZQxBQAXXtsMWghWii3X2QAOiIyKnsE2EZk13R6JjYObj46WyA

**Comment by yaacovCR** [comment]
Wow, that is neat!

**Comment by brainkim** [comment]
@IvanGoncharov It’s not a blocker! Thankfully with TypeScript there are workarounds. Just surfacing the struggle in case others having it.

@benjie `keyof typeof` is a new one to me! That’s fantastic.

**Comment by brainkim** [comment]
The other detail is that we’re using `typeof Enum` in various places (https://github.com/graphql/graphql-js/blob/main/src/language/directiveLocation.ts#L33), and it doesn’t actually seem to work as expected.

```ts
enum Foo {
    a = 1,
    b = 2,
}

type FooLegacy = typeof Foo;

const foo: Foo = Foo.a;

// this errors
const foo1: FooLegacy = Foo.a;
```

https://www.typescriptlang.org/play?ssl=11&ssc=31&pln=1&pc=1#code/KYOwrgtgBAYg9nKBvAUFdUCGUC8UCMANGhgEa5QBMxAviigC4CeADsLAgDLADmmAxkwrM2cAGYc4Abnr84IAM4MoYhAC5JFeHAB0mGSgD0hqAwAWASwVRgAJ1txbClHMXLVcfBu3c+grQh6UkA

**Comment by yaacovCR** [comment]
Tracking in newer issue #4253

**Comment by JoviDeCroock** [comment]
These are two distinct issues, let's leave this open.

**Comment by JoviDeCroock** [comment]
This will be solved in v17 after https://github.com/graphql/graphql-js/pull/4254
