### ISSUE TITLE
cannot access http://graphql.org/

### ISSUE THREAD

**Issue by xosuperpig** [graphql/graphql-js#336]
dns cannot resolve this domain this week.
does this site abandoned?

**Comment by ykad4** [comment]
Work fine now, did you try a proxy or a vpn?

**Comment by xosuperpig** [comment]
I'm using a web proxy from hongkong. It maybe is a problem of the dns serser of my hongkong proxy. thanks.

**Comment by linonetwo** [comment]
Me too, even with a proxy can't I visit it.
