### ISSUE TITLE
16v migration - Error objects get returned as [object Object]

### ISSUE THREAD

**Issue by RodPaDev** [graphql/graphql-js#3369]
## Bug Description
This is our custom error function, it used to work before, it doesn't anymore since the v16 upgrade.

Now whenever an error object is returned this happens `Error: [object Object]`

```
export class CustomError extends Error {
  constructor(message) {
    super(message)
    this.message = message
    this.name = 'CustomError'
  }
}
```

I tried using `GraphQLError` but the same thing happens.

## Reproduce

Return error object instead of only string
## Expected behaviour

Return the whole error object

## Envrionment
- graphql 16.0.1
- node 14.x

**Comment by IvanGoncharov** [comment]
@RodPaDev Can you please provide more details?
Most importantly, can you please provide a minimal example that reproduces your error?

**Comment by RodPaDev** [comment]
Yes, of course my bad, I'm only going to include the resolver as it's happening with every single type that we have.

```
 resolve: async (parent, args) => {
  try {
    // We're using Sequelize here
    const item = await Table.findOne({
      where: {
        id: args.input.id,
        otherId: args.input.otherId
      }
    })

    if (!item) {
      const newItem = await Table.create(args.input)
      return newItem
    }

    throw new CustomError({ key: 'Item is already in Table.' })
  } catch (err) {
    throw err
  }
}
  ```

**Comment by IvanGoncharov** [comment]
@RodPaDev You shouldn't use objects as `message`.
Just do `throw new CustomError('Item is already in Table.')` and it will fix everything.
Not sure how it worked before v16 but passing objects as `message` is not something we will ever support.
If you want to pass additional data with your error please use the `extensions` property.
```js
export class CustomError extends Error {
  constructor(message, key) {
    super(message)
    this.name = 'CustomError'

    this.extensions = { key };
  }
}
```

**Comment by RodPaDev** [comment]
We settled on this, basically the same thing you sent, we also format it before sending up but that doesn't matter in this case. Thanks for the help @IvanGoncharov 👍 

```js
export class CustomError extends Error {
  constructor(message) {
    super(message)
    this.message = 'Internal Server Error'
    this.extensions = { error: message }
    this.name = 'CustomError'
  }
}
```
