### ISSUE TITLE
Canary releases

### ISSUE THREAD

**Issue by IvanGoncharov** [graphql/graphql-js#3383]
As discussed on graphql-js-wg we decided to switch to unstable `main` and provide canary release every week.

Currently, there are a couple of blockers we need to address:
- [ ] Allow publishing NPM packages without updating the `main` (otherwise we will add a bunch of useless commits in git history).
   - [ ] Don't commit `graphql/version.ts` and only generate it during the build process.
   - [ ] Figure out a way to safely release versions without updating `package.json`
- [x] Setup docs site for v16 we should have docs for "stable" version.
- [x] Release v16.1.0
- [x] Switch main to v17.0.0-alpha.0

cc: @saihaj

**Comment by dotansimha** [comment]
@IvanGoncharov are you open to introducing https://github.com/atlassian/changesets in this repo? 
We are using it in many libraries, and it works well. It manages the CHANGELOG, GitHub Releases/tags, and allows to do canary releases, and also automates the stable releases process.
We recently added it in `graphiql` repo as well and it's really helping us there.

**Comment by n1ru4l** [comment]
Some example commit histories from graphiql:

Full commit history: https://github.com/graphql/graphiql/commits/main
Example release commit: https://github.com/graphql/graphiql/commit/c1e2b5eb91a3a8c7a0abb3139123295948aeda4e

**Comment by yaacovCR** [comment]
It looks like this is working?

@IvanGoncharov @saihaj  can we close this issue?
