### ISSUE TITLE
Cannot npm install this repo with github url

### ISSUE THREAD

**Issue by helfer** [graphql/graphql-js#339]
v0.4.18 is from Feb 17, and there have been quite a few changes since then. I'm particularly interested in the changes made to the parser.
Is it planned to release a new npm package soon, or would it be possible to change the master branch so it's possible to npm install graphql-js directly from github? Right now the .npmignore file makes this impossible.
I'd much rather use one of the fixes above, than create a temporary fork.

**Comment by dschafer** [comment]
CC @leebyron, I suspect he was looking to land his RFCs before versioning (since the next release will have breaking changes in it), so I'll leave this to him.

**Comment by leebyron** [comment]
Yea I'm trying to gang up all the breaking changes, but I'll get something out there for those who like to ride the edge

**Comment by helfer** [comment]
@dschafer @leebyron Thanks!

**Comment by helfer** [comment]
Actually, do you have an approximate ETA for the next npm release?

**Comment by leebyron** [comment]
v0.5.0-beta.1 is live on npm now.

**Comment by leebyron** [comment]
There's now an automatic npm tracking branch set up. #347 has details.
