### ISSUE TITLE
Ionic build error

### ISSUE THREAD

**Issue by Evanzsnr** [graphql/graphql-js#3394]
After installing graphql in my ionic app, I built the app and the build failed with the following error

```
ERROR in node_modules/graphql/NotSupportedTSVersion.d.ts:1:63 - error TS1003: Identifier expected.

1 "Package 'graphql' support only TS versions that are >=4.1.0".
```

What could be the cause of this error?

**Comment by saihaj** [comment]
You need upgrade TypeScript versions in your app. It should be greater than `4.1.0`
