### ISSUE TITLE
Can Types have default values?

### ISSUE THREAD

**Issue by kevinSuttle** [graphql/graphql-js#345]
For example: GraphQLBoolean. Can it default to `false` as it does in JavaScript? I know query variables can have default values, but I can't find any info for default types. GraphQLBooleans appear to default to `null`, as other GraphQL types.

**Comment by leebyron** [comment]
Types themselves never have default values, no, as that would presume too much about each contextual use.

Instead, default values are declared next to where they're desired, query variables being a good example.

**Comment by kevinSuttle** [comment]
> Instead, default values are declared next to where they're desired 

Can you give a non-query variable example?

**Comment by leebyron** [comment]
The other example, sort of related to variables, is field/directive arguments and input object fields. Arguments and input object fields can declare default values in the case that they're not provided: http://facebook.github.io/graphql/#sec-The-__InputValue-Type

**Comment by leebyron** [comment]
Feel free to reopen if you wish to discuss further

**Comment by kevinSuttle** [comment]
Thanks. The one thread I did want to tug at: I've not seen any examples of defining queries with query variables in schemas. 

Both https://learngraphql.com/basics/query-variables/5 
and https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56#.pus2p7wmz only reference GraphiQL and how _not_ to write them.

**Comment by leebyron** [comment]
Yes the spec has a few examples of them in use as well as explainers for their use, but in general we need better documentation still.

**Comment by andriyfomenko** [comment]
enum aaa {
AA
BB
}

interface ii {
type: aaa
}

type ZZ_AA implements ii {
type: aaa = AA
...
}

type ZZ_BB implements ii {
type: aaa = BB
...
}

type ZZ = ZZ_AA | ZZ_BB

type Query {
  ZZ_by_type(type: aaa): ZZ
}

that would be quite convenient in my use case to allow for one access query/path to return one of possible ZZ variants from the parameter variable
