### ISSUE TITLE
Check for function type before executing

### ISSUE THREAD

**Issue by vespaiach** [graphql/graphql-js#3458]
I'm experiencing this issue while running `graphql-codegen` with `graphql@16.2.0`

```
    TypeError: visitFn.call is not a function
        at Object.visit (/home/vespaiach/working/lemonade-web/client/node_modules/graphql/language/visitor.js:204:21)
        at Object.plugin (/home/vespaiach/working/lemonade-web/client/node_modules/@graphql-codegen/typescript/index.js:367:35)
```

I have looked into visitor.js file and saw this line of code https://github.com/graphql/graphql-js/blob/47bd8c8897c72d3efc17ecb1599a95cee6bac5e8/src/language/visitor.ts#L259

I think, checking null/undefined before executing is not enough. Maybe, visitFn function need to be checked if it is callable or not too

**Comment by charlypoly** [comment]
Hi @vespaiach!

Could you provide the following?

- packages version (from lockfile), especially for `graphql` and all codegen packages installed.
- do you have a version of `graphql` version installed globally?
- could you provide a repro codesandbox?

Thank you!

**Comment by IvanGoncharov** [comment]
@charlypoly I suspect you are using old version of `graphql-codegen` please update to the newest one.
If you still see this issue after updating, please open this issue in `graphql-codegen` repo.
