### ISSUE TITLE
typecheck error?

### ISSUE THREAD

**Issue by thewillhuang** [graphql/graphql-js#348]
on 0.4.18 this test passes, but for 0.5.0-beta.1 and 0.5.0, the below test fail, is this still the expected behavior? thanks!

```js
// schema.js
import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLString,
  GraphQLNonNull,
  GraphQLInt,
  GraphQLList,
  GraphQLID,
  GraphQLInterfaceType,
} from 'graphql';

const query = new GraphQLObjectType({
    id: {
      type: GraphQLInt,
      args: {
        id: {
          description: 'root query passed to graphql',
          type: new GraphQLNonNull(GraphQLInt),
        },
      },
      resolve: (source, { id }) => id,
    },
});

export default new GraphQLSchema({ query });

// test.js
describe('graphql basic tests', () => {
  it('query wrong type should throw', async () => {
    const { body } = await request
      .post(url)
      .send({ query: 'query wrongType { id(id: "2")}' })
      .endAsync();

    // console.log(body);
    assert.deepEqual(body, {
      errors: [
        {
          message: "Argument \"id\" has invalid value \"2\".\nExpected type \"Int\", found \"2\".",
        },
      ],
    });
  });
}
```

outcome
```js
  1 failing

  1) graphql basic tests query wrong type should throw:

      AssertionError: expected { errors: [ {} ] } to deeply equal { Object (errors) }
      + expected - actual

       {
         "errors": [
      -    {}
      +    {
      +      "message": "Argument \"id\" has invalid value \"2\".\nExpected type \"Int\", found \"2\"."
      +    }
         ]
       }
```

**Comment by leebyron** [comment]
Thanks for the report, that doesn't seem right. I assume you're using express-graphql, Can you let me know exactly what version you're using?

**Comment by helfer** [comment]
Isn't that the expected behavior according to the spec?

> Coercion of Int: When expected as an input type, only integer input values are accepted. All other input values, including strings with numeric content, must raise a query error indicating an incorrect type. If the integer input value represents a value less than -231 or greater than or equal to 231, a query error should be raised.

**Comment by leebyron** [comment]
Yes, the test passing should be correct, but if I interpret correctly, the test is now failing - which is to say that error that was expected is no longer appearing.

**Comment by helfer** [comment]
Yeah, I realized it just after posting. Sorry for the noise.

**Comment by thewillhuang** [comment]
odd, im using graphql-js directly with serverless node version 4.3.2 and all i get is `{ errors: [ {} ] }` in the body of my response. if i switch back to 0.4.18, this test pass as expected.

**Comment by leebyron** [comment]
I'd love to get a repro so I can investigate, but not sure how to piece together 

```js
const { body } = await request
      .post(url)
      .send({ query: 'query wrongType { id(id: "2")}' })
      .endAsync();
```

can you provide maybe a sample bit of code that is end-to-end executable?

**Comment by leebyron** [comment]
Ohhh, perhaps `{ errors: [ {} ] }` is a hint here. There is in fact an error, but the error object does not have serializable properties?

Can you ensure your http level integration with graphql-js is formatting those errors?

**Comment by thewillhuang** [comment]
Got it, I'll get an end to end executable version up a bit later, perhaps its something odd with the combination of modules I'm using...

**Comment by helfer** [comment]
I actually remember observing these empty errors in GraphiQL as well some point after updating to 0.5.0, so there's definitely something there. I didn't follow up though, because I was able to easily debug it by adding an error logger with a little helper tool that I built. 
If you want, you could try doing the same to see what the actual error thrown is. It works as follows (after installing graphql-tools from npm):
```
import { addErrorLoggingToSchema } from 'graphql-tools';
const yourSchema = new GraphQLSchema( ... );
const errorLogger = { log: (e) => console.log(e.message)};
addErrorLoggingToSchema(yourSchema, errorLogger);
export default yourSchema;
// or run your query or tests here directly
```

**Comment by helfer** [comment]
I put together a quick reproduction with a GraphiQL interface [here](http://apollostack.github.io/graphql-left-pad/). If you modify the query so it contains an error, the errors won't be printed by GraphiQL (but you'll find them in the console).
From the looks of it, it seems that graphql no longer serializes the error messages, which is I change that was presumably made so folks could implement their own formatting of errors. I think that's great, but it has the unfortunate side-effect that you can now no longer plug graphql directly into GraphiQL. Maybe we could add an argument to graphql that makes it serialize/format errors?

**Comment by helfer** [comment]
Found the commit, it's pretty well-described too: https://github.com/graphql/graphql-js/commit/09020612ccded1bdaf001b8703d1196a62141b3c

Basically this behavior is expected, and the issue is in the library you're using to call GraphQL.

@leebyron Is there a default error formatting function that people could use? It might be worth documenting that for others who run into the same issue.

**Comment by thewillhuang** [comment]
```js
// setup graphql
import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLNonNull,
  GraphQLInt,
  graphql,
} from 'graphql';

const query = new GraphQLObjectType({
  name: 'Query',
  description: 'the default root query',
  fields: {
    id: {
      type: GraphQLInt,
      args: {
        id: {
          description: 'root query passed to graphql',
          type: new GraphQLNonNull(GraphQLInt),
        },
      },
      resolve: (source, { id }) => id,
    },
  },
});

const Schema = new GraphQLSchema({ query });

// setup tests
import { describe, it } from 'mocha';
import chai, { assert } from 'chai';
import chaiAsPromised from 'chai-as-promised';
chai.use(chaiAsPromised);

describe('graphql error tests', () => {
  it('should thrown on wrong types', async () => {
    const result = await graphql(Schema, 'query wrongType { id(id: "2")}');
    console.log(result);
    assert.deepEqual(result, {
      errors: [
        "Error: Argument \"id\" has invalid value \"2\".\nExpected type \"Int\", found \"2\"."
      ],
    });
  });
});

```

yep, looks like the reason it was returning an error, in 0.4.18 this error was sent back as JSON, but 0.5, it is now an Error Object that I have to handle on the server side.

**Comment by helfer** [comment]
You can just do this:
```
import { formatError } from 'graphql';

// ... code here

if (result.errors){
  result.errors.map(formatErrors);
}
```

That's the exact thing that graphql was doing for you in 0.4.18
