### ISSUE TITLE
Stability of reflection on types like `GraphQLSchema`

### ISSUE THREAD

**Issue by calebmer** [graphql/graphql-js#349]
I have a use case where I am generating a `GraphQLSchema` given a couple of factors. In my tests instead of having every test be an integration test (using the `exec` or `graphql` functions to actually run a query) I'd like to reflect over the generated schema to see if an GraphQL schema is being correctly generated.

So how stable are the properties on `GraphQLSchema`, `GraphQLObject`, `GraphQLList` and similar types? Would you recommend I introspect using the `_*` properties on these types?

**Comment by leebyron** [comment]
Anything that starts with an underscore is an internal property and could likely change in the future. However anything without an underscore is part of the public API and any breaking change would require a major version bump and an explicit call out in the changelog, and that's not something that happens often at all.

Let me know if you have questions on this.

**Comment by calebmer** [comment]
Ok, thanks. After looking at the source code I'm finding helper methods I couldn't find before in the docs or a brief inspection of types like `GraphQLSchema`s prototype.
