### ISSUE TITLE
Change formatError deprecation hint to match return type

### ISSUE THREAD

**Issue by sgohlke** [graphql/graphql-js#3492]
In graphql-js version 16.3.0 there is a deprecation hint for the **formatError** function in error/GraphQLError stating
` * @deprecated Please use `error.toString` instead. Will be removed in v17`
As **toString** returns a string and **toJSON** returns a **GraphQLFormattedError** it might be a good idea to change the deprecation hint to
` * @deprecated Please use `error.toJSON` instead. Will be removed in v17`.

**Comment by IvanGoncharov** [comment]
@sgohlke Good suggestion!
Missed that one but now we have already removed both functions so changes are necessary.

If anyone wants to backport it in the v16 branch please feel free to open a PR for it.
