### ISSUE TITLE
execute function slow if it throws an error

### ISSUE THREAD

**Issue by thdxr** [graphql/graphql-js#3500]
Doing some profiling and a basic Hello World resolver returns in 1ms but takes > 100ms if it throws an error. I was able to trace this to the execute function but not sure what's going on beyond that.

**Comment by thdxr** [comment]
I've been able to confirm this only happens with `NODE_OPTIONS=--enable-source-maps` turned on.  It doesn't happen with a simple thrown error in a try catch block, only when one occurs inside the `execute` function.  Not sure what it's doing with the error to cause this

**Comment by yaacovCR** [comment]
are you able to give more details of your setup, such as OS, version of Node, any other possibly relevant environment details?

a minimal example setup would be great in a repo to further investigate!

**Comment by thdxr** [comment]
I think this is actually just an issue with node's implementatino of sourcemaps so closing this issue

**Comment by dkershner6** [comment]
Just ran into this myself...and this issue solved the problem for me, no source maps here either.
