### ISSUE TITLE
Document contextValue

### ISSUE THREAD

**Issue by angelf** [graphql/graphql-js#352]
The changes introduced in d7cc6f9aed462588291bc821238650c98ad53580 are not yet on the docs (for instance http://graphql.org/docs/api-reference-execution/#execute or the `GraphQLFieldResolveFn` type in http://graphql.org/docs/api-reference-type-system/#graphqlobjecttype, although 5.0.0 is already out.

**Comment by leebyron** [comment]
Good catch thanks. These have been updated!
