### ISSUE TITLE
Github CodeQL "high" severity warning

### ISSUE THREAD

**Issue by jpillora** [graphql/graphql-js#3541]
I don't think this could be used in a realworld attack but I thought I'd raise it here anyway. Feel free to close if not an issue 👍

![image](https://user-images.githubusercontent.com/633843/164617679-fe54c1e3-c691-4a8a-abc8-ef3106903aaa.png)

### Target code

https://github.com/graphql/graphql-js/blob/be1261373e45bfd96676efe612b4e02aa308ce72/src/language/blockString.ts#L125

### Failing Rule

https://codeql.github.com/codeql-query-help/javascript/js-incomplete-sanitization/

https://github.com/github/codeql/blob/4551af90f61a8d5f5c1c88a036595b5919a6c98e/javascript/ql/src/Security/CWE-116/IncompleteSanitization.ql

**Comment by saihaj** [comment]
Thanks! Don't think it impacts us because it is just fro block string comments
