### ISSUE TITLE
关于文档的优化建议

### ISSUE THREAD

**Issue by crazyyf** [graphql/graphql-js#3561]
首先，非常感谢你们开源了这么好的项目供广大开发者使用，其次，我有一些小的建议是关于官方文档的
我是一名来自中国的开发者，当然我的英文不是很好，而官方又没有提供中文版的文档，所以我只能使用谷歌浏览器的翻译功能把英文翻译成中文，供自己阅读，但是在翻译过程中，出现了一个问题，谷歌浏览器会把案例的代码块也一并翻译成中文，经过查阅发现，谷歌浏览器也有对应的解决方法，就是谷歌浏览器不会把HTML中`<code>`标签包裹起来的部分进行翻译，所以我希望官方可以把文档中代码块部分使用`<code>`标签包裹起来，这样也可以方便我们这些来自其他国家的开发者，最后，我十分希望作者可以采纳我的意见对官方文档进行修改。

-来自中国的开发者 coder Y

**Comment by yaacovCR** [comment]
Per Google Translate, which doesn't seem like an exact match:

>First of all, thank you very much for opening up such a good project for developers to use, and secondly, I have some small suggestions about the official documentation
>
> I am a developer from China. Of course, my English is not very good, and the official document does not provide a Chinese version, so I can only use the translation function of Google Chrome to translate English into Chinese for my own reading, but During the translation process, there was a problem. Google Chrome will also translate the code blocks of the case into Chinese. After checking, it is found that Google Chrome also has a corresponding solution, that is, Google Chrome will not translate `<code` in HTML. The part wrapped in the `>` tag is translated, so I hope that the official can wrap the code block in the document with the `<code>` tag, which is also convenient for us developers from other countries. Finally, I very much hope that the author can adopt me comments to modify the official documentation.
>
> -Developer coder Y from China

**Comment by igrlk** [comment]
✋ The fix is here - https://github.com/graphql/graphql.github.io/pull/1274

**Comment by igrlk** [comment]
The fix has been merged in the docs repo! @yaacovCR should this issue be closed now?
