### ISSUE TITLE
How to define unknown levels of nested fields

### ISSUE THREAD

**Issue by stevehu** [graphql/graphql-js#358]
For a multi-level comment system, you have reply of reply and the depth is different for each comment. In the spec, it looks like you have to define the exact structure of data you want to be returned; however, when you load a list of comments, you don't know if one of them have 10 levels of replies. Is there a way to workaround the current spec or the spec can be extended to support it?

**Comment by helfer** [comment]
I don't think there is, at least not in GraphQL. I think the best way to get the same result is to turn the comments tree into a list via a preorder-traversal. The comment should have an additional field called level (or something like that), which will tell the client how to display it.

**Comment by robrichard** [comment]
I think you could do this by having each comment have a field to get child comments. You could write a query to get as many nested levels as you need for the initial read. I'm imagining a system like reddit where you can view x number of nested comments, then click a link to view more past that.

Implement fields as a function to allow for the circular dependency.
```js
var Comment = new GraphQLObjectSchema({
	name: 'Comment',
	fields: () => ({
		id: GraphQLString,
		comments: new GraphQLList(Comment)
	})
})
```

Load three layers of comments for the initial view:
```
{
	post(id: 1) {
		comments {
			id
			comments {
				id
				comments {
					id
				}
			}
		}
	}
}
```

load three more layers when user clicks "load more comments"
```
{
	comment(id: 2) {
		comments {
			id
			comments {
				id 
				comments {
					id
				}
			}
		}
	}
}
```

**Comment by stevehu** [comment]
It was discussed [here](https://github.com/facebook/graphql/issues/91) and the case was closed.
