### ISSUE TITLE
Include flow definitions in npm package

### ISSUE THREAD

**Issue by alexanderchr** [graphql/graphql-js#359]
I'm currently using a cloned repo to get flow typings but it would be really nice if these were included in the npm package.

The downside is of course that you'd have two copies of the code. Another option would be to provide untranspiled code as a separate package. How do other libs with flow definitions handle this?

**Comment by leebyron** [comment]
Agreed that this would be great.

I'll investigate the current best practice that would avoid us having to maintain a separate type definitions file and export these correctly.

**Comment by JohnyDays** [comment]
I have managed to locally make it work, just by copying every JS source file, alongside it's respective output JS file as .js.flow

**Comment by iamchenxin** [comment]
@alexanderchr @JohnyDays I made a solution ((flow-dynamic)[https://github.com/iamchenxin/flow-dynamic] ) for this . See [pr](https://github.com/graphql/graphql-relay-js/pull/89) i push to `Graphql-relay`((detail code)[https://github.com/graphql/graphql-relay-js/pull/89/commits/94c15ffc261cc73fd77ef64c1f99f9ad2b3c05c4#diff-ca9890ee3978e68ab141ce9e3a0b4232R129]) to resolve type cast between Packages. 
@leebyron please take a moment to see this solution.It has no extra produce-time load. And now it is suitable for output `.js.flow`.Now a typed `graphql` will not break any another package used `graphql`.
Thet just need wrap a check function out side their unchecked functions(which interact with `graphql`). 
Or publish a beta version flow-type output `graphql` for us to use.

**Comment by leebyron** [comment]
**Update:** we're going to make this work! Here's the plan:

The Flow team is supportive of the idea of introducing flow types directly in npm packages. Right now the suggestion is to use the same approach @JohnyDays and @nodkz suggested in #412, however as I understand it in the future they hope to include a tool alongside flow which produces higher quality exported flow types.

My primary concern is safely introducing flow types errors for people who are using graphql-js and flow, but have not yet had an opportunity to check for flow errors. I also would like an opportunity to create a window of time for interested people to contribute feedback about the quality of the flow types before introducing them for all.

Here's the upcoming release plan:

**v0.7.0:** Introduce all latest improvements and changes to graphql-js, but no flow-types.
**v0.8.0-beta:** Shortly after, a beta release will contain flow-types.
**v0.8.0:** After some time for people to test and report any issues, a new non-beta release will contain flow types.

**Comment by JohnyDays** [comment]
Awesome! Looking forward to ditching my ad-hoc solution. Cheers

**Comment by clintwood** [comment]
@leebyron, while slightly off topic, it would be great to include the source in the package and include `jsnext:main` pointing to that source for tools like [RollUp](https://github.com/rollup/rollup).  Thanks.

**Comment by leebyron** [comment]
Some exciting news on this front! v0.7.0 was released a couple weeks ago, and after flow v0.34, the graphql-js codebase should be correctly typed again, so I'm looking into releasing a pre-release for people to test.

**Comment by nodkz** [comment]
If somebody wants to test `NULL` in args and `flowtype` in their app, I built `graphql-js` package on commit https://github.com/graphql/graphql-js/commit/2b717f1405ce04eabd5a44df18b5b9b5cdd80fa3. Just run:
```
npm install https://www.dropbox.com/s/zrd3b00dmx3jhae/graphql-0.7.2.tgz\?dl\=1
```

PS. Yarn does not work with this link (((

**Comment by wincent** [comment]
@leebyron: Do we need to do some additional configuration to include the `*.flow` files in the released package? I can't see them in the 0.8.0-beta1 release.

I don't know how the Travis-mediated publishing works, but I can see we're doing some manual transforming and copying in [resources/prepublish.sh](https://github.com/graphql/graphql-js/blob/9792f75faac6340a9e193c068b962b70e7d453bf/resources/prepublish.sh#L24) and [resource/npm-git.sh](https://github.com/graphql/graphql-js/blob/9792f75faac6340a9e193c068b962b70e7d453bf/resources/npm-git.sh#L9). I am not sure where `build` and therefore `build-dot-flow` get run in relation to all that.

**Comment by leebyron** [comment]
You're right @wincent something went wrong with the npm deploy and the flow files went missing. I'm looking into it :/

**Comment by leebyron** [comment]
Hey @wincent I just published 0.8.0-beta3 which made sure the flow files were in there. Let me know what you learn

**Comment by leebyron** [comment]
@nodkz at any point you can also depend directly on git! https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge

**Comment by leebyron** [comment]
Closing this issue since this is out in beta now - please provide feedback!

**Comment by JohnyDays** [comment]
I'll update my projects and check it out. Thanks @leebyron
