### ISSUE TITLE
On finish hook for resolves

### ISSUE THREAD

**Issue by calebmer** [graphql/graphql-js#360]
In my GraphQL schema, one of my resolvers gets a connection from the database pool and passes that connection down to its child fields. Is there a way to register a callback during resolution to allow me to release the connection back to the pool?

**Comment by calebmer** [comment]
Is there something for this or plans to develop it? If someone could point me in the right direction I could submit a PR.

**Comment by helfer** [comment]
@calebmer Is there a good reason this needs to be done on a per-resolver basis? Couldn't you just do it on a per-query basis? I.e. get the connection and stick it on the context before you start executing the query and release the connection when the whole query is done.

I think that would also be more maintainable than passing it down through the resolve functions. For the GraphQL data stack I'm working on (Apollo), we decided it was best if resolve functions didn't know anything about how the data fetching happens behind the scenes.

**Comment by calebmer** [comment]
The key thing here for my case is composability. Ideally the GraphQL schema I'm developing could be another GraphQL schema's field. This makes context level actions difficult and potentially means multiple copies which need different connections.

A context level cleanup hook would be fine.

**Comment by leebyron** [comment]
Is this something you could do via Promise composition?

Conceptually e.g.:

```js
getConnection().then(connection => performQuery(connection).then(result => {
  releaseConnection(connection);
  return result;
})
```

**Comment by leebyron** [comment]
> I think that would also be more maintainable than passing it down through the resolve functions. For the GraphQL data stack I'm working on (Apollo), we decided it was best if resolve functions didn't know anything about how the data fetching happens behind the scenes.

I think this is pretty sound advice

**Comment by leebyron** [comment]
> get the connection and stick it on the context before you start executing the query and release the connection when the whole query is done.

This is conceptually very similar to how GraphQL operates at Facebook

**Comment by calebmer** [comment]
The tricky thing is if you want a field to control session information such as the authed user. Such a field would need to get a new client connection and pass that connection down to child resolvers.

The project I'm working on would like to see authentication done fully through GraphQL and currently the GraphQL JS API doesn't seem to have a good story for this.

**Comment by leebyron** [comment]
In general we recommend against this kind of schema design because it produces the kind of issues you're running into now. We've also not really encountered reasons for having field-specific context like this. Authentication is a great example of something which typically applies to an entire request, and not just one particular field.

**Comment by leebyron** [comment]
Also, GraphQL intentionally does not have a story for authentication because it's strongly recommended to perform authentication before executing the GraphQL request. The `context` variable provided to resolvers is primarily intended to hold this kind of authentication information.

**Comment by calebmer** [comment]
Ok, thanks for explaining 👍
