### ISSUE TITLE
Including the index while completing an array item

### ISSUE THREAD

**Issue by juancampa** [graphql/graphql-js#362]
Given the following demonstrative schema:

```
let Container = new GraphQLObjectType({
  fields: {
    listOfItems: { type: new GraphQLList(Item) }
  }
});
let Item = new GraphQLObjectType({
  resolve: (source, args, context, info) => { /* I want this item's index here */ }
});
```

I would love to have the ```Item```'s index available in it's ```resolve``` function.

This would be analogous to ```Array.map```, which takes a function with the signature ```mappingFunc(item, index array)```.

Reading through the code I found that it would be easy to add such functionality here https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L783-L790 but I'm not sure what would be the best way to pass down a "context" (an "immediate" context that is, unrelated to the current context argument which is global) to ```resolve```

I'm opening this issue to discuss ideas, alternatives, and eventually put up a PR.

**Comment by helfer** [comment]
FWIW: The fourth argument (info) would probably be the best place to pass that in.

**Comment by JeffRMoore** [comment]
Exploring the idea of eliminating the fieldASTs as a parameter, I ran into the problem of how to report error context.  Another way would be to report the path used to reach the data element from the root.  That might be an array such as  ['users', 3, 'name'].  index is just one element of the path.

**Comment by leebyron** [comment]
I'm curious to better understand *why* you want this info? That may help better holistically understand what we're missing.

**Comment by juancampa** [comment]
> I'm curious to better understand why you want this info?

Good question! In my actual use case, the ```Item``` type serves the same purpose as an "edge" type in Relay, and edges have a ```cursor``` field, which in my case maps directly to the index of the element.

Currently, I'm working around it by generating the "cursor" field while resolving the array itself, but it feels hacky.

Now that I think about it, this "hack" might not be a terrible idea since it abstracts the ```Item``` from its container: the cursor could be whatever makes sense to the container.

Ok, I'm getting ideas as I write this comment so sit tight:

It's clear to me now (yes, after writing the above paragraph) that resolving the cursor belongs in the container, but since the cursor has to be passed down to the edge, the resolve function would look something like this:

```
resolve: (source) => {
   return source.map((item, index) => { item, index });
}
```
And this is exactly what graphql-relay-js does, as you know (see [these 4 lines](https://github.com/graphql/graphql-relay-js/blob/master/src/connection/arrayconnection.js#L106-L109)), however, because of ```map```, this will generate some garbage which could be avoided by letting the edge generate itself, in which case, it would need to know its index.

Let me know if this makes sense, if not, I could try to compile a concrete example.

**Comment by juancampa** [comment]
To be honest I don't think this is an issue so feel free to close it
