### ISSUE TITLE
Set default value for contextValue

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#365]
Following up from https://github.com/graphql/graphql-js/pull/326#issuecomment-200235854 often times it does make sense that the `contextValue` is an object. This is because in addition to an authToken, you might have another token (`resetPasswordToken`, `verifyEmailToken`, etc) or even something like a `socket` for subscriptions. However, if you don't need any of those things, it's still nice to call `graphql(Schema, query)` instead of `graphql(Schema, query, null, {})`. To keep it that way, `execute` should default the value to an object here: https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L115

Thoughts?

**Comment by leebyron** [comment]
I'm not sure I follow. If you don't need any of the things you would put in context, why do you want an object? Also, if you want the empty object, is there something wrong with providing that directly?

**Comment by mattkrick** [comment]
Without an implied guarantee of an object we either need to assure it's there:
`graphql(Schema, query, null, {})`

Or, we need to make sure to code a little more defensively in the `resolve` functions.
For example, in the previous version, a standard resolve might look like:
`resolve(source,args, {rootValue: {authToken}})`

This was great because the rootValue is guaranteed to be an object.

If we try something similar without an object present:
`resolve(source, args, {authToken}) // Broken`

**Comment by leebyron** [comment]
I think if you have any usage of context or rootValue in your schema, then it's reasonable to assume you're providing *something* there, and so it's not necessary to code defensively in resolution functions.

Also in the previous version where rootValue was used in place of context, this situation still existed since rootValue also does not have a default value and is `undefined` if not provided, so `resolve(source,args, {rootValue: {authToken}})` could still be considered broken if a rootValue was not provided.

**Comment by Kosta-Github** [comment]
BTW, the documentation of the `rootValue` (https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L47) is missing in the comment right above the function `graphql()` (https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L28-L41)...

**Comment by Kosta-Github** [comment]
BTW, the documentation of the `contextValue` (https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L47) is missing in the comment right above the function `graphql()` (https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L28-L41)...
