### ISSUE TITLE
sub selection missing

### ISSUE THREAD

**Issue by yoyeung** [graphql/graphql-js#366]
Hi All,
I am studying graphql and the repository in here
[https://github.com/yoyeung/graphql-demo](url)

the schema design is
```
type User{
    id: String,
    name: String,
    age: int,
    post:[Post]
}

type Post{
  id:int,
  title: String,
  editors:[User]
}
``` 
when i try use the query to get the data and i will get this error.
http://localhost:3000/graphql?query={posts{id,title,editors}}
```
{
  "errors": [
    {
      "message": "Field \"editors\" of type \"[User]\" must have a sub selection.",
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ]
    }
  ]
}

```
I already set editors inside the Post type.
But i don't know why have this issue?

Because in my schema design, there have cross reference situation.
So it's because of my setting problem or library issue?

Thanks

**Comment by helfer** [comment]
editors returns a list of users. User is an object type, so you must specify which fields of User you want included in your response, for example like this:
```
{
  posts {
    id
    title
    editors {
      id
      name
    }
  }
}
```

In GraphQL, any non-scalar field must have a sub-selection, which means you have to put a { ... } after it, specifying which fields of that type you want.

**Comment by yoyeung** [comment]
Thx @helfer.
