### ISSUE TITLE
Codesandbox - TypeError: Cannot read properties of undefined (reading 'FIELD')

### ISSUE THREAD

**Issue by MrDoomBringer** [graphql/graphql-js#3685]
Looks like at Version 16, the `graphql` module stopped functioning in CodeSandbox. 
Any import statement will throw the TypeError `Cannot read properties of undefined (reading 'FIELD')`
Has anyone had any experience with this?

Example of this issue:
https://codesandbox.io/s/graphql-field-error-eih7xb?file=/src/index.js

**Comment by IvanGoncharov** [comment]
Fixed in https://github.com/graphql/graphql-js/releases/tag/v16.6.0
