### ISSUE TITLE
Introspection query field 'location' on type 'directive' returns an error

### ISSUE THREAD

**Issue by nikhilaravi** [graphql/graphql-js#369]
An introspection query using the `introspectionQuery` from `graphql/utilities` returns this error. 
```
[
  {
    "message": "Cannot query field \"locations\" on type \"__Directive\"."
  }
]
```
referring to this line in the query: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L26

I instead tried using the introspectionQuerySansSubscriptions from `graphiql` and it works as expected. https://github.com/graphql/graphiql/blob/2824165499f2706d3ccc70ee51bf2bb5fa045fba/src/utility/introspectionQueries.js

I just wanted to know if there is an explanation for why the introspectionQuery from graphql utilities fails.

**Comment by leebyron** [comment]
Can you include more information? Is your server running graphql-js? What version? The `locations` field was added in version v0.5.0 as part of complying with the April 2016 draft of the spec which added it.

**Comment by nikhilaravi** [comment]
@leebyron ah thanks for the speedy response, I think the different graphql versions were causing the problem! I'm closing the issue.
