### ISSUE TITLE
[Question] why do some intermediate nodes have no parent? 

### ISSUE THREAD

**Issue by zhaojunz** [graphql/graphql-js#370]
I was reviewing the kitchen sink test in visitor_test.js. The question that I have is that 

`    

  [ 'enter', 'OperationDefinition', 0, undefined ],
      [ 'enter', 'Name', 'name', 'OperationDefinition' ],
      [ 'leave', 'Name', 'name', 'OperationDefinition' ],
      [ 'enter', 'VariableDefinition', 0, undefined ],
`

Shouldn't the parent of OperationDefinition to be Document? and maybe VariableDefinition's parent to be OperationDefinition? 

I probably should the visit code a little bit more, but I just hope that I understand the parent argument clearly. 

Thanks a lot!

**Comment by leebyron** [comment]
They do have a parent, it just is not a node, it is an array - since array's don't have `kind`, we log `undefined` there.

When a node is visited which is an entry into an array, that array is provided as the `parent`.

**Comment by zhaojunz** [comment]
Interesting, thanks!
