### ISSUE TITLE
Resolve function should take Object instead of 3 to 4 arguments

### ISSUE THREAD

**Issue by SunnyGurnani** [graphql/graphql-js#374]
0.5.0 is a bummer. A breaking change just for sequence of arguments.

Since Graphql is ever evolving and I am sure many new good things will come so why don't we design our functions to take a single input argument instead of 3 to 4 arguments ?

```
resolve: input => {
    input.parent;
    input.rootValue;
   input.context;
   input.args;
}
```

**Comment by leebyron** [comment]
Unfortunately this would be just yet another breaking API change which we would really like to avoid. It would also require us to create a new JS object every time we call a resolve function, which could create additional memory pressure.

We're now in a state where our resolve function API is stable for this library.
