### ISSUE TITLE
process is not defined in browsers

### ISSUE THREAD

**Issue by justinfagnani** [graphql/graphql-js#3758]
Even though this seems to have been at least partially addressed in https://github.com/graphql/graphql-js/pull/1058 there are still references to `process` in the code, like https://github.com/graphql/graphql-js/blob/main/src/jsutils/instanceOf.ts#L12 that cause errors when loading modules in the browser.

**Comment by yaacovCR** [comment]
Can you include more details about the error you are experiencing? The ? operator in the line you referenced is supposed to help avoid an error is process is undefined...

**Comment by Andarist** [comment]
It's worth noting here that nowadays `package.json#exports` are a perfect replacement for the `process.env.NODE_ENV !== 'production'` convention (at the expense of complicating the build process)

**Comment by abooayoob** [comment]
@Andarist Can I ask for any pointers on what this means? _package.json#exports are a perfect replacement for the process.env.NODE_ENV !== 'production'_

**Comment by justinfagnani** [comment]
If means that your default export condition can be the production build and the `'development'` export condition can be the development build.

**Comment by yaacovCR** [comment]
> The action here may be to release the `16.x` version that contained the #3501 fix so you don't have to go full major bump that's currently in alpha tag.
> 
> Let me know if I can help. I would love to see this fixed.

Backporting #3501 to the 16.x branch seems like a great idea. A PR would definitely be appreciated and then we can ping @IvanGoncharov for a release. Thanks!

**Comment by kettanaito** [comment]
@yaacovCR, the pull request with the backport for 16.x is open at #3887. cc @IvanGoncharov, if I may, I would appreciate a quick look at that fix to unblock MSW and other consumers experiencing this issue. Thanks!

**Comment by JoviDeCroock** [comment]
This is fixed in https://github.com/graphql/graphql-js/pull/4022 and published in GraphQL 16.8.2, you can find the instructions for various bundlers [here](https://github.com/graphql/graphql-js/blob/16.x.x/website/docs/tutorials/going-to-production.md) on how to remove it in production.
