### ISSUE TITLE
Types use implements and directives at the same time to report an error

### ISSUE THREAD

**Issue by 759325100** [graphql/graphql-js#3765]
# Questions regarding how to use GraphQL

I want to use directives on types, and implements interfaces, but I get an error

my code is:
type User @inherits(type: ["BaseUser"]) implements IUser {
  UserName: String
}

error info is:
{
      "code": "ERR_UNKNOWN",
      "message": "Syntax Error: Unexpected Name \"implements\".",
      "stack": "GraphQLError: Syntax Error: Unexpected Name \"implements\".\n....."
}

Is there a problem with my grammar?

**Comment by yaacovCR** [comment]
I think it’s the square brackets
