### ISSUE TITLE
Version v16.6.0 breaking IE11

### ISSUE THREAD

**Issue by Richacinas** [graphql/graphql-js#3768]
When using that version of this library, our bundle seems to be broken for older browsers like IE11.

The problem seems to be at this class declaration (which of course IE11 doesn't run):

```
class GraphQLError extends Error { ...
```

It throws a *Syntax error* in console:

![image](https://user-images.githubusercontent.com/7046504/198548783-49e8fa3b-5e16-4168-b68f-0c93020915e1.png)

**Comment by Richacinas** [comment]
Downgraded to v15.4.0.

It is working again...

Something has broken since v16.x.x.

**Comment by JoviDeCroock** [comment]
No version in 16.x.x supports IE11 and with its deprecation I think it's safe to say that we have gone past its support in libraries.

You can always force a library to support IE11 by adding it in your transpilation step, in our case it should be limited to adding class transpilation.
