### ISSUE TITLE
Allow '.' as part of field name for type?

### ISSUE THREAD

**Issue by stevewillard** [graphql/graphql-js#378]
Is there any chance a '.' could be added to this regex in assertValidName.js?
```
const NAME_RX = /^[_a-zA-Z][_a-zA-Z0-9]*$/;
```

Use case:
Flattening a JSON object, and using nested keys as field names in a GraphQL schema:

```
{
  "foo": "test",
  "bar": {
    "test1": 1,
    "test2": 2
  }
}
```
to fields:
```
foo
bar.test1
bar.test2
```

**Comment by dschafer** [comment]
We tried to ensure that field names would be valid identifiers in most languages (that's among the reasons why it cannot start with [0-9], as that would rule out C Identifiers); this ensures that it is possible and reasonable to generate model objects that correspond to GraphQL objects.

Concretely, in JS, it's nice to be able to take a GraphQL response like:

```json
{
  "a": "b",
  "c": 1
}
```

and access the fields with `object.a` and `object.c`. If the field name were "bar.test1", we would have to do `object["bar.test1"]`.

https://github.com/taion/graphql-type-json might be helpful; that implements a custom scalar type that represents a JSON value?
