### ISSUE TITLE
Link to the new API docs from somewhere prominent

### ISSUE THREAD

**Issue by hwillson** [graphql/graphql-js#3780]
I had a really hard time finding the location of the new API docs: https://graphql-js.org/

I can submit a PR to add the link to the README, but updating this repo's About section is likely a better place:

![CleanShot 2022-11-18 at 10 23 20](https://user-images.githubusercontent.com/137740/202739694-39b43294-7dd9-4d5c-8f74-a5ba6d3b8707.png)

**Comment by JoviDeCroock** [comment]
This is now shown on the base-readme
