### ISSUE TITLE
`validate` does not check that selection sets are non-empty

### ISSUE THREAD

**Issue by berkowitze** [graphql/graphql-js#3790]
The `validate` function does not find any issues if you pass an AST with an empty selection set for an object/interface field.

Running into this when building a query ast based on a form, and toggling form fields sometimes lead to an empty selection set. I'm going to properly handle "empty" selection sets (by removing the node from the ast), but it being caught by validation would be really nice as well as a backup and for correctness.

From [the spec](https://spec.graphql.org/draft/#sel-EALRHHDDBDFAADFBAy5W):
> If selectionType is an interface, union, or object:
The subselection set of that selection must NOT BE empty.

Repro ([sandbox](https://codesandbox.io/s/festive-cray-95jz9v?file=/src/index.ts)):
```ts
import {
  buildSchema,
  DocumentNode,
  Kind,
  OperationTypeNode,
  validate
} from "graphql";

const s = `
type Query {
  dog: Int
}

schema {
  query: Query
}
`;

const schema = buildSchema(s);

const query: DocumentNode = {
  kind: Kind.DOCUMENT,
  definitions: [
    {
      kind: Kind.OPERATION_DEFINITION,
      operation: OperationTypeNode.QUERY,
      selectionSet: {
        kind: Kind.SELECTION_SET,
        selections: []
      }
    }
  ]
};

console.log(validate(schema, query)); // outputs `[]`
```

Happy to fix this but this would be my first OSS contribution so wanted to ask:
- Is this the right place to post this?
- Is this actually an issue?
- What is the general approach to a fix?
- What is the right wording for any error messaging?

**Comment by yaacovCR** [comment]
This seems like a bug!

**Comment by yaacovCR** [comment]
It seems like from the section you are quoting that the ScalarLeafsRule was co-opted in the spec to also say something about non-leaf types and then did not get implemented. We may need another rule, but it might pay to discuss at a wg meeting whether the spec text should be divided as well.

**Comment by JoviDeCroock** [comment]
Technically this case is covered by the parser already so we'd have to manually construct the AST. I do think it's worth covering this case though, in case a consumer is using an alternative parser

**Comment by JoviDeCroock** [comment]
Added in v17 on `main` thank you for reporting! We'll also bring this up at a WG meeting
