### ISSUE TITLE
GraphQLObjectTypeNormalizedConfig not exported

### ISSUE THREAD

**Issue by oscarthorn** [graphql/graphql-js#3853]
Hi!

It seems `GraphQLObjectTypeNormalizedConfig` is not being exported in [src/type/definition.ts](https://github.com/graphql/graphql-js/tree/main/src/type/definition.ts). Is this an oversight? For example `GraphQLInterfaceTypeNormalizedConfig` is being exported so it is unclear why `GraphQLObjectTypeNormalizedConfig` is not. Both are return types for `toConfig()` functions.

Thanks!

**Comment by yaacovCR** [comment]
@IvanGoncharov fwiw I agree we should be consistent here :)
