### ISSUE TITLE
Nested List Input Coercion not matching GraphQL spec

### ISSUE THREAD

**Issue by abhinand-c** [graphql/graphql-js#3858]
There seems to be a deviation of Nested List Input Coercion in GraphQL library and the GraphQL specification.

The fix for the same is raised in a PR in https://github.com/graphql-python/graphql-core/pull/194 

(This was my first time contributing to GraphQL core library, sorry for missing out on the recommended practice of raising a issue and engaging proper discussion here)

------

> For a nested List ` [[Int!]] `, providing an input value of `[1, 2, 3] `
> **[Expected Behaviour](https://spec.graphql.org/October2021/#sel-HAHjBJLDLEBAAADFAb0le):** should raise validation error
> **Current Behaviour:** coerce value to `[ [1], [2], [3] ]`
> ### Refer: 
> - https://spec.graphql.org/October2021/#sec-List.Input-Coercion
> 
> <img width="607" alt="image" src="https://user-images.githubusercontent.com/44578852/222537258-29541a2e-b652-4d8a-8d11-946ad6f8fcd7.png">

**Comment by Cito** [comment]
I think @abhinand-c is right, the test [here](https://github.com/graphql/graphql-js/blob/e171a14c6f19140d8667e8bbfb4237b72b16b2dc/src/utilities/__tests__/coerceInputValue-test.ts#L398-L401) contradicts the above spec. Probably because the spec was changed in 2018 and the test followed the older spec of 2016.

**Comment by abhinand-c** [comment]
Hi @yaacovCR @Cito 
Is there anything that I could do to help, and possibly speed things up?

**Comment by abhinand-c** [comment]
Sure✨, I'll add this to the WG Meeting agenda, and join the meeting.

**Comment by abhinand-c** [comment]
I think you have covered everything @yaacovCR and I hope we can merge this PR once we get feedback from @leebyron

**Comment by abhinand-c** [comment]
@yaacovCR @leebyron  Was there any further discussion on clarifying the spec?

**Comment by yaacovCR** [comment]
Not that I am aware of.

**Comment by yaacovCR** [comment]
Tracked at https://github.com/graphql/graphql-spec/pull/1057

**Comment by yaacovCR** [comment]
Note: this was ultimately changed into the spec as an update to the version presented in the table, so there is no need to update the reference implementation.
