### ISSUE TITLE
serialize from GraphqlScalarType not allow to return null

### ISSUE THREAD

**Issue by xs3213213213** [graphql/graphql-js#3870]
i am using the version 16.6.0
I have implemented: GraphqlScalarType  like this:

`
```
export const IntScalar = new GraphqlScalarType ({
   ...GraphQLInt,
    serialize(value) {
       if(value === 10000) {
          return null;
       }

    return value;
   }

})
```

`

im getting expected IntScalar.Serialize(10000) to return non-nullable value retrun null

why cant i return null?

**Comment by IvanGoncharov** [comment]
@xs3213213213 Because scalars values are different from null.
You can't mix custom scalar values and null, see here:
https://spec.graphql.org/draft/#sel-EANTLEHJIMDJBA58K
