### ISSUE TITLE
Add validation rules to check for deprecated fields

### ISSUE THREAD

**Issue by stubailo** [graphql/graphql-js#389]
The same way this package includes a validation rule to check for unknown fields, it might be valuable to be able to check for deprecated fields as well.

**Comment by 0xR** [comment]
Shouldn't bee hard according to @leebyron:
https://twitter.com/leeb/status/725429815625408512

**Comment by helfer** [comment]
@0xR if you do it, make sure it's not part of specified rules, because those will make the query fail by default. It should be an optional rule that people can import.

**Comment by stubailo** [comment]
Should be really easy to copy this rule and modify it a bit: https://github.com/graphql/graphql-js/blob/master/src/validation/rules/FieldsOnCorrectType.js
