### ISSUE TITLE
Are there some plans to land flow-type exports in v0.6.0?

### ISSUE THREAD

**Issue by iamchenxin** [graphql/graphql-js#390]
Without standard flow-type outputs in `graphql`'s package.
Some packages dependent on `graphql` get more and more wrong flow-type check.(used wrong type but type-check passed in that package).

Ex: [graphql-relay-js](https://github.com/graphql/graphql-relay-js),It used a subset of graphql.
But cause there is no flow-type output in `graphql`'s standard npm package, so `graphql-relay-js` can do type check arbitrarily, this will lend to some bugs.
Like `graphql-relay-js`  : 
```
type typeResolverFn = (object: any) => ?GraphQLObjectType |
                      (object: any) => ?Promise<GraphQLObjectType>; // wrong ? type can not be resolved with a Promise?
```
vs `grapgql`'s
```
export type GraphQLTypeResolveFn = (
  value: mixed,
  context: mixed,
  info: GraphQLResolveInfo
) => ?GraphQLObjectType
```

And also if there are type-outputs in `graphql`
Something in `graphql`[(L469)](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L469):
```
export type GraphQLFieldResolveFn = (
  source: mixed,
  args: {[argName: string]: mixed}, // should be modified to args:Object or some template?
  context: mixed,
  info: GraphQLResolveInfo
) => mixed

```
would be narrowed rightly in `graph-relay` like this:
```
type RelayFieldResolveFn = (
   source: Object,
   args: {'input':Object},
   context: mixed,
   info: GraphQLResolveInfo
 ) => mixed
```

**Comment by leebyron** [comment]
Merging into #359
