### ISSUE TITLE
Returning too large of a number from Int resolver results in hard to debug errors

### ISSUE THREAD

**Issue by stubailo** [graphql/graphql-js#391]
If I have a field that is supposed to return `GraphQLInt`, then there are two hard-to-debug things that can happen if I return a number that's not within the allowed range, for example `1463692053071` (a timestamp):

1. If the field is optional, then I simply get `null` on the client with no errors at all
2. If the field is required, then I get the error: `Cannot return null for non-nullable field Entry.createdAt.` This is extra misleading since I didn't actually return `null` - I returned a Number that was simply too large.

Sounds like this can just be fixed by adding an error in the coerceInt function instead of silently returning `null`.

**Comment by uhoh-itsmaciek** [comment]
I ran into this same problem and [commented on another related issue](https://github.com/graphql/graphql-js/issues/292#issuecomment-223720563). As I point out there, I think that behavior is in violation of [the spec](https://facebook.github.io/graphql/#sec-Int):

>GraphQL servers should coerce non‐int raw values to Int when possible **otherwise they must raise a field error**. Examples of this may include returning 1 for the floating‐point number 1.0, or 2 for the string "2".

(emphasis added)

Would you accept a patch fixing this behavior?

**Comment by leebyron** [comment]
Hey, I really apologize for letting this issue sit. You're absolutely correct @uhoh-itsmaciek that this is a real bug relative to the correct spec language.

I've attached a PR to fix it.

**Comment by uhoh-itsmaciek** [comment]
Awesome, thanks @leebyron!
