### ISSUE TITLE
Broken source code URL in API docs

### ISSUE THREAD

**Issue by vwkd** [graphql/graphql-js#3914]
The source code URLs in the [API docs](https://graphql-js.org/api) are broken. The host is `undefined` instead of `github.com`. For example, 

https://graphql-js.org/api#ASTKindToNode

links to

https://undefined/graphql/graphql-js/blob/master/language/ast.ts#L191

**Comment by kumarUjjawal** [comment]
I would be happy to fix this if it's open to contribution from the public.

**Comment by mkraft** [comment]
It's still undefined for me.

<img width="1439" alt="Screenshot 2023-09-11 at 6 19 50 PM" src="https://github.com/graphql/graphql-js/assets/1149597/b5a7e7c2-e4ae-405c-b69c-160e8d8f8152">

**Comment by JoviDeCroock** [comment]
Those docs are deprecated, in https://github.com/graphql/graphql-js/issues/4200 we'll set up a redirect to the new ones which you can find at https://graphql.org/graphql-js/graphql/
