### ISSUE TITLE
Syntax error in Nuxt project due to graphql-js pull request #3887

### ISSUE THREAD

**Issue by okaufmann** [graphql/graphql-js#3919]
Hi

It looks like https://github.com/graphql/graphql-js/pull/3887 is causing problems in my Nuxt project. When compiled, there is a syntax error which breaks the app completely:
![CleanShot 2023-06-22 at 00 18 38](https://github.com/graphql/graphql-js/assets/4414498/fc51e99c-5408-466c-9908-07466ad0ab68)

```javascript

((_globalThis$process = globalThis.process) === null || _globalThis$process === void 0 ? void 0 : _globalThis$"development") === "production" ? function instanceOf2(value, constructor) {
      return value instanceof constructor;
    }
```

v16.6.0 works perfectly.

I cannot verify if this is only a problem when used with Nuxt or not.

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.5.3
- Nitro Version:    2.5.0
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      app, runtimeConfig, tailwindcss, components, modules, auth, devtools, formkit, postcss, vite, build
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @vueuse/nuxt@10.2.0, @sidebase/nuxt-auth@0.6.0-beta.2, @formkit/nuxt@0.17.3, nuxt-graphql-client@0.2.27, @pinia/nuxt@0.4.11, @nuxt/devtools@0.6.2
- Build Modules:    -

**Comment by tnyo43** [comment]
I ran into the same problem with a React project.

**Comment by thepassle** [comment]
It looks like the code published by graphql is fine: https://unpkg.com/browse/graphql@16.7.0/jsutils/instanceOf.mjs

<img width="725" alt="image" src="https://github.com/graphql/graphql-js/assets/17054057/96f2a16b-d1e7-4232-93b9-c6cb5adc72c6">

And can be imported as is without any problems:

<img width="542" alt="image" src="https://github.com/graphql/graphql-js/assets/17054057/0cad8b9e-da14-4d4c-a494-7fed01bc3f4e">

So it almost feels like a bug in whatever is transpiling your project, which (judging from your screenshot) also looks like esbuild output. However, running the same code through esbuild again, doesn't result in the error for me:
<img width="1684" alt="image" src="https://github.com/graphql/graphql-js/assets/17054057/6d8a33b9-9345-4167-9163-1dd7b70c4ff6">

Do you know which esbuild configuration options your build process uses? And are there are tools that may transpile/compile your code?

**Comment by Josef-Reichardt** [comment]
I ran into the same issue in a vite / vue / ts project after upgarding from `16.6.0` to `16.7.0`. Unfortunately I'm not able to reproduce the issue in a fresh project. So I'm not sure which combination of libs or tool is the reason for this error.

I'm using node v18.14.0, yarn 1.22.19, vite 4.3.9, vue 3.3.4, typescript 5.1.3, vue-tsc 1.8.1, @esbuild-plugins/node-globals-polyfill 0.2.3, @esbuild-plugins/node-modules-polyfill 0.2.2, and many more ...

The issue only appears if I run the application in dev mode. The production build works fine. 🤔

**Comment by mpgalaxy** [comment]
> It looks like the code published by graphql is fine: https://unpkg.com/browse/graphql@16.7.0/jsutils/instanceOf.mjs
> 
> <img alt="image" width="725" src="https://user-images.githubusercontent.com/17054057/247833611-96f2a16b-d1e7-4232-93b9-c6cb5adc72c6.png">
> And can be imported as is without any problems:
> 
> <img alt="image" width="542" src="https://user-images.githubusercontent.com/17054057/247833656-0cad8b9e-da14-4d4c-a494-7fed01bc3f4e.png">
> So it almost feels like a bug in whatever is transpiling your project, which (judging from your screenshot) also looks like esbuild output. However, running the same code through esbuild again, doesn't result in the error for me: <img alt="image" width="1684" src="https://user-images.githubusercontent.com/17054057/247833913-6d8a33b9-9345-4167-9163-1dd7b70c4ff6.png">
> 
> Do you know which esbuild configuration options your build process uses? And are there are tools that may transpile/compile your code?

**Are you sure the code is fine ?** Shouldn't it be 
```javascript
: _globalThis$(process.env.NODE_ENV) === 'production'
``` 
? ;)

**Comment by thepassle** [comment]
Yeah, I'm sure the code is fine. Why do you think it should be something else?

**Comment by Vincz** [comment]
Same here. The generated code is invalid, a `(` is missing.

**Comment by thepassle** [comment]
> Same here. The generated code is invalid, a `(` is missing.

Aha, I see what you're saying. That makes sense indeed. I imported the module in a browser to check for syntax errors, and when I saw none I assumed that the code was correct, but didnt actually verify the logic.

That would mean the issue is likely somewhere in the buildtooling that graphql uses internally. I try to see if I can figure out where exactly this is going wrong.

**Comment by thepassle** [comment]
I cloned the `main` branch, ran `npm install` and ran a `npm run build:npm`, but I don't seem able to reproduce it. The output looks as follows:
![image](https://github.com/graphql/graphql-js/assets/17054057/da80e5a2-29e6-4015-a9a1-8be98006bb3f)

But the output as published on npm has some transpiled code in it:
<img width="675" alt="image" src="https://github.com/graphql/graphql-js/assets/17054057/bc91aa74-093e-4233-bc03-3af1ad7990eb">

So I'm unable to reproduce it locally. I also checked the ci files to see if maybe any transpilation is happening before publishing, but that also doesnt seem to be the case.

I also noticed that the tsconfig options were recently changed from `es2020` to `es2021` and `es2022`, so I tried running the build with version `es2020` to see if that caused the issue, but that also didnt seem to be the case.

So its not clear to me where the transpilation of optional chaining is taking place. Maybe a maintainer (or anybody else) can also try to verify my findings by locally installing and running a build, and checking `npmDist/jsutils/instanceOf.mjs`?

**Comment by razorness** [comment]
@thepassle if you replace 

https://github.com/graphql/graphql-js/blob/d766c8eb34fb03c5ee63c51380f2b012924e970c/src/jsutils/instanceOf.ts#L12

against ` process.env.NODE_ENV === 'production'`, the npm build looks the same as of [`v16.6.0`](https://unpkg.com/browse/graphql@16.6.0/jsutils/instanceOf.mjs):

![image](https://github.com/graphql/graphql-js/assets/684302/0c82077e-85cc-45d3-a107-d34aa8d9bd4e)

**Comment by thepassle** [comment]
Indeed :) but then the module will still not be able to run in a browser (which is the case for MSW), because the `process` global doesnt exist there

**Comment by IvanGoncharov** [comment]
@okaufmann It's an issue with Nuxt internals, but I added a workaround for it in `16.7.1` Can you please confirm that it is fixed?

**Comment by razorness** [comment]
It works now with ViteJS `v4` (esbuild). But: since you always expect `globalThis.process` to be existend, isn't it the case that the code never reaches `globalThis.process.env.NODE_ENV === 'production'` in browser?

**Comment by IvanGoncharov** [comment]
> It works now with ViteJS `v4` (esbuild). But: since you always expect `globalThis.process` to be existend, isn't it the case that the code never reaches `globalThis.process.env.NODE_ENV === 'production'` in browser?

@razorness For that, you need to define `NODE_ENV` to `production` (done by default in most of bundlers).

**Comment by okaufmann** [comment]
> @okaufmann It's an issue with Nuxt internals, but I added a workaround for it in `16.7.1`
> 
> Can you please confirm that it is fixed?

@IvanGoncharov Thanks for the quick fix it does work perfectly again 🎉

**Comment by WulfP** [comment]
Running into the same issue with quasar 2.12.2 / vite.

Not sure if it is an issue if bundlers replace `process.env.NODE_ENV`. 
I would expect the bundlers to do this.

I created a very simple workarround:

Just change 

   `globalThis.process.env.NODE_ENV === 'production'`

to

   `globalThis.process.env['NODE_ENV'] === 'production'` 
   
and everything works fine because nothing is replaced unexpectedly.

For an instant fix you can run 

`sed "s/process\.env\.NODE_ENV/process.env['NODE_ENV']/g" ./instanceOf.mjs` 

manually or use this script

> #!/bin/bash
fileBase='./node_modules/graphql/jsutils/instanceOf'
mv "${fileBase}.mjs" "${fileBase}.tmp"
sed "s/process\.env\.NODE_ENV/process.env['NODE_ENV']/g" "${fileBase}.tmp" > "${fileBase}.mjs"
rm "${fileBase}.tmp"

in your build-pipline. 

Don´t forget to delete the build-cache after patching the file, in my case `rm -rf node_modules/.q-cache/` does the job.

**Comment by hipertracker** [comment]
Hacking node_module? It's not the best idea.

**Comment by WulfP** [comment]
> Hacking node_module? It's not the best idea.

Imo this is a patch, not a hack. And perfectly fine to handle smaller bugs like this.
But I notice that we have very different opinions.

Maybe quasar does not work like you would expect. Ok.
But I do not think that it "fails miserably".

In my current project, I replaced Nuxt / Vuetify / Apollo, a horrible combination by quasar / graphql-codegen. 
I´m very happy with this decision. Better documentation, better component integration (imo Vuetify is miserable there),
no problems (except the reported one).

Yes, consider quasar as the answer to Nuxt / Vuetify but you are free to stick on your well-known solutions.

**Comment by asantTMC** [comment]
Experiencing the same issue in a React 18 + Vite 4.1 project. Updating Vite to >=4.2 solves the issue regardless of the graphql version
