### ISSUE TITLE
graphql-js v16.7.0 breaks the compilation of SvelteKit

### ISSUE THREAD

**Issue by docseltsam** [graphql/graphql-js#3920]
I use graphql-js in a webapp using SvelteKit. After updating from version 16.6.0 to version 16.7.0 my app does not work anymore. 

As far as I analyzed this correctly, the problem seems to be the change in src/jsutils/instanceOf.ts

from

```
  process.env.NODE_ENV === 'production'
```

to
```
  globalThis.process?.env.NODE_ENV === 'production'
```

SvelteKit seems to replace env.NODE_ENV by the string "development" or "production" on compiling the sources and that ends up in the following invalid code

```
var instanceOf = (
  /* c8 ignore next 6 */
  // FIXME: https://github.com/graphql/graphql-js/issues/2317
  ((_globalThis$process = globalThis.process) === null || _globalThis$process === void 0 ? void 0 : _globalThis$"development") === "production" ? function instanceOf2(value, constructor) {
...
```

the old version of instanceOf lead to this code

```
var instanceOf = (
  /* c8 ignore next 6 */
  // FIXME: https://github.com/graphql/graphql-js/issues/2317
  // eslint-disable-next-line no-undef
  false ? function instanceOf2(value, constructor) {
...
```

I don't know why this change was made so unfortunatly I don't really know how to fix this the best way. In my opionen it would by nice, if this part could be reversed to this old implementation.

**Comment by racc-oo-n** [comment]
I have the same error using [vitejs](https://vitejs.dev/)

**Comment by docseltsam** [comment]
Since I use SvelteKit with Vite, it could be a problem in conjunction with Vite and not SvelteKit.

**Comment by racc-oo-n** [comment]
https://github.com/vitejs/vite/issues/13597

I think there is a solution to our problem 😄

**Comment by IvanGoncharov** [comment]
@docseltsam It's an issue with SvetleKit internals, but I added a workaround for it in `16.7.1` Can you please confirm that it is fixed?

**Comment by vhatsura** [comment]
I can confirm that the workaround added into `16.7.1` resolves the issue with Vite

**Comment by docseltsam** [comment]
I can also confirm that the workaround in ```16.7.1```solves the issue with my app. Thank you very much for your help.
