### ISSUE TITLE
GraphQL 16.7.0 breaks Vue3/Vite3

### ISSUE THREAD

**Issue by UglyHobbitFeet** [graphql/graphql-js#3921]
When I upgrade my package.json, Vue no longer works as expected.  (I get a blank screen instead of rendering my html/divs). Depending on browser console output I get a different error:

Chrome: Error with npm: [vite] Internal server error: Unexpected string

Firefox: Parsing error in the graphql stuff. Missing a )

**Comment by IvanGoncharov** [comment]
@UglyHobbitFeet It's an issue with Vue internals but I added a workaround for it in `16.7.1` Can please confirm that it is fixed?

**Comment by UglyHobbitFeet** [comment]
confirmed, it is fixed!

**Comment by IvanGoncharov** [comment]
@UglyHobbitFeet Thanks 👍
