### ISSUE TITLE
dead code from `instanceOf.ts` is not tree shaked for browser due `globalThis.process`

### ISSUE THREAD

**Issue by dimaMachina** [graphql/graphql-js#3925]
after https://github.com/graphql/graphql-js/pull/3923 and https://github.com/graphql/graphql-js/pull/3501 dead code from [instanceOf](https://github.com/graphql/graphql-js/blob/main/src/jsutils/instanceOf.ts) is no longer tree shaked for browsers

@IvanGoncharov wrote

> Bundlers incorrectly replace (probably RegExp) process.env.NODE_ENV with "development" resulting in:
> ```
> (_globalThis$process = globalThis.process) === null ||
> _globalThis$process === void 0
>   ? void 0
>   : _globalThis$"development";
> ```
but this happens only when using `globalThis.process.env.NODE_ENV`

**Comment by vdineva** [comment]
Any update on this issue? It's not allowing up to upgrade to newer versions of graphql

**Comment by radesai21** [comment]
Can we get an update on this? This is a security warning caused by this https://github.com/advisories/GHSA-9pv7-vfvm-6vr7

**Comment by JoviDeCroock** [comment]
For now you can use something like [`rollup-plugin-replace`](https://www.npmjs.com/package/@rollup/plugin-replace) or the equivalent in your own bundler to do the following

```
{
  `globalThis.process`: JSON.stringify(true),
  `globalThis.process.env.NODE_ENV`: JSON.stringify("production"),
}
```

after #4022 most bundlers will be covered however it is possible you will need the following in some

```
{
  `typeof process`: JSON.stringify('object'),
  `process.env.NODE_ENV`: JSON.stringify("production"),
}
```

**Comment by JoviDeCroock** [comment]
Hey @dimaMachina #4022 is live in the latest 16.x.x line, does this solve your issue?
