### ISSUE TITLE
请问字段可否支持多语言 Can the field support multiple languages?

### ISSUE THREAD

**Issue by Duanxs** [graphql/graphql-js#3933]
目前，Graphql 不支持中文字段，使用上略有不便。像 mysql、mongoDB 均支持多语言字段名，希望 Graphql 也跟进，以方便全球各语言用户。

machine translation: 
Currently, Graphql does not support Chinese fields, which is slightly inconvenient. Like mysql and mongoDB, they support multilingual field names, and I hope that Graphql will follow suit to facilitate users in various languages around the world.

报错样例：

``` graphql
type 用户 {
    姓名: String!
}
```

```
GraphQLError: Syntax Error: Unexpected character: U+7528.
    at syntaxError (/path/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/error/syntaxError.js:15:10)
    at readNextToken (/path/node_modules/.pnpm/graphql@16.7.1/node_modules/graphql/language/lexer.js:420:28)
...
```

**Comment by saihaj** [comment]
there have been many discussion and progress being made to support for Unicode 
- https://github.com/graphql/graphql-spec/issues/256
- https://github.com/graphql/graphql-spec/issues/687
- https://github.com/graphql/graphql-js/pull/3117
- https://github.com/graphql/graphql-js/pull/3322

**Comment by alex-kinokon** [comment]
The main issue has been open for 8 years so I wouldn’t count on it.

**Comment by JoviDeCroock** [comment]
Let's keep this covered under the Spec discussions as we currently just follow the spec. https://github.com/graphql/graphql-spec/issues/256
