### ISSUE TITLE
Unexpected string (at @apollo_client.js?v=:1230:51) in browser

### ISSUE THREAD

**Issue by bricekams** [graphql/graphql-js#3934]
# Error in dev tools

![Screenshot from 2023-07-11 12-54-08](https://github.com/graphql/graphql-js/assets/120424696/4383609c-ce94-4a0a-92f9-2dbc108c67d3)

## Dependencies 
![Screenshot from 2023-07-11 12-57-48](https://github.com/graphql/graphql-js/assets/120424696/bc6aebb5-9acd-4eba-89cb-64327f4f8032)

## Environments:
- node: v18.16.0
- npm: 9.5.1
- yarn: 1.22.19
- pnpm: 8.3.1

**Comment by JoviDeCroock** [comment]
This is fixed in https://github.com/graphql/graphql-js/pull/4022 and published in GraphQL 16.8.2, you can find the instructions for various bundlers [here](https://github.com/graphql/graphql-js/blob/16.x.x/website/docs/tutorials/going-to-production.md) on how to remove it in production.
