### ISSUE TITLE
refactor(src): remove `.js` extension, append it for compiled files

### ISSUE THREAD

**Issue by GervinFung** [graphql/graphql-js#3935]
I believe this thing is common, it's weird to import `.js` file when typescript files are imported/exported in `src` folder, and `tsc` should auto append the file extension for us, however, this problem can be solved with [ts-add-js-extension](https://github.com/GervinFung/ts-add-js-extension). Do take a look at it and let me know what u think

**Comment by yaacovCR** [comment]
I agree 100% that it’s weird, but since we appear to be managing so far, I think we will probably avoid adding another dependency, at least for now.

Thanks for reaching out with your solution!
