### ISSUE TITLE
Printing the @oneOf directive

### ISSUE THREAD

**Issue by hayes** [graphql/graphql-js#3968]
It looks like currently the `printSchema` function doesn't have any handling for `@oneOf`.

I'm not sure if this is intentional or not, because I know printing directives has historically been a controversial topic, but my expectation would be that for directives that are part of the spec and have a corresponding option in the options when creating the type/field in code (eg `deprecationReason`/`@deprecated` ) would be printed when using  `printSchema`.

I'm happy to make a PR to add this, and it looks like it should be a pretty simple fix handled here: https://github.com/graphql/graphql-js/blob/main/src/utilities/printSchema.ts#L207C5-L207C5

**Comment by benjie** [comment]
Thanks for spotting this! Can confirm that the [RFC definitely states](https://github.com/graphql/graphql-spec/pull/825/files#diff-30a69c5a5eded8e1aea52e53dad1181e6ec8f549ca2c50570b035153e2de1c43) the directive should be present; this isn't "metadata" (unlike graphql/graphql-spec#300) - it's a concrete `__Type.isOneOf` introspection field and without this we'd lose introspection<->SDL equivalence.
