### ISSUE TITLE
Enforce GraphQLList length

### ISSUE THREAD

**Issue by aliatsis** [graphql/graphql-js#397]
Is there a way to enforce that a GraphQLList have a certain length of values?
Or, at the very least, has at least 1 value?
An empty array is currently valid, but I need to make sure theres a value inside.

Thanks in advance!

**Comment by helfer** [comment]
There's currently no way to enforce this in the schema. This falls under validation, so you may be interested in the discussion over on #361

**Comment by aliatsis** [comment]
@helfer thanks!
