### ISSUE TITLE
Allow shallow sorting with lexicographicSortSchema

### ISSUE THREAD

**Issue by kbrooks** [graphql/graphql-js#3971]
The lexicographicSortSchema function currently sorts both the top level types and the internal types of the provided schema. This has created an issue with code generation for me because the order of my graphql enums is being sorted which has a runtime impact on my code. 

I would like to propose an optional parameter to this function which disables this "deep" sorting, instead only sorting the top level declarations.

https://github.com/dotansimha/graphql-code-generator/issues/6935

**Comment by kbrooks** [comment]
For anybody who finds this issue I turned off the sorting with this patch
[graphql@16.8.0.patch](https://github.com/graphql/graphql-js/files/12629437/graphql%4016.8.0.patch)

**Comment by IvanGoncharov** [comment]
@kbrooks The purpose of lexicographicSortSchema is to sort everything is much as possible.
If you want to sort just top-level types, this can be done easily:
```
const schemaConfig = schema.toConfig();
const sortedSchema = new GraphQLSchema({
  ...schemaConfig,
  types: [...schemaConfig.types].sort((a, b) => a.name.localeCompare(b.name)),
});
```
