### ISSUE TITLE
Make flow types available by including source file in NPM release.

### ISSUE THREAD

**Issue by nmn** [graphql/graphql-js#400]
If the build system is updated to to just copy all the source files with the `.js.flow` extension next to the built files, flow will pick up the type definitions.

Further, this is the best way to provide flow type definitions as there is no need to maintain a separate type definition file and changes in the source code will automatically show for users using the library.

(Will try to do a PR)

**Comment by iamchenxin** [comment]
@nmn I made a solution ([flow-dynamic](https://github.com/iamchenxin/flow-dynamic) ) for dealing with `graphql`'s Flow type conflict with another packages . See #359 ,seems @leebyron worried about Static Type conflict between packages before. Many of us are hoping a `.js.flow` in official `graphql` package.

**Comment by Aweary** [comment]
@nmn will this change expose internal flow type definitions? For example, if I wanted to import the `Document` type from `graphql/language/ast`?

**Comment by nmn** [comment]
@Aweary If any type is exported from its file (using `export type`) it will be made available.

Further all values imported from module will come with their associated types.

**Comment by leebyron** [comment]
Merging into #359
