### ISSUE TITLE
Type definition for `DefinitionNode` appears to be wrong

### ISSUE THREAD

**Issue by jacob-orbiit** [graphql/graphql-js#4012]
```
Property 'selectionSet' does not exist on type 'DefinitionNode'.
  Property 'selectionSet' does not exist on type 'SchemaDefinitionNode'.ts(2339)
```

I've inspected `parse(op).definitions[0].selectionSet`, and it does indeed exist.

I see [`DefinitionNode`](https://github.com/graphql/graphql-js/blob/2aedf25e157d1d1c8fdfeaa4c0d2f3d9d3457dba/src/language/ast.ts#L325-L328) includes `ExecutableDefinitionNode` → `OperationDefinitionNode`, and `OperationDefinitionNode` has `selectionSet`, but the definition doesn't seem to follow that deep.

**Comment by JoviDeCroock** [comment]
A `DefinitionNode` can also be part of the SchemaDefinition part of the GraphQL lanaguage, this means that to efficiently narrow the type you would have to do.

```js
if (definition.kind === Kind.OPERATION_DEFINITION || definition.kind === Kind.FRAGMENT_DEFINITION) {}
```

Doing the above ensures that you are dealing with the query-language and hence have a selection-set.

**Comment by jacob-orbiit** [comment]
Ah, that does solve the initial `selectionSet` issue. But then it reveals:

```
Property 'alias' does not exist on type 'SelectionNode'.
  Property 'alias' does not exist on type 'FragmentSpreadNode'.
```

```
Property 'name' does not exist on type 'SelectionNode'.
  Property 'name' does not exist on type 'InlineFragmentNode'.
```

```
Property 'operation' does not exist on type 'OperationDefinitionNode | FragmentDefinitionNode'.
  Property 'operation' does not exist on type 'FragmentDefinitionNode'.
```

There surely must be a way to do this would a bunch of narrowing because the code actually works fine (perhaps because my inputs are uniform?).

**Comment by JoviDeCroock** [comment]
I mean, these are all valid type errors and your code will fail for other permutations of the query-language. 😅 

the first one is the distinction between

```
query { x { alias: field ...fragment } }
```

Where you can see whether the `.kind` is a FragmentSpreadNode, same goes for the second where the distinction is between an inline fragment and a selectionNode as an inline fragment has no name only a potential type-condition and the last one is the distinction between defining an operation and defining a fragment. All of these are valid issues to point out

**Comment by jacob-orbiit** [comment]
Ahh, yes. Sorry, of course 🤦‍♂️ Thanks for the explanation.
