### ISSUE TITLE
Just to give my 2c, I'm not sure if `exports.development` and `exports.production` target conditionsa are widely supported, so some `import.env` shenanigans may still be necessary until that's widely adopted.

### ISSUE THREAD

**Issue by Heyitsquoracom** [graphql/graphql-js#4063]
Just to give my 2c, I'm not sure if `exports.development` and `exports.production` target conditionsa are widely supported, so some `import.env` shenanigans may still be necessary until that's widely adopted.

On the topic of this, I find this section a lot more interesting and that's often been on my mind:
> you end up in a mix of CJS and ESM, and **the instanceof checks break on you.**

In my opinion, with `graphql-js`’ unique situation of being a reference standard implementation, it's rather unfortunate that the schema-parts of this library are limited to reference equality when it comes to inheritance chains and checks, and I'd love to see this part be simply removed and replaced. (Be that with `static` constants, symbol checks, typed `Symbol.toStringTag` checks, etc)

This might of course force some level of API-intercompatibility with `graphql` itself across versions, but that's already a reality that exists for the AST, which sees much more re-use and adoption.

imho the problem of ESM and CJS exports being _both_ imported and then intercompatible, which can sometimes happen in Node, is an optimisation-opportunity/issue that's to be fixed and discovered by users, but it's highly inconvenient that the `instanceof` checks break in these scenarios.
Fixing the ESM/CJS bundling issues doesn't get rid of the underlying problem of the `instanceof` checks imho. So no matter what the outcome here is, I'd love to see that addressed too, if everyone's in favour

_Originally posted by @kitten in https://github.com/graphql/graphql-js/issues/4062#issuecomment-2063778671_

**Comment by benjie** [comment]
This appears to be spam; if it's not please explain why you have filed a copy of a comment rather than engaging in the discussion directly?
