### ISSUE TITLE
Introspection queries don't support `@oneOf`

### ISSUE THREAD

**Issue by maciesielka** [graphql/graphql-js#4077]
Related to the issue in https://github.com/graphql/graphql-js/issues/3968, it doesn't appear that the introspection query is selecting the `isOneOf` field from the server, as defined by the [RFC](https://github.com/graphql/graphql-spec/pull/825/files#diff-30a69c5a5eded8e1aea52e53dad1181e6ec8f549ca2c50570b035153e2de1c43).

This has downstream effects like preventing this introspection response from powering codegen that uses that flag to enforce mutual exclusivity amongst the arguments.

I've attempted to add this functionality in https://github.com/graphql/graphql-js/pull/4078

**Comment by JoeM1990** [comment]
In connection with the problem in #3968, it doesn't seem that the RFC-defined isOneOf field is being selected from the server by the introspection query.

This has side effects, such as stopping codegen that utilizes that flag to impose mutual exclusivity among the arguments from being powered by this introspective answer.

I've tried to incorporate this feature into #4078.

**Comment by JoviDeCroock** [comment]
What do you mean precisely @JoeM1990 it is defined [here](https://github.com/graphql/graphql-spec/pull/825/files#diff-5c333e0b20dda16f4725f894df405fde1f42f5fac752a0e3b9eb0680a64a2681R378) that `isOneOf` is a valid field on an `input-object`
