### ISSUE TITLE
Grabbing enum value from the ast

### ISSUE THREAD

**Issue by JohnyDays** [graphql/graphql-js#408]
Is this possible?

As an example if I have an enum `X { key1: value1, key2: value2 }` and I pass `key1` as the input value, in the ast we get `{Selection}.arguments[0].value.value = "key1"` instead of the expected "value1".

I understand the ast is supposed to represent the syntax for the request, but I'm not sure how I can accomplish what I intend here (resolving a deeply nested request in a single query) without being able to grab the enum values from an arbitrarily nested query, and use them at the top.

**Comment by stubailo** [comment]
It's not possible to know the value without having a schema, and a parser shouldn't have any knowledge of that. The AST is just a nicer representation of the query string, so if the query string doesn't have a piece of information then the AST shouldn't either.

Unfortunately, it seems like there is no way to get underlying value of an enum member from a running GraphQL server, even though you need to pass that if you use the enum via variables (so it's not an implementation detail). So I think a good feature to add here would be the ability to query the values of enum members via introspection.

**Comment by leebyron** [comment]
If you have access to the schema, as Sashko mentioned, then you can use the `valueFromAST` function which graphql-js exports:

```js
import { valueFromAST } from 'graphql';

const value = valueFromAST(mySchema, myValueAST);
```
