### ISSUE TITLE
Tutorial data

### ISSUE THREAD

**Issue by rkvirani** [graphql/graphql-js#4082]
# Tutorial Data - Feature Request

Could you please provide the JSON tutorial data that you used?  It would be good practice to code the schema and resolvers for it.  This would help to solidify the knowledge from the tutorial.

Thanks!

**Comment by JoviDeCroock** [comment]
Do you mean the dataset for https://graphql.org/learn/queries/? I don't think there is a particular dataset here, I know there are a few star wars ones out there like https://swapi.dev/ which does seem used in the graphiql examples https://github.com/graphql/swapi-graphql/blob/master/src/schema/apiHelper.js#L42

**Comment by JoviDeCroock** [comment]
Closing this as stale, feel free to ping if there's anything else we can help with
