### ISSUE TITLE
In a response to a query about an Issue, the URL and other info is missing for links created with Reference editor button

### ISSUE THREAD

**Issue by rudifa** [graphql/graphql-js#4093]
In a github repo **Issue** there are 3 ways to insert a link to another issue, PR, e.t.c, for example:

- #3231 - 1: a Reference in a list

#3231 - 2: same Reference not in a list

[link](https://github.com/graphql/graphql-js/pull/3231) - 3: a Link to the same url

**Problem**: in the response to a graphql query the **link info is missing** from the 2 Reference cases.

**Comment by rudifa** [comment]
To reproduce the bug, send this query...
```
query {
  repository(owner: "graphql", name: "graphql-js") {
    issue(number: 4093) {
      title
      number
      body
    }
  }
}
```
... and examine the response, in which **urls are missing** in cases 1 and 2.
```
{
  "data": {
    "repository": {
      "issue": {
        "title": "In a response to a query about an Issue, the URL and other info is missing for links created with Reference editor button",
        "number": 4093,
        "body": "In a github repo **Issue** there are 3 ways to insert a link to another issue, PR, e.t.c, for example:\r\n\r\n- #3231 - 1: a Reference in a list\r\n\r\n#3231 - 2: same Reference not in a list\r\n\r\n[link](https://github.com/graphql/graphql-js/pull/3231) - 3: a Link to the same url\r\n\r\n**Problem**: in the response to a graphql query the **link info is missing** from the 2 Reference cases.\r\n"
      }
    }
  }
}
```
Moreover, here on the repo website, the case 1 also displays a git 'branch' **icon** and the **title** of the link target. These items are also missing from the response.

**Comment by rudifa** [comment]
Actually, I am probably in a wrong place here, as this repo provides a js implementation of graphql spec.

The bug I'm trying to report is presumably in the github's implementation of their graphql server and its interaction with the github databases that store the repos and their issues.

**Advice on where to go with this bug report would be appreciated.**

**Comment by JoviDeCroock** [comment]
I do think this is the wrong place to ask that question, a good thing to check would be the `description` of the fields on `issue` maybe there's an option to make it output the links, if not I reckon the GitHub support staff is your best bet 😅

**Comment by rudifa** [comment]
Thank you @JoviDeCroock. 
In the meantime, I did open a ticket with the GitHub support.

**Comment by JoviDeCroock** [comment]
I'll close this as it's not really related to our repository
