### ISSUE TITLE
Typescript error with 16.9.0 (re ThunkObjMap)

### ISSUE THREAD

**Issue by jeffrson** [graphql/graphql-js#4129]
Hi,
after upgrading to 16.9.0 our utility function for building enums shows a typescript error (using noImplicitAny). The function looks as follows:

```
export function buildStringEnum(name: string, values: { [key: string]: unknown }): graphql.GraphQLEnumType {
    const config: graphql.GraphQLEnumTypeConfig = { name, values: {} }

    for (const value of Object.keys(values)) {
        config.values[value] = { value }
    }

    return new graphql.GraphQLEnumType(config)
}
```

The error is for "config.values[value]":
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'ThunkObjMap<GraphQLEnumValueConfig>'.
  No index signature with a parameter of type 'string' was found on type 'ThunkObjMap<GraphQLEnumValueConfig>'.ts(7053)
```

Is this intended? And how is this supposed to be migrated?

**Comment by JoviDeCroock** [comment]
Your type would be fixed by doing the following

```ts
for (const value of Object.keys(values)) {
  if (typeof config.values === 'object') {
    config.values[value] = { value }
  }
}
```

For some reason TypeScript gets confused and thinks you might be assigning the mapping to either a function or an object due to the addition of the possibility of assigning values through a thunk.

**Comment by jeffrson** [comment]
Thanks a lot for the fast and helpful reply! This fixes it.

Edit: forcing the type of `config` is even better! Great!

**Comment by JoviDeCroock** [comment]
Going to close this issue out as it doesn't look like there's more to discuss here, I this in part comes back to GraphQL-JS exporting too many utility types 😅
