### ISSUE TITLE
Explore possibility of generic types

### ISSUE THREAD

**Issue by AndrewIngram** [graphql/graphql-js#415]
As projects like Relay have shown, it's relatively common to repeat the same generic structures of types multiple times within a project. In the case of Relay, I'm talking about Connections.

The GraphQL definition language already has explicit support for one particular form of generic type, arrays:

```
type Foo {
   id: ID!
   bars: [Bar]
}
```

I'd like to start discussion about being able to do something similar for user-defined structures:

```
generic ConnectionEdge<T> {
   node: T
   cursor: String
}

generic Connection<T> {
   edges: ConnectionEdge<T>
   pageInfo: PageInfo
}

type Foo {
   id: ID!
   bars: Connection<Bar>
}
```

The overall goal is to reduce the amount of boilerplate in creating schemas with repetitive structures.

**Comment by AndrewIngram** [comment]
Realised this should be on the spec repo, moving: https://github.com/facebook/graphql/issues/190

**Comment by langpavel** [comment]
Hey, nice! 
But if you don't use GraphQL language itself but you create this schema on runtime, you only need higher order function as this is already done in graphql-relay.
BTW every used generic type must be materialized somewhere, so can this be really useful?
