### ISSUE TITLE
Error with version v16.9.0: `Can't resolve '@apollo/subgraph/dist/directives''`

### ISSUE THREAD

**Issue by tanmnt** [graphql/graphql-js#4151]
When I from v`^16.8.1` upgrade to v`16.9.0` then errors under the picture

<img width="1212" alt="image" src="https://github.com/user-attachments/assets/d4814e4f-0414-4148-a4a0-bcb6fde6959e">

**Comment by JoviDeCroock** [comment]
This is pointing at a non `graphql-js` module though, have you tried running a `dedupe` command like `pnpm dedupe` to see whether you accidentally duplicatd some modules?

**Comment by yaacovCR** [comment]
Closing, feel free to reopen as necessary.
