### ISSUE TITLE
Add Query to Fetch All Messages

### ISSUE THREAD

**Issue by Teddir** [graphql/graphql-js#4158]
### Description

I would like to add a new query to our GraphQL schema to allow fetching all messages from the database. This change will involve:

- Adding a `getAllMessages` query to the `Query` type in the GraphQL schema.
- Implementing a resolver for `getAllMessages` that retrieves all messages from the `fakeDatabase`.
- Updating documentation to include information about the new query.

This change will enhance the API by providing a way to retrieve all messages in a single request, which is useful for administrative or reporting purposes.

**Comment by JoviDeCroock** [comment]
Hey,

This is the GraphQL open-source repository I think you might have reported this issue in the wrong place.

**Comment by Teddir** [comment]
sorry
