### ISSUE TITLE
Remove unique constrain on named types

### ISSUE THREAD

**Issue by abhishiv** [graphql/graphql-js#416]
[Here](https://github.com/graphql/graphql-js/blob/485b131ea9ffbd92a9fe5853338ba5e8b0050ca0/src/type/schema.js#L233) in src which throws `Schema must contain unique named types but contains multiple ..`

I'm hitting this issue, because I'm trying to serialize a graphql schema dynamically from definitions stored in db. It does it on each request, and this error gets thrown when two applications use the same name - which I can't change.

What's the reasoning behind this constrain?

**Comment by leebyron** [comment]
This constraint is used pervasively throughout GraphQL's internals and its schema language.

For example:

```
type Foo {
  bar: String
}

type Foo {
  bar: Boolean
}

type Query {
  foo: Foo
}

schema { query: Query }
```

Given the above schema, what type will `foo.bar` be for the query below?

```
{ foo { bar }
```

It's ambiguous because it's unclear which version of the `Foo` type you're referring to.

Ensuring that every type in the schema contains a unique name allows GraphQL to avoid this ambiguity and potential source of confusion.

**Comment by leebyron** [comment]
> I'm hitting this issue, because I'm trying to serialize a graphql schema dynamically from definitions stored in db. It does it on each request, and this error gets thrown when two applications use the same name - which I can't change.

I'm not familiar with your project, but if you have two unrelated type domains then perhaps it would be best to support two different GraphQL APIs, one for each. Or, if they need to co-exist, then perhaps you can name the types with prefixes such that they cannot conflict. If the overlapping types are in fact the same type, then perhaps you can detect this during the creation of those types so only one of each name is produced.

**Comment by abhishiv** [comment]
Hey @leebyron

Thanks for you comment. 

`Ensuring that every type in the schema contains a unique name allows GraphQL to avoid this ambiguity and potential source of confusion. `

Yeah that's clear to me, and it does make sense to have this constrain in the case of a single schema. But I'm looking for a way to support multiple schemas, which might have a common type - User for example. Right now it throws on that, because this is checked globally instead of per schema basis.

**Comment by leebyron** [comment]
> Right now it throws on that, because this is checked globally instead of per schema basis.

It is in fact only checked per schema, and not globally. You may create many schema as long as each schema contains unique types.
