### ISSUE TITLE
4D array non optionality error on introspection

### ISSUE THREAD

**Issue by alessdiimperio** [graphql/graphql-js#4167]
4D array support has been added in 18.8.
However if you want to make the arrays non optional the introspectionQuery fails and the playhground doesn't work.
The server does run but you can not introspect it.

Using apollo codegen on iOS we cannot build our models seeing as the introspection doesn't work.

example
coordinates: [[[[Float!]!]!]!]! <-- would fail introspection
coordinates: [[[[Float!]]]] <-- does not fail

This seems like a bug 🤔 

The best way to get a bug fixed is to provide a _pull request_ with a simplified failing test case (or better yet, include a fix).

**Comment by JoviDeCroock** [comment]
We'll need more information than just "it does not work" as this case has explicit tests after https://github.com/graphql/graphql-js/pull/3950/files

**Comment by yaacovCR** [comment]
Closing for now, we can reopen if more information is provided.

**Comment by alessdiimperio** [comment]
Sorry i missed this.

basically the server runs and works fine however when trying to introspect it fails the query when we use the following. [[[[Float!]!]!]!]!

however if we remove on level of ! it works

[[[[Float!]!]!]]! <- works

**Comment by JoviDeCroock** [comment]
@alessdiimperio again, saying it fails does not help us. We need error messages, a reproduction, a failing test,... anything that can help us see what you see. Have you looked at my comment?
