### ISSUE TITLE
How can I execute resolver of children type in subscription?

### ISSUE THREAD

**Issue by aihornmac** [graphql/graphql-js#419]
I am building a real-time app, which uses graphql subscriptions as main api, while supporting normal queries as fallback and for server render. So I have something like
```js
const RootSubscription = new GraphQLObjectType({
  name: 'RootSubscription',
  fields: () => ({
    type: UserProfile,
    description: 'The current user',
    resolve: async (_, args, ctx, ast) => {
      // subscribe database and emit
    }
  })
});

const UserProfile = new GraphQLObjectType({
  name: 'UserProfile',
  fields: () => ({
    id: { type: GraphQLString },
    email: { type: GraphQLString },
    hasPassword: { type: GraphQLBoolean, resolve: _ => !!_.password },
    activated: { type: GraphQLBoolean },
  })
});
```
How can I emit the result resolved by UserProfile inside resolve code block instead of returning an object as source?

**Comment by leebyron** [comment]
graphql-js currently does not have support for subscriptions. This is an ongoing area of research, but unfortunately this library doesn't support anything other than the parser for subscriptions.

**Comment by sheerun** [comment]
@leebyron Are there server semantics available?

**Comment by leebyron** [comment]
Not to my knowledge at this time

**Comment by lednhatkhanh** [comment]
Hey, is there any update about this?

**Comment by wincent** [comment]
@lednhatkhanh: Was formally added to the spec in https://github.com/facebook/graphql/commit/d7e3f06c52f50666a17bd5eed2fdbff35932704a

Support for subscriptions was first added to this repo in v0.10.0 with some follow-up refinement going on in subsequent releases (see the summaries on [the releases page](https://github.com/graphql/graphql-js/releases)).
