### ISSUE TITLE
Incorrect params for field `isRequired` under `pullRequest -> statusCheckRollup -> contexts`

### ISSUE THREAD

**Issue by Oripi** [graphql/graphql-js#4197]
# Bug report

Hi, it looks like there's an issue with the `isRequired` field under `repo -> pullRequests -> nodes -> statusCheckRollup -> contexts -> nodes -> isRequired`

the field requires params, but they should be inferred in this context.
example query:
```graphql
query ($var1: String!, $var2: String!) {
  repo: repository(owner: $var1, name: $var2) {
    pullRequests(first: 4, states: [OPEN]) {
      totalCount
      nodes {
        title
        statusCheckRollup {
          contexts(first: 50) {
            nodes {
              ... on StatusContext {
                id
                description
                # params are required here, but in this context the id of the PR is known
                isRequired
              }
            }
          }
        }
      }
    }
  }
}
```

error:
```
{
	"type": "UNPROCESSABLE",
	"path": [
		"repository",
		"pullRequests",
		"nodes",
		4,
		"statusCheckRollup",
		"contexts",
		"nodes",
		2,
		"isRequired"
	],
	"locations": [
		{
			"line": 19,
			"column": 9
		}
	],
	"message": "A pull request ID or pull request number is required."
}
```

**Comment by Oripi** [comment]
looks like as a workaround i can pass `isRequired(pullRequestNumber:1)` and it'll return correct value, but it's still redundant...

**Comment by JoviDeCroock** [comment]
Hey,

This is the GraphQL reference implementation repository, not the place to pass GitHub related issues 😅  I think your best bet is to reach out to GitHub support.

**Comment by Oripi** [comment]
when you don't read the project's description 😅 
thanks, i'll try there
