### ISSUE TITLE
Enums not tree shaking well

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql/graphql-js#4253]
I have redefined the `Kind` and `OperationTypeNode` enums in Graffle because they do not seem to tree shake well. You can see the code and bundle visualization [in this PR](https://github.com/graffle-js/graffle/pull/1215). With my approach already just those two enums are reduced by over 4kb in Graffle.

![CleanShot 2024-10-24 at 16 14 07@2x](https://github.com/user-attachments/assets/e19e056e-5e79-4efa-8c35-fcb527e2a3e4)

Obviously it would be nice if `graphql` was already fully tree shake optimized from the start. Is there an appetite to adjust how the enums are defined in `graphql`? I think my approach would be a breaking change at the type level because TypeScript enum types, even if using string constants at runtime, are not equivalent to them at the type level.

Feel free to close this issue if there's zero chance of change on the `graphql` package side of course. Convesely, happy to help out on this issue.

**Comment by JoviDeCroock** [comment]
Yeah, there are several issues with the TS enum like https://github.com/graphql/graphql-js/issues/3356. However converting to an object won't solve your issue here, that being said, this is a reference implementation and we have made tradeoffs for DX/readability for that matter. The minzipped size of this object when not using TS enums should not exceed 1kb.

We could split this up between schema-kind and executable kind to improve this a bit more for web implementations.

**Comment by jasonkuhrt** [comment]
Right an object wouldn't solve tree shaking. Rather I defined every enum member as its own constant and then use the namespace to group them. That supports tree shaking and I see actually no DX issue here, since TS allows type names that match a namespace name so it ends up feeling identical to the enum before.

**Comment by JoviDeCroock** [comment]
Grouping them under a namespace won't allow them to be used in JS as follows right?

```js
import { Kind } from 'graphql';

if (selection.kind === Kind.FIELD)
```

My main concern would be to still allow this usage so v17 doesn't have too many breaking changes, in #4254 we move away from the `enum` notation which already saves 20% of the bytes in that file. I consider that to be a good start as it also allows for the type to be omitted and to just use the plain string, which in your case would help you get rid of the type-casting.

I would be a huge fan of evolving into a tree-shakable model though, for now I would advise people that are concerned with that to leverage your approach.

**Comment by jasonkuhrt** [comment]
Here's another approach that might seem/be simpler:

https://www.typescriptlang.org/dev/bug-workbench/?#code/FDD0oAgAQMwSwDYFMB2BDAtkgXBFB7AEyQH0MiBXZAZ1AHMAnNABwAsBHBUAazhUJ59CAOgAu1YEgAezfA1EQAxvhTUFAMQCSAUQAyAEQgBeCAHJ4SBIVOSZchctUKAQsbMAjUxHAQkoxcK2svJKKmoQAMJupopePn4BQfahThCGJqbW3pAJgSBgkLCIqJg4eESk5IRUSLSMLBxcvPygJCRiEnAYwQoA3hBaevoANBDOoxGjhgC+EDAM+BhmwoL8wgBW1DZJIaIAnsxIEADSQsbAEBAAPhD7h-gwAzoGF9e3B0gPY683d5+PER+73uj30IGkPQgACoIGhqCczvNFstViJNtsQD4ish0FhcARiGRKDR6Ew2JxQEJpB0dgoYUilqYVs0BG0Nlt8gVoPAcaVcCxmDSupD+qd+BBZgyzPVyQhto5wjB8Pg3AAKFm4MWEACUxgAfBBeq9LnBHuqzkZLWYLFZTLqfIQVdRFn5WHw6JdLsBpiAtcJBgZshAAEQ2wjBzGFcQAWghSEUoljDAWDGASvwqtM7jQ1ntkBgaEQIHTmbDdqD+G4aeVmc8eYglerGZi5Z8jZLmVbkErQA

```ts


// @filename: node_modules/graphql/kind/kind.ts
export const FIELD = 'field'
export const B = 'b' // etc.
export const C = 'c' // etc.
export const D = 'd' // etc.



// @filename: node_modules/graphql/kind/__.ts
import { FIELD, B, C, D } from './kind.js'

export type Kind =
  | typeof FIELD
  | typeof B
  | typeof C
  | typeof D

export * as Kind from './kind.js'



// @filename: node_modules/graphql/index.ts
export * from './kind/__.js'



// @filename: app.ts
import { Kind } from 'graphql'

const foo = (kind: Kind) => {
    if (kind === 'field') // do something    
}

Kind.FIELD // "field"

// @ts-expect-error
foo('bad') // fail

foo('field') // ok
foo('b') // ok
foo('c') // ok
foo('d') // ok
```

**Comment by JoviDeCroock** [comment]
Well you can't then use i.e. `OperationTypeNode` as a type as it would become a namespace. The tree-shaking [does look to be working correctly](https://rollupjs.org/repl/?version=4.24.2&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEtpbmQlMjAlN0QlMjBmcm9tJTIwJy4lMkZncmFwaHFsJyU1Q24lNUNuY29uc29sZS5sb2coS2luZC5GSUVMRCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMColMjBhcyUyMEtpbmQlMjBmcm9tJTIwJy4lMkZraW5kJyUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJncmFwaHFsLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIwRklFTEQlMjAlM0QlMjAnZmllbGQnJTVDbmV4cG9ydCUyMGNvbnN0JTIwVEVTVCUyMCUzRCUyMCd0ZXN0JyUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJraW5kLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTdEJTdE) so we could do this for Kind in and of itself and let https://github.com/graphql/graphql-js/pull/4254 handle the bundle reduction for the ones we use as a type.

**Comment by jasonkuhrt** [comment]
> Well you can't then use i.e. OperationTypeNode as a type as it would become a namespace.

Hey @JoviDeCroock, I'm not sure what you mean by this.

In my example above for example we see that `Kind` is both namespace and type. TypeScript allows this.

```
// @filename: app.ts
import { Kind } from 'graphql' // <-- type & term levels
```

> EDIT: I tried this out and the using the namespace as a type keeps failing as when we use typeof namespace it fails again - you can check it out here [graphql/graphql-js/pull/new/tree-shake-kind](https://github.com/graphql/graphql-js/pull/new/tree-shake-kind)

Thanks will check it out!

**Comment by jasonkuhrt** [comment]
Currently working on a PR now.

**Comment by JoviDeCroock** [comment]
Fixed it in https://github.com/graphql/graphql-js/pull/4268

**Comment by jasonkuhrt** [comment]
@JoviDeCroock Ah beat me to it. PR is at fwiw https://github.com/graphql/graphql-js/pull/4269 but I'll close it now. Thanks!

**Comment by JoviDeCroock** [comment]
I'll close this as we've merged this into the v17 branch
