### ISSUE TITLE
Maximum introspection depth exceeded: set MAX_LISTS_DEPTH to custom value

### ISSUE THREAD

**Issue by donkeyDau** [graphql/graphql-js#4287]
https://github.com/graphql/graphql-js/pull/4119 introduced `MaxIntrospectionDepthRule`. My project is relying on a greater depth in terms of introspection. Is there a way to set the `MAX_LISTS_DEPTH` by the user of the lib?

**Comment by yaacovCR** [comment]
See also #4118 for some additional details.

Tagging @benjie and @enisdenjo who worked on this recent addition.

to move the conversation forward, could you elaborate on why your project needs to allow for greater depth?

**Comment by donkeyDau** [comment]
> to move the conversation forward, could you elaborate on why your project needs to allow for greater depth?

Thanks you for pointing me into this direction: indeed my introspection query was unnecessary "deep". Reducing the depth made it work with [v.16.9](https://github.com/graphql/graphql-js/releases/tag/v16.9.0) as well!
