### ISSUE TITLE
graphql fn not resolving 0.6.1

### ISSUE THREAD

**Issue by marcelocbf** [graphql/graphql-js#430]
Hi,

I coded a big Schema and started testing but the graphql function was not getting resolved ever. So, I started changing it to detect if it was hanging somewhere.

I started putting a simple console.log on the simplest resolve fn in the schema, it got printed out but nothing getting returned. So, after multiple attempts and getting the code to

```
  let schema = new GraphQLSchema({
    query: new GraphQLObjectType({
      name: 'RootQueryType',
      fields: {
        hello: {
          type: GraphQLString,
          resolve: () => 'world'
        }
      }
    })
  });
```
query to

```
let hello = `
  {
    hello
  }
`;
```
and executing code to

```
  graphql(schema, query)
    .then(r => {
      console.log(`RESULT: ${JSON.stringify(r)}`);
    });
```

it was still not getting to the .log inside the resolve fn. So, I tried npm uninstall / re-install, nothing. I was only able to get it working when I installed version 0.6.0.

Can this be replicated in some other machine or am I the unluckiest individual?

Here is my npm list if helps...

```
├─┬ aws-sdk@2.4.6
│ ├── jmespath@0.15.0
│ ├── sax@1.1.5
│ ├── xml2js@0.4.15
│ └─┬ xmlbuilder@2.6.2
│   └── lodash@3.5.0
├─┬ babel-core@6.10.4
│ ├─┬ babel-code-frame@6.8.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.0.0
│ │ │ ├── strip-ansi@3.0.1
│ │ │ └── supports-color@2.0.0
│ │ ├── esutils@2.0.2
│ │ └── js-tokens@1.0.3
│ ├─┬ babel-generator@6.10.2
│ │ ├─┬ detect-indent@3.0.1
│ │ │ ├── get-stdin@4.0.1
│ │ │ ├── minimist@1.2.0
│ │ │ └─┬ repeating@1.1.3
│ │ │   └─┬ is-finite@1.0.1
│ │ │     └── number-is-nan@1.0.0
│ │ └── lodash@4.13.1
│ ├── babel-helpers@6.8.0
│ ├── babel-messages@6.8.0
│ ├─┬ babel-register@6.9.0
│ │ ├── core-js@2.4.0
│ │ ├─┬ home-or-tmp@1.0.0
│ │ │ ├── os-tmpdir@1.0.1
│ │ │ └── user-home@1.1.1
│ │ ├── lodash@4.13.1
│ │ ├─┬ mkdirp@0.5.1
│ │ │ └── minimist@0.0.8
│ │ └─┬ source-map-support@0.2.10
│ │   └─┬ source-map@0.1.32
│ │     └── amdefine@1.0.0
│ ├─┬ babel-runtime@6.9.2
│ │ └── regenerator-runtime@0.9.5
│ ├─┬ babel-template@6.9.0
│ │ └── lodash@4.13.1
│ ├─┬ babel-traverse@6.10.4
│ │ ├── globals@8.18.0
│ │ ├─┬ invariant@2.2.1
│ │ │ └── loose-envify@1.2.0
│ │ └── lodash@4.13.1
│ ├─┬ babel-types@6.10.2
│ │ ├── lodash@4.13.1
│ │ └── to-fast-properties@1.0.2
│ ├── babylon@6.8.1
│ ├── convert-source-map@1.2.0
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── json5@0.4.0
│ ├── lodash@4.13.1
│ ├─┬ minimatch@3.0.2
│ │ └─┬ brace-expansion@1.1.5
│ │   ├── balanced-match@0.4.1
│ │   └── concat-map@0.0.1
│ ├── path-exists@1.0.0
│ ├── path-is-absolute@1.0.0
│ ├── private@0.1.6
│ ├── shebang-regex@1.0.0
│ ├── slash@1.0.0
│ └── source-map@0.5.6
├── base64-url@1.2.2
├── graphql@0.6.1
├── graphql-relay@0.4.2
├── lodash@4.13.1
└── uuid@2.0.2
```

I can try to debug if someone gives me an idea how...

**Comment by leebyron** [comment]
That's definitely strange that 0.6.0 works for you but 0.6.1 does not.

Can you provide some information about what your runtime environment is like? e.g. if you're running Node, what version?

**Comment by marcelocbf** [comment]
Sure,

Node 4.4.3
npm 3.8.8
macOS 10.11.5

anything else???

I thought too, and it took me a while to try to rollback the version to see what would happen. Is there anything I can do it locally to debug it?

**Comment by marcelocbf** [comment]
Never mind! It's working now! Really confused.
I ran npm update again and I got the following packages updated aws-sdk 2.4.8, base-url 1.3.2, graphql 0.6.1.

I ran the same test I did before and it worked. Maybe some weirdness in my local machine.

Thanks anyways
