### ISSUE TITLE
possible bug when building client schema from introspectation

### ISSUE THREAD

**Issue by cubika** [graphql/graphql-js#432]
graphql can use introspectation to build client schema, when building schema, it’ll parse field’s defaultValue. However, for string types, it strips out double quotes, causing lexer error if the string contains characters other than a-z。Here is an example:

```
{
  name: "pattern",
  type: {
  kind: "SCALAR",
  name: "String"
  },
  defaultValue: "yyyy-MM-dd HH:mm:ss"
}
```

When parsing defaultValue, the value it reads is `yyyy-MM-dd HH:mm:ss`，not `"yyyy-MM-dd HH:mm:ss"`. So the lexer will treate `-` as a minus sign, not a character in a string.

So I guess if we can wrap dobule quotes before parsing, or convert the value based on it's types first.

The corresponding code is here: https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js#L324

**Comment by leebyron** [comment]
This is the result of introspection? The bug we should be looking for may be in the introspection on the server itself. Which implementation are you using on the server?

My read of that corresponding code is that it is correct - it parses `defaultValue` as graphql language, and then builds a value from that - basically the GraphQL equivalent of `JSON.parse`. Consider why `JSON.parse("yyyy-MM-dd HH:mm:ss")` would fail but JSON.parse("\"yyyy-MM-dd HH:mm:ss\"") would produce a javascript string value.

**Comment by cubika** [comment]
I see, thanks. I'll check the server implementation detail about introspection.
