### ISSUE TITLE
[RFC] "3.1.5 Enums" - requires additional consideration. Use complex objects with functions for enum values.

### ISSUE THREAD

**Issue by nodkz** [graphql/graphql-js#435]
In [graphql-compose-connection](https://github.com/nodkz/graphql-compose-connection) I use `Enum type` for storing avaliable sortings for connections, so values represent complex objects with function, eg: 
```js
var ConnectionSortUserEnum = new GraphQLEnumType({
  name: 'ConnectionSortUserEnum',
  values: {
    AGE_ID_DESC: {
      uniqueFields: ['age', '_id'],
      sortValue: { age: -1, _id: 1 },
      directionFilter: (cursorData, filter, isBefore) => {
        // some code for extending filter with data obtained from `before` or `after` cursors 
        return filter;
      },
    },
    ...someOtherSorts
  }
});
```
With such `Enum` graphql server starts and works perfectly ([example](https://graphql-compose-mongoose.herokuapp.com/mongoose-relay?query=%7B%0A%20%20userConnection(sort%3A%20_ID_DESC%2C%20first%3A%203)%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%2C%0A%20%20u2%3A%20userConnection(sort%3A%20_ID_ASC%2C%20first%3A%203)%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D)). 

But throws error when I try to build introspection `graphql(Schema, introspectionQuery)` or run `printSchema(Schema)`:
```
[11:33:10] Starting 'buildSchema'...
ERROR introspecting schema:  [
  {
    "path": [
      "__schema",
      "types",
      1,
      "fields",
      21,
      "args",
      5,

      "defaultValue"
    ],
    "originalError": {}
  }
]
Error
    at invariant (invariant.js:19:11)
    at astFromValue (astFromValue.js:112:3)
    at astFromValue.js:123:22
    at Array.forEach (native)
    at astFromValue (astFromValue.js:117:23)
    at printInputValue (schemaPrinter.js:180:44)
    at Array.map (native)
    at printArgs (schemaPrinter.js:174:39)
    at schemaPrinter.js:155:28
    at Array.map (native)
    at printFields (schemaPrinter.js:154:17)
    at printObject (schemaPrinter.js:121:65)
    at printType (schemaPrinter.js:100:12)
    at Array.map (native)
    at printFilteredSchema (schemaPrinter.js:72:87)
    at printSchema (schemaPrinter.js:37:10)
```

According to [astFromValue.js#L116](https://github.com/graphql/graphql-js/blob/516dfb9674b4dbde1ee17f715e4c0b6bc24a9f92/src/utilities/astFromValue.js#L116) it accepts only `string` values for `Enums`:
```js
  // JavaScript strings can be Enum values or String values. Use the
  // GraphQLType to differentiate if possible.
  if (typeof _value === 'string') {
    if (type instanceof GraphQLEnumType &&
        /^[_a-zA-Z][_a-zA-Z0-9]*$/.test(_value)) {
      return ({ kind: ENUM, value: _value }: EnumValue);
    }
    // Use JSON stringify, which uses the same string encoding as GraphQL,
    // then remove the quotes.
    return ({
      kind: STRING,
      value: JSON.stringify(_value).slice(1, -1)
    }: StringValue);
  }
``` 
* But in graphql specification https://facebook.github.io/graphql/#sec-Enums I did not found explicit requirement that enum value must be `string`.
* Also in `flow-type` [definitions](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L838) value has `any` type:
```js
export type GraphQLEnumValueConfig/* <T> */ = {
  value?: any/* T */;
  deprecationReason?: ?string;
  description?: ?string;
}
```  

So, according to concept of Enum ...
* client gets only `names` from enum
* enum values can be defined only on server (and client does not know anything about internal enum value)

... I think, that if developer define complex value for enum, so it expects that get it in `args` for `resolve` function. And `astFromValue` should not deeply extract AST for `enum's value` it should stops on `enum's name`.

I don't know enough FB internals requirements for ENUMs, so can not provide correct PR for this problem. @leebyron please consider this issue, as soon as possible, because it blocking me.

PS. Passing to enum's value arrow functions, provides for me awesome ability to customise logic in `resolve` methods - https://github.com/nodkz/graphql-compose-connection/blob/master/src/resolvers/connectionResolver.js#L207

**Comment by nodkz** [comment]
Deeper investigations shows that problem with `defaultValue` for input field with Enum type.
Eg.
```js
const RootQuery = new GraphQLObjectType({
  name: 'RootQuery',
  fields: {
    'userConnection': {
      type: UserConnection,
      args: {
         first: { type: GraphQLInt },
         after: { type: CursorType },
         last: { type: GraphQLInt },
         before: { type: CursorType},
         ...additionalArgs,
         sort: {
           type: SortEnumType,
           defaultValue: SortEnumType.getValues()[0].name, // <<<< problem here  <<<<<<<<<<<
           description: 'Sort argument for data ordering',
         },
      },
   },
});
```
- If `sort` arg provided for query (eg. `{ userConnection(first: 5, sort: AGE_ID_DESC) { ... }`) then
  - `astFromValue` works without errors 💚
  - `resolve` functions gets **complex object** via `args.sort` 💚
- If `sort` is not provided, then it takes `defaultValue` from config option:
  - when `defaultValue` equals `SortEnumType.getValues()[0].name`, which equals to `AGE_ID_DESC`, then
    - `astFromValue` works without errors 💚
    - `resolve` function gets **string** name of sorting value in `args.sort` **(I think it should implicitly convert enum name to value)** 💔
  - when `defaultValue` equals `SortEnumType.getValues()[0].value`, which equals to `{ age: -1, _id: 1 }`, then
    - `astFromValue` throws error. **It was called such way `astFromValue(undefined, { age: -1, _id: 1 })`** 💔
    - `resolve` function gets **complex object** in `args.sort` 💚

So what `defaultValue` should be provided for field with `Enum` type?

**Comment by leebyron** [comment]
I added a test to illustrate complex enums which passes correctly. I believe the issue here is that your enum definitions are ill-formed.

Enums are defined as a list of enum descriptors, one field of which is `value`. Example:

```js
  const Complex1 = { someRandomObject: 1 };
  const Complex2 = { someOtherRandomObject: 2 };

  const ComplexEnum = new GraphQLEnumType({
    name: 'Complex',
    values: {
      ONE: { value: Complex1 },
      TWO: { value: Complex2 },
    }
  });
```

**Comment by leebyron** [comment]
b2c8332001d16b70039cb21bd10ccb0e85b7729c also illustrates the use of the Enum getValues() method

**Comment by leebyron** [comment]
Added one last test illustrating `defaultValue`.

Are there any other concerns you have here? I'll add more tests

**Comment by nodkz** [comment]
Your tests answered to all my questions with enums. No more 💚/💔 in my head.  Thank's a lot!!!

Enum definition in my case was covered by flow connected with graphql. Also I checked it with your example. And they are identical.

Problem in my case, that I use function in sort value. This function needs for passing custom logic to resolve function. And `graphql(schema, introspectionQuery)` throws error, when it tries build AST for function in the enum's `defaultValue`.

Add PR with broken test https://github.com/graphql/graphql-js/pull/438/commits/fd96f5a0b0b980c98bbeb3d808a625c8c753247c

**Comment by leebyron** [comment]
Thanks for isolating that! I'll take a closer look

**Comment by leebyron** [comment]
Closing this now, and will get this fix out in the next point release - feel free to reopen if theres anything I missed

**Comment by nodkz** [comment]
Awesome work! All errors are GONE!

All [tested](https://github.com/nodkz/graphql-compose-connection/commit/5589d29bde94840b0817f2deb5c497b611a2c13a) with graphql-compose-connection and ready for at least 0.6.2 

Also was fixed `\"`
<img width="537" alt="screen shot 2016-07-20 at 12 04 24" src="https://cloud.githubusercontent.com/assets/1946920/16976668/3e6ca2dc-4e72-11e6-95dc-7e26e143fedd.png">



BTW. Thanks for 0.29 flow upgrade! 
And how I see you have crazy streak right now, and may be want bump new version tonight. 
So, please accept `flow` files generation from this PR https://github.com/graphql/graphql-js/pull/412
