### ISSUE TITLE
Extending a schema with directives

### ISSUE THREAD

**Issue by josephsavona** [graphql/graphql-js#450]
The `extendSchema` utility supports extending types with new fields, but it isn't clear how to extend a schema with a new directive. Given a `GraphQLSchema` instance, and a directive DSL such as `directive @foo(id: ID!) on FIELD`, is there a way to get a version of the schema with this directive added?

**Comment by robzhu** [comment]
It looks like extendSchema copies over the directives from the input schema: https://github.com/graphql/graphql-js/blob/f06051e592362767e6531c1ceb653f1ef3873500/src/utilities/extendSchema.js#L223-L224

Can you share some details about your use case so that I might be able to suggest alternatives?

**Comment by josephsavona** [comment]
@robzhu It only copies the directives from the input schema and ignores any directives defined in the [extension](https://github.com/graphql/graphql-js/blob/f06051e592362767e6531c1ceb653f1ef3873500/src/utilities/extendSchema.js#L99). It looks like [this switch statement](https://github.com/graphql/graphql-js/blob/f06051e592362767e6531c1ceb653f1ef3873500/src/utilities/extendSchema.js#L117) needs to be modified to account for directives (?).

**Comment by josephsavona** [comment]
The use case is that Relay defines its own directives (`@relay`) that it strips out when processing fields. We'd like to use `extendSchema` to be able to augment the application's schema with the definitions of our custom directives.

**Comment by asiandrummer** [comment]
Closing with #455 committed.
