### ISSUE TITLE
GraphQLInputObjectType validation

### ISSUE THREAD

**Issue by IcanDivideBy0** [graphql/graphql-js#454]
Hello,

Sorry for opening yet another form validation issue, but I can't find any answer on this in other issues.

I'm using the `graphql-date` module to get a `GraphQLDate` type, I want to define a `DateRangeType` and `DateRangeInputType`. I would like to check the start date is prior to the end date, but I can't find a way to validate an InputObject by its own

```js
const DateRangeInputType = new GraphQLInputObjectType({
  name: 'DateRangeInput',
  description: 'A date range',
  fields: () => ({
    start: {
      type: new GraphQLNonNull(GraphQLDate),
    },
    end: {
      type: new GraphQLNonNull(GraphQLDate),
    },
  }),
});
```

Should I use a scalar type to have some kind of validation or did I missed something ?

**Comment by leebyron** [comment]
GraphQL input is pure data (no logic), so typically validation on that pure data is done within a `resolve` function, where app logic should live, so you could write a function called `assertValidDateRange` and then in a resolver:

```js
resolve(obj, { dateRange }) {
  assertValidDateRange(dateRange);
  // do something with obj and dateRange
}
```
