### ISSUE TITLE
ProvidedNonNullArguments throws when no `args` property is defined for a field.

### ISSUE THREAD

**Issue by yoadsn** [graphql/graphql-js#465]
I am using a generated schema from mongoose using the `graffiti-mongoose` library.
In a specific case, the generated schema cannot be queried on a specific field.
Graphql.js throws in `/validation/rules/ProvidedNonNullArguments.js`:

```javascript
"errors": [
  "TypeError: Cannot read property 'forEach' of undefined"
]
```

I think the problem is the assumption that the `args` property would be present on the field definition.
See [here](https://github.com/graphql/graphql-js/blob/3083fc5743ef228326588f0d1c6b1ebcdf0c4a52/src/validation/rules/ProvidedNonNullArguments.js#L54)

The code does:
```javascript
fieldDef.args.forEach(argDef => {
```

But according to the graphql type spec the args property is optional on the field configuration. as seen [here](http://graphql.org/docs/api-reference-type-system/#graphqlobjecttype):

```
type GraphQLFieldConfig = {
  type: GraphQLOutputType;
  args?: GraphQLFieldConfigArgumentMap;
  resolve?: GraphQLFieldResolveFn;
  deprecationReason?: string;
  description?: ?string;
}
```

Could this be a bug in the graphql implementation or the other library which is supposed to generate `args` fields in the cases when this visitor is activated?

**Comment by leebyron** [comment]
Thanks for the report

**Comment by leebyron** [comment]
Looking at the expectations of the library, it expects args to always be defined.
https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L527

You can see that there are two types, a "Config" and a "Definition" type. The "Config" type is what is provided to the `new GraphQLObjectType` constructor, and the "Definition" type is the result of that constructor - that's mostly there to provide a more convenient API so you don't actually have to type out `args: []` when you have no args, but the constructor will then insert the `[]` for you to arrive at the "Definition" type.

If there is a library that is generating this schema, then it has a bug - it is likely not calling `new GraphQLObjectType` and resulting in a broken schema instance.

**Comment by yoadsn** [comment]
Hey Lee,
Thank you - since I opened this issue I have already arrived at the bottom of this and PR'd the other library (graffiti-mongoose) with a fix for the problem.
The only relevant part for graphql is the fact that the bug was caused by them modifying the result from `getFields()` of the type which was the internal (mutable) `_fields` property. If that return value was a copy (of the memoized `getFields()`) or an immutable data structure - this would have been avoided.

For your consideration - although I agree it's their bug.
Please close this issue if you feel nothing more is left to do here.

For reference - RisingStack/graffiti-mongoose/#131 is the relevant bug on `graffiti-mongoose`.

Thanks!

**Comment by leebyron** [comment]
Thanks for the follow up!
