### ISSUE TITLE
ast field in resolve method is undefined in new version (0.7.0)

### ISSUE THREAD

**Issue by shayank** [graphql/graphql-js#473]
my code is work fine in 0.4.x.
but does not work in 0.7.0
## this is my code:
```javascript
const Query = new GraphQLObjectType({
    name: "Queries",
    fields: {
        authors: {
            type: new GraphQLList(Author),
            resolve: function (rootValue, args, info) {
                let fields = {};
                let fieldASTs = info.fieldASTs;
                fieldASTs[0].selectionSet.selections.map(function (selection) {
                    fields[selection.name.value] = 1;
                });
                return authorsCollection.find({}, fields).toArray();
            }
        }
    }
});
```
i guess the problem goes from  this commit:
separateOperations - a utility function for splitting an AST (#456)
### thanks for any help!

**Comment by leebyron** [comment]
Thanks for the report, looking into it!

**Comment by leebyron** [comment]
I added a test case which checks for this case and I can't reproduce your issue. The tests pass showing that the field AST exists as expected.

I don't think #465 could be responsible for any breakage either since that utility was purely additive and did not alter any existing code.

If you have more information about exactly what error you're seeing then I'm happy to write more tests to help isolate the problem.

**Comment by shayank** [comment]
thanks lee!

in your test case resolve mehod is:
```javascript
resolve(val, args, ctx, _info)
```
but, my resolve method is:
```javascript
resolve: function (rootValue, args, info)
```
it seems info must be the 4th args in new versions.

so, is any solution to help me how the problem like this did not happened to me?

**Comment by stubailo** [comment]
This change was made in 0.5 or 0.6 - probably it's a good idea to keep a close eye on the change log, especially around breaking changes (for example, 0.5 -> 0.6 indicates a breaking change)

**Comment by leebyron** [comment]
Aha, good catch guys. Yes, the signature for resolver functions changed between 0.4 and 0.5 in order to treat context more correctly.

All you should need to do to support >= 0.5 is ensure you're accessing info from the fourth argument

**Comment by bantalek** [comment]
It seems the naming convention has been changed to fieldNodes. Versioning listed below.

`
const Query = new GraphQLObjectType({
  name: 'RootQuery',
  fields: {
    users: {
      type: new GraphQLList(User),
      resolve: (rootValue, args, ctx, info) => {
        let fields = {};
        let fieldNodes = info.fieldNodes;
        fieldNodes[0].selectionSet.selections.map((selection) => {
          fields[selection.name.value] = 1;
        });
        return db.users.find({}, fields).toArray();
      }
    }
  }
});
`


` 
fieldName: 'users',
  fieldNodes:
   [ { kind: 'Field',
       alias: null,
       name: [Object],
       arguments: [],
       directives: [],
       selectionSet: [Object],
       loc: [Object] } ],
...
`

"express": "^4.15.2",
"express-graphql": "^0.6.3",
"graphql": "^0.9.1",
"graphql-tools": "^0.10.1",
"lodash": "^4.17.4",
"promised-mongo": "^1.2.0"
