### ISSUE TITLE
"Thenables" does not necessarily means promise objects - Failing execution on "badly-formed" promises

### ISSUE THREAD

**Issue by rricard** [graphql/graphql-js#478]
Some libraries (such as very old mongoose versions) does not use native promises and use an old promise system that for instance won't support the `.catch` statement. those things are typically "thenable" but not "catchable". The issue here is that GraphQL execution engine considers everything "thenable" as "catchable".

This triggers the following stacktrace:

```
TypeError: completed.catch is not a function
      at completeValueWithLocatedError (node_modules/graphql/execution/execute.js:493:29)
      at completeValueCatchingError (node_modules/graphql/execution/execute.js:467:21)
      at resolveField (node_modules/graphql/execution/execute.js:440:10)
      at node_modules/graphql/execution/execute.js:219:20
      at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

This "bug" isn't really one if you use "real" promises everywhere but is one if you have to deal with legacy systems not quite updated yet.

I will provide a simple fix to this issue if you think it's worth fixing.

**Comment by rricard** [comment]
Note that you can fix that in your resolver easily if you are in this situation by wrapping the dysfunctional thenable into a real promise: 

```js
() => Promise.resolve(badThenable)
```

**Comment by denvned** [comment]
BTW, the original [Promises/A+](https://promisesaplus.com/) standard does not define `.catch(onRejected)`. It is added by ES6 Promise API and some other promise impelentations as a shortcut for `.then(undefined, onRejected)`.

**Comment by leebyron** [comment]
Ah this is definitely unintentional and should be considered a bug. graphql-js should only be relying on the more minimal definition of Promises and not relying on catch.

**Comment by rricard** [comment]
@leebyron you fixed that too fast for me ;) Thanks, this will help!
