### ISSUE TITLE
Is it appropriate to use Interface as marker interfaces.

### ISSUE THREAD

**Issue by ecstasy2** [graphql/graphql-js#48]
My use case is to implement a generic graphql server and I would like the ability to infer relationship between types from the schema.
To achieve this, I am thinking of using Interfaces as markers to allow the server to provide additional features to decorated types.

Is a valid use of Interfaces or is it more of a hack.

**Comment by leebyron** [comment]
This sounds like a hack more than a use case but I'm not sure I understand your use case. Can you share more concrete details of an example marker interface and how you expect to use it?

**Comment by ecstasy2** [comment]
In this example, I will require the marker Interface starting with *Has* (HasPlanets), generate a database with a One to Many relationship between Galaxy and Planet.

	type Planet {
	  id: String
	  name: String
	  galaxy: Galaxy
	}

	type Galaxy : HasPlanets {
	  id: String
	  name: String
	}

	interface HasPlanets {
	  planets: [Planet]
	}

Does that make it more clear?

**Comment by leebyron** [comment]
Sorry for losing this issue to time. For posterity, this usage is totally fine.

Usually when I hear "marker interface", I assume it is an interface which defines no fields. That's often a bad-code-smell, but as long as your interface defines some field (even only one field), that's a totally reasonable use case.
