### ISSUE TITLE
GraphQLNonNull and empty strings

### ISSUE THREAD

**Issue by jsonmaur** [graphql/graphql-js#480]
I assumed that if I have an argument with type `new GraphQLNonNull(GraphQLString)`, it would not allow empty strings. But it seems this is not the case. Is there another way to make sure empty strings are caught for required arguments?

**Comment by stubailo** [comment]
Currently GraphQL doesn't handle form-style validation, like ensuring the length of a string (an empty string is definitely not `null`, especially in JavaScript).

You might be interested in this thread, which talks about using custom input types for validation like this: https://github.com/graphql/graphql-js/issues/361

**Comment by jsonmaur** [comment]
Yeah that's what I thought. Thanks, I'll keep an eye on that thread.

**Comment by Cuantico** [comment]
In the schema do it like this
const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const buinessSchema = new Schema({
  name: { type: String, required: true, unique: true },
  address: { type: String, required: true },
  phone: { type: String, required: true },
  email: { type: String, required: true },
  website: { type: String, required: true },
  currency: { type: String, required: true },
  aboutus: { type: String, required: true },
  terms: String,
  slogan: String,
  logo: { type: String, required: true }
});

module.exports = mongoose.model("Buiness", buinessSchema);
