### ISSUE TITLE
resolve() hangs with rejected bluebird Promises

### ISSUE THREAD

**Issue by darthtrevino** [graphql/graphql-js#488]
I ran into this issue with graphql-js 0.7.0. While invoking the Stripe API using Bluebird::promiseFromCallback(), Stripe rejected the invocations with their own error object, not an `Error` instance. This resulted in the graphQL function to hang, and not process the error correctly.

I was able to correct my code by manually converting their errors into `Error` instances, but it seems like graphql should handle non-error based Promise rejections more gracefully.

**Comment by darthtrevino** [comment]
I'm trying to reproduce this in `resolve-test.js`, but it looks okay. I'll submit my tests as a PR.

**Comment by darthtrevino** [comment]
In playing around with this more, it looks like the Stripe error object is special in some way. I'll see if I can reproduce this situation.

**Comment by darthtrevino** [comment]
This error appears to be a combination of async and a specific type of rejection payload:

```js
resolve() {
    function CustomError() {}
    CustomError.prototype = Object.create(Error.prototype);

    return new Promise(resolve => setTimeout(resolve, 100))
    .then(() => new Promise((resolve, reject) => reject(new CustomError())));
}
```

I'll see if I can get the unit tests to pop

**Comment by darthtrevino** [comment]
This has been a PITA to track down, but I'm sure it's a weird isolated case. I'll close this for now.

**Comment by johncmckim** [comment]
@darthtrevino I'm seeing this issue too. It's not a nice one. Have you found a solution?

**Comment by darthtrevino** [comment]
Unfortunately not; I was able to reproduce it pretty consistently in my local serverless-graphql runtime, but not in a unit test. Since I'm not going crazy, and another person has run into this, I'll reopen the issue

**Comment by mygnu** [comment]
having the same issue here too, using rethinkdb (thinky) I believe they use bluebird too

`export const createUser = (args, rootValue) => {
    args.password = hashPwd(args.password)
        // console.log('user not found creating new one', args)
        // const user = new User(args)

    return User.save(args)
        .then((savedUsr) => {
            console.log('savedUsr', savedUsr)
            rootValue.session.token = createToken(savedUsr)
            rootValue.tokenData = decodeToken(rootValue.session.token)
            return savedUsr
        }).catch((err) => {
            console.log(err.message)
                // throw new Error(err.message)
           return err.message
        })
}`

**Comment by johncmckim** [comment]
@darthtrevino I am running the exact same versions of GraphQL + Bluebird.

The issue seems to occur when an Error object is throw. If I use `throw 'error string'` I don't see the same issue. Though, if I throw a string, Bluebird complains that a non error object has been thrown.

**Comment by darthtrevino** [comment]
Doing Promise.reject(<cause string>) works also. That still doesn't capture exceptions that happen from the language runtime or other libraries unless you try/catch everything that's sync, which would be horrible

**Comment by johncmckim** [comment]
There is special error handling in `./src/execution/execute.js`

```js
function resolveOrError(
  resolveFn: GraphQLFieldResolveFn<*>,
  source: mixed,
  args: { [key: string]: mixed },
  context: mixed,
  info: GraphQLResolveInfo
): Error | mixed {
  try {
    return resolveFn(source, args, context, info);
  } catch (error) {
    // Sometimes a non-error is thrown, wrap it as an Error for a
    // consistent interface.
    return error instanceof Error ? error : new Error(error);
  }
}
```

It could also be related to this function
```js
function isThenable(value: mixed): boolean {
  return typeof value === 'object' &&
    value !== null &&
    typeof value.then === 'function';
}
```

I don't exactly know what's going on, but it seems likely that it's something in `execute.js` doing not handling an error'd promise.

**Comment by darthtrevino** [comment]
On the latest version of Node, I'm seeing this unhandled promise rejection logged: 
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot redefine property: stack
```

**Comment by darthtrevino** [comment]
It looks like it's blowing up when on `Promise.reject()` here. Removing Promise.reject eliminates this when `npm link`ed

```
if (isThenable(completed)) {
      return ((completed: any): Promise<*>).then(
        undefined,
        error => Promise.reject(locatedError(error, fieldASTs, path))
      );
    }
```

**Comment by darthtrevino** [comment]
In GraphQLError.js, making the stack property immutable seems to fix this problem, but it would conflict with https://github.com/graphql/graphql-js/issues/439
```
Object.defineProperty(this, 'stack', {
      value: copyString(originalError.stack),
      writable: false
    });
```

**Comment by darthtrevino** [comment]
Related to https://github.com/petkaantonov/bluebird/pull/1238

**Comment by darthtrevino** [comment]
Actually, it looks like it needs a `configurable: true` setting on the property:

```
Object.defineProperty(this, 'stack', {
      value: copyString(Error().stack),
      writable: true,
      configurable: true
    });
```
