### ISSUE TITLE
passing in context without express-graphql ?

### ISSUE THREAD

**Issue by andyfenelon** [graphql/graphql-js#498]
is there any way to pass in context without the express-graphql package ?

the reason i ask without express is it's for a lambda function

im trying to process the jwt from the event then i need to pass it down as you would context in express-graphql.
```
module.exports.graphql = function(event, context, cb) {

  return graphql(Schema, event.body.query)
    .then((response) => {
      cb(null, response)
    })
    .catch((error) => {
      cb(error)
    });

};
```
 (ignore the arg 'context' thats in relation to the lambda).

**Comment by helfer** [comment]
Yes, it's the fourth argument.

https://github.com/graphql/graphql-js/blob/a725499b155285c2e33647a93393c82689b20b0f/src/graphql.js#L47

**Comment by andyfenelon** [comment]
thanks.
