### ISSUE TITLE
When passing in ast into GraphQLError getting Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by robertstettner** [graphql/graphql-js#507]
Example code from a `parseLiteral` function for a custom `GraphQLScalarType`:
```
if (ast.kind !== Kind.STRING) {
    throw new GraphQLError('Query error: Can only parse strings to dates but got a: ' + ast.kind, [ast]);
}
```
It returns: `Cannot read property 'start' of undefined`

This is probably due to the fact that the condition is set incorrectly on the [filter](https://github.com/graphql/graphql-js/blob/master/src/error/GraphQLError.js#L106).
It should be `node.loc != null` to capture `undefined`'s as well.

**Comment by leebyron** [comment]
Thanks for the report!
