### ISSUE TITLE
Processing after attribute was resolved

### ISSUE THREAD

**Issue by charypar** [graphql/graphql-js#51]
It would be very useful to add another callback to a field definition which would give you a chance to "post-process" the field value once it has been resolved.

This is useful for collection filtering when using interfaces. The inputs for different types implementing the  interface are often different, but the outputs are the same (i.e. the interface structure). The fields on the interface are also likely to be arguments of list fields, e.g.

```
interface Article {
  genre: String
}

type Blog : Article {
  genre: String
}

type News : Article {
  genre: String
}

type Feed {
   items(genre: [String]): [Article]
}
```

If `Blogs` and `News` come in in different formats and are coerced into the same structure by their respective types, without the post-processing the filtering is tricky and needs to do the same kind of type detection `Article` does to decide on how to resolve the `genre` for filtering, which is also already being done by `Blog` and `News` as well.

Am I missing some obvious way to do this?

**Comment by leebyron** [comment]
Interface fields do not contain resolvers, but just describe the fields which implementing types must also declare.

When a field returns a value of an Interface type (like `items` in your example), the Interface type's `resolveType` is called which must return one of the concrete Object types:

```js
var ArticleType = new GraphQLInterfaceType({
  name: 'Article',
  resolveType(obj) {
    if (isBlog(obj)) {
      return BlogType;
    } else if (isNews(obj)) {
      return NewsType;
    }
  }
});

...
```

**Comment by leebyron** [comment]
Another option instead of defining `resolveType` on the interface is to define `isTypeOf` on the object types.

If you do this, then the interface will loop through all of it's implementing types calling `isTypeOf` until it gets a `true` result and will resolve to using that type.

**Comment by charypar** [comment]
It's not the interface field resolvers (there's no such thing) it's resolvers of fields of interface types (base is an object type, it just has a field that's an interface type). What I'd like to do is post-processing the items list itself once it's resolved, e.g. if `genre` on `Blog` and `genre` on `News` are very different (e.g. you need to run some business logic on tags or something), yet you want to filter the list by it, you end up duplicating the `genre` fetching logic for filtering `items` in the `items` field resolver on Feed. 

It would be useful to get to manipulate the list _after_ all the resolvers on Blog or News ran, resulting in a unified object format (i.e. Article) and be able to do some processing then. The only way to do it now is to use the source formats (which Article uses to decide if it's a Blog or a News and which Blog or News then uses to figure out the genre). I suppose this is only ever really useful for lists.

So graphically(-ish) the processing would go like this

```
top.fetchFeed -> Feed.fetchItems -> Article.resolveType; [type].fetchGenre -> Feed.postProcessItems
```

Hope that clarifies what I mean.

**Comment by leebyron** [comment]
I understand now what you mean. That is not something we intend to support. It's actually unclear what the "postProcessItems" function would accept or return. It may not be the best place to do a filter, as ideally a filter helps you prevent actually fetching that information from a database or other backing service and a post-process would be too late to do that sort of work.

I would suggest creating utility functions which your types can use to avoid duplicating work:

```js
var NewsType = new GraphQLObjectType({
  name: 'News',
  fields: {
    genre: {
      type: GraphQLString,
      resolve(obj) { 
        return postProcessGenre(obj.newsGenre);
    }
  }
});

var BlogType = new GraphQLObjectType({
  name: 'Blog',
  fields: {
    genre: {
      type: GraphQLString,
      resolve(obj) { 
        return postProcessGenre(obj.blogGenre);
    }
  }
});
```

Does this handle your case?

**Comment by charypar** [comment]
Oh I think I see your point - in my example if I don't ask for the `genre` in the subsection, I won't get it in the return value, therefore I can't filter by it. The input for the post-processing is not well defined... Didn't realise that.

The code suggestion doesn't handle my case (I'm after filter items list based on `genre`) but I can see how doing the type resolution twice (once to resolve genre, once to filter by genre) and reusing the `genre` fetching logic is still simpler than trying to nail down post-processing.

**Comment by leebyron** [comment]
I'm going to close this task out for now since we've come to some sort of resolution. But feel free to re-open or open new tasks in the future
