### ISSUE TITLE
use buildSchema for root-level node field resolver

### ISSUE THREAD

**Issue by Gregoor** [graphql/graphql-js#516]
As of the Relay Spec, a root-level node-field is needed, that resolves the app's types. Unfortunately that does not seem to be possible, when using buildSchema, as this error is thrown:

`Generated Schema cannot use Interface or Union types for execution`
Thrown at:
- https://github.com/graphql/graphql-js/blob/89f3f1a319bb913616f2910e8a806170155ffaf0/src/utilities/buildASTSchema.js#L410
- https://github.com/graphql/graphql-js/blob/89f3f1a319bb913616f2910e8a806170155ffaf0/src/utilities/buildASTSchema.js#L436

I'd gladly help working on a PR enabling this, if someone were so kind to give me a primer on why this error was introduced.

**Comment by helfer** [comment]
@Gregoor unions and interfaces need to define a resolveType or ofType method in the code, and that can't be expressed in schema language. There are packages like [graphql-tools](https://github.com/apollostack/graphql-tools) that help you get around this limitation.

**Comment by Gregoor** [comment]
Awesome, thanks (and what a fitting nickname you have 😄 )!

**Comment by alex-wilmer** [comment]
>  and that can't be expressed in schema language

This is also repeated on the graphql docs. Can we get a bit more explanation on the specifics here? I've been fiddling with trying to resolve an interface using `rootValue` but I'm guessing this is impossible. Thanks
