### ISSUE TITLE
Support schema-language directives in schemaPrinter

### ISSUE THREAD

**Issue by gluck** [graphql/graphql-js#518]
schemaPrinter only supports `@deprecated` schema-language directive, custom directives (e.g. on FIELD_DEFINITION) aren't included in the output.

Is this intended to remain like that (maybe for compatibility reasons with other GraphQL libs which do not support the syntax), or simply waiting for someone to pick up the task ?

Thx

**Comment by leebyron** [comment]
Sounds like a bug, thanks for the report

**Comment by leebyron** [comment]
Closing as won't repro. Please feel free to open if you found a specific case that's still a bug.

We currently have a test against printing directives in the schema language:  https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/schema-printer-test.js#L53 that has been passing consistently.

**Comment by gluck** [comment]
This is testing `graphql/language/printer`, but I was using `graphql/utilities/schemaPrinter`, didn't know there were 2 printers, sorry for the confusion.
Will try to use the other one, thanks.

**Comment by gluck** [comment]
Actually, I can't use this printer coz it works at AST level, but I have already built (and extended) the schema. Let me know if my original question makes sense (or not) in this context.

Thanks.
