### ISSUE TITLE
Executing multiple queries sequentially?

### ISSUE THREAD

**Issue by matthewmueller** [graphql/graphql-js#524]
Haven't thought too much about it but it seems like this should work as a single request:

``` graphql
query getArticles ($limit: Int!) {
  articles: allArticles (first: $limit) {
    title
    slug
    text
  }
}

query getUser ($user: ID!) {
  user: User (id: $user) {
    firstName
    lastName
  }
}
```

Where the queries are executed sequentially and data is populated with `{ articles, users }`, and throws if aliases / queries are conflicting. Since it's sequentially executed, you don't run into any issues with race conditions if you use mutations.

That would allow you to make a really simple query batching system on the client and then allow dataloader to cache the overlapping pieces of the queries from the single request.

**Comment by leebyron** [comment]
I'm a bit confused about this - first why you would want these two to run sequentially rather than in parallel, and also if you wanted both, why you wouldn't just combine them into one query, especially if you expect the data to be returned as one result.

**Comment by robzhu** [comment]
@matthewmueller, this issue has been inactive for a while now, so I assume you figured it out or found an alternative. Feel free to reactivate if you want to provide more details to Lee's response.

**Comment by janhancic** [comment]
Not OP, but the use case for not having them part of the same query is that you have two independent components that require it's own data. They request their data at the same time, so the FE can combine the two queries into one request, but really they don't have anything to do with each other.

In this case they should be executed in parallel tho, no reason not to.

**Comment by bartclaeys** [comment]
So, is it possible or not to combine two queries like that?

**Comment by janhancic** [comment]
@bartclaeys I ended up doing the following (note that I use my own logic for fetching graphql on the client):

- FE captures any fetch requests for graphql that are triggered in a certain time window
- after the time window it combines them into an array `[{query: ..., variables: ...}, ...]` and sends one HTTP request
- the backend (graphene in my case) then checks if the request is an array, and if it is it executes all the queries in parallel
- the responses then get sent back to the FE in an array, which then unpacks them and returns them to callers

You can also just concatenate the queries together into one string and send it over, most graphql servers should be able to handle it (but you might have name clashes, in which case you'd have to manually add aliases).

It all comes down to which client you're using. Apollo for example will do that for you. If you're using custom solutions (like me) then you'll have to roll your own logic. Hope that helps somewhat.
