### ISSUE TITLE
When should I use initial types on the schema?

### ISSUE THREAD

**Issue by paulofaria** [graphql/graphql-js#549]
Hello, I have a quick question.

When should I use initial types on the schema? What is the use case?
The star wars example uses it right here:

https://github.com/graphql/graphql-js/blob/master/src/__tests__/starWarsSchema.js#L295

Why is that needed? Thanks!

**Comment by leebyron** [comment]
It's specifically needed when you have types which implement interfaces but are otherwise not referenced anywhere in the schema. However it's also best practice as it guarantees an order of types.

**Comment by paulofaria** [comment]
Awesome! Good to know. I created a Swift implementation for GraphQL.  I'll add that as a note on the examples.

https://github.com/GraphQLSwift/GraphQL

Also created a higher level schema framework.

https://github.com/GraphQLSwift/Graphiti

If you're interested you can see the star wars schemas here:

https://github.com/GraphQLSwift/GraphQL/blob/master/Tests/GraphQLTests/StarWarsTests/StarWarsSchema.swift
https://github.com/GraphQLSwift/Graphiti/blob/master/Tests/GraphitiTests/StarWarsTests/StarWarsSchema.swift

The GraphQL implementation is pretty close to the js one. Although I had to do some black magic reflection hacking since Swift doesn't provide reflection out of the box. I was pretty impressed about how js is so close to Swift when using Flow. Awesome job with GraphQL by the way! I'm loving it so far. I think it can really become the next thing! 

Cheers!
