### ISSUE TITLE
Missing default export?

### ISSUE THREAD

**Issue by bali182** [graphql/graphql-js#556]
When importing the package, the destructuring and require imports work well, but the default import just returns undefined:

```js
import { GraphQLObjectType, GraphQLString, GraphQLSchema } from 'graphql' // ✓
const graphql = require('graphql') // ✓

import graphql from 'graphql' // ⚠ graphql is undefined

```
Is this intentional?

**Comment by stubailo** [comment]
I think maybe what you're looking for is:

import * as graphql from 'graphql'

That's just how es2015 modules work.

**Comment by bali182** [comment]
```js
// a.js
export foo = 'foo'
export bar = 'bar'

export default { foo, bar } // this is what I'm missing

// b.js

import { foo, bar } from './a'
import a from './a'  // this is what I'm missing
```

Now `import * as ` works properly, but it would be nice if everything would be default exported as well.

**Comment by robzhu** [comment]
Given the readily available solution for what you're trying to do, I'm closing this issue.
