### ISSUE TITLE
root as context?

### ISSUE THREAD

**Issue by mickhansen** [graphql/graphql-js#56]
This is a question for practice rather than a problem.

`resolve` methods take a root object as the 3rd argument, and so does the graphql method.

Is `root` meant as **the** way to pass around context information (like the session if wanting to implement `viewer` from the relay video examples)?

**Comment by leebyron** [comment]
Yes, that's what I intended it for :)

I hope this will be more clear as we get more examples up

**Comment by mickhansen** [comment]
Great, thanks :)

**Comment by xpepermint** [comment]
@leebyron can you please add this to the `Readme` file. This functionality in great, feels like working in `express.js`. It's very useful but you can only know about it if you read the source or other resources.
