### ISSUE TITLE
What type is the `defaultFieldResolver<any, *>`?

### ISSUE THREAD

**Issue by TonyPythoneer** [graphql/graphql-js#588]
I have a question about this: [export const defaultFieldResolver: GraphQLFieldResolver<any, *>](https://github.com/graphql/graphql-js/blob/914dde29098425df45cee95b6feb81b9fed97edb/src/execution/execute.js#L1045)

What is `*`? Is it mentioned on flowtype document?

**Comment by intellix** [comment]
Figured this out. There's no documentation about it and it's not mentioned anywhere. There's not one mention of an asterisk in documentation. 
You'll get an error message though if you download flow and change that * to something like A with:
```
index.js:14
 14: export const defaultFieldResolver: GraphQLFieldResolver =
                                        ^^^^^^^^^^^^^^^^^^^^ GraphQLFieldResolver. Application of polymorphic type needs <list of 2 arguments>. (Can use `*` for inferrable ones)
```

Mystery solved :)

**Comment by asiandrummer** [comment]
@intellix awesome find - thanks :D 
@TonyPythoneer hopefully this answers your question - let us know if you have any other questions!
