### ISSUE TITLE
Update iterall dependency - Typescript breacking

### ISSUE THREAD

**Issue by nakedcity** [graphql/graphql-js#593]
Please see https://github.com/leebyron/iterall/pull/12 which is already merged into the master

**Comment by robzhu** [comment]
Can you please post more details about how typescript is breaking?

**Comment by nakedcity** [comment]
It's due to a wrong definition in the iterall lib please see above url of reference

**Comment by asiandrummer** [comment]
@nakedcity seems like the dependency is now `iterall@1.0.3` - closing this as resolved.
