### ISSUE TITLE
Using Input types inside compound Object types.

### ISSUE THREAD

**Issue by richburdon** [graphql/graphql-js#599]
Suppose I have a filter type that I use to constrain a query:

```
input Filter {
  type: String
  labels: [String]
  text: String
}
```

And I want to create a set of folders that contain the filter definitions; e.g., 

```
type Folder {
  name: String
  filter: Filter
}
```

This seems perfectly reasonable, but can't be achieved since Input types can't include Output types.

@leebyron, you don't really explain WHY in [https://github.com/graphql/graphql-js/issues/423]. In your own example:

```
input Location {
  lat: Float
  lon: Float
}
```

Should we create pairs of each basic type (Location and InputLocation; Address, InputAddress; TelephoneNumber, InputTelephoneNumber, Name, InputName, etc.)?

Given the class vs struct analogy. It seems that structs (input types) could reasonable by included in class (output type) definitions?

Related Apollo discussion: https://github.com/apollostack/graphql-tools/issues/179

**Comment by leebyron** [comment]
The primary reason is that under the hood these are two very different structures - one is responsible for taking input values and coercing them into server-side values, the other is responsible for fetching information from a server. If we were to allow input types as output types, they would have to implement *both* of these structures.

In addition to this, the input and output types are very often not the same with regards to nullability, which behaves differently in input and output contexts. For inputs, non-null means that it's required to be provided whereas for outputs, non-null means that it's guaranteed to provide a value if queried. A really common scenario for wanting to reuse input types is when building a CRUD style API where you want to provide fields to update in a mutation. In these kinds of APIs it's really common for a type to have non-null (guaranteed to exist) fields but shouldn't be required to be provided during a mutation. For these kinds of APIs, there are often types such as `Address` and `AddressUpdate` for the output and input types respectively.

Finally there's just the potential user confusion of defining an input type, and then using it as an output type - given the differences that input types have, this could make GraphQL more difficult to understand, and we've strived to keep things easier to understand even if that sometimes comes at the cost of convenience.

**Comment by richburdon** [comment]
@leebyron thanks for the response and sorry for the "late" response. 

I understand the concerns, but it seems that in hindsight, GQL could have been designed to address these (e.g., protocol buffers support similar semantics but don't have this issue.

I have a nested Input type system that defines about 20 types. So I need to redefine all 20 types (and modify them each time they grow/change) just so that I can return the same JSON data structure from my requests. Do you see that this can be brittle -- is this considered an edge case? The only practical solution I can see is to write yet-another-pre-compiler.

**Comment by stubailo** [comment]
Protocol buffers are super different because fields don't have arguments. While protobuf to my knowledge just describes the shape of an object graphql object types can do a lot more. Input types are much simpler and just describe the shape.

I think the best solution here is to do some code generation on the server to generate two types, one output and one input?

**Comment by richburdon** [comment]
Once again, thanks again for the quick response.

Re protos, I think you're probably right; you can define services (https://developers.google.com/protocol-buffers/docs/proto#services), but I don't think you can easily inline them inside types -- although I think that's a design choice -- and I'm suggesting that's possibly the same here?

````
type MyMutation {
  foo(input: MyComplexInputType!): MyComplexType!
}

input MyComplexInputType { foo: Foo! }
type MyComplexType { foo: Foo! }

input FooInput { bar: BarInput! }
type Foo { bar: Bar! }

input BarInput { title: String! }
type Bar { title: String! }

// Turtles all the way down...
````

How could I do this on the server? I need definitions I can use in the GQL files. So I'd have to write another DSL? What I'm doing now:

````
type MyMutation {
  foo(input: MyComplexInputType!): String!    // Return JSON and lose nice type checking.
}

input MyComplexInputType { foo: Foo! }
input FooInput { bar: BarInput! }
input BarInput { title: String! }
````

**Comment by karloluis** [comment]
Has there been any further development on this discussion? It seems like it has been agreed upon by the community to keep input output types separate for all intents and purposes.

This drives me to question could the type definitions for both scenarios be structured so that they are easily maintainable? How does that look like at scale?

**Comment by brysgo** [comment]
@leebyron - you say the main reason for input types is to disambiguate required fields. Could this problem be solved by having a different operator to specify if a field is required for input or output?

**Comment by brysgo** [comment]
Or having type definitions be input and out put by default, but have some operator like:

```graphql
type MyType {
  fieldOnInputAndOutput: String!
  > {
    fieldOnlyOnOutput
  }
  < {
    fieldOnlyOnInput
  }
}
```

**Comment by TriStarGod** [comment]
Any update on this?

**Comment by akotlar** [comment]
Agreed; as a relatively new user I've found the existence of separate input and output types a leaky implementation detail, that causes user friction, and which may increase chance of error, as it seems I have to duplicate portions of my schema between input and output, unless I just haven't found the appropriate feature, quite possible.

**Comment by krishna81m** [comment]
Looks like we need another "data/field type" OR at the least "interface type" that just has scalar/object attributes that types and inputs can extend OR implement and each add their own customization inpuyt type can add non-null etc., if needed? 

The whole point is to do reusable/consistent fields i.e., names/data types for input/output especially for large schemas

**Comment by hafbau** [comment]
The way I've been able to work around this is define the schema string as a variable and then reuse that.

```ts
const myType = `
  foo: String,
  bar: ID
`

const typeDefs = gql`
  input MyTypeInput { ${myType} }
  type MyType { ${myType} }
`
```

Please let me know if there's a simpler/better idea out there for a newbie.

**Comment by RoyLeibo** [comment]
@richburdon I totally agree with you. It have no sense to force us to use different types for input and output, it is harder to maintain and can cause many other issues.
The reasons why separate those fields are not strong enough for my opinion.

**Comment by tstewart-klaudhaus** [comment]
GraphQL is great and I have used it successfully now for years. However this misalignment between input and output data is grating, and always a difficult conversation to have with customers and colleagues. I agree with the person who called it a "leaky implementation detail". I understand the difference between output type fields (which can have parameters and can thus be thought of like methods) and input structures (which may have different nullability conditions than their related output type) but it seems to me that the conceptual nature of an input type is a subset of the conceptual nature of an output type, and it is frustrating not to be able to use it as such. This is also revealed in union types - usable in output types but not input types. I am currently (again) building workarounds in my projects with code generation. I'm not expecting this to change, and accept it as a tradeoff in using this standard (similar to the many tradeoffs I accept in using CSS or JavaScript, say) but I'm dropping this comment to express empathy with others coming to terms with this.
