### ISSUE TITLE
isValidJSValue does not always return an array

### ISSUE THREAD

**Issue by li-kai** [graphql/graphql-js#601]
I'm not sure if this is an expected behaviour of the method, as the docs say that it returns an array of errors. Here's a failing test case in mocha:

```js
describe('isValidJSValue', () => {
  it('is returning an array of errors', () => {
    expect(isValidJSValue('a', GraphQLInt)).to.be.an.instanceof(Array);
  });
});
```

**Comment by robzhu** [comment]
Thanks for filing this. I think you're right, we're not catching the exception inside isValidJSValue. I'll have a PR up shortly.
