### ISSUE TITLE
Ideas on how to optimize GraphQL execution (and validation) ?

### ISSUE THREAD

**Issue by youknowriad** [graphql/graphql-js#607]
Hi and thanks for the awesome library!

I'm doing a small experiment here https://github.com/Automattic/wp-calypso/pull/9386 and I'm using GraphQL on the client instead of the server (Due to some of our API constraints). 
I'm basically running GraphQL.execute() on every Redux.subscribe, which can be run a lot.

GraphQL is already fast, but all micro-optimisations can be helpful here, so I'm wondering what can we do to improve GraphQL resolution algorithm's performance. Can we disable validation on Prod for example and just assume the queries and the schema are valid (Maybe not even relying on the schema and use just the query against the resolvers) ? Is there any other kind of optimisation you can think of? Thank you for your help.

**Comment by robzhu** [comment]
You might want to follow the RFC for adding persisted queries: https://github.com/graphql/express-graphql/pull/109

The idea is that you can persist a valid query ahead of time and then skip the validation step when executing.
