### ISSUE TITLE
Sending queries to the backend 

### ISSUE THREAD

**Issue by helixether** [graphql/graphql-js#611]
Does graphql expect queries be sent s's strings to be to the graphql backend for querying? If so, how do you guys handle query generation for front end apps?

**Comment by robzhu** [comment]
For the Facebook mobile apps, we validate and persist the queries ahead of time and the mobile client just specifies an ID. This video goes into more detail: https://atscaleconference.com/videos/graphql-in-native-applications-at-scale/
