### ISSUE TITLE
[Feature request] allow connectionDefinitions to accept a thunk

### ISSUE THREAD

**Issue by holmesal** [graphql/graphql-js#612]
Currently `ConnectionDefinitions` doesn't accept a thunk, which means any types used need to be defined immediately, which can lead to some awkward circular dependency issues.

My current (hacky) solution is to call connections as methods instead, and return (or create and cache) the connection when it is actually requested:

```js
import {
    connectionDefinitions
} from 'graphql-relay';

import * as types from './types';

// todo - find a cleaner way to do this? connectionDefinitions doesn't accept a thunk...
var connectionTypes = {};
const getType = (name, nodeType) => {
    if (!connectionTypes[nodeType]) {
        connectionTypes[nodeType] = connectionDefinitions({name, nodeType: types[nodeType]}).connectionType;
    }
    return connectionTypes[nodeType];
};

export const ActionConnection = () => getType('Action', 'ActionType');
export const UserConnection = () => getType('User', 'UserType');
```

It would be oh-so-awesome if instead I could just do something like:

```js
import {
    connectionDefinitions
} from 'graphql-relay';

import * as types from './types';

export const UserConnection = connectionDefinitions(() => ({name: 'User', nodeType: types.UserType}));
```

**Comment by sibelius** [comment]
@holmesal great idea

you should move this issue to graphql-relay-js repo

checkout it my issue there: https://github.com/graphql/graphql-relay-js/issues/113

**Comment by holmesal** [comment]
d'oh, wrong repo 😁

**Comment by sibelius** [comment]
@holmesal post this idea there on graphql-relay-js and link it here
