### ISSUE TITLE
buildSchema root mutation

### ISSUE THREAD

**Issue by k15a** [graphql/graphql-js#622]
I am sorry if this is somewhere documented but I couldn't find any resources about this.

Is it possible to specify a root mutation like rootValue does for the query?
My goal is to use buildSchema to build my schema and then have a resolver for the mutation and query.

Something like this:

```JS
import { graphql, buildSchema } from 'graphql'

const users = []

const schema = buildSchema(`
  type User {
    username: String
    password: String
  }

  type Query {
    users: [User]
  }

  type Mutation {
    signup (username: String, password: String): User
  }
`)

const query = {
  user: () => users
}
const mutation = {
  signup: (user) => users.push(user)
}

graphql(schema, '{ users { username } }', query, /* mutation? */).then((response) => {
  console.log(response);
});
```

**Comment by asiandrummer** [comment]
Hi @k15a - you might have forgotten to define a schema definition documented [here](http://graphql.org/learn/schema/#the-query-and-mutation-types):
```
schema {
  query: Query
  mutation: Mutation
}
```

**Comment by DxCx** [comment]
@asiandrummer i dont remember when exactly, but this is not a requirement anymore.
if not defined, Query & Mutation will be used.

@k15a , why using root object for this instead of context?
context is much more suitable for this.

**Comment by k15a** [comment]
@DxCx How should context help with this problem? Isn't context something to pass for example the auth code or a db connection down?

**Comment by DxCx** [comment]
for example, this should work:
```javascript
import { graphql, buildSchema } from 'graphql'

const users = []

const schema = buildSchema(`
  type User {
    username: String
    password: String
  }

  type Query {
    users: [User]
  }

  type Mutation {
    signup (username: String, password: String): User
  }
`)

const context = {
  users: users
}
const mutation = {
  signup: (root, args, ctx) => ctx.users.push({ userName: args.userName });
}

graphql(schema, '{ users { username } }', context).then((response) => {
  console.log(response);
});
```

**Comment by DxCx** [comment]
context is the object used to connect the schema to any outer layer.
in your case, thats an array of users that should be filled.
it is also used, as you mentioned, for communicating with databases..

**Comment by DxCx** [comment]
i just noticed that you didn't connect resolvers to the schema, so mutation isn't really going to work,
but you should be able to get the idea...

**Comment by k15a** [comment]
Yeah that's my problem :D how can I connect the mutation to the schema?

**Comment by DxCx** [comment]
http://dev.apollodata.com/tools/graphql-tools/generate-schema.html
Enjoy :)

**Comment by k15a** [comment]
So it's not supported by `graphql-js`?

**Comment by DxCx** [comment]
I'm not sure how it should be done with bare graphql-js,
maybe someone else can shade some lights..

**Comment by chentsulin** [comment]
Just curious the anwser and find orginal PR https://github.com/graphql/graphql-js/pull/471 . Maybe  could get some help from @lacker?

**Comment by leebyron** [comment]
The same `rootValue` is used for all types of operations, so to build on your original example @k15a, you could write:

```js
const rootValue = {
  user: () => users,
  signup: (user) => users.push(user)
}

graphql(schema, '{ users { username } }', rootValue).then((response) => {
  console.log(response);
});
```

Or if you're using Babel and have object spread syntax:

```
const query = {
  user: () => users
}
const mutation = {
  signup: (user) => users.push(user)
}

graphql(schema, '{ users { username } }', {...query, ...mutation}).then((response) => {
  console.log(response);
});
```
