### ISSUE TITLE
GraphQLInputObjectType returning undefined

### ISSUE THREAD

**Issue by rohmanhm** [graphql/graphql-js#624]
Hi, I had a problem with my GraphQL, 
`InputType.description` return `User Schema Type`, yes it's I want. BUT
`InputType.hu` and `InputType.fields` return `undefined`.

So, this is a bug or I make mistakes?

Here's my code

```
import {
  GraphQLInputObjectType,
  GraphQLString,
  GraphQLID,
} from 'graphql';

export let fields = {
  id: { type: GraphQLID },
  firstName: { type: GraphQLString },
  lastName: { type: GraphQLString },
  email: { type: GraphQLString },
  address: { type: GraphQLString }
};

const InputType = new GraphQLInputObjectType({
  name: 'UserType',
  hu: {
    pol: true
  },
  description: 'User Schema Type',
  fields: {
    foo: 'bar'
  }
});

console.log('TEST', InputType.fields, InputType.description, InputType.bulat, fields);

export default InputType;

```

Here the result's

```
TEST undefined User Schema Type undefined { id: { type: ID },
  firstName: { type: String },
  lastName: { type: String },
  email: { type: String },
  address: { type: String } }
```

**Comment by asiandrummer** [comment]
@rohmanhm - If you look at [how the function parameter is defined](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L1057), it allows `name`/`description`/`fields` to be passed in to compose a `GraphQLInputObjectType` type object. I'm not sure what `hu` attribute is, but if you wanted that to be one of the fields, then you'd have to include it inside `fields` attribute with a corresponding type. Same for `foo` - maybe you wanted `fields: { foo: { type: GraphQLString } }` as well?

I'm not sure what you're looking to achieve, but I'd follow [this example](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L976) and other examples described in the comment section here.

**Comment by rohmanhm** [comment]
`hu` in this case just an example (tested), because of `name` and `description` work perfectly like I want. But, I don't know why `fields` can't access and return `undefined`.

I make a new project, but still show `undefined`
this is the code
```
const UpdatePersonInputType = new GraphQLInputObjectType({
  name: 'updatePersonInputType',
  description: 'udpate person model input type',
  fields: {
    firstName: { type: GraphQLString },
    lastName: { type: GraphQLString },
    email: { type: GraphQLString }
  }
});

console.log(UpdatePersonInputType.fields, UpdatePersonInputType.name);
```

this is message from my console (terminal)
`undefined 'updatePersonInputType'`

**"graphql": "^0.8.2"**

**Comment by asiandrummer** [comment]
Because we don't expose `fields` as a public property - please try using `getFields()` to get the list of the fields you've defined.
```
UpdatePersonInputType.getFields()
```

**Comment by rohmanhm** [comment]
Oh man, It's worked !!
Thanks
