### ISSUE TITLE
Java based Graphql clients support for Graphql-js implementation

### ISSUE THREAD

**Issue by sudheerj** [graphql/graphql-js#657]
We preferred to use Graphql-js implementation because it is a reference implementation.But many of our clients/applications are Java based.Are there any Java based Graphql clients similar to REST clients? There are JS Graphql Clients such as Apollo,Relay,Lokka etc but not Java based.Thanks in advance for the help.

Best regards

**Comment by stubailo** [comment]
This one is getting pretty far along, but not released yet: https://github.com/apollostack/apollo-android

Are you looking for a client for Android or server-side Java?

Anyway, this doesn't have anything to do with graphql-js (this repository) since it doesn't matter what you're using on the server, any GraphQL client would be compatible with a server written in any language.

**Comment by sudheerj** [comment]
Thanks for the response Stubailo.We need a client for server-side java.We are looking something similar to Java REST Clients in the graphql world.Some of our UI applications built on JSF framework so we need a better way to compose query,variables from the HTTP request.i.e,We are looking for a better way to interact Java UI interface with graphql-js queries.

**Comment by sudheerj** [comment]
Ok. But currently we need to use it for web applications instead mobile apps and apollo-andriod is not released yet too.Do we have any other workarounds to submit queries from Java calls.I need to create graphql queries based on JSON request and submit to the server.

**Comment by stubailo** [comment]
You can also easily call graphql with any http client. I'm not sure what you mean by Java web application though - is this an HTML web server written in java that is calling graphql from the server side?

**Comment by sudheerj** [comment]
Thanks stubailo.I thought java clients makes easier to integrate graphql queries.We can just craete JSON object(query,variables,operationname) and that can be sent as POST body in REST API calls.So I feel it is not required to have Java Clients for this purpose.

**Comment by stubailo** [comment]
Yep that's correct. The Android client has features specifically for integrating it into a mobile UI.

**Comment by smolinari** [comment]
Could this be more like what you are looking for @sudheerj ?

https://github.com/graphql-java/graphql-java

Scott

**Comment by sudheerj** [comment]
Thanks Stubailo.I will look into Android client and its features.Good work on your Apollo works.Also the nice presentations in conferences.

@smolinari,

              I still belive graphql-js is far better than graphql-java.We already have our own generic query language based on java but it didn't follow the graphql spec.Because it is legacy code.Based on the reviews I opted graphql-js reference implementation.
