### ISSUE TITLE
Error: request entity too large in graphql services of node

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [graphql/graphql-js#658]
I am working on node based graphql project, trying to send base64 formate image to server.

I am using bodyparser module and configured it as bellow.

```
app.use(bodyparser.text({type: 'application/graphql'}));

app.use(bodyparser.json({limit: '50mb'}));
app.use(bodyparser.urlencoded({limit: '50mb', extended: true}));
```
I am able to send base64 images by direct node services but when it come to graphql services, it is throwing error as "Error: request entity too large".

Please help me to overcome.

**Comment by robzhu** [comment]
I would not recommend using GraphQL to handle large chunks of binary data.

**Comment by HarshaVardhanPVK** [comment]
You mean there is no way to handle large chunks of data or it is difficult to handle in GraphQL?

**Comment by robzhu** [comment]
Generally, for dealing with large amounts of binary data like this, you'll want to use some sort of streaming mechanism: https://nodejs.org/api/stream.html. One problem is that the GraphQL server is going to want to parse the request first. To make this efficient, you would need to introduce some sort of chunking mechanism, which also introduces server-side state for partially transferred data. It's possible, but it's a lot of work for very little benefit. Instead, I suggest using HTTP URI's to reference large, static binary resources.

**Comment by HarshaVardhanPVK** [comment]
Thanq very much for your quick response, I will go with plain node service only to handle large chunk...

**Comment by robzhu** [comment]
Cool, let me know if you run into any more issues along the way.

**Comment by HarshaVardhanPVK** [comment]
Sure, Thanq...
