### ISSUE TITLE
GraphQL integration with Cassandra

### ISSUE THREAD

**Issue by sudheerj** [graphql/graphql-js#660]
In our legacy application we already implemented our own Generic query language to fetch the data for  what we need.Considering the standard we tried to adopt GraphQL instead of our own stuff API .Eariler we used MongoDB as storage engine and written wrappers API for query parsing,validation etc.Considering the distributed nature we moved to Cassandra DB.

Is there any better integration or APIs with Cassandra DB.Is there any frameworks to convert GraphQL queries to Cassandra queries.Otherwise it is going to be very difficult or complex to implement query parsing ,validation and writing lot of CQL stuff.

**Comment by smolinari** [comment]
This might be of interest. 

http://codefoundries.com/developer/cassandra/cassandra-meet-relay.html

Since GraphQL is supposed to be a thin layer API between your business logic and your front-ends, I highly doubt you'll find specific implementations for any particular database. 

Scott

**Comment by robzhu** [comment]
> it is going to be very difficult or complex to implement query parsing ,validation and writing lot of CQL stuff

Can you give an example of an input GraphQL query, the resulting query against the DB, and why you consider it to be very difficult?

**Comment by sudheerj** [comment]
I already seen cassandra-meet-relay.Other than using cassandra-driver I didn't find any useful information from that link.There are no proper examples for easy integration.

`query RootQuery {
    accounts(skip: 0,limit: 13,sort_field: "account_number",sort_order: "descending",filter:"{'account_number': { '$not': { '$gt': 4522 }  }}"){
account_number,
account_name
}
}
`

**Comment by smolinari** [comment]
What do you consider is "easy integration"? 

Scott

**Comment by sudheerj** [comment]
I mean If there is an API for parsing,validation from Graphql to Cassandra then it will be easy to implement for kind of appliations

**Comment by smolinari** [comment]
If you mean parsing and validation in terms of business rules and logic, this is within the business domain and each business should be figuring that layer out for themselves. There are plenty of libraries to help with this, but it is up to you to select which one to use (or create your own). This image shows you where GraphQL would sit as an API. What you are asking for is the blue area and AFAIK, this hasn't been built out to be a standardized back-end (yet). 

![10-01-_2017_15-19-15](https://cloud.githubusercontent.com/assets/3314957/21809506/54d5592e-d748-11e6-8a8e-d15200e9689f.jpg)

Scott

**Comment by sudheerj** [comment]
Thanks smolinari  for your detailed response.The query parameters(sometimes it include so many filter conditions) need to extracted for each field and add it for CQL(Cassandra query language).It will be painful for each query.The CQL queries will be scattered with lots of condtions.

**Comment by robzhu** [comment]
> I already seen cassandra-meet-relay.Other than using cassandra-driver I didn't find any useful information from that link.There are no proper examples for easy integration.
> 
> query RootQuery {
> accounts(skip: 0,limit: 13,sort_field: "account_number",sort_order: "descending",filter:"{'account_number': { '$not': { '$gt': 4522 } }}"){
> account_number,
> account_name
> }
> }

This example query seems very close to the database layer. You already mentioned that you migrated from MongoDB to Cassandra. If you expose too many persistence layer details at the API layer, you will have trouble moving off Cassandra or joining it with other data sources (perhaps some sort of distributed cache?), or even doing in-memory data manipulation that CQL can't handle. This is one of the reasons why Relay, for example, defines a more generalized "Connection" concept that can map to any underlying data source(s). 

If you're absolutely sure you want to design your GraphQL API like this, then it seems you're going to have to roll up your sleeves with Cassandra. GraphQL binding layers also exist for other DBs, check out: https://github.com/calebmer/postgraphql

**Comment by smolinari** [comment]
@robzhu - I agree with your analysis of exposing too many persistence layer details at the API layer. That is also why I am not too certain postgraphql is what @sudheerj is looking for either. It is missing exactly what he is looking for, business logic and validation, so it is purely persistence layer details at the API layer. 😉 

Scott

**Comment by robzhu** [comment]
@sudheerj I think there's a good amount of info for you here, but nothing specific that we can do to help you in terms of feature work on graphql-js. Closing the issue, re-open if you believe if it is unresolved.

**Comment by sudheerj** [comment]
Thanks Robzhu and smolinari for your comments.Relay connection concept is just talking about pagination model.But most of my complexity lies in fields conditions with lots of operators.For example, all possible CQL conditions might appear [To](http://www.datastax.com/dev/blog/a-deep-look-to-the-cql-where-clause) apply each condition on persistance layer might cause scattered code,lots of parsing,validations etc.
