### ISSUE TITLE
Errors executing GraphQL in Lambdas

### ISSUE THREAD

**Issue by TimothyDalbey** [graphql/graphql-js#666]
Using version 3.10.9 of GraphQL, in a Lamda specifically I am getting the following error:

```
Syntax error in module 'endpoints/graph/handler': SyntaxError
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```
This occurs when I add the following line of code to my handler:

`var { graphql, buildSchema } = require('graphql');`

The handler works as expected in my local environment.

**Comment by robzhu** [comment]
GraphQL doesn't have a version 3.10.9. Can you double check your package.json or link me to your repo?

**Comment by TimothyDalbey** [comment]
Ah -  yes, I did.  I also determined the cause of the issue.  

Lambda doesn't fully support ES6, and it chokes on a variety of new features.  This is one of them.

**Comment by robzhu** [comment]
Glad you figured out the cause. Do you have a suitable workaround?

**Comment by TimothyDalbey** [comment]
Basically just need to alter the inclusion to read as follows:

```
var graphql = require('graphql').graphql;
var buildSchema  = require('graphql').buildSchema;
```
And of course, all other analogous statements need to be handled in the same way

There are other points down the road where Lambda barfs as well.  Specifically, it doesn't like the destructuring assignment in the resolvers (which is also new to ES6) as below ...

```
({ id }) => {}
```
... but again, that can be trivial to address once you understand where the errors are being surfaced.  Otherwise, things went fairly smoothly.
