### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by justinjzs** [graphql/graphql-js#667]
An error appear when I clone this repository and run 'npm install'
error details in the below:
> graphql@0.8.2 prepublish C:\Users\JustinJin\demo\store\graphql-js
> . ./resources/prepublish.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! graphql@0.8.2 prepublish: `. ./resources/prepublish.sh`
npm ERR! Exit status 1
....
how to resolve it?

**Comment by stubailo** [comment]
Looks like the prepublish script doesn't run on Windows, especially since it's written as a unix shell script.

You might want to try cloning in cygwin or the Windows linux subsystem.

**Comment by leebyron** [comment]
Yes, unfortunately you need to use Mac, Linux, or the Windows linux subsystem to develop GraphQL-js, though it should install cleanly on typical Windows usage as a dependency.
