### ISSUE TITLE
Add minify option to printSchema

### ISSUE THREAD

**Issue by aihornmac** [graphql/graphql-js#685]
Since printed schema has much smaller file size and better integrity than introspection, we are using it instead. Wonder if an `minify` option can be added to `printSchema` to remove extra spaces, line-breaks, comments, etc.

**Comment by IvanGoncharov** [comment]
It's planned to `14.2.0` and tracked in #1628
Since it's not an SDL specific and would work with valid GraphQL document we decided to move it in the separate `stripIgnoredTokens` function.
```js
const sdl = printSchema(schema);
const minifiedSDL = stripIgnoredTokens(sdl);
```
