### ISSUE TITLE
Release flow v0.38.0 support on NPM

### ISSUE THREAD

**Issue by ajhyndman** [graphql/graphql-js#689]
Hey guys, awesome work keeping this project and flow moving so quickly!

I'm currently trying to use `graphql-js` in a project of mine, alongside flow 0.38.0.  I see that a couple fixes were already committed to master in this repo, but we haven't seen an NPM release since November.  Any chance that will be remedied soon?  :)

**Comment by excitement-engineer** [comment]
I am running into the same issue:)

**Comment by robzhu** [comment]
Yep, we're working on it =)

**Comment by robzhu** [comment]
0.9.0 is now available on npm and should include the flow 0.38.0 compatibility fix.

**Comment by ajhyndman** [comment]
Thanks guys!
