### ISSUE TITLE
Integer coercion is misleading

### ISSUE THREAD

**Issue by zerkms** [graphql/graphql-js#69]
The `coerce` function for the integers is defined as

    export var GraphQLInt = new GraphQLScalarType({
      name: 'Int',
      coerce(value) {
        var num = +value;
        return num === num && num <= MAX_INT && num >= MIN_INT ? num | 0 : null;
      },
      coerceLiteral(ast) {
        if (ast.kind === Kind.INT) {
          var num = parseInt(ast.value, 10);
          if (num <= MAX_INT && num >= MIN_INT) {
            return num;
          }
        }
      }
    });

Which means that if a number does not fit the 32 bits, then the significant bits will be truncated.

Which is generally a not expected behaviour, since the coercion must either produce a valid result, or a `null`.

References:

* https://github.com/graphql/graphql-js/blob/master/src%2Ftype%2Fscalars.js#L20

**Comment by leebyron** [comment]
Thanks for the report, I'll add tests

**Comment by zerkms** [comment]
@leebyron sorry for disturbing, but in es6/2015 there is a `Math.trunc()` that could help eliminate the entire `(num < 0 ? Math.ceil : Math.floor)` expression

**Comment by leebyron** [comment]
I'm aware of this, but decided to not require a global object polyfill since GraphQL.js should be included as a side-effect-free library.
