### ISSUE TITLE
How to union InputTypes

### ISSUE THREAD

**Issue by Zweer** [graphql/graphql-js#694]
Hi all,

I'm trying to design something like:
```
type Set {
  id: ID!
  set: String!
  language: String!
}
```

where the couple "set"-"language" is unique. (why am I using also the "id" field? because the library I use to wrap the database doesn't allow me to have composite foreign-keys)
Because of that I can identify a single set either by its "id" or by its "set"-"language", so in a "set" query I should have three parameters:
```
type Query {
  set(id: ID, set: String, language: String): Set
}
```
Now my question is: is there a way to make mandatory the "language" argument if I specify the "set" one (and vice versa), or making "set" and "language" throwing exceptions if I specify the "id"?
Or I'd better use "non mandatory" arguments and then in the "resolve" field throw exceptions if there is a "strange" situation?

Thanks a lot!
Zwe

**Comment by robzhu** [comment]
So you would like a mutation to fail based on a combination of input type and conditional input args provided to the GraphQL layer? Do you have a repo you can link or provide a runnable example of what the limitation you're seeing?

**Comment by Zweer** [comment]
Of course: https://github.com/mtg-omega/models/tree/graphql-issue (use the "graphql-issue" branch)

As you can see in graphql/set.js I've defined the model (it is resolved by a sql model defined in sql/set.js if you care), while in \_\_tests\_\_/graphql/set.js I've defined the tests it should pass (the last 4 fail)...

Thanks a lot!

**Comment by robzhu** [comment]
Hey sorry for taking a while to get back to you on this. Looks like the sample link is dead. I'm closing the issue for now. If you haven't found a solution, feel free to reopen.
