### ISSUE TITLE
Input Types validation error message is misleading

### ISSUE THREAD

**Issue by IdeaHunter** [graphql/graphql-js#709]
After upgrade to 0.9.1 i got an error message:

`MutationInputChannel.updateVideoContent field type has a resolve property, but Input Types cannot define resolvers`

When I got a look at my typescript code:
```js
updateVideoContent(id: string,  files: FileList): boolean
```
I thought - `updateVideoContent` has type of `boolean` - whats wrong with it - its not even the object type and should be fine.
15 min later i got what it talking about - it told me that `updateVideoContent` should not be added to MutationInputChannel in the first place.

Maybe word **type** should be removed, since error is not about it _type_ but about field _itself_?

**Comment by wincent** [comment]
Thanks for posting, @IdeaHunter.

Getting the wording right here is tricky. The input object type has a field, and the field is of a type, hence the wording "field type". This is consistent with a similar validation that we perform on input object types [here, in the same file](https://github.com/graphql/graphql-js/blob/21b34a3057f6968da469160558cdd1d8534a84d8/src/type/definition.js#L1053).

Any ideas for clearer wording here, @robzhu?
