### ISSUE TITLE
Passing arguments to the 'fields' function when creating a schema

### ISSUE THREAD

**Issue by l50741** [graphql/graphql-js#716]
Hi all,

I am attempting to build a GraphQL schema at runtime from the schema that is returned from a Gaffer instance. 

For each of the Gaffer edges, I would like to create a Type for the 'source' and 'destination' values (or use one that was previously generated). Each type will need a field which relates to an edge.

For example, a simple graph could have the following edges:
`region -- (contains) --> location -- (contains) -- > road -- (has) --> junction`

In this case, a Type called 'region' would need a field called 'locations', which is a list of type 'location', and then so on down the chain.

However, if the graph is more complicated and forms a more cyclic format, we have to set the 'fields' on a type using a function which will run once all the initial types have been created. #202 

The problem is that there doesn't seem to be a way of, once inside the 'fields' function knowing the name of the type being defined, thus making it hard to programmatically work out which types to add fields.

In the example below (sorry the long, and fairly rough code example)
- Create a basic Javascript object for each Type (from the source and destination of the edges)
- Add a 'fields' function to each of the type objects, which should (but doesn't) work out which fields each type should have
- Build each of the type objects into proper GraphQL types
- Add these types to the root query
- Construct the root query - At this point, the 'fields' functions are processed but each function no longer knows what type for which it is building the fields

Is there any way to pass an argument to the fields function to help work out which fields to include?

```js
getSchema() {
return gaffer.getGraphSchema().then(response => {
    let typeObjects = {};
    let gafferSchema = JSON.parse(response);
    let edges = gafferSchema.edges;

    // For each edge in the schema, build a type for both the source and destination
    for (var edgeName in edges) {
        if (edges.hasOwnProperty(edgeName)) {
            var edge = edges[edgeName];
            if (typeObjects[edge.source] === undefined) {
                typeObjects[edge.source] = {
                    name: edge.source
                };
            }
            if (typeObjects[edge.destination] === undefined) {
                typeObjects[edge.destination] = {
                    name: edge.destination
                };
            }
        }
    }

    // For each of the new types created, register a 'fields' function to run when 
    // the GraphQLSchema is constructed.
    for (var typeName in typeObjects) {
        if (typeObjects.hasOwnProperty(typeName)) {
            typeObjects[typeName].fields = () => {
                // Fields function, runs when the GraphQLSchema is built, has no
                // no reference to the current 'typeName' - typeName is always the
                // last value in the array loop.
            }
            typeObjects[typeName] = new GraphQLObjectType(typeObjects[typeName]);
        }
    }

    var query = {
        name: 'RootQueryType',
        fields: {}
    };

    // Add each of the new GraphQLObjectTypes to the query as root parameters, along with a
    // generic 'name' argument.
    for (var objectName in typeObjects) {
        if (typeObjects.hasOwnProperty(objectName)) {
            query.fields[objectName] = {
                type: typeObjects[objectName],
                args: {
                    name: {
                        type: new GraphQLNonNull(GraphQLString)
                    }
                },
                resolve: (root, { name }) => {
                    return { _name: name };
                }
            }
        }
    }

    // Build the graph schema and process all the 'fields' functions
    return new GraphQLSchema({
        query: new GraphQLObjectType(query)
    });
});
```

**Comment by l50741** [comment]
There is a way around the problem I was experiencing. If all type are being added to the root query type fields (as in the loop near the bottom of my example) we know the order in which the 'fields' functions are going to be resolved. Which means with a array/queue we could figure out what the current type was.

It is a bit of a messy way of doing it, and I have a feeling it might get more complicated to calculate the order in which the 'fields' functions get resolved if there are types which are not included as part of the root.

Would still be interested to know if there was another way of defining the fields with a function that has parameters and not a thunk.

**Comment by Maxpain177** [comment]
+1

**Comment by IvanGoncharov** [comment]
@l50741 Why can't you write something like this?
```js
    for (var typeName in typeObjects) {
        if (typeObjects.hasOwnProperty(typeName)) {
            const currentTypeName = typeName;

            typeObjects[typeName].fields = () => {
              // You can use currentTypeName here
            }
            typeObjects[typeName] = new GraphQLObjectType(typeObjects[typeName]);
        }
    }
```

**Comment by IvanGoncharov** [comment]
@l50741 I think my previous snippet fully address your problem but feel free to reopen if not.
