### ISSUE TITLE
Addition of resolveMany

### ISSUE THREAD

**Issue by calebmer** [graphql/graphql-js#721]
As an alternative to `DataLoader` for connection fields or other fields with lots of arguments, what do you think about adding a `resolveMany` resolver function? What this function would do is instead of taking the signature `(source, args, context, info) => value` it would take the signature: `(sources, args, context, info) => values`. Note the `sources` as the first argument and `values` as the return which would be arrays of equal lengths. Another signature could be `(args, context, info) => (source) => value` for much the same effect.

How would it be decided which `sources` to group together? `DataLoader` groups together every request that gets run in the same tick, but `resolveMany` could go a step further and get a little more GraphQL specific by grouping together every `source` for a given field. For example:

```graphql
fragment on Person {
  friends(first: 5) {
    edges {
      node {
        friends(first: 5) {
          edges {
            node {
              friends(first: 5) {
                ...
              }
            }
          }
        }
      }
    }
  }
}
```

Here `resolveMany` would resolve for all of the person nodes whenever we reach a `friends(first: 5)` field. The advantage of a `resolveMany` over a `DataLoader` in this case is that it would be difficult to get a cache key for all of the connection arguments when it would make more sense to just batch resolve for an entire field when we could.

This may be possible to implement in user-land, but it may also be worth implementing in GraphQL.js.

**Comment by leebyron** [comment]
I think it's an interesting idea, but this would essentially be baking DataLoader directly into graphql-js and I'd prefer to keep the abstractions separated.

**Comment by calebmer** [comment]
Ok. If anyone wants to use an approach like this I built [`graphql-resolve-batch`](https://github.com/calebmer/graphql-resolve-batch) which implements the same semantics as this proposal. The current implementation uses the [first item in `fieldNodes` as a cache key](https://github.com/calebmer/graphql-resolve-batch/blob/b23b7b2c0efd3667e282dd812ce2ba7813fad52d/src/batch.js#L46). It would be great to see this pattern officially supported as a primitive alternative to `DataLoader` given it shouldn’t be too hard to implement within GraphQL’s execution semantics.
