### ISSUE TITLE
@include(unless null) ? 

### ISSUE THREAD

**Issue by hakimelek** [graphql/graphql-js#738]
Is there a way to do that? 

I don't know if there is already an issue or a solution for this, but here is a reference to the question: 
http://stackoverflow.com/questions/36451910/graphql-query-only-include-field-if-not-null

**Comment by stubailo** [comment]
GraphQL currently does not support this as a feature in the specification. What would the benefit of this be? Also, if this is a spec question it should go on the facebook/graphql repository, because the implementation won't have it until it's specified.

**Comment by hakimelek** [comment]
The benefit would be to return the field if it is not null, a much cleaner response.
