### ISSUE TITLE
Having more than one RootQuery object in the schema

### ISSUE THREAD

**Issue by saudpunjwani101** [graphql/graphql-js#745]
It's not like an issue or something but more likely a refactor thing.

I was wondering if there's a way I can create multiple rootQuery objects and pass them as array in the schema object. My current rootQuery module contains like 200 lines of code. I wanted to refactor it somehow. 

So for now what we write is this

const Schema = new GraphQLSchemaType({
 query: RootQuery
})

what I want would be something like this 
 
const Schema = new GraphQLSchemaType({
 query: [RootQuery1, RootQuery2]
})

I tried but it doesn't seem to work. If there's a workaround I'll be grateful. Thanks guys

**Comment by stubailo** [comment]
Why not define the fields in separate modules, then import them and attach to the Query type? I think you just need a better way of organizing the fields, not multiple types.

**Comment by saudpunjwani101** [comment]
Yes that's what I'm doing
