### ISSUE TITLE
Accept stringed object as query argument. 

### ISSUE THREAD

**Issue by jaycetan** [graphql/graphql-js#748]
My goal is to be able to pass a stringed object in a GraphQL query.

**Goal**:
```
 {
    accounts (filter: 
      '{"fieldName": "id",
      "fieldValues":["123"],
      "filterType":"in"}'){
        id
      }
 }
```

**Error**: "Syntax Error GraphQL request (1:22) Unexpected single quote character ('), did you mean to use a double quote (\")?"

Problem is GraphQL doesn't seem to accept strings surrounded with single quotes.

Using single quotes inside of the object won't be possible because this would require major changes to the client which compiles these objects.

**Example**:
```
 { 
 "fieldName": "id",
 "fieldValues":["123"],
 "filterType":"in"
 }
```

**Schema**: 
```
 accounts: {
   type: new GraphQLList(accountType),
   args: {
   id: { type: GraphQLString },
    status: { type: GraphQLString },
    filter: { type: GraphQLString },
    sort: { type: GraphQLString },
   },
   resolve: (root, args, { loaders }) => loaders.account.load(args),
},
```

**Comment by stubailo** [comment]
Have you tried using a backslash to escape the double quotes inside the query? Also if you are passing in complex arguments it's usually easier to do so with variables!

**Comment by jaycetan** [comment]
@stubailo, Thanks for the input. I tried the backslashes but it did not work for me. Also, this would not be a feasible solution as we would still have to make code changes to the client.

**Comment by stubailo** [comment]
I mean what you are sending right now is not a spec compliant graphql query so you'll have to make some client changes unless you do some hacks.

**Comment by helfer** [comment]
@jaycetan If you really want to send stringified objects for whatever reason, you can define a custom JSON scalar type for that. It's definitely not something that needs a change in the spec.

**Comment by jaycetan** [comment]
Thanks for the help @helfer !

**Comment by bwyss** [comment]
double backslash worked for me

**Comment by development-vargamarcel** [comment]
Well, not recommended, but you could simply replace all quotes with something else and on the server put back the strings in their place. Like so:
`
 {
    accounts (filter: 
      "{~fieldName~: ~id~,
      ~fieldValues~:[~123~],
      ~filterType~:~in~}" ){
        id
      }
 } 
`

On the server, replace all ~ with "
