### ISSUE TITLE
Make validation tests reusable

### ISSUE THREAD

**Issue by neelance** [graphql/graphql-js#749]
What do you think in general about the idea to make the validation tests reusable for other GraphQL server implementations? The server would load the test schema and then the JavaScript test code would send queries to that server and check the returned errors.

**Comment by OlegIlyenko** [comment]
In case you haven't seen it yet, a while back we started work on "GraphQL Compatibility Acceptance Tests":

https://github.com/graphql-cats/graphql-cats

I already contains several validation, parsing and execution scenarios. Would appreciate your feedback on this initiative.

**Comment by neelance** [comment]
Thanks for the link, I didn't know about that project yet. I will definitely give it a try.

**Comment by IvanGoncharov** [comment]
Having standartise test suite is great idea but it should be totally separate project from reference implementation.
ATM I think we need to focus on `graphql-cats` since it's already adopted by `Sangria` and `graphql-java`.
