### ISSUE TITLE
how to prune a tree with visitor ?

### ISSUE THREAD

**Issue by gre** [graphql/graphql-js#754]
I can see you can only replace or remove a node value but it doesn't seem you can change the tree itself. is it a limitation of the visitor?
I would have expected the `BREAK` (or false) return value to prune a branch, but it does not seem to happen, the returned edited AST still contain my branch.

**Comment by leebyron** [comment]
visitor does in fact remove nodes or branches if you `return false;` during a visit.

However it does not mutate the input AST, instead `visit()` returns a new AST with the change applied.
