### ISSUE TITLE
why there is a ~ folder in this project

### ISSUE THREAD

**Issue by noscripter** [graphql/graphql-js#756]
This could easily lead mistakes accounting developer's home directory.

![image](https://cloud.githubusercontent.com/assets/1673877/23987299/dcda7554-0a63-11e7-810b-7a21c9fee12d.png)

**Comment by langpavel** [comment]
No, there it is not. Check in another environment please

**Comment by wincent** [comment]
Thanks for the report, @noscripter, but as @langpavel said, this looks to be a local issue, so I'm going to close this.
