### ISSUE TITLE
GraphQLEnumType numbers in string don't play well

### ISSUE THREAD

**Issue by superandrew213** [graphql/graphql-js#758]
I'm getting an issue when I include ```'2xs': { value: '2xs' }``` as one of the options. Numbers in the string seem to cause the issue.

```
new GraphQLEnumType({
  name: 'Options',
  values: {
    '2xs': { value: '2xs' },
    'xs': { value: 'xs' },
    's': { value: 's' },
  },
})
```

**Comment by superandrew213** [comment]
I see https://github.com/graphql/graphql-js/blob/master/src/utilities/assertValidName.js#L42-L46 that names can't start with a number. Why is that?

**Comment by stubailo** [comment]
That's specified, so it must be intentional: https://facebook.github.io/graphql/#Name

**Comment by superandrew213** [comment]
Fair enough. What do you think is the best way to handle this? Your options start with numbers or are only numbers.

**Comment by langpavel** [comment]
Use prefix

**Comment by superandrew213** [comment]
I'm a bit confused with this. For example: 
```
var episodeEnum = new GraphQLEnumType({
  name: 'Episode',
  description: 'One of the films in the Star Wars Trilogy',
  values: {
    NEWHOPE: {
      value: 4,
      description: 'Released in 1977.',
    },
    EMPIRE: {
      value: 5,
      description: 'Released in 1980.',
    },
    JEDI: {
      value: 6,
      description: 'Released in 1983.',
    },
  }
});
```

Which value will be presented to the client to select from? Are all these values supposed to be internal and we should use something else to look up client presentable values.

What about this https://facebook.github.io/graphql/#sec-The-__EnumValue-Type
`__EnumValue` type should have `name, description, isDeprecated & deprecationReason`? How come we are using `value` instead of `name`.

**Comment by langpavel** [comment]
Sorry @superandrew213 Did you use enum in C or similar language? Enum represents discrete values, more than TRUE or FALSE but I don't spot more than 20 enum values in my entire carrier. Oh.. when they are right enum values! You have safe 30 bits across languages and platforms, you can use them as flags. You can, this not mean you should!
I don't understand why you want use numbers as representation of enum value. Try go back in history, enums are like Symbols in era of 8-16 bits.

**Comment by stubailo** [comment]
The client is only aware of `name` - value is purely an internal thing for the server.

**Comment by superandrew213** [comment]
Thanks! We should add it to the examples to make it a bit more clear.
