### ISSUE TITLE
 buildSchema is not a function 

### ISSUE THREAD

**Issue by abdennour** [graphql/graphql-js#761]
The [official website of graphql](http://graphql.org/code/#graphql-js-graphql-js-github-https-github-com-graphql-graphql-js-npm-https-www-npmjs-com-package-graphql)refers to this repository to create the helloworld . 

```js
var { graphql, buildSchema } = require('graphql');

var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

var root = { hello: () => 'Hello world!' };

graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});

```

When i run  this file with `node` cmd , I got : 

```
var schema = buildSchema(`
             ^

TypeError: buildSchema is not a function
    at Object.<anonymous> 

```

What is the new version of `buildSchema` ?

**Comment by wincent** [comment]
Thanks for the report. This seems to be something local to your environment. We're definitely [exporting the function](https://github.com/graphql/graphql-js/blob/ea28cda530d1c1bddfa332ef207b86ef5db5d621/src/index.js#L281), and you can see us using it in other projects ([example](https://github.com/graphql/graphql-language-service/blob/a38ee318ce92c5295b28bdf994037a8e9291172e/src/client.js#L15)).

Here is a minimal attempt at reproing:

```
$ mkdir /tmp/repro
$ cd !$
$ npm install graphql
$ vim index.js
$ cat index.js
var { graphql, buildSchema } = require('graphql');

var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

var root = { hello: () => 'Hello world!' };

graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
$ node index.js
{ data: { hello: 'Hello world!' } }
```

I'm going to close this for now, but in the meantime I suggest starting from a clean environment and seeing if you can get things working there, like in the example above.

**Comment by ezos86** [comment]
Node version most likely
