### ISSUE TITLE
validation: arguments on field that has no arguments

### ISSUE THREAD

**Issue by neelance** [graphql/graphql-js#763]
This is about https://github.com/graphql/graphql-js/blob/7c044c62b5facc8945aca693bc5dc2b6a1635b20/src/validation/__tests__/ArgumentsOfCorrectType-test.js#L130. There is a test of type `expectPassesRule` which passes arguments to `dog`, but `dog` has no arguments in the schema. Am I right that this is a bug?

**Comment by OlegIlyenko** [comment]
I think this particular aspect is checked in different validation rule: `KnownArgumentNames`. In general, all validation rules are build in such a way that they only verify very specific aspect of a query and just ignore all other unrelated issues.

**Comment by neelance** [comment]
Okay yes, `ArgumentsOfCorrectType` is not supposed to fail on unknown arguments. Still, it is a bit weird to have such a test case in the `null into nullable type` scenario, since it does not test that behavior.

**Comment by OlegIlyenko** [comment]
Indeed, the test name chose looks a bit confusing considering the context :) It probably should be something like "should not fail on unknown arguments".

**Comment by neelance** [comment]
Is there any specific reason why you would want to ensure such behavior?

**Comment by OlegIlyenko** [comment]
If the goal is to ensure that validation checks only specific aspect of the query and does not break on (can handle) potentially invalid quires (which are broken because of some unrelated issues), then I think this kind of test is quite valuable.

**Comment by neelance** [comment]
Okay, so the validation should not completely blow up on invalid input. Fair point.
