### ISSUE TITLE
input validation too loose for string and boolean

### ISSUE THREAD

**Issue by itajaja** [graphql/graphql-js#771]
this

```js
{ "foo": [1, 2, 3]}
```

is a correct payload for the muation

```js
export default mutationWithClientMutationId({
  name: 'Test',

  inputFields: {
    foo: { type: new GraphQLNonNull(GraphQLString) },
  },
...
```

happening beacuse of [this](https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L91-L92).

Clearly `[1, 2, 3]` is not a string and this should probably be rejected. This kind of coercion makes sense for output types, but for mutation input this seems very odd, even more so considering that other things are validated (non-nullness, integers). I mean, if `[1, 2, 3]` is a string, then why isn't `"foo"` a valid integer? I am seeing a disparity here. Is there a reason for that?

**Comment by leebyron** [comment]
This looks like a bug similar to #827 

https://facebook.github.io/graphql/#sec-String

**Comment by vladar** [comment]
Coercion of booleans also seems invalid: 

```json
{"foo": "false"}
```

will be coerced to `true` by GraphQL Boolean Type without raising errors ([here](https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L117)) even if specs [explicitly says](http://facebook.github.io/graphql/#sec-Boolean):

```
When expected as an input type, only boolean input values are accepted. 
All other input values must raise a query error indicating an incorrect type.
```

**Comment by leebyron** [comment]
Now fixed in master and will be included in the next release
