### ISSUE TITLE
Accept special chars in name

### ISSUE THREAD

**Issue by Alphapage** [graphql/graphql-js#777]
Hello,

I would be great to add special chars to type name and field name like : 
/ + ? \ @ &  or %
It would be possible to use names like those: na%me, my/custom\name or me&you.

It seems that adding the code for those chars in readName function from lexer.js or lexer.js.flow seems easy.

I can find any problems or specs to ignore such a feature.

Thanks in advance for your answers.

**Comment by leebyron** [comment]
Please take a look at https://facebook.github.io/graphql/#sec-Names

Since GraphQL interoperates with many programming languages, a common base has been used which works with the most environments.
