### ISSUE TITLE
Add example in definition/__tests__ of all types working together

### ISSUE THREAD

**Issue by dschafer** [graphql/graphql-js#78]
The top level **tests** describes a pretty simple schema, but it doesn't go into input objects or unions. A more comprehensive example would be useful.

**Comment by ruslantalpa** [comment]
I needed a reference output for introspection feature for lua implementation so i created this simple example https://github.com/ruslantalpa/graphql-js/tree/tests_refactor/src/__tests__/todo
If @leebyron thinks it's worth developing (adding more properties showcasing different things like input objects, unions ...) and has some suggestions, i can work on it a bit more to make it PR worthy

**Comment by leebyron** [comment]
Awesome!

**Comment by JoviDeCroock** [comment]
Should be covered in https://github.com/graphql/graphql-js/blob/16.x.x/src/__tests__/starWarsSchema.ts
