### ISSUE TITLE
Accessing enum values

### ISSUE THREAD

**Issue by juliocanares** [graphql/graphql-js#796]
I was wondering if there is a way to access an enum value.

by example if I have an enum like this

```
const graphQLEnum = new GraphQLEnumType({
  name: 'ExportEnum',
  values: {
    PURCHASES: { value: 'purchases' },
    USERS: { value: 'users' },
    GOODS_BATCH: { value: 'goods_batch' }
  }
})

console.log(graphQLEnum.PURCHASES)  // purchases


```

**Comment by leebyron** [comment]
`graphQLEnum.getValues()` will return a collection of all enum values, each of which has properties like `name`, `description`, and `value`. This is the same API GraphQL uses internally and powers the introspection API
