### ISSUE TITLE
Are directives on types considered as valid?

### ISSUE THREAD

**Issue by xpepermint** [graphql/graphql-js#797]
Would the definition below be considered as a valid schema definition - something that I can use in a project and will not be removed in the future? Directives are parsed as expected though.

```gql
interface User @resolver(path: "IUserResolver.js") {
  name: String
}
type Admin implements User {
  name: String
  isAdmin: Boolean @resolver(path: "AdminIsAdminResolver.js")
}
```

**Comment by wincent** [comment]
The `graphql` NPM package explicitly allows directives on both [interface definitions](https://github.com/graphql/graphql-js/blob/490dc494ac0bdc45c5d762811b8fc3d796dae3a8/src/language/ast.js#L427) and [field definitions](https://github.com/graphql/graphql-js/blob/490dc494ac0bdc45c5d762811b8fc3d796dae3a8/src/language/ast.js#L411).

There may be a small gap in the spec here, in that it [only says](https://facebook.github.io/graphql/#sec-Language.Directives) directives are "for fields, fragments, and operations". We should probably update that to mention interface definitions too (feel free to report an issue on [the GraphQL repo](https://github.com/facebook/graphql) or submit a PR), but in the meantime I'd say you usage is safe.

**Comment by xpepermint** [comment]
Thanks!
