### ISSUE TITLE
Determining if a type is a connection

### ISSUE THREAD

**Issue by ryanmcclure4** [graphql/graphql-js#801]
I'm navigating a graphQL schema typeMap and need to determine which type fields are connections. Since a connection would be a GraphQLObjectType that has an `edges` field, I can use this as a check. This works, but what might be a better, more direct way of checking this?

**Comment by leebyron** [comment]
Since connections are just a common convention in GraphQL schema, then yes I would suggest duck-typing it. Look for an `edges` field and likely also look for arguments like `first` and `after`
