### ISSUE TITLE
Issues with ScalarLeafs validation rule?

### ISSUE THREAD

**Issue by leebyron** [graphql/graphql-js#804]
Seeing issues like:

```
Expected at least one selection for non-scalar field `id` on type `ID!`.
```

In v0.9.2 and v0.9.3

**Comment by leebyron** [comment]
@wincent could you help with this? Repos when running Relay tests after upgrading to the latest version of graphql

**Comment by wincent** [comment]
Yep, will check it out.

**Comment by wincent** [comment]
This is caused by 12b2137f8a0b1a72752b.

**Comment by leebyron** [comment]
Oh awesome thanks for the bisect, I know exactly how to fix this now!

**Comment by wincent** [comment]
Ha, it wasn't a bisect. I eyeballed the commit history and this commit was my first guess, testing confirmed it was the cause.

**Comment by leebyron** [comment]
well thanks for the eyesect

**Comment by leebyron** [comment]
This was my mistake for looking for an issue within validation, on closer inspection this issue was just contained within Relay. I'm going to close this issue in favor of https://github.com/facebook/relay/pull/1611
