### ISSUE TITLE
GraphQL Errors

### ISSUE THREAD

**Issue by ablbol** [graphql/graphql-js#805]
Please forgive me for asking about errors in GraphQL.  I tried to read previous issues but got no where.  I have everything working fine except for handling errors.  suppose that I have sign up form with email and password and both are declared non null in my mutation.  I am bypassing the client validation for now just to be safe and see the behavior from the server.  When I don't enter anything in the form and submit it, I get errors that look like this:
```
Variable "$email" of type "String" used in position expecting type "String!
Variable "$password" of type "String" used in position expecting type "String!
```

Is there a way to get readable errors in the client side such as: 

```
Email is required
Password is required
```
If you can point me to an example, I would really appreciate it.  I am new to GraphQL and would be very greatfull.
Thanks

**Comment by ablbol** [comment]
Is there a way in GraphQL to format errors in a more readable way.  For example instead of this message:
```
Variable "$gender" of required type "String!" was not provided.
```
I would like to get this message:
```
Gender is required
```
Thanks

**Comment by ivome** [comment]
I opened up a separate issue in the graphql spec repository which addresses the same issue: facebook/graphql#298

**Comment by wincent** [comment]
Thanks for the link @ivome, and for the question @ablbol. As the current format of the error messages is dictated by the spec, and we already have an open issue for that  on the other repo, let's close this one so as to keep all the discussion about the issue in one place. (And hopefully, one of the suggestions in that issue enables you to move forward, @ablbol).
