### ISSUE TITLE
Undocumented breaking change in 0.9.2

### ISSUE THREAD

**Issue by kassens** [graphql/graphql-js#811]
12b2137f8a0b1a72752b5ee54660127a5a042a33 introduced a breaking change where non-nullable fields are no longer considered leaf types by `isLeafType`.

See the breakage reported in facebook/relay#1614.

**Comment by leebyron** [comment]
This one's ambiguous, but I agree should have been included on the changelog. It was a bug fix, but that did result in behavior change

**Comment by kassens** [comment]
Feel free to close if the change log is immutable.

**Comment by wincent** [comment]
It's not immutable.

**Comment by wincent** [comment]
Note that it was already in the changelog as:

> * Improvements to Flow checking (#699) and type safety (#698), (#697).

but at the time I wrote it I didn't realize it was a breaking change. I've edited the release notes to instead say:

> * Remove ambiguity in `isLeafType` check: it no longer performs named type unwrapping and is consistent with the other `isCompositeType`/`isAbstractType` checks (#697).

Feel free to [edit them further](https://github.com/graphql/graphql-js/releases/tag/v0.9.2) if you think they can be improved.

**Comment by kassens** [comment]
This is perfect. Flow checking/type safety sounded internal or that they wouldn't affect runtime.
