### ISSUE TITLE
0.8.x breaking change with errors thrown from scalar resolvers

### ISSUE THREAD

**Issue by thebigredgeek** [graphql/graphql-js#821]
It appears that 0.8.x introduced a breaking change with errors thrown from scalar resolvers.  Upon upgrading, it appears that errors thrown from scalar resolvers (exclusively) have, by the time they have reached `formatErrors`, been transformed into a shape like:

```bash
[1] [1]   message: 'Variable "$input" got invalid value {"stripeCardName":"asdasdada","stripeCardNumber":"42424242424223113","stripeCardExp":"00/00","stripeCardCVC":"233"}.\nIn field "stripeCardNumber": Expected type "CreditCardNumber", found "42424242424223113": The credit card number you entered appears to be invalid.',
[1] [1]   locations: [ { line: 1, column: 28 } ],
[1] [1]   path: undefined }
```
where the original error message was "The credit card number you entered appears to be invalid", and the original error object contained a bunch of useful meta data as an error created with [apollo-errors](https://github.com/thebigredgeek/apollo-errors) that instructed the client about validation issues (in this case, a credit card number that isn't valid according to ccn validation algorithms).

Was this intended?  It seems strange to force an error format like this, especially as a breaking change.

It looks like [this](https://github.com/graphql/graphql-js/pull/561) might have been the change, according to the [v0.8.0 release changelog](https://github.com/graphql/graphql-js/releases/tag/v0.8.0)

**Comment by helfer** [comment]
@thebigredgeek the PR in question is [this](https://github.com/graphql/graphql-js/pull/553) one, and I believe it was very much intentional. Just looking at the error message and the PR, I'm guessing that maybe the error isn't being thrown from a resolver, but from `parseValue`?

**Comment by thebigredgeek** [comment]
Yes, you are correct.  Is `parseValue` not part of the scalar's resolver, though?
