### ISSUE TITLE
Problem on returning a nullable DateTime scalar

### ISSUE THREAD

**Issue by thebergamo** [graphql/graphql-js#826]
**Problem**
I'm trying to create a new resource using a mutation. The result of this mutation is a type with a date value. If I just pass a value to the type and try to retrieve it, all looks fine. But if I don't send the value and try to retrieve the value, well, we expect the value will going be null, right?

I'm using this scalar extension: https://www.npmjs.com/package/graphql-iso-date is an excellent work from  @excitement-engineer, thanks very much for that. 

Ok, in my try to seek and destroy the problem, I'm getting in this part of the `execute/execution`[1] in resolution of the promise, the returned value is a random date, but not in a normal way because, that have spaces between the time part.  e.g: `Error: Expected a value of type "Date" but received: 2009-07-08T03 : 22 : 29-03:00`

The model I'm returning in the resolver function, don't have this field. I'm trying to write my own scalar date type, just to try to debug and keep it simple as I can, but the problem persist in this parte of the graphql-js and I'm not sure how I can deal with this problem. 

I'll appreciate any kind of help in this issue! If it's a problem on my side or just a bug inside the graphql execute function.

** how to run?**
my current schema
```graphql
type Task implements Node {
  id: ID!
  scheduledAt: Date
  executedAt: Date
  plant: Plant!
  user: User!
  meta: TaskMeta
}
```

my scalar dateType (exported as Date in the resolver)
```js
const DateTimeScalar = {
  __parseValue(value) {
    return moment(value).toDate(); // value from the client
  },
  __serialize(value) {
    if (!moment(value).isValid()) {
      console.log('PLEASE!!!')
      return;
    }
    return moment(value).format(); // value sent to the client
  },
  __parseLiteral(ast) {
    if (ast.value && moment(ast.value).isValid()) {
      return moment(ast.value).format();
    }
    return null;
  }
}
```

respose returned in the resolver fn
```js
{ 
    task:
        {
            scheduledAt: '2017-04-24T22:16:44-03:00',
            user: { id: 'b4fc0b7c-c975-48de-a0dd-b9ddad54f522' },
            plant: { id: 'eb468b1c-42c6-4e82-9ab6-a7c9b046f3db' },
            meta: { id: undefined },
            id: 'ba3b3d08-1ee8-407a-a5d1-4885fb6a9f7f'
        }
}   
```

[1] - https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L778

**Comment by thebergamo** [comment]
Sorry about that, after hours plugged to solve this problem, now I can figure out that!

It's an issue with the mock server.

**Comment by wincent** [comment]
@thebergamo: Glad to hear that you figured it out. Thanks for closing the loop.

**Comment by aymericbouzy** [comment]
Running in the same issue @thebergamo, can you give details on how you solved it?
