### ISSUE TITLE
Support Tree Shaking through the module field in package.json

### ISSUE THREAD

**Issue by jwickens** [graphql/graphql-js#843]
Webpack and rollup use the module field in the package.json to find a build with ES6 imports which enables tree shaking. 

You can use babel to transpile with
```
{
  "presets": [["es2015", {"modules": false}]]
}
```
You will have  configure babel to transpile flow too.

Enabling this in this library could potentially reduce client builds by around 100kb

**Comment by wincent** [comment]
Thanks for posting this issue, @jwickens. I thought we already had one to track this, but I can't find it. I must have been thinking of [this one](https://github.com/facebook/relay/issues/1590) on the Relay repo.

**Comment by baer** [comment]
@wincent PR https://github.com/graphql/graphql-js/pull/880 is a step in this direction since it allows for variable output types. After that is merged, implementing this should just be using the `BABEL_ENV` variable to create different build targets. I'm more than happy to take on this work.

**Comment by baer** [comment]
Okay, now that #880 is merged, this should be somewhat straightforward! The holdup is that there is a unique build/deploy process that will have to change to support it.

@leebyron @wincent I spent a minute looking through how this gets all bundled up, and it seems like the [build steps](https://github.com/graphql/graphql-js/blob/master/package.json#L30) in the `package.json` are never used. I don't see any references to `dist` in the code. Instead, there are a couple of bash scripts [here](https://github.com/graphql/graphql-js/blob/master/resources/gitpublish.sh#L9) and [here](https://github.com/graphql/graphql-js/blob/master/resources/prepublish.sh#L24) that build the project. 

Would you mind if I consolidate the duplicate `sed` and `babel` commands and use `npm scripts` to get this tidied up? I'm not sure I see how to do a secondary "modules" build with babel running in the root like it is now.

**Comment by baer** [comment]
Okay, I've got a first pass at what this type of change would look like. Before I get it all tucked in, I'd love to get some feedback.

https://github.com/graphql/graphql-js/pull/939

**Comment by leebyron** [comment]
Supported in master (thanks to @baer's hard work) and will be included with the next release
