### ISSUE TITLE
master builds failing due to GitHub 

### ISSUE THREAD

**Issue by wincent** [graphql/graphql-js#853]
PR commits like [this one](https://github.com/graphql/graphql-js/commit/3a5444ac7b75daf1d8135029ce2ed853449f12b1) are [passing in CI as PRs](https://travis-ci.org/graphql/graphql-js/builds/232511224?utm_source=github_status&utm_medium=notification), but failing when they land on master ([sample](https://travis-ci.org/graphql/graphql-js/builds/232512205?utm_source=github_status&utm_medium=notification)).

```
fatal: Authentication failed for 'https://[secure]@github.com/graphql/graphql-js.git/'
```

This is because we run `npm-git` [only on master](https://github.com/graphql/graphql-js/blob/d75c779064ded1f8d1e7adae947dd482306d8c16/.travis.yml#L40-L45), and it is dying at [this line](https://github.com/graphql/graphql-js/blob/d75c779064ded1f8d1e7adae947dd482306d8c16/resources/npm-git.sh#L29).

@leebyron: did you change/invalidate your API key lately by any chance?

**Comment by leebyron** [comment]
Fixed in 20d05a67de1ab2a26ff90dfc841ada6bbd166161
