### ISSUE TITLE
Error in defining circular dependencies, despite using thunks

### ISSUE THREAD

**Issue by ErikWittern** [graphql/graphql-js#854]
I know that using thunks, circular dependencies between GraphQL type definitions can be achieved, for example:

```javascript
const User = new GraphQLObjectType({
  name: 'User',
  fields: () => ({
    name: { type: GraphQLString },
    item: {
      type: Item
    }
  })
})

const Item = new GraphQLObjectType({
  name: 'Item',
  fields: () => ({
    id: { type: GraphQLString },
    user: {
      type: User
    }
  })
})
```

However, this approach does not work when I reorganize the code to the following:

```javascript
const dict = {}

const userFields = {
  name: { type: GraphQLString },
  item: {
    type: dict.Item
  }
}

dict.User = new GraphQLObjectType({
  name: 'User',
  fields: () => (userFields)
})

dict.Item = new GraphQLObjectType({
  name: 'Item',
  fields: () => ({
    id: { type: GraphQLString },
    user: {
      type: dict.User
    }
  })
})
```

The error states: `Error: User.item field type must be Output Type but got: undefined.`. Can I avoid this error while maintaining a structure like the above? I am trying to create a GraphQL schema programmatically, and thus rely on this or a similar code structure.

**Comment by ErikWittern** [comment]
Hm, I think I see the problem: because of my code's structure, `userFields` is interpreted when `dict.Item` is still `undefined`, thus diminishing the effect of the thunk. Is there a suitable workaround for cases like this?

**Comment by ErikWittern** [comment]
I found an answer: when needing to programmatically create a `fields` object, which may rely on circular dependencies / other dependencies not yet resolved, it needs to be done from within the fields thunk. For example:

```javascript
const dict = {}

dict.User = new GraphQLObjectType({
  name: 'User',
  fields: () => {

    // programmatically build up fields here...

    let userFields = {
      name: { type: GraphQLString },
      item: {
        type: dict.Item
      }
    }

    return userFields
  }
})

dict.Item = new GraphQLObjectType({
  name: 'Item',
  fields: () => ({
    id: { type: GraphQLString },
    user: {
      type: dict.User
    }
  })
})
```

**Comment by wincent** [comment]
Glad to hear you got it sorted out. Thanks for sharing your solution!
