### ISSUE TITLE
Introspection?

### ISSUE THREAD

**Issue by Rakden** [graphql/graphql-js#859]
Hi,
I am trying to make sure I am not looking at a bug and that this is intended behavior. Are there any limitations on querying the __schema field that can be set outside of writing validation rules? I am thinking of requests like those found in [utilities](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js)
Thanks,

**Comment by Rakden** [comment]
Found #113 answers most of my questions.

**Comment by wincent** [comment]
Glad to hear it @Rakden.
