### ISSUE TITLE
GraphQL Schema Definition Language support in graphql-java

### ISSUE THREAD

**Issue by ajmalsha** [graphql/graphql-js#872]
Can we implement GraphQL Schema Definition language support in graphql-java ? if yes then how?

**Comment by baer** [comment]
Did you intend to post this on the [graphql-java/graphql-java](https://github.com/graphql-java/graphql-java) project or maybe on the [spec repo](https://github.com/facebook/graphql)?

**Comment by leebyron** [comment]
Please open issues for other projects on their respective github projects!
