### ISSUE TITLE
Installation error via NPM

### ISSUE THREAD

**Issue by ddialar** [graphql/graphql-js#893]
Hi all,

I have tried to install the _graphql_ module via _npm_ based on the next system properties:
- NodeJS version: v7.10.0
- NPM version: 4.2.0
- OS: Linux Mint 18.1
- OS version: 64bits

Once said that, when I run 

> $ npm install --save graphql

I received the next message:

> Refusing to install package with name "graphql" under a package npm ERR! also called "graphql". Did you name your project the same npm ERR! as the dependency you're installing?

Researching on the NPM official page, they have previewed these kind of cases and they say that we have to use the _**--force**_ option.

Finally, I changes my installation command by the next one and everything was fine.

> $ npm install --save --force graphql

Regards.

**Comment by papandreou** [comment]
Does the project that you're trying to install the `graphql` package into also happen to be called `graphql` in package.json?

**Comment by ddialar** [comment]
Hi @papandreou,

yes, the `graphql` package is already defined into the package.json file, once I installed it with the _--force_.

My caveat was rised because if you try to install the module via `npm install --save graphql`, based on my OS configuration, likelly you are going to get the same error that I received.

Regards.

**Comment by papandreou** [comment]
@ddialar That's not what I meant -- what is the value of the top-level "name" field in the package.json of the project you're trying to install the graphql package into?

**Comment by ddialar** [comment]
I think that I know what you are talking about...

Next is the content of my current package.json file:
```
{
  "name": "graphql",
  "version": "1.0.0",
  "description": "A GraphQL testing server",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "ddialar",
  "license": "MIT",
  "dependencies": {
    "express": "^4.15.3",
    "express-graphql": "^0.6.6",
    "graphql": "^0.10.1",
    "lodash": "^4.17.4"
  }
}
```

**Comment by papandreou** [comment]
Right, I think you'll have to rename your own project, or at least change it to a private namespace, eg. `@ddialar/graphql`.

**Comment by ddialar** [comment]
@papandreou thank you so much for that information.

That is the first time that I have this kind of issue.

Once said that, I'm going to close the issue.

Regards.

**Comment by wincent** [comment]
Glad to see you got it sorted out.
