### ISSUE TITLE
Allow begining pipe in union types

### ISSUE THREAD

**Issue by alexandrebodin** [graphql/graphql-js#897]
Hi 

Everything was said in the titile. I would be great to be able to write:

```graphql
union unionType = 
  | TypeA
  | Type B
  | Type C
```
instead of
```graphql
union unionType = 
    TypeA
  | Type B
  | Type C
```

This would be great for prettier / graphql to make cleaner formatting. And overall go the same wayas Flow and Elm for example :)

**Comment by robzhu** [comment]
Hey @alexandrebodin, thanks for filing this issue. The proposal reasonable and we should be able to get it added soon.

**Comment by alexandrebodin** [comment]
@robzhu If you can give me some pointers I'm down for doing a PR

**Comment by robzhu** [comment]
@alexandrebodin awesome, thanks for volunteering =). Start with `schema-parser-test.js:460`. It has an example of parsing a union type from graphql schema format. If you trace through that, you'll probably find yourself at `language/parser.js: parseUnionTypeDefinition`. My general advice is to write the failing test first and work backward. I can follow up on your PR with the related spec text changes. Take a look and let me know if you still want to commit to doing this work.

**Comment by alexandrebodin** [comment]
@robzhu 

PR done here: https://github.com/graphql/graphql-js/pull/907 
(also opened a PR on the spec)

**Comment by robzhu** [comment]
Thank you for your contributions! Both PRs have been merged, closing the issue now.
