### ISSUE TITLE
interface GraphQLField in definition.d.ts file is not correct

### ISSUE THREAD

**Issue by nisimjoseph** [graphql/graphql-js#901]
in the interface `GraphQLField` field `args` is not supposed to be an `Array`. it a Hash `{[index:string]:GraphQLArgument}`.
the GraphQL runtime is not accepting this `Array` type and give runtime exception.

**Comment by robzhu** [comment]
@nisimjoseph can you please provide sample code of the incorrect type definition?

**Comment by leebyron** [comment]
Closing this issue since typescript definitions are not part of this project.

You can take a look at the types used in GraphQL.js in https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L586
