### ISSUE TITLE
graphql-js vs graphql-java

### ISSUE THREAD

**Issue by vtahlani** [graphql/graphql-js#906]
Which one should be using? 
My understanding - graphql-js is more dynamic and easy to write but it runs on Node/Express which is signal threaded  this may be a challenge for production applications, also would be able to use JavaAPIs?

graphql-java - is more static even if i use IDL - how to use custom functions, dynamic coding etc...

Any suggestions?

**Comment by sibelius** [comment]
I think this is better to StackOverflow or slack channel instead of an issue

**Comment by robzhu** [comment]
Hey @vtahlani! My advice: use whichever server you/your team is more comfortable with. If you're adding GraphQL to an existing service, bias toward using the same language as your business domain logic. GraphQL-java and GraphQL-js are both actively maintained and used in production at many companies. Also check out Sangria: https://github.com/sangria-graphql, @OlegIlyenko's incredible GraphQL Scala implementation.

**Comment by vtahlani** [comment]
Thanks @robzhu .
