### ISSUE TITLE
Define extra properties to errors

### ISSUE THREAD

**Issue by kbariotis** [graphql/graphql-js#912]
From the [specs](http://facebook.github.io/graphql/#sec-Errors)

> GraphQL servers may provide additional entries to error as they choose to produce more helpful or machine‐readable errors, however future versions of the spec may describe additional entries to errors.

As far as I understand, we should be able to define custom properties to errors that are being exposed to the GraphQL response. Like this:

```
{
  "errors": [
    {
      "message": "Name for character with ID 1002 could not be fetched.",
+    "type": "NOT_FOUND",
      "locations": [ { "line": 6, "column": 7 } ],
      "path": [ "hero", "heroFriends", 1, "name" ]
    }
  ],
  "data": {
    "hero": {
      "name": "R2-D2",
      "heroFriends": [
        {
          "id": "1000",
          "name": "Luke Skywalker"
        },
        null,
        {
          "id": "1003",
          "name": "Leia Organa"
        }
      ]
    }
  }
}
```

Is this currently possible? Should we consider adding it to this library?

**Comment by IvanGoncharov** [comment]
@kbariotis Currently it's possible only by providing a custom function to format errors. See example for `express-graphql`: https://github.com/graphql/express-graphql#debugging-tips

I'm already working on PR that adds `extensions` arg  to constructor of `GraphQLError`, in your example argument value would be `{type: 'NOT_FOUND'}`. I still need to add tests, so I plan to submit my PR in the next couple of days.

**Comment by kbariotis** [comment]
@IvanGoncharov thats great! Let me know if you want my review or any help.

Also, I am not using `express` but `graphql-js` directly, so the `formatError` is not really helpful.

**Comment by IvanGoncharov** [comment]
@kbariotis I submitted my implementation for review as #928
