### ISSUE TITLE
Suggest the ability to define resolve at the type level

### ISSUE THREAD

**Issue by serle** [graphql/graphql-js#92]
I understand the point given in the examples re- parallel field resolve calls, but generally I would think that it would more common on the back end, certainly at the leaf type level, to be able to resolve all the fields necessary for a given type in one go. Could a type level resolve capability be added to the spec.

**Comment by leebyron** [comment]
I'm not sure I follow your suggestion. Could you please write a little bit of code that suggests what code you wish you could write and how it should behave?

**Comment by leebyron** [comment]
I'm closing this issue now since the request isn't clear. Please feel to re-open in the future.
