### ISSUE TITLE
Suggest capability to centralise resolve functions out of the type definitions 

### ISSUE THREAD

**Issue by serle** [graphql/graphql-js#93]
I think it would be more manageable to separate the resolve declaration in the type schema from the resolve implementation code. This could enable the back-end resolve implementations to be produced by independent server-side teams potentially in other languages all together.

**Comment by leebyron** [comment]
I'm sorry I don't quite understand what you're asking for here. Could you please write some example code that you wish you could write that you can't now?

**Comment by leebyron** [comment]
Closing this aging issue.

For posterity: You can always construct types in graphql-js in any way that is legal JS, that can include defining resolver functions in one file and referencing them in another if that feels better for you.
