### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by drmax24** [graphql/graphql-js#936]
Hello! Can you allow more characters for enum? We need to use dash in our project.

We use larave-graphql [https://github.com/Folkloreatelier/laravel-graphql](url) and it limits chars to be compatible with your library.

https://github.com/Folkloreatelier/laravel-graphql/issues/153#issuecomment-312426066

P.S.: we use enum for input filtering. Specified enum values go to graphql schema and become visible in query builder. This is very good. If we limit enum to few allowed chars then i don't know how our company can benefit from using enum at all.

**Comment by rohitghatol** [comment]
I can understand your pain. I too was looking for the same thing. 

However the spec says for enum values are Name tokens which are defined by regex : /[_A-Za-z][_0-9A-Za-z]*/. So we are out of luck here.

https://github.com/graphql/graphql-js/issues/668

**Comment by MCON** [comment]
I can't see any strict rule in facebook docs

**Comment by rohitghatol** [comment]
If you see the spec it reads like this -
> EnumValue: Name but not true or false or null.

The **_Name_** has a link to this section - http://facebook.github.io/graphql/#Name

Name::
/[_A-Za-z][_0-9A-Za-z]*/

**Comment by MCON** [comment]
We would like to see some solution

**Comment by ramblinjacket** [comment]
I have a similar situation as @drmax24. i have predefined enums that include a dash in the name and it would be confusing to user base to change this.  Can there not be an escape character or similar to navigate around this?

**Comment by leebyron** [comment]
Enums are defined to be `Name` so they can be easily represented in all major programming languages. If `SOME-TYPE` were translated to JavaScript, it would be interpreted as a subtraction.

Enum values are purely representative and can represent any runtime value, not even just a string. Consider this example: https://github.com/graphql/graphql-js/blob/master/src/type/__tests__/enumType-test.js#L31-L40

The Enum names are only represented within the query string and variable values from a client's point of view.

**Comment by ragnarkurmwunder** [comment]
You can use underscore instead of dash.
