### ISSUE TITLE
What is the TOptions type?

### ISSUE THREAD

**Issue by ijsnow** [graphql/graphql-js#943]
Hello, I'm just doing some reading/digging around to see what's going on under the hood for fun/learning.

I stumbled upon the TOptions type in this file https://github.com/graphql/graphql-js/blob/07cc624677f4c7120e588e530c6fdb2d87e6210a/src/language/lexer.js#L23-L30.

I'm just curious about what this is/what it does because I don't see it used anywhere else in the repo other than those few lines and it's not defined anywhere.

Just a brief explanation or a link for me would be cool :)

Thanks!

**Comment by leebyron** [comment]
These are the options the Lexer uses during parsing. That strongly types the `options` field of the Lexer.
