### ISSUE TITLE
understanding _ in resolve function in new GraphQLObjectType

### ISSUE THREAD

**Issue by webmobiles** [graphql/graphql-js#950]
what does mean '_' parameter in resolve function ?. what is it for ?where i can read documentation about resolve parameters?

```
 const queryType = new GraphQLObjectType({
        name: 'RootQuery',
        fields: {
            usersCount: {
                type: GraphQLInt,
                resolve: (_, args, { db }) =>
                    db.collection('users').count()
            }
        }
    });
```

**Comment by papandreou** [comment]
It means "don't care"/"anonymous parameter". Since the first argument is not actually used by the function, don't bother assigning a proper name to it.

Related discussion: https://github.com/graphql/graphql-js/issues/844

**Comment by webmobiles** [comment]
Thanks !
