### ISSUE TITLE
Get queried type fields in resolver?

### ISSUE THREAD

**Issue by jonmanzo** [graphql/graphql-js#954]
Looked everywhere and assume I'm missing something as I figure this has to be possible... Here's what I'm looking to accomplish:

Within a resolver, I would like to know which fields were included in the request for the type currently resolving. This way I can increase speed and save $ by altering the resolver fetch to only return data from the store that is necessary to fulfill the request.

**Comment by robrichard** [comment]
I have a package on npm that does this: https://github.com/robrichard/graphql-fields

**Comment by jonmanzo** [comment]
Thanks Rob!
