### ISSUE TITLE
RFC: postResolve callback

### ISSUE THREAD

**Issue by mattkrick** [graphql/graphql-js#957]
The result that I return from a mutation isn't necessarily the result that gets returned from `execute` or `subscribe`. For example, let's assume a `Post` collection and `Comment` collection with the following query:
 ```
Post(idx: $idx) {
  title
  comments {
    body
  }
}
```
Now, my query is:
```
resolve(_, {idx}) => Post[idx]
```
This returns only a partial result, but that's cool because on my Post schema, i have the following: 
```
comments: {
  type: new GraphQLList(Comment),
  resolve({idx}) => Comments.filter(comment => comment.postIdx === idx)
}
```
Now let's say I want to send that result to a pubsub. if i did it from within the query, then that resolve function for comments would get executed once per listener, bleh.
Alternatively, I could fetch comments from within the query, but then if the query doesn't need comments, it's a wasted db hit.
Another approach is to catch the value returned from `execute`, look for the field `Post`, and publish that value to the pubsub, but that breaks with aliases, not to mention it isn't very modular.
The last option I have is to implement an in-memory cache to reduce the cost of `comments.filter`, but that only reduces the cost a little bit, plus then I'd want to clear it after all the listeners got called, and that's a headache.

It'd be much easier to resolve my query/mutation, let graphql do it's magical thing by filling up the return object, and then having it call a `postResolve` callback with the response. 

Of course, if there's a simpler way to accomplish this, I'd love to learn!

**Comment by leebyron** [comment]
I think you may be bending GraphQL for a purpose it wasn't designed to solve. I think your approach of reaching into the value returned from `execute` to get a partial result makes the most sense.

Typically when sending values over a pubsub, I don't see the results of a GraphQL query execution but instead more simplified metadata (which upon the "sub" side might trigger a GraphQL query before sending to an interested client)
