### ISSUE TITLE
Problem Storing GraphQLObjectType on ES6 Static Property 

### ISSUE THREAD

**Issue by bbar** [graphql/graphql-js#959]
I'm trying to store a GraphQLObjectType as a static property in an ES6 class, but am running into an error.

Here's an example of a file:

```
// DoesntWork.js

const {
  GraphQLObjectType,
  GraphQLString,
} = require('graphql');

class Name {
  constructor(first, last) {
    this.first = first;
    this.last = last;
  }

  static get type() {
    return new GraphQLObjectType({
      name: 'Name',
      description: 'A person\'s name.',
      fields: {
        first: {
          type: GraphQLString,
          description: 'Person\'s first name.',
        },
        last: {
          type: GraphQLString,
          description: 'Person\'s last name.',
        },
      },
    });
  }

  static async getNames() {
    return [new Name('Brent', 'Barbata')];
  }
}

module.exports = Name;
```

Now, If I try to use `Name.type` somewhere in the schema, everything is fine. But, if I try to use it more than once, I get the following error:

> Schema must contain unique named types but contains multiple types named "Name".

Alternatively, consider this refactored file:

```
// Works.js

const {
  GraphQLObjectType,
  GraphQLString,
} = require('graphql');

class Name {
  constructor(first, last) {
    this.first = first;
    this.last = last;
  }

  static async getNames() {
    return [new Name('Brent', 'Barbata')];
  }
}

Name.type = new GraphQLObjectType({
  name: 'Name',
  description: 'A person\'s name.',
  fields: {
    first: {
      type: GraphQLString,
      description: 'Person\'s first name.',
    },
    last: {
      type: GraphQLString,
      description: 'Person\'s last name.',
    },
  },
});

module.exports = Name;
```
With this file, I'm able to use `Name.type` all over my schema without any problems. Any ideas on why this might be happening?

**Comment by leebyron** [comment]
The problem is that each call to `get type` is calling `new GraphQLObjectType` and creating a new instance of the type. If you include that in a schema multiple times, you'll get many object types with the same name.

Compare to your second example where `new GraphQLObjectType` is called only once.
