### ISSUE TITLE
File Upload Example?

### ISSUE THREAD

**Issue by appjitsu** [graphql/graphql-js#960]
I am trying to create a custom input type using vanilla graphql (ie: non-apollo).

ref: https://github.com/jaydenseric/apollo-upload-server/issues/9

Got any examples for uploading files?

**Comment by papandreou** [comment]
@appjitsu, for an app I'm working on where I need to be able to receive multiple uploaded files as part of a mutation, I came up with the idea of accepting a `multipart/form-data` request where the first part is `application/graphql` and the subsequent ones are arbitrary files that are associated with the mutation.

The `multipart/form-data` handling is a piece of middleware, so it ought to be reusable. I've uploaded it here along with a very simple usage example: https://gist.github.com/papandreou/abd7b8f00f7bff699a06e21330a2004a

I have no idea if there's a better, more "official" way of achieving the same thing, though :)

**Comment by jaydenseric** [comment]
Perhaps not exactly what you are after since it does use Apollo, but you might find [jaydenseric/apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples) helpfull.

**Comment by robzhu** [comment]
@appjitsu, please take a look at some of the suggestions for handling file upload. Closing this issue for, feel free to re-open if you believe it's unresolved.

**Comment by up9cloud** [comment]
memo for who wanna use other client with `import { GraphQLUpload } from 'apollo-upload-server'`

> nodejs
```js
import fs from 'fs'
import FormData from 'form-data'
import axios from 'axios'

let o = {
  query: `mutation ($file: Upload!) {
    uploadFile (file: $file)
  }`,
  variables: {
    file: null
  }
}
let map = {
  '0': ['variables.file']
}
let fd = new FormData()
fd.append('operations', JSON.stringify(o))
fd.append('map', JSON.stringify(map))
fd.append(0, fs.createReadStream(`${__dirname}/app.js`), 'app.js')

let res = await axios.post('/graphql', fd, {
  headers: {
    ...fd.getHeaders()
  }
})
expect(res.status).to.be.equal(200)
expect(res.data).to.be.jsonSchema(schema)
```

**Comment by zackify** [comment]
Thanks so much @up9cloud. This is a really weird api if you ask me. Thanks to you I was able to make a function that correctly makes the file map from a graphql `variables` object. Here it is in case this helps someone: https://github.com/zackify/react-uploader/blob/master/src/clients/graphql/create-file-map.js

**Comment by jaydenseric** [comment]
I no longer use Apollo on the server or client these days, and use just the vanilla GraphQL.js API.

There is a simple server side example of both approaches here:

https://github.com/jaydenseric/graphql-upload#class-graphqlupload

And the best reference for a client library that constructs a fetch request handling possible files is here:

https://github.com/jaydenseric/graphql-react/blob/1b1234de5de46b7a0029903a1446dcc061f37d09/src/universal/graphqlFetchOptions.mjs

An example of uploading a file from a server environment:

https://github.com/jaydenseric/graphql-upload/blob/9b49be4cc5012307e7a08deb6d08ec071a708d5d/src/test.mjs#L79

Alternatively, the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec) has example cURL requests:

https://github.com/jaydenseric/graphql-multipart-request-spec#curl-request

> This is a really weird api if you ask me.

Rest assured, the spec has to be the way it is for good performance and to handle all sorts of situations like a client disconnecting half way through uploading several files, or using the same file as a variable in multiple mutations.

Only library authors really need to understand how it works; users of [server and client implementations](https://github.com/jaydenseric/graphql-multipart-request-spec#implementations) can take it for granted.

**Comment by zackify** [comment]
@jaydenseric thank you for the reply! The spec being that way now makes sense to me. Your client example helps a lot as well.

**Comment by Hongbo-Miao** [comment]
@jaydenseric have to thank you again! Spent hours online to find a solution without using Apollo. Your [client demo](https://github.com/jaydenseric/graphql-react/blob/1b1234de5de46b7a0029903a1446dcc061f37d09/src/universal/graphqlFetchOptions.mjs) is very helpful! Thanks!

**Comment by alesson-delmiro** [comment]
@up9cloud after 3 days looking for a solution, your solution worked for me, thanks my friend, you're the real MVP

**Comment by lcruz09** [comment]
@up9cloud thanks! Your approach was very useful to me as well 👍

**Comment by roapham** [comment]
@up9cloud Thank you very much !
For one who has error `...createReadStream is not a function...` 
I changed

`fd.append(0, fs.createReadStream(`${__dirname}/app.js`), 'app.js')
`

to
`
fd.append(0, file)
`

It will work but I don't understand why or what is the different.
I appreciate some explanations. Thanks again !

**Comment by weishijun14** [comment]
For some guys who want to upload multi files:
example 4 files upload:
```javascript
// * 多文件上传 
export const multiUploadExcel = async (params: any) => {
  let formdata = new FormData();

  const queryString = {
    query: `
      mutation ($files: [Upload!]!) {
        multiUpload (files: $files) {
          filename
          mimetype
          encoding
          dateArr
        }
      }
    `,
    variables: {
      files: [null, null, null, null],
    },
  };

  formdata.append("operations", JSON.stringify(queryString));
  formdata.append(
    "map",
    JSON.stringify({
      "0": ["variables.files.0"],
      "1": ["variables.files.1"],
      "2": ["variables.files.2"],
      "3": ["variables.files.3"],
    })
  );
  formdata.append("0", params.files[0], params.files[0].name);
  formdata.append("1", params.files[1], params.files[1].name);
  formdata.append("2", params.files[2], params.files[2].name);
  formdata.append("3", params.files[3], params.files[3].name);

  return await request(graphqlUrl, METHOD.POST, formdata, {
    headers: { "Content-Type": "multipart/form-data" },
  });
};
```
