### ISSUE TITLE
Consider re-licensing

### ISSUE THREAD

**Issue by choefele** [graphql/graphql-js#971]
Hi,

I assume you are aware of the recent discussions around the so-called 'Facebook BSD+Patents License'. The Apache Software Foundation Legal Affairs Committee [has announced](https://issues.apache.org/jira/browse/LEGAL-303?focusedCommentId=16088663&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16088663) that this license is no longer allowed to be used as a direct dependency in Apache projects. Based on this decision, the RocksDB project [re-licensed their code](https://github.com/facebook/rocksdb/releases/tag/v5.5.4) and people [have reached out to other Facebook projects](https://github.com/facebook/react/issues/10191) to consider doing the same. (I’m not affiliated with Apache in any way.)

I understand that the decision on which license to use is completely up to Facebook and I’m grateful that you started and open-sourced GraphQL. I just wanted to make you aware that the current license prevents some companies and organisations to use GraphQL.

I would kindly ask if you would consider changing the license of this project to something that’s easier to integrate for other companies.

Thanks

**Comment by leebyron** [comment]
No one on our team of engineers is well versed enough to make these legal decisions, but I will bring this to our legal team for further consideration

**Comment by sirmak** [comment]
any progress after react post ?

**Comment by wincent** [comment]
Thanks for pinging, @sirmak.

For others reading this, the referenced post is https://code.facebook.com/posts/112130496157735/explaining-react-s-license/

We appreciate for this request. We have seriously considered it but have decided not to change our license at this time (although the post title mentions "React's license", the body of it explains how we evaluated the question in the context of "all of our other open source" projects too).

I'm going to close this as I don't think I have anything else to add beyond what's in that post. Please read it if you'd like to know more.

**Comment by kaqqao** [comment]
Does the license affect the reference implementation only or the GraphQL specification as well?

**Comment by rmosolgo** [comment]
It doesn't seem like it, here's the issue on the spec: https://github.com/facebook/graphql/issues/351

**Comment by leebyron** [comment]
@kaqqao - as I understand it, the license in this repo applies only to this project

**Comment by DmitryEfimenko** [comment]
React is being relicensed to MIT: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/

Please give this topic further consideration

**Comment by choefele** [comment]
GraphQL spec now licensed as OWFa v1.0 and GraphQL.js + Relay as MIT  https://medium.com/@leeb/relicensing-the-graphql-specification-e7d07a52301b

Thanks for making this change
