### ISSUE TITLE
Possible desire for `findDescriptionChanges` utility

### ISSUE THREAD

**Issue by eapache** [graphql/graphql-js#981]
We needed it internally so I wrote a quick-and-dirty version based on `findBreakingChanges`. Right now it just walks two schemas and records all the types, fields, args, etc. which have descriptions added or changed, but not removed (aka anything that might need to be reviewed by a docs team).

If there is sufficient interest I don't mind cleaning it up and PRing it here cc @swalkinshaw

**Comment by leebyron** [comment]
Sounds great, send a PR when willing
