### ISSUE TITLE
Dynamic Object Support

### ISSUE THREAD

**Issue by bradennapier** [graphql/graphql-js#990]
So I see that others jsut say to do a stringify on it but that kind of urks me a bit.  To me it makes absolute sense that GraphQL should support dynamic objects in some way.  Personally I would like to see more of a marriage between GraphQL and Flow in the way things are defined and work... it's possible they could even combine their overall syntax in many ways (problem beign graphql meant to support multiple languages of course).

In my case I have quite a few objects that define things dynamically with ID's as the keys and a boolean as the value or something similar.  Perhaps some kind of "MapType" to support dynamic values ?  These could still validate the general types, but the keys themselves would not be known.

```js
{
     "id-one": true,
     "id-two": false
}
// or could really be considered as a JS Map
[
    [ "id-one", true ],
    [ "id-two", false ]
]
```
In this case, we can validate the "key" in the map is of "String" type and that the value is of "boolean" type.  

It's really a pain to deal with dynamic objects atm and I can see many others have struggled with this. 

Any other ways of handling this I am missing?

I believe this can be somewhat handled with "ScalarType" but it seems like there is almost no real documentation going over how to actually handle that properly or in a good way and I've had trouble finding much information on it.  Specifically how and where one would validate the value(s) and how to handle type failures, etc.

**Comment by bowlwinkle** [comment]
I agree and have a similar problem.  Is this getting any exposure?  Is there already a way to do this that someone can share?

**Comment by niwinz** [comment]
We are using this: https://gist.github.com/niwinz/dfdc9ba04002f3e3678a9e1f44e31caf,  Just use that type on fields where you want return anything json serializable.

**Comment by IvanGoncharov** [comment]
Closing this issue since `graphql-js` is implemented according to GraphQL spec.
In order to implement this feature, it should be added to the first, see https://github.com/facebook/graphql/issues/101
